import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{createHash}from'node:crypto';import{createRequire}from'node:module';import{setup,json,PNG}from'./publication.mjs';import{traceSourcePixels}from'../C169_NAPE_RECUT_20261002/source-trace.mjs';import{createSourceJoinProbe,assessSourceJoinContinuity}from'../../port/v2/tools/quadruped-proof/source-join-continuity.mjs';import{createSkeletonPoseProgram}from'../../port/v2/tools/creature-animation/skeleton-pose.mjs';import{familyContractForRecord}from'../../port/v2/tools/creature-animation/family-contracts.mjs';
const{loadCreatureRigV1}=await import('../../port/v2/apps/game/src/creature-rig.ts');const require=createRequire(new URL('../../port/v2/package.json',import.meta.url)),{BufferImageSource,Texture}=require('pixi.js');
const base='audits/C172_SHARED_HEAD_SPIKE_20261002',sha=b=>createHash('sha256').update(b).digest('hex'),read=p=>fs.readFileSync(p),pins=new Map(),pin=p=>pins.set(p,sha(read(p))),inputs=json(base+'/inputs.json').rows;
function scan(d,match){for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isDirectory())scan(p,match);else if(match.test(p))pin(p);}}
scan('port/v2/apps/game/src/motion',/\.ts$/);for(const p of['port/v2/apps/game/src/battle2/choreography.ts','port/v2/apps/game/src/creature-rig.ts','port/v2/apps/game/src/creature-rig-contact.ts'])pin(p);scan('port/v2/tools/creature-animation',/\.(mjs|ts|wasm)$/);for(const p of['publication.mjs','compare-freeze.mjs','inputs.json','measurement.json'])pin(base+'/'+p);for(const i of inputs)for(const p of i.inputs){assert.equal(sha(read(p.path)),p.sha256);pin(p.path);}
const rows=[];
for(const input of inputs){const variants=[],heldMs=input.native.stillTime-input.native.turn.offsetMs-input.native.turn.beats.reactionStart;
 for(const mode of['original','candidate']){const s=setup(input,input.fit,mode==='original'),probe=createSourceJoinProbe({record:s.record,binding:s.binding,atlas:{width:s.atlas.width,height:s.atlas.height,rgba:s.atlas.data}}),skeleton=createSkeletonPoseProgram(familyContractForRecord(s.record),s.record.landmarks),atlasFile=path.join(input.fit,'parts/atlas',fs.readdirSync(path.join(input.fit,'parts/atlas')).find(p=>p.endsWith('.png'))),atlasBytes=read(atlasFile),keyed=PNG.sync.read(read(input.fit+'/parts/keyed.png')),alpha=Uint8Array.from({length:keyed.width*keyed.height},(_,i)=>keyed.data[i*4+3]),texture=new Texture({source:new BufferImageSource({resource:new Uint8Array(s.atlas.data),width:s.atlas.width,height:s.atlas.height})}),master=read(input.inputs.find(p=>p.path.endsWith('/master.png')).path),rig=await loadCreatureRigV1(s.record,s.binding,master,alpha,atlasBytes,async()=>texture),facings=[];
 try{for(const side of['left','right']){let maxDrift=0,samples=0;const times=[...Array.from({length:121},(_,i)=>s.timeline.durationMs*i/120),s.timeline.durationMs-.001,s.timeline.durationMs+.001,heldMs],parity=[],observations=[];
  for(const ms of times){const f=s.publish(side,ms);maxDrift=Math.max(maxDrift,...f.publishedContacts.map(c=>c.driftPx));samples++;}
  for(const ms of[0,s.timeline.durationMs*.25,s.timeline.durationMs*.5,s.timeline.durationMs*.75,heldMs]){const frame=s.publish(side,ms);rig.applyPose(frame.resolved);let coordinates=0;for(const part of rig.parts){const actual=part.display.children[0].geometry.getBuffer('aPosition').data,expected=frame.positions[part.id];assert.equal(actual.length,expected.length);assert(Buffer.from(actual.buffer,actual.byteOffset,actual.byteLength).equals(Buffer.from(expected.buffer,expected.byteOffset,expected.byteLength)),'actual CreatureRig publication differs '+part.id);coordinates+=actual.length;}parity.push({elapsedMs:ms,coordinates,byteParity:true});const joins=assessSourceJoinContinuity(probe,frame.positions),matrices=skeleton.evaluate(frame.resolved),bounds=s.binding.paintSkin.parts.map(p=>{const v=frame.positions[p.id],owner=s.binding.parts.find(o=>o.id===p.id);return{part:p.id,joint:owner.joint,minX:Math.min(...v.filter((_,i)=>i%2===0))*s.record.geometry.width,maxX:Math.max(...v.filter((_,i)=>i%2===0))*s.record.geometry.width,minY:Math.min(...v.filter((_,i)=>i%2===1))*s.record.geometry.height,maxY:Math.max(...v.filter((_,i)=>i%2===1))*s.record.geometry.height};});observations.push({elapsedMs:ms,sourcePixelGround:s.record.geometry.groundLineY*s.record.geometry.height,publishedContacts:frame.publishedContacts,pose:frame.resolved,jointMatrices:matrices,paintBounds:bounds,sourceJoins:joins});}
  const frame=s.publish(side,heldMs),points=traceSourcePixels(s.record,s.binding,s.atlas,frame.positions),at=json(base+'/diagnosis.json').rows.find(r=>r.id===input.id).nearestPositiveAlpha[0],point=points.find(p=>p.source[0]===at.source[0]&&p.source[1]===at.source[1]);assert(point);const stage=s.stage(...point.published,side),distance=side==='right'?Math.hypot(stage[0]-input.visibleTipStagePx[0],stage[1]-input.visibleTipStagePx[1]):null;if(mode==='original'&&side==='right')assert(distance<.25,'exact original native defect must reproduce');facings.push({side,samples,refusals:0,maximumPublishedContactDriftPx:maxDrift,actualRuntimeParity:parity,attributedPixel:{...point,stage,distanceToOriginalNativeTip:distance},observations});
 }}finally{rig.dispose();}variants.push({mode,facings});}
 const row={id:input.id,fit:input.fit,variants};rows.push(row);fs.writeFileSync(base+'/'+input.id+'/comparison-freeze.json',JSON.stringify(row,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({id:input.id,variants:variants.map(v=>({mode:v.mode,facings:v.facings.map(f=>({side:f.side,samples:f.samples,refusals:f.refusals,maxContactDrift:f.maximumPublishedContactDriftPx}))}))}));}
for(const[p,h]of pins)assert.equal(sha(read(p)),h,'source drift '+p);
fs.writeFileSync(base+'/comparison-freeze.json',JSON.stringify({schema:'cf.c172-runtime-publication-comparison/v1',scope:'Actual contact/skin/ARAP plus loaded CreatureRig CPU texture publication. No browser/GPU/performance or native admission.',coordinateUnits:'Posed source-coordinate pixels unless explicitly native stage. Joint matrices normalized source coordinates.',rows,sourcePins:[...pins].map(([path,sha256])=>({path,sha256})),sourceUnchanged:true,nativeRun:false,qualityAccepted:false},null,2)+'\n',{flag:'wx'});
