import fs from'node:fs';import assert from'node:assert/strict';import{setup,json,PNG}from'./publication.mjs';import{traceSourcePixels}from'../C169_NAPE_RECUT_20261002/source-trace.mjs';import{rasterPaint}from'../C132_FAINT_GROUND_20261002/render-mesh.mjs';import{createOpaqueSeamSamplingGuard,applyOpaqueSeamSamplingGuard}from'../../port/v2/tools/creature-animation/seam-sampling-guard.mjs';
const base='audits/C172_SHARED_HEAD_SPIKE_20261002',diagnosis=json(base+'/diagnosis.json'),rows=[];
for(const input of json(base+'/inputs.json').rows){const held=input.native.stillTime-input.native.turn.offsetMs-input.native.turn.beats.reactionStart,byMode={};
 for(const mode of['original','candidate']){const s=setup(input,input.fit,mode==='original'),frame=s.publish('right',held),pts=traceSourcePixels(s.record,s.binding,s.atlas,frame.positions),tip=diagnosis.rows.find(r=>r.id===input.id).nearestPositiveAlpha[0],p=pts.find(p=>p.source[0]===tip.source[0]&&p.source[1]===tip.source[1]);assert(p);const nearest=pts.filter(q=>q.joint==='head').map(q=>({...q,restDistance:Math.hypot(q.source[0]-p.source[0],q.source[1]-p.source[1])})).sort((a,b)=>a.restDistance-b.restDistance)[0];assert(nearest);const posedDistance=Math.hypot((nearest.published[0]-p.published[0])*s.record.geometry.width,(nearest.published[1]-p.published[1])*s.record.geometry.height);byMode[mode]={tip:p,head:nearest,posedSourcePx:posedDistance,restSourcePx:nearest.restDistance,ratio:posedDistance/nearest.restDistance};
 const guard=createOpaqueSeamSamplingGuard({record:s.record,binding:s.binding,atlas:{width:s.atlas.width,height:s.atlas.height,rgba:s.atlas.data}}),atlas={...s.atlas,data:applyOpaqueSeamSamplingGuard(Uint8Array.from(s.atlas.data),s.atlas.width,s.atlas.height,guard)};
 for(const side of['left','right']){const f=s.publish(side,held);fs.writeFileSync(base+'/'+input.id+'/'+mode+'-source-freeze-held-'+side+'.png',PNG.sync.write(rasterPaint(s.record,s.binding,atlas,f.positions,side==='left'?1:-1)),{flag:'wx'});}
 }
 rows.push({id:input.id,...byMode});console.log(JSON.stringify({id:input.id,original:byMode.original.ratio,candidate:byMode.candidate.ratio,tip:byMode.original.tip.source,head:byMode.original.head.source}));
}fs.writeFileSync(base+'/measurement-freeze.json',JSON.stringify({units:'posed source-coordinate pixels, not native/screen pixels',rows},null,2)+'\n',{flag:'wx'});
