import fs from'node:fs';import assert from'node:assert/strict';import{setup,json}from'./publication.mjs';import{createSourceJoinProbe,assessSourceJoinContinuity}from'../../port/v2/tools/quadruped-proof/source-join-continuity.mjs';
const base='audits/C172_SHARED_HEAD_SPIKE_20261002',rows=[];
for(const input of json(base+'/inputs.json').rows){const old=setup(input,input.fit,true),now=setup(input),probe=createSourceJoinProbe({record:now.record,binding:now.binding,atlas:{width:now.atlas.width,height:now.atlas.height,rgba:now.atlas.data}}),held=input.native.stillTime-input.native.turn.offsetMs-input.native.turn.beats.reactionStart,facings=[];
 for(const side of['left','right']){const gaps=new Map(),hands=new Map();let samples=0;const times=[...Array.from({length:121},(_,i)=>now.timeline.durationMs*i/120),held];
  for(const ms of times){const a=old.publish(side,ms),b=now.publish(side,ms),aj=assessSourceJoinContinuity(probe,a.positions),bj=assessSourceJoinContinuity(probe,b.positions);assert.equal(aj.status,'PASS');assert.equal(bj.status,'PASS');samples++;
   for(const z of bj.excluded){const o=aj.excluded.find(x=>x.parts.join('|')===z.parts.join('|')),delta=z.maxGapPx-o.maxGapPx,key=z.parts.join('|');if(!gaps.has(key)||delta>gaps.get(key).maximumIncreaseSourcePx)gaps.set(key,{parts:z.parts,maximumIncreaseSourcePx:delta,originalGapSourcePx:o.maxGapPx,candidateGapSourcePx:z.maxGapPx,elapsedMs:ms,sourceWorstOriginal:o.worst,sourceWorstCandidate:z.worst});}
   for(const p of now.binding.parts.filter(p=>p.joint?.endsWith('Hand'))){const originalMaxY=Math.max(...a.positions[p.id].filter((_,i)=>i%2===1))*now.record.geometry.height,candidateMaxY=Math.max(...b.positions[p.id].filter((_,i)=>i%2===1))*now.record.geometry.height,delta=candidateMaxY-originalMaxY;if(!hands.has(p.id)||delta>hands.get(p.id).maximumDownwardIncreaseSourcePx)hands.set(p.id,{part:p.id,maximumDownwardIncreaseSourcePx:delta,originalMaxY,candidateMaxY,elapsedMs:ms,groundSourcePx:now.record.geometry.groundLineY*now.record.geometry.height});}
  }facings.push({side,samples,sourceGapComparisons:[...gaps.values()].sort((a,b)=>b.maximumIncreaseSourcePx-a.maximumIncreaseSourcePx),handComparisons:[...hands.values()]});}
 rows.push({id:input.id,facings});console.log(JSON.stringify({id:input.id,facings:facings.map(f=>({side:f.side,samples:f.samples,largestGapIncrease:f.sourceGapComparisons[0],hands:f.handComparisons}))}));
}fs.writeFileSync(base+'/regression-freeze.json',JSON.stringify({schema:'cf.c172-source-bound-regression/v1',units:'posed source-coordinate pixels; existing observation-only source joins, not native/screen distances or an admission gate',rows},null,2)+'\n',{flag:'wx'});
