/** Audit-only paired exact-output oracle; never shipped. */
import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {createWasmOrientationForward as prior} from './before/wasm-orientation-forward.mjs';
const out=process.env.CF_KERNEL_REPORT;assert(out&&!fs.existsSync(out));
const bytes=a=>Buffer.from(a.buffer,a.byteOffset,a.byteLength),sha=a=>createHash('sha256').update(bytes(a)).digest('hex');
const report={schema:'cf.forward-dirty-parity/v1',scope:'Alternating old/new leaf calls on identical actual static inputs; Node host timing, not native/phone. All coordinates, pass counts and stalled state compared.',calls:0,failures:[],rows:[]};
const compare=(a,b,ar,br,as,bs)=>{assert(bytes(a).equals(bytes(b)),'coordinate bytes');assert.equal(ar,br,'passes');assert.equal(as,bs,'stalled');};
const c=new Float64Array([-0,1]),changed=c.slice();changed[0]=0;assert.throws(()=>compare(c,changed,1,1,false,false));assert.throws(()=>compare(c,c,1,2,false,false));assert.throws(()=>compare(c,c,1,1,false,true));report.controls=['signed-zero-byte mutant rejected','pass count mutant rejected','stalled mutant rejected'];
process.on('exit',code=>{report.status=code===0&&report.calls>0&&!report.failures.length?'PASS_EXACT':'FAIL';const quantile=(a,q)=>a.slice().sort((a,b)=>a-b)[Math.ceil(a.length*q)-1];if(report.rows.length){const a=report.rows.map(r=>r.beforeMs),b=report.rows.map(r=>r.afterMs);report.timing={calls:a.length,beforeTotalMs:a.reduce((x,y)=>x+y,0),afterTotalMs:b.reduce((x,y)=>x+y,0),beforeP50Ms:quantile(a,.5),afterP50Ms:quantile(b,.5),beforeP95Ms:quantile(a,.95),afterP95Ms:quantile(b,.95)};}fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n',{flag:'wx'});if(report.status!=='PASS_EXACT')process.exitCode=1;});
export function wrapKernel(current,c,runtime){const next=current(c,runtime),old=prior(c,runtime);assert(next&&old,'Both WASM leaves must admit');return {kind:next.kind,byteLength:next.byteLength,get stalled(){return next.stalled;},run(p,n){const ep=p.slice(),inputSha256=sha(p);let r,er,beforeMs,afterMs;try{const before=()=>{const t=performance.now();er=old.run(ep,n);beforeMs=performance.now()-t;},after=()=>{const t=performance.now();r=next.run(p,n);afterMs=performance.now()-t;};if(report.calls%2){after();before();}else{before();after();}compare(p,ep,r,er,next.stalled,old.stalled);report.calls++;report.rows.push({call:report.calls,inputSha256,positionSha256:sha(p),passes:r,stalled:next.stalled,beforeMs,afterMs});return r;}catch(error){report.failures.push(String(error.stack??error));throw error;}}};}
