import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {createHash} from 'node:crypto';
const base=import.meta.dirname,root=path.resolve(base,'../..'),sha=b=>createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p));
const initial=read(base+'/pilot.json'),successors=read(base+'/pilot-framing-successors.json'),selected=read(base+'/pilot-selected.json'),all=[...initial,...successors],observations=[...read(base+'/observations.json'),...read(base+'/observations-framing.json')];
if(initial.length!==24||successors.length!==4||selected.length!==24||new Set(selected.map(r=>r.name)).size!==24)throw Error('Exact unique24 with four retained successors');
for(const r of all){const d=root+'/'+r.packet,g=read(d+'/generation.json'),q=read(d+'/request.json'),bytes=fs.readFileSync(d+'/master.png'),source=g.sourcePath.startsWith('~/')?path.join(os.homedir(),g.sourcePath.slice(2)):path.resolve(root,g.sourcePath);if(sha(bytes)!==g.masterSha256||!bytes.equals(fs.readFileSync(source))||sha(fs.readFileSync(d+'/prompt.txt'))!==q.promptSha256||g.promptSha256!==q.promptSha256||q.referenceSha256!==sha(fs.readFileSync(root+'/'+q.reference)))throw Error('Immutable provenance '+r.name);const o=observations.find(o=>o.id===r.id);if(o?.masterSha256!==g.masterSha256||o.width!==1254||o.height!==1254)throw Error('Native dimensions '+r.name);if(read(d+'/visual-review.json').masterSha256!==g.masterSha256)throw Error('Stale review');}
for(const r of selected)if(observations.find(o=>o.id===r.id)?.framing.status!=='PASS_FRAMING_ONLY')throw Error('Selected framing red');
const controls=[...read(base+'/controls.json').controls,...read(base+'/controls-framing.json').controls];if(controls.length!==33||controls.some(c=>c.status!=='PASS'))throw Error('Control count/status');
const mailbox=path.join(os.homedir(),'Projects/celestial-frontier-anthropic-mac/audits/MAILBOX/TO_CODEX.md'),mail=fs.readFileSync(mailbox),lines=mail.toString('utf8').split('\n'),latest=lines.filter(l=>/^\| C\d+ \|/.test(l)).at(-1);
fs.writeFileSync(base+'/batch-end-mailbox.json',JSON.stringify({schema:'cf.readonly-mailbox-check/v1',path:'~/Projects/celestial-frontier-anthropic-mac/audits/MAILBOX/TO_CODEX.md',sha256:sha(mail),latestRow:latest.match(/^\| (C\d+) \|/)[1],latestMessage:latest,mode:'read-only'},null,2)+'\n',{flag:'wx'});
const files=[];function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isSymbolicLink())throw Error('No audit symlinks');if(e.isDirectory())walk(f);else if(e.isFile()&&e.name!=='delivery.json'){const b=fs.readFileSync(f);if(/\.(json|mjs|md|txt)$/.test(e.name)&&(b.includes(Buffer.from(os.homedir()))||b.includes(Buffer.from('/'+'Users/'))))throw Error('Unsanitized record '+path.relative(root,f));files.push({path:path.relative(root,f),sha256:sha(b),bytes:b.length});}}}walk(base);files.sort((a,b)=>a.path.localeCompare(b.path));
const d={schema:'cf.g2-source-delivery/v1',scope:'24 selected source candidates,28 native paintings retained; explicit visual holds, no rig/native/gallery admission',selectedOriginals:24,initialOriginals:24,framingSuccessors:4,retainedNativePaintings:28,selectedPilot:'audits/C203_CREATURE_SUPPLY_B_20261004/pilot-selected.json',selectedPilotSha256:sha(fs.readFileSync(base+'/pilot-selected.json')),families:{quadruped:8,'biped-bird':8,fish:8},coveredAtSelection:270,recentDeliveriesExcluded:48,qualityAccepted:false,rigAdmission:false,native:false,controls:{passed:33,failed:0,firstInstrumentRefusalRetained:'controls-framing-first-refusal.json'},explicitVisualHolds:['Far-side roots/ears/wings/fins partly occluded; exact per-source notes retained','Capybara toe/webbing detail; Serow tail proportion; bear differentiation','Glossy bird eyes/bill and fish scales; Blenny cirri; Angelfish fin proportions','Marlin/Swordfish rear finlet-like projections/underside fins; Fangtooth skull/eye/fang exaggeration'],nativeDimensions:[1254,1254],selectedFramingPass:24,initialFramingRefused:['Arapaima','Arowana','Marlin','Swordfish'],selectedMasterBytes:selected.reduce((n,r)=>n+fs.statSync(root+'/'+r.master).size,0),retainedMasterBytes:all.reduce((n,r)=>n+fs.statSync(root+'/'+r.master).size,0),files,bytes:files.reduce((n,f)=>n+f.bytes,0)};
fs.writeFileSync(base+'/delivery.json',JSON.stringify(d,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({files:files.length,bytes:d.bytes,selectedMasterBytes:d.selectedMasterBytes,retainedMasterBytes:d.retainedMasterBytes,deliverySha256:sha(fs.readFileSync(base+'/delivery.json')),latestMailbox:read(base+'/batch-end-mailbox.json').latestRow}));
