/** Bounded offline replay of retained failure times. No rendering, acceptance,
 * changed source/bindings, per-species repair, CPU qualification or native rerun. */
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {compileBodyCard} from '../../../port/v2/apps/game/src/motion/body-card.ts';
import {buildTimeline} from '../../../port/v2/apps/game/src/motion/timeline.ts';
import {createGsapPlayer} from '../../../port/v2/apps/game/src/motion/gsap-adapter.ts';
import {createCreatureRigPerformance} from '../../../port/v2/apps/game/src/creature-rig-performance.ts';
import {createFamilyContactSolver,contactPaintDriftPx} from '../../../port/v2/apps/game/src/creature-rig-contact.ts';
import {blendCreaturePoses,closedLoopPose} from '../../../port/v2/apps/game/src/motion-pose-blend.ts';
import {familyContractForRecord} from '../../../port/v2/tools/creature-animation/family-contracts.mjs';
import {createSkeletonPoseProgram} from '../../../port/v2/tools/creature-animation/skeleton-pose.mjs';
import {createCompiledSkinField,applyCompiledSkinField} from '../../../port/v2/tools/creature-animation/compiled-skin-field.mjs';
import {createArapScratch,solveArapSkin} from '../../../port/v2/tools/creature-animation/arap-skin.mjs';
import {applyPaintPart,assertPaintPartShape} from '../../../port/v2/tools/creature-animation/paint-skin.mjs';
const base=path.resolve('audits/ANATOMY_COMPLETION_20260917'),out=path.join(base,'review-diagnosis-01');
const hashes=new Map(),read=p=>{const b=fs.readFileSync(p);hashes.set(p,createHash('sha256').update(b).digest('hex'));return JSON.parse(b.toString());};
function fixture(folder){
 const record=read(path.join(base,folder,'record.json')),binding=read(path.join(base,folder,'binding.json')),skin=binding.paintSkin,{width:w,height:h}=record.geometry;
 const program=createSkeletonPoseProgram(familyContractForRecord(record),record.landmarks),compiled=createCompiledSkinField(skin,w,h),scratch=createArapScratch(skin.vertices,skin.triangles,w,h,skin.solver),target=new Float32Array(skin.vertices.length*2),field=target.slice(),positions={};
 const card=compileBodyCard(record,record.genome),contact=createFamilyContactSolver(record),players={},timelines={};let lastContact;
 const rig={recipeHash:record.recipeHash,templateId:record.template.id,applyPose(pose){const matrices=program.evaluate(pose);applyCompiledSkinField(compiled,matrices,target);solveArapSkin(scratch,target,field);for(const p of skin.parts){const buf=new Float32Array(p.vertices.length*2);applyPaintPart(p,field,buf);assertPaintPartShape(p,skin,buf,w,h);positions[p.id]=buf;}}};
 function player(id){if(!players[id]){const tl=buildTimeline(card,id,record.identity.seed);let pose={};const p=createGsapPlayer(tl,{setJoint(j,rotation,dx,dy){pose[j]={rotation,dx,dy};}},{now:()=>0});players[id]={sample(ms){pose={};p.seek(ms);return pose;},stop:()=>p.stop()};timelines[id]=tl;}return players[id];}
 function action(id,ms){const p=player(id),tl=timelines[id];const owner=createCreatureRigPerformance(record,rig,[{id,durationMs:tl.durationMs,loop:tl.loop,dispose(){},seek(at,t){for(const[j,k]of Object.entries(p.sample(at)))t.setJoint(j,k.rotation,k.dx,k.dy);}}]);owner.play(id,0,0);return owner.update(ms,(pose,phase)=>{lastContact=contact.resolve(pose,{...phase,actionId:tl.actionId});return lastContact.pose;});}
 function presentation(ms){const idle=card.template.id.startsWith('plant-')?'sway':'idle',sequence=idle==='sway'?['disturb','harvest','grow']:['approach','melee:pinch','hit'],slot=8000/sequence.length;player(idle);let pose=closedLoopPose(player(idle).sample,ms,timelines[idle].durationMs),phase={actionId:timelines[idle].actionId,elapsedMs:ms,durationMs:timelines[idle].durationMs,weight:1};const smooth=x=>{x=Math.max(0,Math.min(1,x));return x*x*(3-2*x);};for(let i=0;i<sequence.length;i++){const id=sequence[i],start=1000+i*slot,end=start+slot;if(ms>=start&&ms<end){player(id);const age=ms-start,weight=Math.min(smooth(age/120),smooth((end-ms)/160)),q=id==='approach'?closedLoopPose(player(id).sample,age,timelines[id].bodyMs):player(id).sample(Math.min(Math.max(0,age-120),timelines[id].durationMs));pose=blendCreaturePoses(pose,q,weight);phase={actionId:timelines[id].actionId,elapsedMs:id==='approach'?age:Math.max(0,age-120),durationMs:timelines[id].durationMs,weight};}}lastContact=contact.resolve(pose,phase);rig.applyPose(lastContact.pose);return lastContact.pose;}
 return {record,binding,skin,w,h,program,scratch,target,field,positions,card,contact,rig,action,presentation,player,timelines,get lastContact(){return lastContact;},close(){for(const p of Object.values(players))p.stop();}};
}
function marks(f){return f.contact.chains.map(c=>{const owner=f.binding.parts.find(p=>p.joint===c.end),part=f.skin.parts.find(p=>p.id===owner.id),end=f.record.landmarks[c.end];let best;part.vertices.forEach((v,index)=>{const xy=[0,0];for(let k=0;k<3;k++){const p=f.skin.vertices[v.triangle[k]];xy[0]+=p.x*v.barycentric[k]/f.w;xy[1]+=p.y*v.barycentric[k]/f.h;}const distance=Math.hypot(xy[0]-end[0],xy[1]-end[1]);if(!best||distance<best.distance)best={joint:c.end,part:part.id,index,xy,distance,vertex:v};});return best;});}
function contactRows(f,pose){const matrices=f.program.evaluate(pose);return marks(f).flatMap(mark=>{const c=f.lastContact.contacts.find(c=>c.joint===mark.joint);if(!c.stance)return [];const p=f.positions[mark.part],current=[p[mark.index*2],p[mark.index*2+1]],rest=f.record.landmarks[mark.joint],m=matrices[mark.joint],offset=[mark.xy[0]-rest[0],mark.xy[1]-rest[1]],predicted=[c.target.x+m[0]*offset[0]+m[2]*offset[1],c.target.y+m[1]*offset[0]+m[3]*offset[1]],target=[c.target.x,c.target.y];return [{joint:mark.joint,part:mark.part,index:mark.index,sourceOffsetPx:Math.hypot(offset[0]*f.w,offset[1]*f.h),worldRotationDeg:Math.atan2(m[1],m[0])*180/Math.PI,driftPx:contactPaintDriftPx(current,mark.xy,target,rest,[f.w,f.h]),rotationOnlyPredictionPx:contactPaintDriftPx(predicted,mark.xy,target,rest,[f.w,f.h]),predictionErrorPx:Math.hypot((current[0]-predicted[0])*f.w,(current[1]-predicted[1])*f.h),supports:mark.vertex.triangle.flatMap((i,k)=>mark.vertex.barycentric[k]>1e-10?[{i,barycentric:mark.vertex.barycentric[k],pinned:!!f.scratch.pins[i],weights:f.skin.vertices[i].weights}]:[])}];});}
const contacts=[];
for(const name of ['mud-crab','vent-crab']){const f=fixture('crab-fits-03/'+name),report=read(path.join(base,name+'-native-04/report.json')),rows=report.gates.rows.filter(r=>r.failure&&r.id!=='approach:scuttle').map(r=>({id:r.id,ms:r.failure.ms,error:r.failure.error}));rows.push({id:'presentation',ms:report.gates.presentation.failure.ms,error:report.gates.presentation.failure.error});for(const r of rows){const pose=r.id==='presentation'?f.presentation(r.ms):f.action(r.id,r.ms),marks=contactRows(f,pose),joint=/drift ([^:]+):/.exec(r.error)[1],original=Number(r.error.split(': ').at(-1)),matched=marks.find(x=>x.joint===joint);assert(matched.driftPx>.25);assert(Math.abs(matched.driftPx-original)<1e-4,'Must reproduce retained drift');assert(matched.predictionErrorPx<1e-4,'Rigid endpoint rotation must account for actual field');assert(matched.supports.every(s=>s.pinned&&s.weights.length===1&&s.weights[0][0]===joint&&s.weights[0][1]===1));contacts.push({subject:name,...r,recordedDriftPx:original,measured:matched});}f.close();}
function folded(f,buf,normalized=false){const pos=i=>[buf[i*2]*(normalized?f.w:1),buf[i*2+1]*(normalized?f.h:1)],rows=[];for(let t=0;t<f.skin.triangles.length/3;t++){const indices=f.skin.triangles.slice(t*3,t*3+3),[a,b,c]=indices.map(pos),ratio=((b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]))/f.scratch.areas[t];if(ratio<=0||!Number.isFinite(ratio)){const parts=f.skin.parts.filter(p=>indices.every(i=>p.fieldTriangles.includes(i))).map(p=>p.id);rows.push({triangle:t,indices,ratio,sourceArea:f.scratch.areas[t],allPinned:indices.every(i=>f.scratch.pins[i]),pins:indices.filter(i=>f.scratch.pins[i]),parts,vertices:indices.map(i=>({...f.skin.vertices[i],position:pos(i)}))});}}return rows;}
const flora=[],f=fixture('persimmon-04');
for(const r of [{id:'rest',ms:0},{id:'disturb',ms:62},{id:'disturb',ms:67.16666666666667},{id:'presentation',ms:1200}]){let error=null;try{if(r.id==='rest')f.rig.applyPose({});else if(r.id==='presentation')f.presentation(r.ms);else f.action(r.id,r.ms);}catch(e){error=String(e);}const target=folded(f,f.target,true),final=folded(f,f.scratch.stats.rigid?f.field:f.scratch.position,f.scratch.stats.rigid),counts={};for(const t of final)for(const p of t.parts)counts[p]=(counts[p]??0)+1;flora.push({...r,error,stats:{...f.scratch.stats},orientation:{visits:f.scratch.orientationQueue.visits,projections:f.scratch.orientationQueue.projections,stalled:f.scratch.orientationQueue.stalled},targetFolds:target.length,allPinnedTargetFolds:target.filter(t=>t.allPinned).length,finalFolds:final.length,allPinnedFinalFolds:final.filter(t=>t.allPinned).length,parts:counts,foldedTriangles:final});}
assert.equal(flora[0].error,null);assert.equal(flora[0].finalFolds,0);assert.equal(flora[1].error,null);assert.equal(flora[2].finalFolds,84);assert.equal(flora[3].finalFolds,209);
const ablations=[],at=67.16666666666667,raw=f.player('disturb').sample(at);
for(const joints of [['leaf3'],['leaf4'],['leaf3','leaf4'],Object.keys(raw).filter(j=>j.startsWith('leaf'))]){
 const pose=structuredClone(raw);for(const j of joints)pose[j]={rotation:0,dx:0,dy:0};let error=null;
 try{f.rig.applyPose(pose);}catch(e){error=String(e);}
 ablations.push({control:'neutralize local foliage rotation (diagnostic only; not adopted)',joints,error,stats:{...f.scratch.stats}});
}
// Remove only leaf3/leaf4 rigid pins in a separate scratch instance. No binding is written.
applyCompiledSkinField(createCompiledSkinField(f.skin,f.w,f.h),f.program.evaluate(raw),f.target);
for(const joints of [['leaf3'],['leaf4'],['leaf3','leaf4']]){
 const pins=f.skin.solver.pins.filter(i=>!f.skin.vertices[i].weights.some(([j])=>joints.includes(j))),scratch=createArapScratch(f.skin.vertices,f.skin.triangles,f.w,f.h,{...f.skin.solver,pins}),output=f.field.slice();let error=null;
 try{solveArapSkin(scratch,f.target,output);for(const part of f.skin.parts){const p=new Float32Array(part.vertices.length*2);applyPaintPart(part,output,p);assertPaintPartShape(part,f.skin,p,f.w,f.h);}}catch(e){error=String(e);}
 ablations.push({control:'remove named rigid pins in memory (diagnostic only; not a valid candidate)',joints,removedPins:f.skin.solver.pins.length-pins.length,error,stats:{...scratch.stats}});
}
f.close();
const result={schema:'cf.anatomy-bounded-diagnosis/v1',producer:'6a58e40eeb552e925c94e0173d6298c4b05303e3',scope:'Offline actual timeline/performance/contact/compiled-field/ARAP replay at retained failure times; no native/CPU/visual qualification',contacts,flora,ablations,inputHashes:[...hashes].map(([path,sha256])=>({path,sha256}))};
fs.writeFileSync(path.join(out,'diagnosis-02.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({contacts:contacts.map(r=>({subject:r.subject,action:r.id,ms:r.ms,...r.measured})),flora:flora.map(({foldedTriangles,...r})=>r),ablations},null,2));
