/* One immutable local-study run. This is not a product certificate or admission lane.
 * Usage (after source review): node tools/with-toolchain-lock.mjs --label civet-study --
 *   node audits/CIVET_WATER_AND_MOTION_20260908/study-runner.mjs FRESH_OUTPUT_NAME
 */
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { build } from '../../port/v2/node_modules/vite/dist/node/index.js';
import { openChromiumCdp } from '../../port/v2/tools/browsercdp.mjs';
import { acquireWorkspaceLock } from '../../port/v2/tools/workspacelock.mjs';
const repo = fs.realpathSync(fileURLToPath(new URL('../..', import.meta.url))), base = path.dirname(fileURLToPath(import.meta.url));
assert.equal(fs.realpathSync(process.cwd()), repo); assert.equal(process.platform, 'darwin');
assert.equal(execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim(), repo);
assert.equal(execFileSync('git', ['branch', '--show-current'], { encoding: 'utf8' }).trim(), 'openai/mac');
assert.equal(process.argv.length, 3); assert(/^[a-z0-9][a-z0-9-]*$/.test(process.argv[2]), 'A fresh simple output name is required');
const out = path.join(base, process.argv[2]); assert(!fs.existsSync(out), 'Output exists; this runner does not retry or overwrite');
const release = acquireWorkspaceLock('Civet shallow water and articulated motion study'); fs.mkdirSync(out);
const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const write = (file, bytes) => fs.writeFileSync(path.join(out, file), bytes, { flag: 'wx' });
const report = { schema: 'cf-civet-water-motion-native/v1', certification: false, status: 'RUNNING', startedAt: new Date().toISOString(), sourceCommit: execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(), node: process.version, sources: {}, modes: [], runtimeErrors: [], cleanupErrors: [], pending: null, limitations: [
  'Standalone local authoring bench. No native Compendium, battle, world navigation, protected save or product certificate claim.',
  'One-view texture deformation supports finite breathing and neck brace/thrust/recoil, not jaw articulation, walking, a 3D rig or unseen anatomy.',
  'Single shared decoded Civet texture within each document; measurements are resource-owner facts, not native driver heap, device heat or a total app memory cap.',
  'Recovered matte retains attenuated whiskers and a small light fringe at magnification; production clean-edge and human art acceptance remain open.',
  'DOM-hidden cancellation and synthetic document-hidden event coverage are distinct. Physical background-tab/PWA/Safari behavior remains unqualified.',
] };
const persist = () => fs.writeFileSync(path.join(out, 'report.json'), JSON.stringify(report, null, 2) + '\n');
let server, browser;
const retainedPNGs=new Map();function png(file,data){assert(data.startsWith('data:image/png;base64,'));const bytes=Buffer.from(data.split(',')[1],'base64'),hash=sha(bytes);if(retainedPNGs.has(hash))return retainedPNGs.get(hash);write(file,bytes);const row={path:file,bytes:bytes.length,sha256:hash};retainedPNGs.set(hash,row);return row;}
const region=(frame,name)=>frame.metrics.regions.find(r=>r.name===name);
function acceptMotion(frames,clip){assert(frames.length>=1);for(const f of frames){assert(f.metrics,'Missing native baseline');assert(f.state.sourceIdentityUnchanged);for(let p=0;p<4;p++){const foot=region(f,'paw'+p);assert(foot.ink>0,'Paw has no native ink');assert.equal(foot.exactChanged,0,'Native paw pixels slid');}}
 if(clip==='breathe'){const phases=[1500,3000,4500].map(at=>{const f=frames.find(f=>f.state.elapsed>=at&&f.state.elapsed<at+250);assert(f,'Missing native breath phase '+at);const r=region(f,'chest');return{at,lift:r.beforeShape.top-r.afterShape.top,changed:r.changed};});for(const i of [0,2]){assert(phases[i].lift>2,'Breathing crest excursion is below 2 CSS pixels: '+phases[i].lift);assert(phases[i].changed>100,'No readable chest change');}assert(Math.abs(phases[1].lift)<.8,'Chest did not exhale between the two breaths');}
 else{const right=frames.map(f=>region(f,'head').afterShape.right-region(f,'head').beforeShape.right);if(clip==='strike'){assert(Math.min(...right)<-2,'No visible native anticipation');assert(Math.max(...right)>3,'No visible native forward thrust');}else assert(Math.min(...right)<-2,'No visible reaction');
 assert(frames.some(f=>{const r=region(f,'tail');return Math.hypot(r.afterShape.centroid.x-r.beforeShape.centroid.x,r.afterShape.centroid.y-r.beforeShape.centroid.y)>1;}),'Tail has no distinct native travel');
 for(const name of ['hindLeg','foreLeg'])assert(frames.some(f=>region(f,name).changed>20),'Missing native limb flex: '+name);}}
function decode(file){return execFileSync('/opt/homebrew/bin/magick',[path.join(out,file),'-depth','8','RGBA:-'],{maxBuffer:8*1024*1024});}
function keepScene(label,v){for(const key of ['before','after','background','ink','noOcclusion','noRipples','noShadows']){v[key]=png(`${label}-${key}.png`,v[key+'Png']);delete v[key+'Png'];}const before=decode(v.before.path),after=decode(v.after.path),bg=decode(v.background.path),ink=decode(v.ink.path),noOcc=decode(v.noOcclusion.path),noRipples=decode(v.noRipples.path),noShadows=decode(v.noShadows.path);const allowed=new Uint8Array(960*430);
 for(let y=0;y<430;y++)for(let x=0;x<960;x++)if(ink[(y*960+x)*4+3]>0)for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++)if(y+dy>=0&&y+dy<430&&x+dx>=0&&x+dx<960)allowed[(y+dy)*960+x+dx]=1;
 for(const r of v.owner.declaredRegions)for(let y=Math.max(0,Math.floor(r.bounds.y0));y<=Math.min(429,Math.ceil(r.bounds.y1));y++)for(let x=Math.max(0,Math.floor(r.bounds.x0));x<=Math.min(959,Math.ceil(r.bounds.x1));x++)allowed[y*960+x]=1;
 let outsideChanged=0,outsideObserved=0,legacyOutside=0,opaqueInk=0,lumaBefore=0,lumaAfter=0;const luma=(a,i)=>.2126*a[i]+.7152*a[i+1]+.0722*a[i+2];
 for(let i=0;i<before.length;i+=4){const index=i/4;if(!allowed[index]){outsideObserved++;if([0,1,2,3].some(c=>after[i+c]!==before[i+c]))outsideChanged++;}if(ink[i+3]===0&&[0,1,2,3].some(c=>before[i+c]!==bg[i+c]))legacyOutside++;if(ink[i+3]>=250){opaqueInk++;lumaBefore+=luma(before,i);lumaAfter+=luma(after,i);}}
 const contacts=v.owner.declaredContacts.map(c=>{const water=v.owner.declaredRegions.find(r=>r.paw===c.paw&&r.role==='waterline'),ripple=v.owner.declaredRegions.find(r=>r.paw===c.paw&&r.role==='broken-ripple');const shadow=v.owner.declaredRegions.find(r=>r.paw===c.paw&&r.role==='submerged-shadow');let immersedInk=0,closerToWater=0,rippleChanges=0,shadowDarkened=0;
  const center=(water.bounds.x0+water.bounds.x1)/2;for(let y=Math.max(0,Math.floor(water.bounds.y0));y<=Math.min(429,Math.ceil(water.bounds.y1));y++)for(let x=Math.max(0,Math.ceil(center-2.5));x<=Math.min(959,Math.floor(center+2.5));x++){const i=(y*960+x)*4;if(ink[i+3]<150)continue;immersedInk++;const d=a=>Math.abs(a[i]-bg[i])+Math.abs(a[i+1]-bg[i+1])+Math.abs(a[i+2]-bg[i+2]);if(d(noOcc)-d(after)>5)closerToWater++;}
  for(let y=Math.max(0,Math.floor(ripple.bounds.y0));y<=Math.min(429,Math.ceil(ripple.bounds.y1));y++)for(let x=Math.max(0,Math.floor(ripple.bounds.x0));x<=Math.min(959,Math.ceil(ripple.bounds.x1));x++){const i=(y*960+x)*4;if(ink[i+3]===0&&[0,1,2].some(k=>Math.abs(after[i+k]-noRipples[i+k])>1))rippleChanges++;}
  for(let y=Math.max(0,Math.floor(shadow.bounds.y0));y<=Math.min(429,Math.ceil(shadow.bounds.y1));y++)for(let x=Math.max(0,Math.floor(shadow.bounds.x0));x<=Math.min(959,Math.ceil(shadow.bounds.x1));x++){const i=(y*960+x)*4;if(ink[i+3]===0&&luma(noShadows,i)-luma(after,i)>1)shadowDarkened++;}return{id:c.id,immersedInk,closerToWater,rippleChanges,shadowDarkened};});
 v.pixels={outsideChanged,outsideObserved,legacyOutside,opaqueInk,lightRatio:lumaAfter/lumaBefore,contacts};return v;}
function acceptScene(v){assert.equal(v.pixels.legacyOutside,0,'Unpainted resident pixels remain');assert.equal(v.pixels.outsideChanged,0,'Water effect escaped declared local regions');assert(v.pixels.outsideObserved>350000);assert(v.pixels.opaqueInk>1000);assert(v.pixels.lightRatio>.83&&v.pixels.lightRatio<.96,'Scene light absent/excessive');assert.deepEqual(v.pixels.contacts.map(c=>c.id),['Civet:paw:0','Civet:paw:1','Civet:paw:2','Civet:paw:3']);for(const c of v.pixels.contacts){assert(c.immersedInk>0,'Empty immersion ruler '+c.id);assert(c.closerToWater>0,'Missing waterline immersion '+c.id);assert(c.rippleChanges>0,'Missing painted ripple '+c.id);assert(c.shadowDarkened>0,'Missing submerged shadow '+c.id);}assert.deepEqual(v.owner.alphaRow,[0,0,0,1,0]);}
try {
  for (const name of ['study.html', 'study-harness.ts', 'study-runner.mjs', 'serve-study.mjs', 'study.tsconfig.json', 'asset.json', 'water-owner.ts']) {
    const bytes = fs.readFileSync(path.join(base, name)); write(name, bytes); report.sources[path.relative(repo, path.join(base, name))] = sha(bytes);
  }
  const asset = JSON.parse(fs.readFileSync(path.join(base, 'asset.json'), 'utf8'));
  assert.equal(asset.schema, 'cf-painted-civet-study-asset/v2'); assert.equal(asset.path, 'civet-selected-v1.webp');
  const assetBase=path.join(base,'../CREATURE_SCENE_COHESION_20260908');
  const assetBytes = fs.readFileSync(path.join(assetBase, asset.path)); assert.equal(sha(assetBytes), asset.sha256); assert.equal(assetBytes.length, asset.bytes);
  const baselineBase = path.join(base, '../CREATURE_PAINTED_CIVET_20260908/baseline');
  const baseline = JSON.parse(fs.readFileSync(path.join(baselineBase, 'report.json'), 'utf8')); assert.equal(baseline.status, 'PASS');
  const scene = { background: { path: './study-assets/earth-background-original.webp', sha256: baseline.background.sha256, width: 960, height: 430 } };
  const normalized = { path: './study-assets/' + asset.path, sha256: asset.sha256, width: asset.width, height: asset.height, alphaBounds: asset.alphaBounds, contactY: asset.contactY, civetPaws: asset.civetPaws };
  report.asset = asset; report.scene = scene; persist();
  const dist = path.join(out, 'dist');
  await build({ root: base, configFile: false, logLevel: 'warn', resolve: { alias: { 'pixi.js': path.join(repo, 'port/v2/node_modules/pixi.js/lib/index.mjs') } }, define: { __CF_CIVET_ASSET__: JSON.stringify(normalized), __CF_CIVET_SCENE__: JSON.stringify(scene) }, plugins: [{ name: 'immutable-study-inputs', transform(_code, id) {
    const file = id.split('?')[0];
    if (file.startsWith(repo + path.sep) && !file.includes('/node_modules/') && fs.existsSync(file) && fs.statSync(file).isFile()) report.sources[path.relative(repo, file)] = sha(fs.readFileSync(file));
    return null;
  } }], build: { outDir: dist, emptyOutDir: false, minify: false, sourcemap: false, rollupOptions: { input: path.join(base, 'study.html') } } });
  fs.mkdirSync(path.join(dist, 'study-assets'));
  fs.copyFileSync(path.join(assetBase, asset.path), path.join(dist, 'study-assets', asset.path), fs.constants.COPYFILE_EXCL);
  for (const name of ['earth-background-original.webp']) {
    const bytes = fs.readFileSync(path.join(baselineBase, name)), expected = scene.background;
    assert.equal(sha(bytes), expected.sha256); fs.writeFileSync(path.join(dist, 'study-assets', name), bytes, { flag: 'wx' });
  }
  const mime = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png', '.webp': 'image/webp' };
  server = http.createServer((request, response) => {
    try {
      assert(['GET', 'HEAD'].includes(request.method)); const pathname = decodeURIComponent(new URL(request.url, 'http://127.0.0.1').pathname);
      const file = fs.realpathSync(path.resolve(dist, '.' + (pathname === '/' ? '/study.html' : pathname))); assert(file.startsWith(dist + path.sep));
      response.writeHead(200, { 'Content-Type': mime[path.extname(file)] || 'application/octet-stream', 'Cache-Control': 'no-store' }); response.end(request.method === 'HEAD' ? undefined : fs.readFileSync(file));
    } catch { response.writeHead(404); response.end(); }
  });
  await new Promise((resolve, reject) => { server.once('error', reject); server.listen(0, '127.0.0.1', resolve); });
  browser = await openChromiumCdp({ label: 'Civet water and articulated motion', userDataPrefix: 'cf-civet-water-motion-20260908', commandTimeoutMs: 15000, onEvent: event => { if (event.method === 'Runtime.exceptionThrown') report.runtimeErrors.push(event.params.exceptionDetails); } });
  report.browser = browser.browser;
 for(const mode of [{name:'desktop',width:1440,height:1000,dpr:1,mobile:false},{name:'phone',width:390,height:844,dpr:2,mobile:true}]){
  const result={...mode,status:'RUNNING',frames:[],controls:[],scenes:[],videos:[],events:[]};report.modes.push(result);persist();
  const {targetId}=await browser.send('Target.createTarget',{url:'about:blank'}),{sessionId}=await browser.send('Target.attachToTarget',{targetId,flatten:true});
  const send=(method,params={})=>browser.send(method,params,sessionId),api='window.__CF_WATER_STUDY__';
  const evaluate=async expression=>{report.pending={mode:mode.name,expression};const v=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});assert(!v.exceptionDetails,JSON.stringify(v.exceptionDetails));report.pending=null;return v.result.value;};
  const snapshot=()=>evaluate(`${api}.snapshot()`),waitFor=async(expression,ms=8000)=>{const deadline=Date.now()+ms;while(Date.now()<deadline){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,35));}throw Error('Native condition timed out: '+expression);};
  const frames=()=>evaluate('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r(true))))');
  const native=async id=>{await evaluate(`document.getElementById(${JSON.stringify(id)}).scrollIntoView({block:'center'})`);await frames();const h=await evaluate(`(()=>{const e=document.getElementById(${JSON.stringify(id)}),r=e.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2,h=document.elementFromPoint(x,y);return{x,y,width:r.width,height:r.height,hit:h===e||e.contains(h),disabled:e.disabled}})()`);assert(h.hit&&!h.disabled,'Unavailable control '+id);await send('Input.dispatchMouseEvent',{type:'mousePressed',x:h.x,y:h.y,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:h.x,y:h.y,button:'left',clickCount:1});await frames();result.events.push({id,hit:h});};
  const rest=s=>{assert.equal(s.clip,'rest');assert.equal(s.pendingRaf,false);assert(s.actors.every(a=>a.restExact));assert.deepEqual(s.failures,[]);};
  const capture=async label=>{const v=await evaluate(`${api}.nativeFrame()`);v.image=png(`${mode.name}-${label}.png`,v.png);delete v.png;result.frames.push(v);return v;};
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:mode.width,height:mode.height,deviceScaleFactor:mode.dpr,mobile:mode.mobile});await send('Page.navigate',{url:'http://127.0.0.1:'+server.address().port+'/'});await waitFor(`!!${api}`);result.initial=await evaluate(`${api}.ready`);await frames();rest(await snapshot());assert(await evaluate(`document.getElementById('rest').disabled`));const initial=await capture('initial-creature');
  for(const [next,times]of [['breathe',[1500,3000,4500]],['strike',[448,864,1248]],['recoil',[308,715]]]){
   await evaluate(`${api}.armRecording()`);const before=await snapshot();await native(next);const begun=await snapshot();assert.equal(begun.counters.started,before.counters.started+1);assert(begun.journal.some(x=>x.event==='request'&&x.clip===next&&x.trusted===true));const samples=[];
   for(const at of times){await waitFor(`${api}.snapshot().elapsed>=${at}&&${api}.snapshot().clip==='${next}'`);const sample=await capture(`${next}-${at}`);assert.equal(sample.state.sequence,begun.sequence);assert(sample.state.elapsed>=at&&sample.state.elapsed<at+250,'Missed live phase '+next+':'+at);samples.push(sample);}
   acceptMotion(samples,next);await waitFor(`${api}.snapshot().clip==='rest'`);const completed=await snapshot();rest(completed);assert.equal(completed.counters.completed,before.counters.completed+1);assert.equal(completed.counters.cancelled,before.counters.cancelled);assert.equal(completed.sequence,begun.sequence);assert.equal(completed.lastCancellation,'finite movement completed');assert(await evaluate(`document.getElementById('rest').disabled`));const settled=await capture(next+'-settled');assert.equal(settled.image.sha256,initial.image.sha256,'Paint did not settle exactly');await waitFor(`${api}.recording()?.done===true`);
   const video=await evaluate(`${api}.recording()`);assert(video.frames>30);const bytes=Buffer.from(video.dataURL.split(',')[1],'base64'),file=`${mode.name}-${next}-native.webm`;write(file,bytes);result.videos.push({path:file,bytes:bytes.length,sha256:sha(bytes),frames:video.frames,mime:video.mime});persist();
  }
  for(const mutation of ['constant-rest','subpixel','rigid-block','frozen-tail','held-breath']){
   await evaluate(`${api}.setMotionMutation('${mutation}')`);const next=mutation==='frozen-tail'?'strike':'breathe';await native(next);const times=next==='strike'?[448,864]:[1500,3000,4500],samples=[];for(const at of times){await waitFor(`${api}.snapshot().elapsed>=${at}&&${api}.snapshot().clip==='${next}'`);samples.push(await capture(`${mutation}-${at}`));}let rejection=null;try{acceptMotion(samples,next);}catch(e){rejection=String(e);}assert(rejection,'Native deficient-motion control accepted: '+mutation);result.controls.push({kind:mutation,rejected:true,reason:rejection});await native('rest');rest(await snapshot());await evaluate(`${api}.setMotionMutation('none')`);const restored=await capture(mutation+'-restored');assert.equal(restored.image.sha256,initial.image.sha256);}
  // Actual width change preserves the same active clip and sequence. Stop is a native user action.
  await native('breathe');await waitFor(`${api}.snapshot().elapsed>450`);const preResize=await snapshot();await send('Emulation.setDeviceMetricsOverride',{width:mode.name==='desktop'?900:mode.width-30,height:mode.height,deviceScaleFactor:mode.dpr,mobile:mode.mobile});await waitFor(`${api}.snapshot().canvas.width!==${preResize.canvas.width}&&${api}.snapshot().elapsed>${preResize.elapsed+30}`);await frames();const resized=await snapshot();assert.notEqual(resized.canvas.width,preResize.canvas.width);assert(resized.elapsed>preResize.elapsed&&resized.counters.frames>preResize.counters.frames&&resized.pendingRaf);assert.equal(resized.clip,'breathe');assert.equal(resized.sequence,preResize.sequence);assert.equal(resized.counters.cancelled,preResize.counters.cancelled);await native('rest');const stopped=await snapshot();rest(stopped);assert(stopped.journal.some(x=>x.event==='native-stop'&&x.trusted===true));await send('Emulation.setDeviceMetricsOverride',{width:mode.width,height:mode.height,deviceScaleFactor:mode.dpr,mobile:mode.mobile});await frames();result.controls.push({kind:'active-resize-and-native-stop',preResize,resized,stopped});
  for(const id of ['effects','reduced']){await native('breathe');await native(id);rest(await snapshot());const before=await snapshot();await native('strike');const refused=await snapshot();rest(refused);assert.equal(refused.counters.started,before.counters.started);await native(id);result.controls.push({kind:'native-'+id,refused});}
  await native('breathe');await native('hide');rest(await snapshot());await native('hide');rest(await snapshot());result.controls.push({kind:'native-hide'});
  await native('environment');assert.equal((await snapshot()).mode,'environment');const on=await capture('environment-water');await native('cohesion');const off=await capture('environment-off');assert.notEqual(on.image.sha256,off.image.sha256);await native('cohesion');const restoredWater=await capture('environment-restored');assert.equal(on.image.sha256,restoredWater.image.sha256);
  result.controls.push({kind:'native-painted-water-toggle',on:on.image,off:off.image,restored:restoredWater.image});
  const good=keepScene(mode.name+'-water',await evaluate(`${api}.sceneProbe('none')`));result.scenes.push(good);acceptScene(good);
  for(const mutation of ['noWater','noShadows','shiftWater','noLight','noOcclusion','noRipples','missingPaw','strongLight']){const v=keepScene(mode.name+'-'+mutation,await evaluate(`${api}.sceneProbe('${mutation}')`));result.scenes.push(v);let rejection=null;try{acceptScene(v);}catch(e){rejection=String(e);}assert(rejection,'Deficient water control accepted: '+mutation);result.controls.push({kind:mutation,rejected:true,reason:rejection});}
  const finalScene=keepScene(mode.name+'-water-restored',await evaluate(`${api}.sceneProbe('none')`));acceptScene(finalScene);assert.equal(finalScene.after.sha256,good.after.sha256);result.scenes.push(finalScene);
  await evaluate('window.scrollTo(0,0)');await frames();const geometry=await evaluate(`(()=>{const v=document.getElementById('study-view'),c=v.querySelector('canvas'),r=c.getBoundingClientRect(),t=document.querySelector('.toolbar').getBoundingClientRect();return{width:innerWidth,clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,canvas:r.toJSON(),toolbar:t.toJSON()}})()`);result.geometry=geometry;assert.equal(geometry.scrollWidth,geometry.clientWidth);assert(geometry.canvas.width>0&&geometry.canvas.width<=geometry.clientWidth);assert(geometry.canvas.y>=geometry.toolbar.bottom-1,'Toolbar covers visible scene');const shot=await send('Page.captureScreenshot',{format:'png'});write(`${mode.name}-native-environment.png`,Buffer.from(shot.data,'base64'));
  const retiredWater=await evaluate(`${api}.retireWater()`);retiredWater.scene=png(`${mode.name}-water-retired.png`,retiredWater.scenePng);delete retiredWater.scenePng;retiredWater.sibling=png(`${mode.name}-sibling-after-water-disposal.png`,retiredWater.siblingPng);delete retiredWater.siblingPng;assert(retiredWater.siblingInk>1000);result.retiredWater=retiredWater;assert.equal(retiredWater.restoredSceneChannelChanges,0);assert(retiredWater.siblingTextureAlive);assert(retiredWater.state.disposed);assert(retiredWater.state.graphics.every(g=>g.destroyed&&g.contextDestroyed));assert(retiredWater.state.waterSprites.every(s=>s.destroyed));assert(retiredWater.state.submergedRoot.destroyed&&retiredWater.state.surfaceRoot.destroyed&&retiredWater.state.filterDestroyed);assert(retiredWater.state.borrowedSourcesIntact&&retiredWater.state.meshTransformUnchanged);assert(retiredWater.state.borrowed.every(b=>b.alive&&b.parentIntact&&b.indexRestored&&b.filtersRestored&&b.transformUnchanged));assert.deepEqual(retiredWater.state.failures,[]);
  const retired=await evaluate(`${api}.dispose()`);result.retired=retired;assert(retired.disposed&&retired.earthDestroyed);assert.equal(retired.counters.meshesDestroyed,2);assert.equal(retired.counters.geometriesDestroyed,2);assert.equal(retired.counters.texturesDestroyed,2);assert.equal(retired.counters.sourcesDestroyed,2);assert.equal(retired.counters.bitmapsClosed,2);assert(retired.actors.every(a=>a.meshDestroyed&&a.geometryDestroyed&&a.rootDestroyed&&a.buffers.length>=3&&a.buffers.every(b=>b.destroyed)));assert(retired.resources.every(r=>r.textureDestroyed&&r.sourceDestroyed&&r.bitmapWidth===0));rest(retired);assert.deepEqual((await evaluate(`${api}.dispose()`)).counters,retired.counters);await browser.send('Target.closeTarget',{targetId});result.status='PASS';persist();
 }
 for(const [file,expected]of Object.entries(report.sources))assert.equal(sha(fs.readFileSync(path.join(repo,file))),expected,'Source changed: '+file);assert.deepEqual(report.runtimeErrors,[]);
 const inventory=[];const walk=directory=>{for(const entry of fs.readdirSync(directory,{withFileTypes:true})){const full=path.join(directory,entry.name);if(entry.isDirectory())walk(full);else{const bytes=fs.readFileSync(full);inventory.push({path:path.relative(dist,full),bytes:bytes.length,sha256:sha(bytes)});}}};walk(dist);report.dist={path:path.relative(repo,dist),inventory};report.status='PASS';
}catch(error){report.status='FAIL';report.failure=String(error?.stack||error);process.exitCode=1;}
finally{if(browser)try{await browser.close();report.browserClosed=true;}catch(error){report.cleanupErrors.push(String(error));}if(server)try{await new Promise(resolve=>server.close(resolve));}catch(error){report.cleanupErrors.push(String(error));}try{release();}catch(error){report.cleanupErrors.push(String(error));}if(report.cleanupErrors.length){report.status='FAIL';process.exitCode=1;}report.finishedAt=new Date().toISOString();persist();console.log(JSON.stringify({status:report.status,out,modes:report.modes.map(m=>({name:m.name,status:m.status,frames:m.frames.length,controls:m.controls.length,videos:m.videos.length})),failure:report.failure,runtimeErrors:report.runtimeErrors.length,cleanupErrors:report.cleanupErrors},null,2));}
