import fs from 'node:fs';import path from 'node:path';import {execFileSync} from 'node:child_process';import {actionsFor} from '../../../port/v2/apps/game/src/motion/family-actions.ts';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {createFamilyContactSolver} from '../../../port/v2/apps/game/src/creature-rig-contact.ts';
import {fixture,contactRows} from '../../ANATOMY_SINGLE_RUN_20260919/R3-S/offline.ts';
import {createSourceJoinProbe,assessSourceJoinContinuity} from '../../../port/v2/tools/quadruped-proof/source-join-continuity.mjs';
const mode=process.env.CF_STATIC_SUPPORTS??'observed';assert(['rest','observed'].includes(mode),'Explicit supports mode');
const input=path.resolve('audits/VISION_D2_GUARDIAN_20260921/fit-01'),out=process.env.CF_STATIC_OUTPUT??input+'/static.json';if(fs.existsSync(out))throw Error('New output required');const req=createRequire(process.cwd()+'/port/v2/package.json'),{PNG}=createRequire(req.resolve('free-tex-packer-core'))('pngjs'),f=fixture(input),contactOwner=mode==='rest'?Object.assign(f.contact,createFamilyContactSolver(f.record)):f.contact,manifest=JSON.parse(fs.readFileSync(input+'/parts/manifest.json')),atlas=PNG.sync.read(fs.readFileSync(input+'/parts/atlas/'+manifest.creatureId+'.png')),probe=createSourceJoinProbe({record:f.record,binding:f.binding,atlas:{width:atlas.width,height:atlas.height,rgba:atlas.data}}),ids=[...new Set(['idle','approach','melee:bite',...Object.keys(actionsFor(f.card.template.id,f.card.anatomy))])],report={supportsMode:mode,solverProducer:execFileSync('git',['log','-1','--format=%H','--','port/v2/apps/game/src/creature-rig-contact.ts'],{encoding:'utf8'}).trim(),fitProducer:'1ff30009d9b8cda3a92d72a2ef07a36c8506d91b',fitRecipeHash:f.record.recipeHash,bindingHash:f.binding.bindingHash,producer:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),scope:'Static authored rows plus presentation; guardian CPU and 60 px compiler comparison NOT measured here',rows:[],contacts:f.contact.chains.map(c=>c.end),status:'PASS',exactRest:false};
try{f.rig.applyPose({});const rest=structuredClone(f.positions);for(const id of [...ids,'presentation']){let ms=0;const row={id,samples:0,maxPaintDriftPx:0,maxGapPx:0,maxJointErrorPx:0,paintGate:'PASS',solverCompleted:false,error:null};report.rows.push(row);try{if(id!=='presentation')f.player(id);const n=id==='presentation'?600:120;for(let i=0;i<=n;i++){ms=id==='presentation'?i*1000/60:f.timelines[id].durationMs*i/n;const pose=id==='presentation'?f.presentation(ms):f.action(id,ms),contacts=contactRows(f,pose),seams=assessSourceJoinContinuity(probe,f.positions);row.samples++;row.maxJointErrorPx=Math.max(row.maxJointErrorPx,f.lastContact.maxError*Math.max(f.w,f.h));row.maxPaintDriftPx=Math.max(row.maxPaintDriftPx,...contacts.map(c=>c.driftPx),0);row.maxGapPx=Math.max(row.maxGapPx,seams.maxGapPx);if(seams.status!=='PASS')throw Error('Source join gap '+seams.maxGapPx);if(row.maxPaintDriftPx>.25){row.paintGate='RED';if(mode==='observed')throw Error('Paint drift '+row.maxPaintDriftPx);}}row.solverCompleted=true;if(row.paintGate==='RED')report.status='RED';f.rig.applyPose({});assert.deepEqual(f.positions,rest);}
catch(e){row.error={ms,message:String(e.stack??e),contact:f.lastContact,pose:f.lastPose};report.status='RED';}console.log(JSON.stringify({id,samples:row.samples,drift:row.maxPaintDriftPx,gap:row.maxGapPx,solverCompleted:row.solverCompleted,paintGate:row.paintGate,error:row.error?.message.split('\n')[0]}));}
f.rig.applyPose({});assert.deepEqual(f.positions,rest);report.exactRest=true;}finally{f.close();fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');}
if(report.status!=='PASS')process.exitCode=1;
