import fs from 'node:fs';import http from 'node:http';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {openChromiumCdp} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/browsercdp.mjs';
const root='/Users/nick/Projects/celestial-frontier-openai-mac/audits/CREATURE_BLENDER_CANID_20260908/comparison';const out=root+'/native-review';fs.mkdirSync(out);
const bytes=fs.readFileSync(root+'/review.html');const errors=[];const report={schema:'cf-canid-review-document-check/v1',status:'FAIL',certification:false,htmlSha256:crypto.createHash('sha256').update(bytes).digest('hex'),errors,rows:[]};let browser,server;
try{
 server=http.createServer((req,res)=>{if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);res.end();return;}if(req.url!=='/'){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end(req.method==='HEAD'?undefined:bytes);});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 browser=await openChromiumCdp({label:'offline Wolf comparison',userDataPrefix:'cf-canid-review',onEvent:e=>{if(e.method==='Runtime.exceptionThrown')errors.push(e.params.exceptionDetails.text);}});report.browser=browser.browser;
 const {targetId}=await browser.send('Target.createTarget',{url:'about:blank'});const {sessionId}=await browser.send('Target.attachToTarget',{targetId,flatten:true});const send=(method,params={})=>browser.send(method,params,sessionId);
 await send('Runtime.enable');await send('Page.enable');
 const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});assert(!r.exceptionDetails,JSON.stringify(r.exceptionDetails));return r.result.value;};
 await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:'http://127.0.0.1:'+server.address().port+'/'});
 let ready=false;for(let n=0;n<100;n++){ready=await evaluate('document.querySelectorAll("img").length===10&&[...document.images].every(i=>i.complete&&i.naturalWidth===i.width)');if(ready)break;await new Promise(r=>setTimeout(r,100));}assert(ready,'all ten review images must decode at declared dimensions');
 report.rows.push(await evaluate('({width:innerWidth,images:[...document.images].map(i=>({width:i.width,naturalWidth:i.naturalWidth,alt:i.alt})),bodyOverflow:document.documentElement.scrollWidth>innerWidth})'));
 assert.equal(report.rows[0].bodyOverflow,false);let shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(out+'/desktop.png',Buffer.from(shot.data,'base64'));
 await evaluate('document.querySelector("#pose").value="081";document.querySelector("#pose").dispatchEvent(new Event("change"));');await evaluate('document.querySelector("#pose-image").decode()');assert.equal(await evaluate('document.querySelector("#pose-image").alt'),'Wolf frame 81');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});await evaluate('window.scrollTo(0,0)');report.rows.push(await evaluate('({width:innerWidth,bodyOverflow:document.documentElement.scrollWidth>innerWidth,strips:[...document.querySelectorAll(".strip")].map(x=>({width:x.clientWidth,scrollWidth:x.scrollWidth}))})'));
 assert.equal(report.rows[1].width,390);assert.equal(await evaluate("document.documentElement.clientWidth"),390);assert.equal(await evaluate("document.documentElement.scrollWidth"),390);assert.equal(report.rows[1].bodyOverflow,false);shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(out+'/phone.png',Buffer.from(shot.data,'base64'));
 assert.equal(errors.length,0);report.status='PASS';
}catch(error){report.failure=String(error.stack||error);process.exitCode=1;}
finally{if(browser)try{await browser.close();}catch(e){report.status='FAIL';errors.push(String(e));process.exitCode=1;}if(server)await new Promise(resolve=>server.close(resolve));fs.writeFileSync(out+'/review.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,rows:report.rows,errors,failure:report.failure}));}
