import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{createHash}from'node:crypto';import{createRequire}from'node:module';
import{intakeAuthoredPixels}from'../../port/v2/tools/creature-animation/authored-intake.mjs';
import{cutAuthoredParts,assertRestCoverage}from'../../port/v2/tools/creature-animation/part-masks.mjs';
import{hashJSON}from'../../port/v2/tools/creature-animation/quadruped-template.mjs';
import{placeRemainderIslands,MAX_SHARE}from'../G1_AUTO_AUTHOR_20260926/remainder-islands-fit.mjs';
const base='audits/C168_PRIMATE_REFERENCES_20261002',req=createRequire(path.resolve('port/v2/package.json')),sharp=createRequire(req.resolve('free-tex-packer-core'))('sharp'),sha=b=>createHash('sha256').update(b).digest('hex'),json=p=>JSON.parse(fs.readFileSync(p)),rows=[];
assert.equal(MAX_SHARE,.05);
function ownershipEquals(labels,rgba){for(let i=0;i<labels.length;i++){const k=labels[i];if(!k)assert.equal(rgba[i*4+3],0,'ownership background');else assert.deepEqual([...rgba.subarray(i*4,i*4+3)],[(k*83)%200+35,(k*137)%200+35,(k*47)%200+35],'ownership replay differs');}}
for(const p of json(base+'/packets.json')){
 const fit=p.packet+'/fit01',master=fs.readFileSync(p.packet+'/master.png'),source=fs.readFileSync(p.source+'/master.png'),record=json(fit+'/record.json'),declaration=json(fit+'/declaration.json');assert.equal(sha(master),sha(source));
 const {data,info}=await sharp(master).ensureAlpha().raw().toBuffer({resolveWithObject:true}),key=intakeAuthoredPixels(new Uint8ClampedArray(data),info.width,info.height),cut=await cutAuthoredParts(record,master,key.rgba,declaration);
 const actualKey=await sharp(fit+'/parts/keyed.png').ensureAlpha().raw().toBuffer();assert.deepEqual(Buffer.from(key.rgba),actualKey,'exact established keyer output');assertRestCoverage(key.rgba,info.width,info.height,cut.parts);
 const actualOwnership=await sharp(fit+'/parts/ownership.png').ensureAlpha().raw().toBuffer();ownershipEquals(cut.labels,actualOwnership);const again=await cutAuthoredParts(record,master,key.rgba,declaration);assert.deepEqual(cut.labels,again.labels,'deterministic ownership replay');
 const index=cut.parts[0].rgba.findIndex((v,i)=>i%4===3&&v>0)-3;assert(index>=0);const missing=structuredClone(cut.parts);missing[0].rgba[index+3]=0;assert.throws(()=>assertRestCoverage(key.rgba,info.width,info.height,missing),/missing\/extra painted pixel/);
 const duplicate=[...cut.parts,cut.parts[0]];assert.throws(()=>assertRestCoverage(key.rgba,info.width,info.height,duplicate),/overlapping visible parts/);
 const recolored=structuredClone(cut.parts);recolored[0].rgba[index]^=1;assert.throws(()=>assertRestCoverage(key.rgba,info.width,info.height,recolored),/changed master colour/);
 const changed=Buffer.from(master);changed[changed.length-1]^=1;await assert.rejects(()=>cutAuthoredParts(record,changed,key.rgba,declaration),/hash/i);
 const corrupt={...declaration,declarationHash:'0'.repeat(64)};await assert.rejects(()=>cutAuthoredParts(record,master,key.rgba,corrupt),/corrupted declaration/);
 const invented=structuredClone(declaration);invented.parts[0].joint='invented-far-eye';delete invented.declarationHash;invented.declarationHash=await hashJSON(invented);await assert.rejects(()=>cutAuthoredParts(record,master,key.rgba,invented),/unknown joint/);
 const remainder=cut.parts.findIndex(x=>x.id==='body')+1;let islands;try{const v=placeRemainderIslands(cut.labels,info.width,info.height,remainder);islands={status:'PASS',remainderPixels:v.remainderPixels,movedPixels:v.moved,islands:v.islands,applied:false};}catch(e){islands={status:'REFUSED',reason:e.message,applied:false};}
 const stat=json(p.packet+'/static01.json');rows.push({id:p.id,name:p.name,masterSha256:sha(master),sourceMasterUnchanged:true,authoringSha256:sha(fs.readFileSync(p.packet+'/authoring.json')),recordRecipeHash:record.recipeHash,bindingHash:json(fit+'/binding.json').bindingHash,dimensions:{width:info.width,height:info.height},sourceRgbaChanges:0,exactKeyedRgba:true,exactOwnershipReplay:true,deterministicRepeat:true,exactPartReconstruction:true,controls:['deleted paint refused','duplicate paint refused','recolored paint refused','changed master refused','corrupt declaration refused','invented joint refused'],unchangedIslandCap:MAX_SHARE,islands,staticStatus:stat.status,actionRows:stat.rows.length,redRows:stat.rows.filter(r=>r.status!=='PASS').map(r=>({id:r.id,ms:r.firstRefusal?.ms,error:r.firstRefusal?.error?.split('\n')[0]})),presentation:{status:stat.presentation?.status,action:stat.presentation?.firstRefusal?.action,ms:stat.presentation?.firstRefusal?.ms,error:stat.presentation?.firstRefusal?.error?.split('\n')[0]},qualityAccepted:false,nativeRuns:0});
}
const synthetic=(large)=>{const w=20,h=10,labels=new Uint8Array(w*h);for(let y=1;y<=6;y++)for(let x=1;x<=10;x++)labels[y*w+x]=1;labels[4*w+15]=1;labels[5*w+15]=1;if(large){labels[4*w+14]=1;labels[5*w+14]=1;}labels[4*w+16]=2;return{w,h,labels};};
let s=synthetic(false);assert.equal(placeRemainderIslands(s.labels,s.w,s.h,1).moved,2);s=synthetic(true);assert.throws(()=>placeRemainderIslands(s.labels,s.w,s.h,1),/structural, not a sliver/);
const helpers=['audits/C163_REFERENCE_REPAIR_20261002/intake-v2.mjs','audits/C163_REFERENCE_REPAIR_20261002/static-runner.mjs','audits/C163_REFERENCE_REPAIR_20261002/static.ts','port/v2/tools/creature-animation/part-masks.mjs','port/v2/tools/creature-animation/authored-intake.mjs','audits/G1_AUTO_AUTHOR_20260926/remainder-islands-fit.mjs'];
const proof={schema:'cf.c168-primate-reference-proof/v1',status:'CONSERVATION_CONTROLS_PASS_CANDIDATES_HELD',rows,capControls:['2/62 pixels moves under unchanged 5%','4/64 pixels refuses under unchanged 5%'],helpers:helpers.map(path=>({path,sha256:sha(fs.readFileSync(path))})),nativeRuns:0,globalPoolChanged:false};
fs.writeFileSync(base+'/proof.json',JSON.stringify(proof,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(proof,null,2));
