/** Three exact attempted canonical poses only; no row replay or acceptance. */
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {compileBodyCard,buildTimeline,createGsapPlayer} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/apps/game/src/motion/index.ts';
import {createCreatureRigPerformance} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/apps/game/src/creature-rig-performance.ts';
import {createFamilyContactSolver,observedContactSupports,predictContactSupport,contactPaintDriftPx} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/apps/game/src/creature-rig-contact.ts';
import {familyContractForRecord} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/creature-animation/family-contracts.mjs';
import {createSkeletonPoseProgram} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/creature-animation/skeleton-pose.mjs';
import {createCompiledSkinField,applyCompiledSkinField} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/creature-animation/compiled-skin-field.mjs';
import {createArapScratch,solveArapSkin} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/creature-animation/arap-skin.mjs';
import {applyPaintPart,assertPaintPartShape} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/creature-animation/paint-skin.mjs';
const base='/Users/nick/Projects/celestial-frontier-openai-mac/audits/ARCHETYPE_FINISH_20260923/12-myriapod',out=path.join(base,'static-paint-diagnosis05/later-arap/report.json');assert(!fs.existsSync(out));
const sha=b=>createHash('sha256').update(b).digest('hex'),inputs=new Map();const read=rel=>{const file=path.join(base,rel),b=fs.readFileSync(file);inputs.set(file,sha(b));return JSON.parse(b.toString());};
const record=read('fit-08/record.json'),binding=read('fit-08/binding.json'),original=read('static-05.json'),prior=read('static-paint-diagnosis05/report.json'),pre=read('fit-08/pre-regional-binding.json'),regions=read('fit-08/regional-authoring-receipt.json');assert.equal(record.recipeHash,original.recordRecipeHash);assert.equal(binding.bindingHash,original.bindingHash);assert.equal(binding.bindingHash,prior.bindingHash);
const skin=binding.paintSkin,w=record.geometry.width,h=record.geometry.height,pins=new Set(skin.solver.pins),prePins=new Set(pre.paintSkin.solver.pins),card=compileBodyCard(record,record.genome),program=createSkeletonPoseProgram(familyContractForRecord(record),record.landmarks),compiled=createCompiledSkinField(skin,w,h),supports=observedContactSupports(record,binding);
const triKey=t=>t.slice().sort((a,b)=>a-b).join(','),triangleOwners=new Map(),vertexOwners=new Map();for(const part of skin.parts){for(let k=0;k<part.fieldTriangles.length;k+=3){const key=triKey(part.fieldTriangles.slice(k,k+3));if(!triangleOwners.has(key))triangleOwners.set(key,new Set());triangleOwners.get(key).add(part.id);}for(const v of part.vertices)for(const i of v.triangle){if(!vertexOwners.has(i))vertexOwners.set(i,new Set());vertexOwners.get(i).add(part.id);}}
const area=(xy,t)=>(xy[t[1]*2]-xy[t[0]*2])*(xy[t[2]*2+1]-xy[t[0]*2+1])-(xy[t[1]*2+1]-xy[t[0]*2+1])*(xy[t[2]*2]-xy[t[0]*2]);const union=new Map(),rows=[];
for(const [action,start]of [['hit',5],['dodge',7]]){
 const retained=original.rows.find(r=>r.id===action);assert.equal(retained.firstRefusal.sampleIndex,start-1);assert(prior.findings.some(f=>f.action===action&&f.reproduced));
 const tl=buildTimeline(card,action,record.identity.seed),scratch=createArapScratch(skin.vertices,skin.triangles,w,h,skin.solver),target=new Float32Array(skin.vertices.length*2),field=new Float32Array(target.length);let sampled={},raw,phase,lastContact,attemptedPose,stage;
 const positions={},contact=createFamilyContactSolver(record,supports),gsap=createGsapPlayer(tl,{setJoint(j,rotation,dx,dy){sampled[j]={rotation,dx,dy};}},{now:()=>0});
 const rig={recipeHash:record.recipeHash,templateId:record.template.id,applyPose(pose){attemptedPose=pose;stage='target';applyCompiledSkinField(compiled,program.evaluate(pose),target);stage='arap';solveArapSkin(scratch,target,field);stage='part-shape';for(const part of skin.parts){const buf=new Float32Array(part.vertices.length*2);applyPaintPart(part,field,buf);assertPaintPartShape(part,skin,buf,w,h);positions[part.id]=buf;}}};
 const owner=createCreatureRigPerformance(record,rig,[{id:action,durationMs:tl.durationMs,loop:tl.loop,dispose(){},seek(ms,t){sampled={};gsap.seek(ms);for(const[j,k]of Object.entries(sampled))t.setJoint(j,k.rotation,k.dx,k.dy);}}]);owner.play(action,0,0);
 const marks=contact.chains.map(chain=>{const part=skin.parts.find(p=>p.id===binding.parts.find(p=>p.joint===chain.end)?.id);let best;part.vertices.forEach((v,index)=>{const xy=[0,0];for(let k=0;k<3;k++){xy[0]+=skin.vertices[v.triangle[k]].x*v.barycentric[k]/w;xy[1]+=skin.vertices[v.triangle[k]].y*v.barycentric[k]/h;}const end=record.landmarks[chain.end],distance=Math.hypot(xy[0]-end[0],xy[1]-end[1]);if(!best||distance<best.distance)best={joint:chain.end,part:part.id,index,xy,distance};});return best;});
 const row={action,startIndex:start,endIndex:120,attempted:0,pass:0,errors:[],firstErrorExamples:{}};
 try{for(let index=start;index<=120;index++){
  const ms=tl.durationMs*index/120;row.attempted++;stage='sampling';raw=null;lastContact=null;attemptedPose=null;field.fill(123);
  try{owner.update(ms,(pose,context)=>{raw=structuredClone(pose);phase={...context,actionId:tl.actionId,realm:card.realm,...tl.actionId.startsWith('melee:')?{travel:'stage'}:{}};stage='contact';lastContact=contact.resolve(pose,phase);return lastContact.pose;});stage='painted-contact';assert(lastContact.maxError<=1e-8);for(const c of lastContact.contacts){if(!c.stance)continue;const m=marks.find(m=>m.joint===c.joint),p=positions[m.part],drift=contactPaintDriftPx([p[m.index*2],p[m.index*2+1]],m.xy,[c.target.x,c.target.y],record.landmarks[c.joint],[w,h]);if(drift>.25)throw Error('Contact paint drift '+c.joint+': '+drift);}row.pass++;
  }catch(error){const folded=[];if(stage==='arap'&&error.code==='ARAP_FOLD')for(let k=0;k<skin.triangles.length;k+=3){const ids=skin.triangles.slice(k,k+3),ratio=area(scratch.position,ids)/scratch.areas[k/3];if(Number.isFinite(ratio)&&ratio>0)continue;const triangle=k/3,targetRatio=area(scratch.target,ids)/scratch.areas[k/3];folded.push({triangle,ratio,targetRatio});if(!union.has(triangle))union.set(triangle,{triangle,indices:ids,parts:[...(triangleOwners.get(triKey(ids))??[])],vertices:ids.map(i=>({index:i,restPx:[skin.vertices[i].x,skin.vertices[i].y],pinned:pins.has(i),inheritedPin:prePins.has(i),weights:skin.vertices[i].weights,parts:[...(vertexOwners.get(i)??[])],regionalSelections:(regions.regions??[]).filter(r=>r.vertexIndices.includes(i)).map(r=>({id:r.id,joint:r.joint,pin:r.pin}))})),firstSample:{action,index,ms,phase,rawPose:raw,resolvedPose:attemptedPose,targets:ids.map(i=>[target[i*2]*w,target[i*2+1]*h]),privateFailed:ids.map(i=>[scratch.position[i*2],scratch.position[i*2+1]])},events:[]});union.get(triangle).events.push({action,index,ms,ratio,targetRatio});}
   const entry={sampleIndex:index,ms,phase,stage,error:String(error.stack??error),code:error.code??null,cause:error.cause?String(error.cause.stack??error.cause):null,stats:stage==='arap'?{...scratch.stats}:null,folded,outputUnpublished:stage==='arap'?field.every(x=>x===123):null};row.errors.push(entry);if(!row.firstErrorExamples[stage])row.firstErrorExamples[stage]={...entry,rawPose:raw,resolvedPose:attemptedPose,contact:lastContact};
  }
 }}finally{gsap.stop();owner.dispose();}rows.push(row);
}
const triangles=[...union.values()].sort((a,b)=>a.triangle-b.triangle),parts=[...new Set(triangles.flatMap(t=>t.parts))].map(part=>{const ts=triangles.filter(t=>t.parts.includes(part)),events=ts.flatMap(t=>t.events);return {part,faces:ts.map(t=>t.triangle),faceCount:ts.length,rootPins:[...new Set(ts.flatMap(t=>t.vertices.filter(v=>v.pinned&&v.weights[0][0]==='root').map(v=>v.index)))],kneePins:[...new Set(ts.flatMap(t=>t.vertices.filter(v=>v.pinned&&v.weights[0][0].endsWith('Knee')).map(v=>v.index)))],actions:['hit','dodge'].map(action=>{const ev=events.filter(e=>e.action===action),samples=[...new Set(ev.map(e=>e.ms))];return {action,samples:samples.length,firstMs:samples.length?Math.min(...samples):null,lastMs:samples.length?Math.max(...samples):null};})};});
const result={schema:'cf.later-arap-diagnostic/v1',scope:'Exactly hit5..120 and dodge7..120,230 previously unexecuted later ARAP samples. Earlier passes/first failures referenced from retained source reports. Contact, target, ARAP, part-shape and existing painted-contact guards only; no source-join/rest/other rows/presentation/native acceptance.',recordRecipeHash:record.recipeHash,bindingHash:binding.bindingHash,priorFirstFailuresReference:'../report.json',rows,triangles,parts,inputs:[...inputs].map(([file,sha256])=>({file,sha256,unchanged:sha(fs.readFileSync(file))===sha256}))};assert.equal(rows.reduce((n,r)=>n+r.attempted,0),230);assert(result.inputs.every(i=>i.unchanged));fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({output:out,rows:rows.map(r=>({action:r.action,attempted:r.attempted,pass:r.pass,errors:r.errors.length,errorStages:[...new Set(r.errors.map(e=>e.stage))]})),faceUnion:triangles.length,parts:parts.map(p=>({part:p.part,faces:p.faceCount,actions:p.actions}))},null,2));
