/** Grounded, folded-wing bird source study. Missing views are not invented. */
import fs from'node:fs';import path from'node:path';import{sealPortableFamilyRecord as sealFamilyRecord}from'../creature-animation/portable-record-writer.mjs';import{hashBytes,hashJSON}from'../creature-animation/quadruped-template.mjs';import{buildAuthoredParts}from'../creature-animation/build-authored-parts.mjs';import{buildPaintSkin}from'../creature-animation/build-paint-skin.mjs';import{smoothSkinWeights}from'../creature-animation/smooth-skin-weights.mjs';
const out=path.resolve(process.argv[2]);if(fs.existsSync(out))throw Error('New directory required');fs.mkdirSync(out,{recursive:true});const source='audits/ART_KIT_ENGINE_FIRST_20260912/masters/family-bird.png',master=fs.readFileSync(source),write=(n,v)=>fs.writeFileSync(path.join(out,n),JSON.stringify(v,null,2)+'\n');
const landmarks={root:[.66,.49],pelvis:[.55,.53],spine:[.66,.46],chest:[.77,.40],neck0:[.79,.30],neck1:[.80,.21],head:[.80,.13],beak:[.885,.14],legNearKnee:[.565,.66],legNearAnkle:[.53,.81],legNearFoot:[.565,.89],legFarKnee:[.69,.66],legFarAnkle:[.725,.785],legFarFoot:[.755,.858],wingNearRoot:[.65,.36],wingNearTip:[.465,.56],wingFarRoot:[.70,.38],wingFarTip:[.58,.51],tailFan:[.12,.45]};
const record=await sealFamilyRecord({kind:'biped-bird',identity:{speciesVisualKey:'authored:accepted-bird-family-master',seed:424242,ownerId:'authored:bird-family/accepted-master',earthName:null},template:{id:'biped-bird',version:1},geometry:{cutoutAssetHash:await hashBytes(master),width:1254,height:1254,groundLineY:.94,depthLayers:[{id:'far',order:0},{id:'near',order:1}]},landmarks,materials:{surface:'feathers'},clipSetId:'biped-bird-v1',source,coverage:{scope:'painted bird family reference, folded wings',occluded:['far wing; anatomy exists but has no independent painted pixels'],unproven:['open wing or flight','ground contact solver','named species identity','battle staging']}});write('record.json',record);
const parts=[],part=(id,joint,polygon,layer='near')=>parts.push({id,joint,polygon,layer});
part('near-foot','legNearFoot',[[.45,.855],[.65,.84],[.68,1],[.45,1]]);part('far-foot','legFarFoot',[[.665,.818],[.875,.812],[.88,.95],[.66,.95]],'far');
part('beak','beak',[[.842,.107],[.94,.09],[.95,.17],[.851,.169]]);
part('head','head',[[.72,.045],[.9,.045],[.9,.19],[.72,.19]]);part('neck-upper','neck1',[[.715,.17],[.88,.17],[.885,.28],[.71,.28]]);part('neck-lower','neck0',[[.715,.265],[.90,.25],[.92,.40],[.715,.40]]);
part('near-wing','wingNearTip',[[.39,.39],[.54,.30],[.65,.315],[.745,.435],[.72,.565],[.565,.66],[.455,.61]]);
part('tail','tailFan',[[0,.36],[.48,.35],[.515,.485],[.445,.574],[0,.60]],'far');
part('near-shin','legNearAnkle',[[.48,.745],[.605,.738],[.605,.88],[.48,.882]]);part('near-thigh','legNearKnee',[[.48,.61],[.63,.61],[.63,.765],[.48,.77]]);
part('far-shin','legFarAnkle',[[.66,.72],[.805,.72],[.805,.85],[.66,.85]],'far');part('far-thigh','legFarKnee',[[.65,.58],[.83,.58],[.83,.742],[.65,.746]],'far');
part('chest','chest',[[.72,.385],[.955,.38],[.95,.72],[.73,.70]]);part('torso','spine',[[0,0],[.001,0],[0,.001]]);
const body={schema:'cf.authored-part-masks/v1',recordRecipeHash:record.recipeHash,cutoutSha256:record.geometry.cutoutAssetHash,remainderPart:'torso',parts};write('declaration.json',{...body,declarationHash:await hashJSON(body)});
const intake=await buildAuthoredParts({id:'bird',recordFile:path.join(out,'record.json'),masterFile:source,declarationFile:path.join(out,'declaration.json'),output:path.join(out,'parts')}),compiled=await buildPaintSkin(path.join(out,'parts'),{seamBridges:{groups:[]}},record,{boundaryStep:24,interiorStep:64,includeTopology:true}),{bindingHash,...binding}=compiled.binding;binding.sourceJoinTopology={remainderPartId:'torso'};binding.paintSkin=smoothSkinWeights(binding.paintSkin);binding.paintSkin.solver={iterations:4,globalIterations:4,targetWeight:.35,pins:[]};write('binding.json',{...binding,bindingHash:await hashJSON(binding)});write('receipt.json',{...compiled.receipt,intake});console.log(JSON.stringify({intake,vertices:binding.paintSkin.vertices.length}));
