import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {pathToFileURL} from 'node:url';import {rolldown} from 'rolldown';import{createRequire}from'node:module';
import {familyContractForRecord} from '../creature-animation/family-contracts.mjs';import {createSkeletonPoseProgram}from'../creature-animation/skeleton-pose.mjs';import{applyPaintSkin,applyPaintPart,assertPaintPartShape,paintPartAreas}from'../creature-animation/paint-skin.mjs';import{createArapScratch,solveArapSkin}from'../creature-animation/arap-skin.mjs';import{createSourceJoinProbe,assessSourceJoinContinuity}from'../quadruped-proof/source-join-continuity.mjs';import{createOpaqueSeamSamplingGuard}from'../creature-animation/seam-sampling-guard.mjs';
const [dirArg,sourceArg,outArg]=process.argv.slice(2),dir=path.resolve(dirArg),source=path.resolve(sourceArg),out=path.resolve(outArg),read=n=>JSON.parse(fs.readFileSync(path.join(dir,n)));if(fs.existsSync(out))throw Error('New report required');
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'cf-family-sweep-')),bundle=await rolldown({input:path.join(source,'motion/index.ts'),platform:'node'});try{await bundle.write({dir:scratch,format:'es',entryFileNames:'producer.mjs'});}finally{await bundle.close();}
const {compileBodyCard,buildTimeline,sampleTimeline}=await import(pathToFileURL(path.join(scratch,'producer.mjs'))),record=read('record.json'),binding=read('binding.json'),skin=binding.paintSkin,program=createSkeletonPoseProgram(familyContractForRecord(record),record.landmarks),card=compileBodyCard(record,record.genome),w=record.geometry.width,h=record.geometry.height,field=new Float64Array(skin.vertices.length*2),target=new Float64Array(field.length),solver=skin.solver?createArapScratch(skin.vertices,skin.triangles,w,h,skin.solver):null;
const require=createRequire(import.meta.url),{PNG}=createRequire(require.resolve('free-tex-packer-core'))('pngjs'),png=PNG.sync.read(fs.readFileSync(path.join(dir,'parts/atlas/'+JSON.parse(fs.readFileSync(path.join(dir,'parts/manifest.json'))).creatureId+'.png'))),atlas={rgba:png.data,width:png.width,height:png.height},probe=createSourceJoinProbe({record,binding,atlas});const guard=createOpaqueSeamSamplingGuard({record,binding,atlas});
const positions=Object.fromEntries(skin.parts.map(p=>[p.id,new Float32Array(p.vertices.length*2)])),areas=new Map(skin.parts.map(p=>[p.id,paintPartAreas(p,skin)])),rows=[];
for(const action of ['idle','approach','melee','hit']){const tl=buildTimeline(card,action,record.identity.seed),row={action,resolved:tl.actionId,durationMs:tl.durationMs,samples:0,status:'PASS',maximumGap:0};for(let i=0;i<=120;i++){const ms=tl.durationMs*i/120,p=sampleTimeline(tl,ms),pose=Object.fromEntries(Object.entries(p.joints).map(([j,rotation])=>[j,{rotation,dx:j==='root'?p.root.dx:0,dy:j==='root'?p.root.dy:0}]));try{applyPaintSkin(skin,program.evaluate(pose),w,h,target);if(solver)solveArapSkin(solver,target,field);else field.set(target);for(const part of skin.parts){applyPaintPart(part,field,positions[part.id]);assertPaintPartShape(part,skin,positions[part.id],w,h,areas.get(part.id));}const seams=assessSourceJoinContinuity(probe,positions);if(seams.status!=='PASS')throw Error('seam '+seams.maxGapPx);row.maximumGap=Math.max(row.maximumGap,seams.maxGapPx);row.samples++;}catch(e){row.status='FAIL';row.firstFailure={ms,error:String(e)};break;}}rows.push(row);}
fs.writeFileSync(out,JSON.stringify({scope:'actual source, pure producer sampling; not native visual acceptance',status:rows.every(r=>r.status==='PASS')?'PASS':'FAIL',card,guard:guard.receipt,rows},null,2)+'\n');fs.rmSync(scratch,{recursive:true,force:true});console.log(JSON.stringify(rows));if(rows.some(r=>r.status!=='PASS'))process.exitCode=1;
