/** Audit-only instrumentation; never imported by product code. */
import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {createWasmOrientationActive as prior} from './before/wasm-orientation-active.mjs';
const out=process.env.CF_KERNEL_REPORT;assert(out&&!fs.existsSync(out),'New report required');
const bytes=a=>Buffer.from(a.buffer,a.byteOffset,a.byteLength),sha=a=>createHash('sha256').update(bytes(a)).digest('hex');
const clone=q=>Object.fromEntries(Object.entries(q).map(([k,v])=>[k,ArrayBuffer.isView(v)?v.slice():v]));
const report={schema:'cf.active-incident-parity/v1',status:'RUNNING',scope:'Paired active-leaf calls on identical actual Centipede static inputs; timings exclude audit cloning/comparison, include wrapper copies; Node host diagnostic, not phone/native CPU.',calls:0,failures:[],rows:[]};
const same=(a,b,label)=>{assert.equal(a.constructor,b.constructor,label+' type');assert(bytes(a).equals(bytes(b)),label+' bytes');for(let i=0;i<a.length;i++)assert(Object.is(a[i],b[i]),label+' value '+i);};
const keys=['heap','location','priority'],scalars=['size','projections','visits','stalled'];
const compare=(p,q,r,ep,eq,er)=>{same(p,ep,'position');for(const k of keys)same(q[k],eq[k],k);for(const k of scalars)assert(Object.is(q[k],eq[k]),k);assert(Object.is(r,er),'return');};
// Comparator controls include a position bit, stale heap slot, priority bit,
// visits and signed zero; matching position alone cannot prove kernel parity.
const baseP=new Float64Array([-0,1]),baseQ={heap:new Uint32Array([1]),location:new Int32Array([-1]),priority:new Float64Array([.5]),size:0,projections:0,visits:0,stalled:false};
report.controls=[];compare(baseP,baseQ,0,baseP.slice(),clone(baseQ),0);
for(const [id,mutate]of [['position-bit',(p,q)=>new Uint8Array(p.buffer)[8]^=1],['heap-slot',(p,q)=>q.heap[0]^=1],['priority-bit',(p,q)=>new Uint8Array(q.priority.buffer)[0]^=1],['visits',(p,q)=>q.visits++],['signed-zero',(p,q)=>p[0]=0]]){const p=baseP.slice(),q=clone(baseQ);mutate(p,q);assert.throws(()=>compare(p,q,0,baseP,baseQ,0));report.controls.push({id,status:'REJECTED'});}
process.on('exit',code=>{report.status=code===0&&report.calls>0&&!report.failures.length?'PASS_EXACT':'FAIL';const quantile=(a,q)=>a.slice().sort((a,b)=>a-b)[Math.ceil(a.length*q)-1];if(report.rows.length){const a=report.rows.map(r=>r.beforeMs),b=report.rows.map(r=>r.afterMs);report.timing={calls:a.length,beforeTotalMs:a.reduce((x,y)=>x+y,0),afterTotalMs:b.reduce((x,y)=>x+y,0),beforeP50Ms:quantile(a,.5),afterP50Ms:quantile(b,.5),beforeP95Ms:quantile(a,.95),afterP95Ms:quantile(b,.95)};}fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n',{flag:'wx'});if(report.status!=='PASS_EXACT')process.exitCode=1;});
export function wrapKernel(current,c,runtime){const next=current(c,runtime),old=prior(c,runtime);assert(next&&old,'Both real WASM leaves must admit');return {...next,run(p,q,n){const ep=p.slice(),eq=clone(q),inputSha256=sha(p);let r,er,beforeMs,afterMs;try{const before=()=>{const t=performance.now();er=old.run(ep,eq,n);beforeMs=performance.now()-t;},after=()=>{const t=performance.now();r=next.run(p,q,n);afterMs=performance.now()-t;};if(report.calls%2){after();before();}else{before();after();}compare(p,q,r,ep,eq,er);report.calls++;report.rows.push({call:report.calls,inputSha256,positionSha256:sha(p),heapSha256:sha(q.heap),prioritySha256:sha(q.priority),visits:q.visits,projections:q.projections,beforeMs,afterMs});return r;}catch(error){report.failures.push(String(error.stack??error));throw error;}}};}
