/** The arena plates a battle2 film draws (2026-10-02): the SAME runtime files the game routes to — the registered set's delivery-manifest
 * paths in `apps/game/src/battle2/arena-sets.generated.json` (generated by tools/morph/arena-sets.mjs; the game's `ARENA_FALLBACK_ASSETS`
 * for the accepted temperate set) — never a hard-coded proof-directory copy. The temperate set's MID is the approved despilled copy
 * (`ARENA_V1_ACCEPTANCE_20260912/arena-mid-despilled.png`), so a film matches what the game draws. Node only; no browser. */
import fs from 'node:fs'; import path from 'node:path';

export const ARENA_SETS_FILE = path.resolve(import.meta.dirname, '../../apps/game/src/battle2/arena-sets.generated.json');
export const ARENA_FALLBACK_SET_ID = 'earth-temperate-v1';
const AUDIT_PATH = /^audits\/(?!.*\.\.)[A-Za-z0-9_./-]+$/;

/** The served flat names the film entries fetch → absolute source paths for one registered set (default: the accepted temperate set). */
export function arenaPlateFiles(repo, setId = ARENA_FALLBACK_SET_ID, sets = JSON.parse(fs.readFileSync(ARENA_SETS_FILE, 'utf8'))) {
  if (sets?.schema !== 'cf.arena-sets/v1' || !Array.isArray(sets.sets)) throw Error('arena plates: cf.arena-sets/v1 required');
  const row = sets.sets.find((s) => s.id === setId); if (!row) throw Error(`arena plates: set ${setId} is not registered`);
  const at = (k) => { const v = row[k]; if (typeof v !== 'string' || !AUDIT_PATH.test(v)) throw Error(`arena plates: ${setId}.${k} must be a repo-relative path under audits/`); return path.join(repo, v); };
  return Object.freeze({ setId: row.id, biome: row.biome, files: Object.freeze({ 'arena-recipe.json': at('recipe'), 'arena-far.png': at('far'), 'arena-mid.png': at('mid'), 'arena-near.png': at('near') }) });
}
