/** Local unmorphed archetype study. Published paint meshes determine medium sizing;
 * every pose still passes the performance/contact owners and every refusal is retained. */
import { Application, Container, Graphics, Particle, ParticleContainer, Sprite, Text, Texture } from 'pixi.js';
import { compileAnatomyAttack } from 'cf-proof/anatomy-attacks.ts';
import { combatantScale, composeArena } from 'cf-proof/battle2/arena.ts';
import { selectHabitatArena } from 'cf-proof/battle2/habitat-arena.ts';
import { compileHabitatBattle, resolvePhysicalHabitat, containHabitatBody } from 'cf-proof/battle-habitat.ts';
import { createPartsRig } from 'cf-proof/battle2/parts-rig.ts';
import { BattleStage, turnPlanInputFromTranscriptEvent } from 'cf-proof/battle2/stage.ts';
import { loadCreatureRigV1 } from 'cf-proof/creature-rig.ts';
import { parseEffectSequenceAnchors } from 'cf-proof/effects/anchors.ts';
import { PARTICLE_DISC_SIZE, particleDiscRgba } from 'cf-proof/effects/particle-texture.ts';
import { createPixiEffectHost } from 'cf-proof/effects/pixi-adapter.ts';
import { EffectThemeLibrary, isProceduralImage } from 'cf-proof/effects/theme-library.ts';
import { compileBodyCard } from 'cf-proof/motion/body-card.ts';
import { primeRecorder } from '../quadruped-proof/capture-contract.mjs';
import { publishedMeshBounds, mergePaintedBounds, fitPaintedEnvelope, placedPaintedBounds, assessPaintedContainment, assertPublishedSample } from './painted-envelope.mjs';

const FRAME = { width: 1024, height: 576 }, SIDES = ['left', 'right'];
const get = n => fetch(n).then(r => { if (!r.ok) throw Error(n); return r; });
const json = n => get(n).then(r => r.json()), bytes = async n => new Uint8Array(await (await get(n)).arrayBuffer());
const image = async n => { const b = await bytes(n), bmp = await createImageBitmap(new Blob([b])), c = new OffscreenCanvas(bmp.width, bmp.height); c.getContext('2d').drawImage(bmp, 0, 0); bmp.close(); return { bytes:b, canvas:c, width:c.width, height:c.height, rgba:c.getContext('2d').getImageData(0, 0, c.width, c.height).data }; };
const alphaBox = (rgba,w,h) => { let x0=w,y0=h,x1=-1,y1=-1; for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(rgba[(y*w+x)*4+3]>8){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);} if(x1<0)throw Error('empty alpha');return{x:x0,y:y0,width:x1-x0+1,height:y1-y0+1}; };
const percentile = xs => { const a=[...xs].sort((a,b)=>a-b);if(!a.length)throw Error('missing measured samples');return a[Math.floor(a.length*.95)]; };
const transform=n=>({x:n.x,y:n.y,scaleX:n.scale.x,scaleY:n.scale.y,rotation:n.rotation??0,pivotX:n.pivot?.x??0,pivotY:n.pivot?.y??0});
const state={status:'LOADING'};window.cfBattle2Proof={state};
try {
 const app=new Application();await app.init({width:FRAME.width,height:FRAME.height,resolution:1,background:0x141d22,antialias:true,autoStart:false,preference:'webgl'});document.body.append(app.canvas);
 const script=await json('script.json'),world=await json('world.json');if(Object.hasOwn(script,'morph'))throw Error('This archetype-only harness does not admit morph requests');
 const loadSide=async side=>{const record=await json(side+'-record.json'),binding=await json(side+'-binding.json'),keyed=await image(side+'-keyed.png'),master=await bytes(side+'-master.png'),atlas=await bytes(side+'-atlas.png');if(record.guardian)throw Error('Guardian sizing is outside this archetype-only study');const alpha=Uint8Array.from({length:keyed.width*keyed.height},(_,i)=>keyed.rgba[i*4+3]),card=compileBodyCard(record,record.genome),paintRig=await loadCreatureRigV1(record,binding,master,alpha,atlas);return{record,binding,card,paintRig,rig:createPartsRig({record,rig:paintRig,card,alphaBox:alphaBox(keyed.rgba,keyed.width,keyed.height),binding,heightProbe:'external-painted-envelope',...(script.supports==='observed'?{contactSupports:'observed'}:{})}),name:record.identity.earthName??record.kind};};
 let actors={left:await loadSide('left'),right:await loadSide('right')};
 const [recipe,anchorsRaw,far,mid,near]=await Promise.all([json('arena-recipe.json'),json('wild-anchors.json'),image('arena-far.png'),image('arena-mid.png'),image('arena-near.png')]);
 const parsed=parseEffectSequenceAnchors(anchorsRaw);if(!parsed.ok)throw Error(parsed.reason);const anchors=parsed.anchors,themes=new EffectThemeLibrary([anchors]),texture=img=>Texture.from(img.canvas);
 const compiled=compileHabitatBattle({contextId:'local-archetype-study',seed:recipe.seed,round:0,kind:'wild',home:world,visitor:world,left:resolvePhysicalHabitat(actors.left.record),right:resolvePhysicalHabitat(actors.right.record)});if(compiled.status!=='READY')throw Error('habitat: '+compiled.reason);
 const layout=composeArena({id:world.key,groundLineNormalized:recipe.groundLineNormalized,plates:{far,mid,near}},FRAME),masses=Object.fromEntries(SIDES.map(s=>[s,actors[s].card.massClass.multiplier]));
 const massScales=Object.fromEntries(SIDES.map(s=>[s,combatantScale(actors[s].rig.bounds,actors[s].rig.cutout.height,masses[s],FRAME.height).scale]));
 const factory={container:()=>new Container(),sprite:t=>new Sprite(t),text:t=>new Text({text:t,style:{fontFamily:'Arial',fontSize:28,fill:0xffefd5}}),graphics:()=>new Graphics()};
 const plates={far:texture(far),mid:texture(mid),near:texture(near)};
 // The retained far plate remains painted. Wet-world foreground is explicitly procedural water,
 // covering the dry near plate instead of presenting aquatic bodies over the forest floor.
 const wet=SIDES.some(s=>compiled[s].medium==='water');
 if(wet){const blank=new OffscreenCanvas(1,1);plates.mid=Texture.from(blank);const c=new OffscreenCanvas(FRAME.width*3,FRAME.height),g=c.getContext('2d'),gradient=g.createLinearGradient(0,compiled.surfaceY*FRAME.height,0,FRAME.height);gradient.addColorStop(0,'rgba(24,83,101,.90)');gradient.addColorStop(1,'rgba(12,38,49,.98)');g.fillStyle=gradient;g.fillRect(0,compiled.surfaceY*FRAME.height,FRAME.width*3,FRAME.height);g.strokeStyle='#a7dcc2';g.lineWidth=2;g.beginPath();g.moveTo(0,compiled.surfaceY*FRAME.height);g.lineTo(FRAME.width*3,compiled.surfaceY*FRAME.height);g.stroke();plates.mid=Texture.from(c);plates.near=Texture.from(blank);}
 const phaseTextures=new Map();for(const p of anchors.phases)if(!isProceduralImage(p.keyedImage))phaseTextures.set(p.keyedImage,texture(await image(p.keyedImage.replace(/^.*\//,''))));
 const discCanvas=new OffscreenCanvas(PARTICLE_DISC_SIZE,PARTICLE_DISC_SIZE);discCanvas.getContext('2d').putImageData(new ImageData(particleDiscRgba(),PARTICLE_DISC_SIZE,PARTICLE_DISC_SIZE),0,0);
 const effects={host:createPixiEffectHost({Container,Sprite,Particle,ParticleContainer}),seed:recipe.seed,particleTexture:Texture.from(discCanvas),phaseTextures:a=>a.phases.map(p=>isProceduralImage(p.keyedImage)?null:phaseTextures.get(p.keyedImage)),emittersForTheme:t=>themes.emittersFor(t,'desktop'),tintForTheme:t=>themes.tintFor(t)};
 let clockMs=0,stage,plans=[],turns=[],offsets=[],totalMs=0,current=-1,attackLabels={},timingEvents=[];
 const makeStage=(scales,stands,withEffects)=>new BattleStage({factory,clock:()=>clockMs,layout:{...layout,plates:layout.plates.map(p=>wet&&p.id!=='far'?{...p,x:-FRAME.width,y:0,scale:1,width:FRAME.width*3,height:FRAME.height}:p),stands},plates,rigs:{left:actors.left.rig,right:actors.right.rig},masses,presentationScales:scales,...(withEffects?{effects}:{}),timing:{now:()=>performance.now(),sample:e=>timingEvents.push(e)}});
 const buildPlans=stands=>{attackLabels={left:null,right:null};const attackFor=(side,ordinal)=>{const key=side==='A'?'left':'right',s=actors[key],a=compileAnatomyAttack(s.card,compiled[key].medium,ordinal);attackLabels[key]=`${a.attack.verb} (${a.attack.contactJoint})`;return{verb:a.attack.verb,timeline:a.timeline,contactMs:a.contactMs,contactJoint:a.attack.contactJoint};};const ctx={A:{side:'A',name:actors.left.name,mass:masses.left,card:actors.left.card,theme:script.themes?.A??'wild',seed:1},B:{side:'B',name:actors.right.name,mass:masses.right,card:actors.right.card,theme:script.themes?.B??'stone',seed:2},arena:{groundLineY:layout.groundLineY,stands,halfWidths:stage.halfWidths()},seed:recipe.seed,anchorsForTheme:t=>themes.anchorsFor(t),readyMs:script.readyMs??600,commandMs:script.commandMs??300,attackFor};const ord={A:0,B:0};turns=[];for(const row of script.rows){const side=row.side==='B'||(row.dodge===true&&row.an===actors.right.name)?'B':'A',t=turnPlanInputFromTranscriptEvent(row,ctx,ord[side]);if(t.kind!=='turn')throw Error('Unstaged script row: '+t.reason);turns.push(t.input);ord[side]++;}if(!turns.length)throw Error('no stageable turn');plans=[];offsets=[];totalMs=0;for(const input of turns){clockMs=totalMs;const plan=stage.play(input);plans.push(plan);offsets.push(totalMs);totalMs+=plan.beats.end;}current=-1;};
 const counters=()=>Object.fromEntries(SIDES.map(s=>[s,actors[s].rig.refusals()]));
 const assertPublished=label=>{for(const s of SIDES)if(actors[s].rig.refusals())throw Error(label+' '+s+': '+actors[s].rig.lastRefusal());};
 const stageAt=(g,render=true)=>{const before=Object.fromEntries(SIDES.map(s=>[s,{applied:actors[s].rig.applied(),refusals:actors[s].rig.refusals()}]));let i=0;while(i+1<plans.length&&g>=offsets[i+1])i++;if(current!==i){clockMs=offsets[i];stage.play(turns[i]);current=i;}clockMs=Math.min(g,offsets[i]+plans[i].beats.end-1e-6);const frame=stage.tick();for(const s of SIDES)assertPublishedSample({before:before[s],after:{applied:actors[s].rig.applied(),refusals:actors[s].rig.refusals()}});if(render)app.renderer.render(app.stage);return frame;};
 const localBounds=side=>publishedMeshBounds(actors[side].paintRig.parts.map(part=>({id:part.id,positions:part.display.children[0]?.geometry?.getBuffer('aPosition')?.data}))); 
 const times=()=>{const t=new Set([0,totalMs]);for(let ms=0;ms<totalMs;ms+=1000/60)t.add(ms);for(let i=0;i<plans.length;i++)for(const ms of Object.values(plans[i].beats))t.add(offsets[i]+ms);return[...t].sort((a,b)=>a-b);};
 const probeStands=Object.fromEntries(SIDES.map(s=>[s,{x:layout.stands[s].x,y:compiled[s].medium==='ground'?layout.groundLineY:(compiled[s].band.minY+compiled[s].band.maxY)/2}]));stage=makeStage(massScales,probeStands,false);buildPlans(probeStands);assertPublished('probe plan');const envelope={left:null,right:null};let cameraMin=0,cameraMax=0,sizingSamples=0;
 for(const ms of times()){stageAt(ms,false);assertPublished('sizing at '+ms);cameraMin=Math.min(cameraMin,stage.root.y);cameraMax=Math.max(cameraMax,stage.root.y);for(const side of SIDES){const b=placedPaintedBounds({bounds:localBounds(side),root:transform(actors[side].rig.root),holder:{x:0,y:0,scaleX:1,scaleY:1},camera:{x:0,y:0}}).arena,p=envelope[side];envelope[side]=p?mergePaintedBounds([p,b]):b;}sizingSamples++;}
 const sizing={};for(const side of SIDES){const b=envelope[side],band=compiled[side].band,medium=compiled[side].medium,extra=(cameraMax-cameraMin)/(2*FRAME.height),sizingBand=medium==='ground'?band:{minY:band.minY+extra,maxY:band.maxY-extra};const fit=fitPaintedEnvelope({bounds:b,foot:{x:0,y:0},frame:FRAME,medium,band:sizingBand,massScale:massScales[side],edgeReserveFraction:.05});sizing[side]={scale:fit.scale,massScale:massScales[side],envelope:b,...fit.painted,medium,band};}
 const sizingReceipt={samples:sizingSamples,cameraMinPx:cameraMin,cameraMaxPx:cameraMax,presentationBandFraction:.90,method:'One composed published-mesh sizing pass, 5% presentation margin on each band edge; unchanged final containment gate; independent fresh final rigs.',sides:sizing};stage.dispose();actors={left:await loadSide('left'),right:await loadSide('right')};
 const habitat=selectHabitatArena({contextId:'local-archetype-study',seed:recipe.seed,round:0,kind:'wild',worlds:{home:world,visitor:world},groundLineY:layout.groundLineY,left:{record:actors.left.record,genome:null,label:actors.left.name,painted:sizing.left},right:{record:actors.right.record,genome:null,label:actors.right.name,painted:sizing.right}});if(habitat.status!=='READY')throw Error(habitat.reason);
 const stands=Object.fromEntries(SIDES.map(s=>[s,{x:layout.stands[s].x,y:habitat.stands[s].y}]));stage=makeStage(Object.fromEntries(SIDES.map(s=>[s,sizing[s].scale])),stands,true);app.stage.addChild(stage.root);buildPlans(stands);assertPublished('final plan');if(totalMs>10000)throw Error('Ten-second film cannot cover '+totalMs+'ms script');
 const holder=side=>stage.root.children.find(n=>n.children?.includes(actors[side].rig.root));
 const containment=ms=>{assertPublished('publication at '+ms);return SIDES.map(side=>{const h=holder(side);if(!h)throw Error('Missing stage holder');if(h.scale.y!==sizing[side].scale)throw Error('Placement/render scale mismatch');const placed=placedPaintedBounds({bounds:localBounds(side),root:transform(actors[side].rig.root),holder:transform(h),camera:{x:stage.root.x,y:stage.root.y}}),row=assessPaintedContainment({placed,frame:FRAME,medium:habitat.stands[side].medium,band:habitat.stands[side].band});if(row.status!=='PASS')throw Error('Painted containment refused '+JSON.stringify({side,ms,...row}));return{side,ms,...row};});};
 let denseRows=[];for(const ms of times()){stageAt(ms,false);denseRows.push(...containment(ms));}let oversizedRefused=false;try{containHabitatBody(compiled.left.band,.5,2);}catch{oversizedRefused=true;}if(!oversizedRefused)throw Error('Oversized negative control accepted');stageAt(0);timingEvents=[];
 const gates=()=>({status:'DIAGNOSTIC_PASS',scope:'Unmorphed archetype; local actual stage/motion/contact/rig owners; procedural water overlay when aquatic; art review remains human.',frame:FRAME,world,habitat:habitat.label,stands,attacks:attackLabels,totalMs,sizing:sizingReceipt,oversizedRefused,dense:{samples:denseRows.length,rows:denseRows},refusals:counters(),turns:plans.map((p,i)=>({turn:i,outcome:p.outcome,attacker:p.attacker.side,beats:p.beats,offsetMs:offsets[i],runUp:p.runUp,attack:p.attack?{verb:p.attack.verb,contactMs:p.attack.contactMs,contactJoint:p.attack.contactJoint}:null}))});
 const still=ms=>{stageAt(ms);containment(ms);return app.canvas.toDataURL('image/png').split(',')[1];};
 async function capture(){const stream=app.canvas.captureStream(0),track=stream.getVideoTracks()[0],chunks=[],recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp9',videoBitsPerSecond:5000000}),stopped=new Promise(r=>recorder.onstop=r);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};let started=false,recordError=null;recorder.onstart=()=>started=true;recorder.onerror=e=>recordError=e.error??Error('Recorder failed');stageAt(0);recorder.start();await primeRecorder({started:()=>started,paint:()=>stageAt(0),requestFrame:()=>track.requestFrame(),schedule:requestAnimationFrame,now:()=>performance.now()});const frames=[],bounds=[];let start;try{await new Promise((resolve,reject)=>{const step=t=>{try{start??=t;const elapsed=t-start,ms=Math.min(elapsed,totalMs);timingEvents=[];const cpu=performance.now();stageAt(ms);const wholeStageCpuMs=performance.now()-cpu;bounds.push(...containment(ms));const timing={sampleTurnMs:0,rigMs:{left:0,right:0},events:timingEvents.length};for(const e of timingEvents){timing.sampleTurnMs+=e.sampleTurnMs;for(const s of SIDES)timing.rigMs[s]+=e.rigMs[s];}frames.push({ms:elapsed,wholeStageCpuMs,timing,perRigUpperBoundMs:Object.fromEntries(SIDES.map(s=>[s,timing.sampleTurnMs+timing.rigMs[s]]))});track.requestFrame();if(elapsed>=10000)resolve();else requestAnimationFrame(step);}catch(e){reject(e);}};requestAnimationFrame(step);});}finally{recorder.stop();await stopped;stream.getTracks().forEach(t=>t.stop());}if(recordError)throw recordError;const buffer=new Uint8Array(await new Blob(chunks).arrayBuffer());let b64='';for(let i=0;i<buffer.length;i+=8192)b64+=String.fromCharCode(...buffer.subarray(i,i+8192));return{video:btoa(b64),frames:frames.length,durationMs:frames.at(-1)?.ms??0,cpuP95Ms:percentile(frames.map(f=>f.wholeStageCpuMs)),perRigUpdateP95Ms:Object.fromEntries(SIDES.map(s=>[s,percentile(frames.map(f=>f.perRigUpperBoundMs[s]))])),timingScope:'Each per-rig upper bound charges the entire shared sampleTurn time plus its own performance/contact/publication; event sums include transition ticks. Whole stage additionally includes effects and rendering. Bounds admission cost excluded from these scopes.',frameDeltaP95Ms:percentile(frames.slice(1).map((f,i)=>f.ms-frames[i].ms)),frameSamples:frames,paintedBounds:bounds,refusalsAtEnd:counters(),lastRefusal:Object.fromEntries(SIDES.map(s=>[s,actors[s].rig.lastRefusal()]))};}
 window.cfBattle2Proof={state,gates,still,capture};state.status='READY';
}catch(e){state.status='FAIL';state.error=String(e?.stack??e);}
