import fs from 'node:fs';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';
import {compileLibraryMaster as canonicalCompile,libraryFamily} from '../../port/v2/tools/painted-creature/compile-library-master.mjs';
import {compileLibraryMaster as auditCompile} from './compiler.audit.mjs';
const base='audits/C186_CREATURE_SUPPLY_20261002',sha=b=>createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p));
const corrections={
 Impala:'Correct the previous source which visibly has a third foreleg/five legs: one natural Impala with exactly its four real legs, two forelegs and two hindlegs. Quiet natural stance, four distinct complete feet on a common baseline, connected individually to actual torso emergence. Keep the real tail, two visible ears, lyre-shaped ringed horns, black hind-hoof tufts and rump stripes; never reinterpret a fifth painted leg as fringe.',
 'Banana Slug':'Expose the actual small oral opening underneath the front head, separately from the two short sensory tentacles and two long ocular tentacles. No invented lips or large face. Preserve the complete genuine anatomy and leave generous empty margins around all stalks.',
 Prawn:'Correct the prior hidden walking-leg roots by choosing a shallow underside view: every actual thoracic root-to-tip path must be readable as far as biological visibility allows. Retain all ten real walking legs, swimmerets and antennules; do not delete or relocate real structures to fit a coarse template. Keep entire antennae inside generous margins.',
 Crab:'Correct the prior obscured posterior walking chains: direct slightly elevated frontal view with eight complete actual leg silhouettes and true roots visible where they emerge from beneath the carapace, plus both genuine claws. Do not add hidden limbs, cut holes in shell or substitute eye stalks for legs.',
 'Brittle Star':'Use the biologically short-armed Ophiacantha kokusai representative documented in biological-reference.json, with five complete arms and a clearly bounded real disc. This is a fresh painting with real natural proportions, never geometric stretching of the former source or adaptation of anatomy to a rig threshold.',
 Dog:'Previous source has long fur obscuring proximal limb attachments. Use a naturally short body coat with the canonical high plumed tail, both natural erect ears and black nose. Keep four real complete leg silhouettes visibly separate from shoulder/hip emergence through every paw in a quiet level stance. Preserve fur and real joints; no shaved anatomy or hidden-part invention.',
 Wolf:'The earlier upper limb roots overlap and its generated rig refuses gallop compression. Paint a natural neutral standing wolf with all four actual leg silhouettes independently readable through knee/hock and paw, broad blocky head, erect triangular ears, narrow deep chest and a low straight bushy tail. This source correction does not claim to repair the solver or existing static refusal.',
 Jaguar:'Preserve the stocky powerful real Jaguar and mandatory rosettes with dark central spots. Four short real legs must be independently traceable from visible torso emergence to full paws, with a quiet natural level stance; no long-legged leopard substitute and no extra fringe-shaped leg. Prior source authoring reported unassigned limb-down paint.',
 Serval:'Preserve the exceptionally long real legs, enormous upright oval ears, short tail and spotted/barred coat. Show all four actual narrow leg shafts separately from their natural visible roots through the paws on one level, not merely separated toe tips. Keep genuine slender proportions; do not shorten legs to fit a generic cat. Prior authoring left two limb-down structures unassigned.',
 Otter:'A slight natural head turn reveals both tiny actual external ears from attached base to tip, without enlarging them into mammal reference ears. Preserve sleek streamlined tube body, broad whiskered muzzle, thick tapering muscular tail and four short actual legs with separate feet. Prior source lacks far-ear-tip coverage.',
 Wolverine:'Separate the actual four thick short legs and huge clawed paws from the natural fur outline, preserving the heavy bear-like build, humped shoulders, real pale stripe along each flank and bushy tail. A slight natural stance separation reveals limb paths without clipping fur, inventing joints or adding legs. Prior authoring leaves limb-down/fringe paint unexplained.',
 Badger:'Preserve the real broad low-slung body, white facial stripe and long digging foreclaws. Show four actual limb silhouettes from their visible low torso emergence through each foot, both small attached ears where naturally visible, and the real short tail separately from hind feet. Never lengthen the tail to mimic a reference. Prior source has unassigned limb paint and short-tail/ear coverage refusals.',
 Beaver:'Slight natural head turn reveals both actual small rounded ears while preserving broad whiskered muzzle and orange incisors. Four actual short leg silhouettes and feet are distinct; the entire flat scaly paddle tail remains connected at its real base and separate from hind feet. No enlarged ears or furry rat tail. Prior authoring lacks far-ear-tip coverage.'
};
const names=['Impala','Banana Slug','Prawn','Crab','Brittle Star','Sloth','Tortoise','Box Turtle','Pond Turtle','Snapping Turtle','Softshell Turtle','Turtle','Dog','Wolf','Jaguar','Serval','Otter','Wolverine','Badger','Beaver','Seahorse','Giant Squid','Vampire Squid','Nautilus'];
const biological={Sloth:'BIOLOGICAL PRIORITY: a natural three-toed sloth in a low terrestrial crawling/resting posture, not hanging from an absent prop. Preserve long hooked scythe claws, real long arms, shaggy greenish fur and round flat face. Its anatomy takes priority over generic four-paw stance. No branch or invented gripping support.',Tortoise:'BIOLOGICAL PRIORITY: shell is the actual body wall; four real columnar scaly legs emerge beneath its rim. No mammal ears, artificial tail elongation, webbing or hoof substitution.', 'Box Turtle':'BIOLOGICAL PRIORITY: high genuine domed shell with hinged plastron, scaly clawed feet, short natural tail and real neck. Shell is the body, not a removable hat. No external mammal ears.', 'Pond Turtle':'BIOLOGICAL PRIORITY: low streamlined true shell, real webbed clawed feet and extended wrinkled neck. Legs emerge from beneath the true shell rim; no mammal ears or fabricated exposed upper limbs.', 'Snapping Turtle':'BIOLOGICAL PRIORITY: real rough ridged shell, massive hooked beak, long saw-toothed crested tail and four genuine clawed feet. Do not replace the shell with hide, add ears, shorten its tail or exaggerate hidden limb roots.', 'Softshell Turtle':'BIOLOGICAL PRIORITY: naturally flat leathery pancake shell with no scutes, tubular snorkel snout and four broad fully webbed feet. No hard tortoise dome, added ears or invented scute plates.',Turtle:'BIOLOGICAL PRIORITY: canonical representative freshwater pond turtle; shell is the body wall, neck and four real feet emerge under its rim. Preserve species-correct shell, true short tail and no external ear flaps.',Seahorse:'BIOLOGICAL PRIORITY: real seahorse upright in its natural vertical swimming posture, head facing right, tubular snout, small genuine dorsal and pectoral fins and complete curled prehensile tail. This supersedes generic horizontal fish layout. No caudal fin, invented anal/pelvic fins, coral prop or gripping branch.'};
const files=execFileSync('rg',['--files','audits','-g','pilot*.json'],{encoding:'utf8'}).trim().split('\n'),prior=new Map();
for(const f of files.filter(p=>/\/pilot[^/]*\.json$/.test(p))){let v;try{v=read(f);}catch{continue;}if(!Array.isArray(v))continue;for(const r of v)if(typeof r?.name==='string'){const list=prior.get(r.name)??[];list.push({pilot:f,id:r.id,master:r.master??null,packet:r.packet??null});prior.set(r.name,list);}}
const coveragePath='audits/GENERATED_GALLERY_20260927/coverage.json',coverage=read(coveragePath),accepted=new Set(coverage.families.flatMap(f=>f.names));if(coverage.covered!==218)throw Error('Coverage changed; review exclusions');
const fauna=read('port/v2/reference/fauna.json'),unprovided=fauna.filter(s=>!prior.has(s.name)&&!accepted.has(s.name)).map(s=>s.name),profileText=fs.readFileSync('port/v2/apps/game/src/earth-fauna-profiles.ts','utf8'),unprovidedRoutes=[];
for(const line of profileText.split('\n')){const m=line.match(/group\("([^"]+)",(\[[^\]]*\]),(\[[^\]]*\])/);if(!m)continue;for(const name of JSON.parse(m[2]))if(unprovided.includes(name)){const s=fauna.find(s=>s.name===name);let route=null;try{route=libraryFamily({id:m[1],candidateTemplates:JSON.parse(m[3])},s);}catch{}unprovidedRoutes.push({name,profile:m[1],candidates:JSON.parse(m[3]),controlledRoute:route});}}
const specialists=Object.keys(read(base+'/specialized-layouts.json')),composition='COMPOSITION PRIORITY: small complete natural animal centered on native 1254 x 1254 pure magenta canvas. Entire silhouette including every tip occupies only the central HALF of the canvas, about 300 pixels empty on all sides. Preserve actual proportions; no crop, floor, shadow, prop or text.';
const rows=[];
for(const[i,name]of names.entries()){
 if(accepted.has(name))throw Error('Accepted duplicate '+name);if(!corrections[name]&&prior.has(name))throw Error('Already supplied '+name);
 const id=String(i+1).padStart(2,'0')+'-'+name.toLowerCase().replaceAll(' ','-'),packet=base+'/'+id,isSpecial=specialists.includes(name),c=await(isSpecial?auditCompile:canonicalCompile)(name,packet),q=read(packet+'/request.json'),canonical=fs.readFileSync(packet+'/prompt.txt','utf8'),appendix=corrections[name]?'TARGETED SOURCE CORRECTION: '+corrections[name]:biological[name]??'';
 if(sha(canonical)!==q.promptSha256)throw Error('Canonical prompt changed');const prompt=composition+'\n'+appendix+'\n\n'+canonical+'\n\n'+appendix+'\n'+composition+'\n';
 fs.writeFileSync(packet+'/prompt.canonical.txt',canonical,{flag:'wx'});fs.writeFileSync(packet+'/prompt.txt.tmp',prompt,{flag:'wx'});fs.renameSync(packet+'/prompt.txt.tmp',packet+'/prompt.txt');
 const purpose=corrections[name]?'TARGETED_SOURCE_REPAINT':'NEW_SOURCE_IDENTITY',repairReason=corrections[name]?{correction:corrections[name],priorSources:prior.get(name)??[]}:null;
 fs.writeFileSync(packet+'/request.json.tmp',JSON.stringify({...q,basePromptSha256:q.promptSha256,promptSha256:sha(prompt),batchCompilerSha256:sha(fs.readFileSync(import.meta.filename)),purpose,repairReason,priorPilotPaths:[...new Set((prior.get(name)??[]).map(r=>r.pilot))],auditCompilerExtension:isSpecial,sourceCorrection:appendix,compositionCheck:composition,admission:'SOURCE_CANDIDATE_ONLY; no presence, reference-pool, fit or native admission'},null,2)+'\n',{flag:'wx'});fs.renameSync(packet+'/request.json.tmp',packet+'/request.json');rows.push({id,name,family:c.family,packet,master:packet+'/master.png',purpose,repairReason});console.log(id,c.family);
}
fs.writeFileSync(base+'/pilot.json',JSON.stringify(rows,null,2)+'\n',{flag:'wx'});
fs.writeFileSync(base+'/selection.json',JSON.stringify({schema:'cf.g2-selection/v1',coveredAtSelection:218,total:24,targetedSourceRepaints:13,newSourceIdentities:11,priorRequestedNames:prior.size,specialists,unprovidedRoutes,scope:'Seven first non-flipper quadrupeds and eight named old quadruped visibility corrections; five direct reference-source corrections; Seahorse is the only unprovided bird/insect/admitted-fish-route identity. Three existing-supported cephalopods fill remaining slots with parent-authorized fallback. Twenty unchanged canonical routes, four disclosed audit layouts; no new runtime support.',evidence:[coveragePath,'port/v2/reference/fauna.json','port/v2/apps/game/src/earth-fauna-profiles.ts'].map(path=>{const b=fs.readFileSync(path);return{path,sha256:sha(b),bytes:b.length};}),rows},null,2)+'\n',{flag:'wx'});
