/** Diagnostic: choose one continuous torso gain for the whole dodge clip from
 * source two-bone geometry. This does not accept a rig or relax a runtime guard. */
import fs from 'node:fs';import path from 'node:path';
import {compileBodyCard,buildTimeline,createGsapPlayer} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/apps/game/src/motion/index.ts';
import {createFamilyContactSolver,observedContactSupports} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/apps/game/src/creature-rig-contact.ts';
import {familyContractForRecord,familyContactChains} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/creature-animation/family-contracts.mjs';
import {createSkeletonPoseProgram} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/creature-animation/skeleton-pose.mjs';
import {createTwoBoneChain,transformPoint} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/creature-animation/kinematics.ts';
const root='/Users/nick/Projects/celestial-frontier-openai-mac',out=process.argv[2];if(!out||fs.existsSync(out))throw Error('New output required');
const paths=['audits/ART_BATTLE_FOCUS_20260925/12-gull/fit-03','audits/ARCHETYPE_SPRINT_20260922/03-biped-bird/fit-01'];
const point=([x,y])=>({x,y}),angle=(a,b)=>Math.atan2(b.y-a.y,b.x-a.x),wrap=a=>Math.atan2(Math.sin(a),Math.cos(a)),body=['root','pelvis','spine','chest'];
const scaled=(p,g)=>Object.fromEntries(Object.entries(p).map(([j,k]:[string,any])=>[j,body.includes(j)?{...k,rotation:k.rotation*g,...j==='root'?{dx:(k.dx??0)*g,dy:(k.dy??0)*g}:{}}:{...k}]));
const report:any={scope:'Source-geometric dodge torso envelope diagnosis, no runtime change or acceptance; fixed gain and original feet/limits, actual GSAP samples',subjects:[]};
for(const dir of paths){const r=JSON.parse(fs.readFileSync(path.join(root,dir,'record.json'),'utf8')),b=JSON.parse(fs.readFileSync(path.join(root,dir,'binding.json'),'utf8')),card=compileBodyCard(r,r.genome),def=familyContractForRecord(r),program=createSkeletonPoseProgram(def,r.landmarks),tl=buildTimeline(card,'dodge',card.identity.seed);let raw:any={};const player=createGsapPlayer(tl,{setJoint(j,rotation,dx,dy){raw[j]={rotation,dx,dy};}},{now:()=>0}),poses=[];
for(let i=0;i<=120;i++){raw={};player.seek(tl.durationMs*i/120);poses.push(raw);}player.stop();
const chains=familyContactChains(def).map(c=>{const root=point(r.landmarks[c.hip]),joint=point(r.landmarks[c.knee]),end=point(r.landmarks[c.end]),cross=(end.x-root.x)*(joint.y-root.y)-(end.y-root.y)*(joint.x-root.x);return {...c,root,joint,endPoint:end,chain:createTwoBoneChain({root,joint,end,bend:cross<0?-1:1})};});
function admissible(g:number,reserve:number){for(const original of poses){const pose=scaled(original,g);for(const c of chains)pose[c.hip]={rotation:0};const matrices=program.evaluate(pose);for(const c of chains){const m=matrices[c.hip],root=transformPoint(m,c.root);const distance=Math.hypot(c.endPoint.x-root.x,c.endPoint.y-root.y);if(distance<Math.abs(c.chain.lengths.upper-c.chain.lengths.lower)||distance>c.chain.lengths.upper+c.chain.lengths.lower||distance<.000001)return false;let solved;try{solved=c.chain.solve(root,c.endPoint);}catch{return false;}const upper=wrap(angle(solved.root,solved.joint)-angle(c.root,c.joint)),lower=wrap(angle(solved.joint,solved.end)-angle(c.joint,c.endPoint));for(const[j,a]of [[c.knee,wrap(upper-Math.atan2(m[1],m[0]))],[c.end,wrap(lower-upper)],[c.terminal,wrap(-lower)]] as any){if(!j)continue;const l=(def.contactLimitsDeg??def.limitsDeg)[j],deg=a*180/Math.PI;if(deg<l.min*reserve||deg>l.max*reserve)return false;}}}return true;}
const rows=[];for(const reserve of [1,.9,.8]){let lo=0,hi=1,g=1;if(!admissible(1,reserve)){for(let i=0;i<12;i++){const mid=(lo+hi)/2;if(admissible(mid,reserve))lo=mid;else hi=mid;}g=lo;}const results=[];for(const mode of ['rest','observed']){const solver=createFamilyContactSolver(r,mode==='observed'?observedContactSupports(r,b):{});let passes=0,first=null;for(let i=0;i<poses.length;i++){try{solver.resolve(scaled(poses[i],g),{actionId:'dodge',elapsedMs:tl.durationMs*i/120,durationMs:tl.durationMs,weight:1,realm:card.realm});passes++;}catch(e){first??={i,error:String(e)};}}results.push({mode,passes,first});}rows.push({reserve,g,results});}const row={name:r.identity.earthName,rows};report.subjects.push(row);console.log(JSON.stringify(row));}
fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n',{flag:'wx'});
