import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';
import {buildPaintSkin} from '../../port/v2/tools/creature-animation/build-paint-skin.mjs';
import {hashBytes,hashJSON} from '../../port/v2/tools/creature-animation/quadruped-template.mjs';import {finishConservation} from '../../port/v2/tools/painted-creature/finish-conservation.mjs';
const require=createRequire(new URL('../../port/v2/package.json',import.meta.url)),sharp=createRequire(require.resolve('free-tex-packer-core'))('sharp');
/** Batch form of painted-creature/rebind-finished.mjs (same guards) for finish-batch.mjs output. Repo root:
 * node audits/AI_FINISH_C121_20261001/rebind-batch.mjs FINISHED_DIR SUBJECTS.json NEW_OUTPUT */
export async function rebindFinished(list,finished,output){
 await fs.mkdir(output);const rows=[];
 for(const {id,fit} of list){
  try{const source=fit,dir=path.resolve(fit),record=JSON.parse(await fs.readFile(path.join(dir,'record.json'))),binding=JSON.parse(await fs.readFile(path.join(dir,'binding.json'))),finish=await fs.readFile(path.join(finished,id+'-finished.png')),receipt=JSON.parse(await fs.readFile(path.join(finished,id+'-receipt.json')));
   if(receipt.status!=='PASS'||receipt.sha256!==await hashBytes(finish)||receipt.receipt.identity.recordRecipeHash!==record.recipeHash||receipt.receipt.identity.cutoutAssetHash!==record.geometry.cutoutAssetHash)throw Error('Unqualified finished original');
   const masterBytes=await fs.readFile(path.resolve(record.source));if(await hashBytes(masterBytes)!==record.geometry.cutoutAssetHash)throw Error('Original master changed');
   const master=await sharp(masterBytes).ensureAlpha().raw().toBuffer({resolveWithObject:true}),pixels=await sharp(finish).ensureAlpha().raw().toBuffer(),labels=await sharp(path.join(finished,'prepared',id+'-labels.png')).ensureAlpha().raw().toBuffer();const conservation=finishConservation(master.data,pixels,labels,master.info.width,master.info.height);if(conservation.status!=='PASS')throw Error('Conservation refused');
   const manifest=JSON.parse(await fs.readFile(path.join(dir,'parts/manifest.json'))),atlasFile='parts/atlas/'+manifest.creatureId+'.png',atlasBytes=await fs.readFile(path.join(dir,atlasFile));if(await hashBytes(atlasBytes)!==binding.atlasSha256)throw Error('Atlas source changed');const atlas=await sharp(atlasBytes).ensureAlpha().raw().toBuffer({resolveWithObject:true}),originalAtlas=Buffer.from(atlas.data);
   let keyedApplied=0;const out=path.join(output,id);await fs.cp(dir,out,{recursive:true,errorOnExist:true,force:false});
   for(const part of binding.parts){const f=part.frame,b=part.cutout,file='parts/parts/'+part.id+'.png',raw=await sharp(path.join(dir,file)).ensureAlpha().raw().toBuffer();for(let y=0;y<b.height;y++)for(let x=0;x<b.width;x++){const i=(y*b.width+x)*4;if(!raw[i+3])continue;const source=((y+b.y)*master.info.width+x+b.x)*4;/* only finisher-changed pixels: keeps the auto keyer's despilled edges (a generated original's master RGB differs there) */if(pixels[source]===master.data[source]&&pixels[source+1]===master.data[source+1]&&pixels[source+2]===master.data[source+2])continue;for(let c=0;c<3;c++){raw[i+c]=pixels[source+c];atlas.data[((y+f.y)*atlas.info.width+x+f.x)*4+c]=raw[i+c];}}
    const bytes=await sharp(raw,{raw:{width:b.width,height:b.height,channels:4}}).png().toBuffer();await fs.writeFile(path.join(out,file),bytes);manifest.parts.find(p=>p.name===part.id+'.png').sha256=await hashBytes(bytes);
   }
   const newAtlas=atlas.data.equals(originalAtlas)?atlasBytes:await sharp(atlas.data,{raw:{width:atlas.info.width,height:atlas.info.height,channels:4}}).png().toBuffer();await fs.writeFile(path.join(out,atlasFile),newAtlas);{const kf=path.join(dir,'parts/keyed.png'),k=await sharp(kf).ensureAlpha().raw().toBuffer({resolveWithObject:true});let applied=0;for(let i=0;i<k.data.length;i+=4){if(!k.data[i+3])continue;if(pixels[i]===master.data[i]&&pixels[i+1]===master.data[i+1]&&pixels[i+2]===master.data[i+2])continue;k.data[i]=pixels[i];k.data[i+1]=pixels[i+1];k.data[i+2]=pixels[i+2];applied++;}await fs.writeFile(path.join(out,'parts/keyed.png'),await sharp(k.data,{raw:{width:k.info.width,height:k.info.height,channels:4}}).png().toBuffer());keyedApplied=applied;}await fs.writeFile(path.join(out,'parts/manifest.json'),JSON.stringify(manifest,null,2)+'\n');
   const partsBinding=JSON.parse(await fs.readFile(path.join(dir,'parts/binding.json')));const {bindingHash:oldPartsHash,...partsBody}=partsBinding;partsBody.atlasSha256=await hashBytes(newAtlas);await fs.writeFile(path.join(out,'parts/binding.json'),JSON.stringify({...partsBody,bindingHash:await hashJSON(partsBody)},null,2)+'\n');
   const before=await buildPaintSkin(path.join(dir,'parts'),{seamBridges:{groups:[]}},record),after=await buildPaintSkin(path.join(out,'parts'),{seamBridges:{groups:[]}},record);if(JSON.stringify(before.binding.parts)!==JSON.stringify(after.binding.parts)||JSON.stringify(before.binding.paintSkin)!==JSON.stringify(after.binding.paintSkin))throw Error('Recompiled texture geometry changed');
   const {bindingHash,...body}=binding;body.atlasSha256=await hashBytes(newAtlas);const next={...body,bindingHash:await hashJSON(body)};if(JSON.stringify(next.parts)!==JSON.stringify(binding.parts)||JSON.stringify(next.paintSkin)!==JSON.stringify(binding.paintSkin))throw Error('Texture changed geometry');await fs.writeFile(path.join(out,'binding.json'),JSON.stringify(next,null,2)+'\n');
   const proof={id,status:'PASS',painterBindingHash:bindingHash,finishedBindingHash:next.bindingHash,geometryByteIdentical:true,recompiledPaintSkinIdentical:true,recordUnchanged:true,keyedApplied,changedRgbOnlyCopied:true,atlasSha256:next.atlasSha256,conservation,source,finished};await fs.writeFile(path.join(out,'finished-rebind.json'),JSON.stringify(proof,null,2)+'\n');rows.push(proof);
  }catch(e){rows.push({id,status:'LEAF_RED',error:String(e)});}
 }
 await fs.writeFile(path.join(output,'rebind-summary.json'),JSON.stringify(rows,null,2)+'\n');return rows;
}

if(process.argv[1]&&import.meta.url.endsWith(path.basename(process.argv[1]))){const [finished,subjects,output]=process.argv.slice(2);const rows=await rebindFinished(JSON.parse(await fs.readFile(subjects,'utf8')),finished,output);console.log(JSON.stringify(rows.map(r=>({id:r.id,status:r.status,error:r.error}))));}
