import fs from'node:fs';import assert from'node:assert/strict';import{createHash}from'node:crypto';
import{compileBodyCard}from'../../port/v2/apps/game/src/motion/body-card.ts';
import{withPaintedContactSupports}from'../../port/v2/apps/game/src/motion/painted-supports.ts';
import{buildActionTimeline,sampleTimeline}from'../../port/v2/apps/game/src/motion/timeline.ts';
import{actionsFor}from'../../port/v2/apps/game/src/motion/family-actions.ts';
import{createFamilyContactSolver,observedContactSupports}from'../../port/v2/apps/game/src/creature-rig-contact.ts';
const B='audits/C202_ARTHROPOD_REFERENCES_20261004',fit=B+'/11-beetle-relaxed-legs/fit01',read=(f:string)=>JSON.parse(fs.readFileSync(f,'utf8')),record=read(fit+'/record.json'),binding=read(fit+'/binding.json'),card=withPaintedContactSupports(compileBodyCard(record,record.genome),record,binding),raw=actionsFor('insect',card.anatomy)!.hit!,torso=new Set(['root','thorax']);
const scaled=(gain:number)=>({...raw,poses:raw.poses.map(p=>({...p,joints:Object.fromEntries(Object.entries(p.joints).map(([j,v])=>[j,v*(torso.has(j)?gain:1)])),root:{dx:p.root.dx*gain,dy:p.root.dy*gain}}))});
function probe(gain:number,samples=128){const tl=buildActionTimeline(card,scaled(gain),card.identity.seed),modes=[];for(const travel of ['solver','stage']as const){const solver=createFamilyContactSolver(record,observedContactSupports(record,binding));let maxCompression=0,refusal=null,checked=0;for(let i=0;i<=samples;i++){const ms=tl.durationMs*i/samples,p=sampleTimeline(tl,ms),pose={...Object.fromEntries(Object.entries(p.joints).map(([j,rotation])=>[j,{rotation}])),root:p.root};try{const r=solver.resolve(pose,{actionId:'hit',elapsedMs:ms,durationMs:tl.durationMs,realm:card.realm,weight:1,travel});assert((r.maxError??0)<=1e-8);maxCompression=Math.max(maxCompression,r.compression??0);checked++;}catch(e){refusal={ms,error:String(e).split('\n')[0]};break;}}modes.push({travel,checked,maxCompression,limit:solver.scaleLength*.08,refusal});}return{gain,pass:modes.every(x=>!x.refusal),modes};}
const probes=[probe(1),probe(0)],zero=probes[1];let selected=null;if(!probes[0].pass&&zero.pass){let low=0,high=1;for(let i=0;i<12;i++){const m=(low+high)/2,r=probe(m);probes.push(r);if(r.pass)low=m;else high=m;}const gain=low*.9,r=probe(gain,480);probes.push(r);if(gain>0&&r.pass)selected={gain,action:scaled(gain),validation:r};}
const before=buildActionTimeline(card,raw,card.identity.seed),after=selected?buildActionTimeline(card,selected.action,card.identity.seed):null;if(after){assert.deepEqual(after.phases,before.phases);assert.equal(after.durationMs,before.durationMs);assert.deepEqual(after.secondary,before.secondary);assert.deepEqual(after.limitsRad,before.limitsRad);assert.deepEqual(after.deform,before.deform);for(const[j,keys]of Object.entries(before.tracks))if(!torso.has(j))assert.deepEqual(after.tracks[j],keys);}
fs.writeFileSync(B+'/hit-gain-diagnosis.json',JSON.stringify({schema:'cf.c202-audit-hit-authoring/v1',scope:'Audit-only pure contact proof on actual source-bound supports; not moving paint or native qualification',recordRecipeHash:record.recipeHash,bindingHash:binding.bindingHash,masterSha256:record.geometry.cutoutAssetHash,probes,selected,preserved:['all non-torso tracks','secondary curves','limits','deform','timing','phase inventory'],productChanged:false},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({selectedGain:selected?.gain??null,original:probes[0],zero:probes[1],final:selected?.validation??null}));
