import fs from 'node:fs';
const base=import.meta.dirname,source='audits/C196_SIMPLE_ORIGINALS_20261002',common='One whole anatomically accurate adult in the approved painted hand, isolated on pure magenta. Entire natural body and every appendage fit in the middle HALF of a native 1254 by 1254 canvas with about 300 pixels of empty magenta on every side. No floor, scenery, cast shadow, guides, labels or props. Preserve biological anatomy rather than matching a coarse rig inventory. ';
const simple={
 Shrimp:{family:'crustacean-small',legs:10,accuracy:'one actual shrimp with five pairs of thoracic walking legs, natural abdominal swimmerets, real short antennules and long antennae; no lobster claws or invented appendages',layout:common+'Right-facing shallow three-quarter side view, slightly elevated so both sides of the real thoracic walking legs can be traced through natural joints to their tips. Show all five actual walking-leg pairs, the complete six-section curved abdomen and terminal fanned tail, serrated rostrum and stalked eyes. Both long antennae remain continuously visible from bases to full unshortened tips. Preserve actual shorter antennules and abdominal swimmerets clearly attached in their real regions; do not delete real structures to simplify a template. No giant lobster claws. Keep every tail/antenna/leg tip well inside the margin.'},
 'Brittle Star':{family:'radial',legs:0,accuracy:'one headless radial animal with a tiny actual central disc and exactly five naturally long flexible arms; no jellyfish bell, eyes or invented mouth on its dorsal surface',layout:common+'Dorsal, slightly oblique view of a natural five-armed brittle star. Show its distinct tiny central disc and five fully extended gently curving noncrossing whip arms, all five biological arm bases and complete natural tips visible. Arms are thin, segmented and many times longer than the disc is wide, with real small marginal spines. Preserve natural proportions; never enlarge the disc to satisfy a geometry guard or substitute thick starfish arms. No fake jellyfish bell, face, eyes, dorsal mouth or sixth arm.'},
 'Fiddler Crab':{family:'brachyuran',legs:8,accuracy:'one male fiddler crab with four actual walking-leg pairs, two grossly unequal real claws and two stalked eyes; no visible vertebrate tail or extra legs',layout:common+'Slightly elevated front three-quarter view exposing the natural broad carapace, both long eye stalks, all FOUR actual walking-leg pairs as eight distinct connected root/bend/tip paths, and both real claws. The male has one enormously oversized major claw and one tiny minor claw; preserve this essential asymmetry. Both claws are slightly open so each real palm, fixed finger, movable dactyl and hinge are visible; tips must not overlap walking feet or hide the small claw. Keep the last actual walking pair visible by natural viewpoint and spacing, never infer or invent hidden feet. Do not substitute matched symmetric claws, spider jaws or extra appendages.'},
 Spider:{family:'arachnid',legs:8,accuracy:'one true spider with two-part body, eight actual walking legs and two front chelicerae; natural small pedipalps are not extra walking legs; no antennae or sting',layout:common+'Elevated front three-quarter view of a representative orb-weaver or house spider. Clearly show large abdomen, narrow connecting pedicel and smaller cephalothorax; all four genuine walking-leg pairs attach only to the cephalothorax. Eight complete natural root/knee/foot paths remain independently readable with gently offset poses and no crossings. Both actual chelicerae are visible at the front. Retain small mouth-adjacent pedipalps as real anatomy, never count them as ninth/tenth walking legs or delete them to fit a coarse template. No antennae, scorpion tail or stinger. Every long leg tip stays inside generous margins.'}
};
let s=fs.readFileSync(source+'/materialize.mjs','utf8');const once=(a,b)=>{if(s.split(a).length!==2)throw Error('Unique preparation transform');s=s.replace(a,b);};const start=s.indexOf('const simple={\n'),end=s.indexOf('\n};\ns+=',start);if(start<0||end<start)throw Error('Simple dictionary boundary');s=s.slice(0,start)+'const simple='+JSON.stringify(simple,null,2)+s.slice(end+2);once('return {legs:0,accuracy:row.accuracy,layout:row.layout}','return {legs:row.legs,accuracy:row.accuracy,layout:row.layout}');once("output:'audits/C196_SIMPLE_ORIGINALS_20261002/compiler.audit.mjs'","output:'audits/C196_INVERTEBRATE_ORIGINALS_20261002/compiler.audit.mjs'");fs.writeFileSync(base+'/materialize.mjs',s,{flag:'wx'});
let c=fs.readFileSync(source+'/compile.mjs','utf8');for(const[a,b]of [["base='audits/C196_SIMPLE_ORIGINALS_20261002'","base='audits/C196_INVERTEBRATE_ORIGINALS_20261002'"],["['Earthworm','Sponge','Snail','Mussel']","['Shrimp','Brittle Star','Fiddler Crab','Spider']"],["+'-'+name.toLowerCase()","+'-'+name.toLowerCase().replaceAll(' ','-')"]]){if(c.split(a).length!==2)throw Error('Unique compile preparation');c=c.replace(a,b);}fs.writeFileSync(base+'/compile.mjs',c,{flag:'wx'});
let t=fs.readFileSync(source+'/controls.mjs','utf8');for(const[a,b]of [["assert.equal(request.requestedVisibleLegs,0)","assert.equal(request.requestedVisibleLegs,{'Shrimp':10,'Brittle Star':0,'Fiddler Crab':8,'Spider':8}[row.name])"],["exact canonical route, zero requested legs and bound source","exact canonical route, biological requested legs and bound source"]]){if(t.split(a).length!==2)throw Error('Unique control preparation');t=t.replace(a,b);}fs.writeFileSync(base+'/controls.mjs',t,{flag:'wx'});
for(const f of ['retain.mjs','observe.mjs','framing.mjs','review.mjs'])fs.copyFileSync(source+'/'+f,base+'/'+f,fs.constants.COPYFILE_EXCL);
