/** @module battle2/arena-registry [app] — which painted arena a battle is fought on (2026-10-01, Dakk's vision: every creature
 * fights on its own home ground). Pure and clock-free: the arena follows the battle's WORLD (home-versus-visitor rule), the
 * world's live biome picks the painted plate set, and a biome without one falls back deterministically with its reason.
 *
 * - Biome vocabulary: the 43 live biomes of the generator (`@cf/domain-strays` `BIOME_SETS`, grouped by world type: terran,
 *   ocean, ice, desert, rocky, venus, lava, gas), checked at load against `BIOME_PROFILE_KEYS_V1`. Nothing is invented here.
 * - Sets: `arena-sets.generated.json`, generated by `tools/morph/arena-sets.mjs` from the delivery manifests listed in
 *   `tools/morph/arena-deliveries.json` (cf.arena-delivery/v1): the runtime paths are each manifest's own (the temperate set's
 *   MID is the approved despilled copy). `arena-registry.test.ts` validates every row with `arena-delivery.ts`.
 * - Fight world: wild → the wild creature's world, guardian → its lair (both the battle's `home`), duel → host and visitor
 *   alternate by round from a seeded first host — the SAME rule `compileHabitatBattle` applies (`fightWorld`, pinned equal by test).
 * - Set choice: the world's own biome (`match: 'biome'`), else a set painted for another biome of the same world type
 *   (`'kin'`), else the accepted Earth temperate set (`'fallback'`; on a world with liquid the stage's procedural wet arena
 *   draws the water, as before). Among several sets the pick is seeded by the WORLD (key + seed), so a world always shows the
 *   same home ground, battle after battle. No Math.random, no clock. */
import { mulberry32 } from '@cf/domain-rand';
import { BIOME_SETS } from '@cf/domain-strays';
import { BIOME_PROFILE_KEYS_V1, type BiomeProfileKeyV1 } from '@cf/domain-biome-profile';
import type { ArenaWorld } from '../battle-habitat.js';
import ARENA_SETS_JSON from './arena-sets.generated.json';

/** The arena proof directory every battle2 asset path is relative to (the wiring's `arena-recipe.json` URL lives here). */
export const ARENA_PROOF_DIR = 'audits/ARENA_EFFECTS_V42_PROOF_20260912/' as const;
export const ARENA_FALLBACK_SET_ID = 'earth-temperate-v1' as const;
export const ARENA_WORLD_TYPES = Object.freeze(['terran', 'ocean', 'ice', 'desert', 'rocky', 'venus', 'lava', 'gas'] as const);
export type ArenaWorldType = typeof ARENA_WORLD_TYPES[number];

/** Live biome → its world type, read from the generator's own table (never retyped). Throws at load on any drift. */
export const ARENA_BIOME_WORLD_TYPE: Readonly<Record<BiomeProfileKeyV1, ArenaWorldType>> = (() => {
  const out: Partial<Record<string, ArenaWorldType>> = {};
  if (JSON.stringify(Object.keys(BIOME_SETS).sort()) !== JSON.stringify([...ARENA_WORLD_TYPES].sort())) throw new Error('arena registry: BIOME_SETS world types drifted');
  for (const type of ARENA_WORLD_TYPES) for (const b of BIOME_SETS[type]!) { const k = b.k; if (typeof k !== 'string' || out[k]) throw new Error(`arena registry: bad or duplicate biome ${String(k)}`); out[k] = type; }
  const keys = Object.keys(out).sort(), live = [...BIOME_PROFILE_KEYS_V1].sort();
  if (JSON.stringify(keys) !== JSON.stringify(live)) throw new Error('arena registry: BIOME_SETS and BIOME_PROFILE_KEYS_V1 disagree');
  return Object.freeze(out as Record<BiomeProfileKeyV1, ArenaWorldType>);
})();

/** One registered set, as generated from its delivery manifest. Every path is repo-relative under audits/. */
export interface ArenaSetRow {
  readonly id: string; readonly biome: BiomeProfileKeyV1;
  /** The delivery manifest (cf.arena-delivery/v1) this row was generated from. */
  readonly delivery: string;
  /** Runtime files: the recipe, the opaque FAR and the keyed (alpha) MID/NEAR the stage draws. */
  readonly recipe: string; readonly far: string; readonly mid: string; readonly near: string;
  /** The painted masters (FAR scene; MID/NEAR key-painted on magenta) whose SHA-256 the recipe and acceptance record. */
  readonly masters: Readonly<{ far: string; mid: string; near: string }>;
  /** Acceptance record (`cf.arena-template-acceptance/v1`, qualityAccepted true). */
  readonly acceptance: string;
}
const AUDIT_PATH = /^audits\/(?!.*\.\.)[A-Za-z0-9_./-]+$/;
function checkRow(r: unknown, i: number): ArenaSetRow {
  const o = r as Record<string, unknown>, at = `arena sets row ${i}`;
  if (!o || typeof o !== 'object') throw new TypeError(`${at}: not an object`);
  const p = (v: unknown, k: string): string => { if (typeof v !== 'string' || !AUDIT_PATH.test(v)) throw new TypeError(`${at}: "${k}" must be a repo-relative path under audits/`); return v; };
  const id = o.id; if (typeof id !== 'string' || !/^[a-z0-9-]+$/.test(id)) throw new TypeError(`${at}: id must be kebab-case`);
  const biome = o.biome; if (typeof biome !== 'string' || !Object.hasOwn(ARENA_BIOME_WORLD_TYPE, biome)) throw new TypeError(`${at}: biome "${String(biome)}" is not one of the 43 live biomes`);
  const m = (o.masters ?? {}) as Record<string, unknown>;
  return Object.freeze({ id, biome: biome as BiomeProfileKeyV1, delivery: p(o.delivery, 'delivery'), recipe: p(o.recipe, 'recipe'), far: p(o.far, 'far'), mid: p(o.mid, 'mid'), near: p(o.near, 'near'),
    masters: Object.freeze({ far: p(m.far, 'masters.far'), mid: p(m.mid, 'masters.mid'), near: p(m.near, 'masters.near') }), acceptance: p(o.acceptance, 'acceptance') });
}
/** Parse and freeze the generated sets (exported for the tests' mutants). */
export function parseArenaSets(json: unknown): readonly ArenaSetRow[] {
  const j = json as { schema?: unknown; sets?: unknown };
  if (!j || j.schema !== 'cf.arena-sets/v1' || !Array.isArray(j.sets)) throw new TypeError('arena sets: schema cf.arena-sets/v1 with a sets array required');
  const rows = j.sets.map(checkRow), ids = new Set<string>();
  for (const r of rows) { if (ids.has(r.id)) throw new TypeError(`arena sets: duplicate id ${r.id}`); ids.add(r.id); }
  if (!ids.has(ARENA_FALLBACK_SET_ID)) throw new TypeError(`arena sets: the fallback set ${ARENA_FALLBACK_SET_ID} must stay registered`);
  return Object.freeze(rows);
}
export const ARENA_SETS: readonly ArenaSetRow[] = parseArenaSets(ARENA_SETS_JSON);

/** A repo-relative path as an asset path relative to the arena proof directory (what `devAssetSource` resolves). */
export function arenaAssetPath(repoRelative: string): string {
  if (repoRelative.startsWith(ARENA_PROOF_DIR)) return repoRelative.slice(ARENA_PROOF_DIR.length);
  if (!repoRelative.startsWith('audits/')) throw new TypeError(`arena registry: ${repoRelative} is not under audits/`);
  return '../' + repoRelative.slice('audits/'.length);
}
export interface ArenaSetAssets { readonly recipe: string; readonly far: string; readonly mid: string; readonly near: string; }
/** The runtime files of a set, relative to the arena proof directory (e.g. `arena-recipe.json`, `../ARENA_V1_ACCEPTANCE_20260912/arena-mid-despilled.png`). */
export function arenaSetAssets(row: ArenaSetRow): ArenaSetAssets {
  return Object.freeze({ recipe: arenaAssetPath(row.recipe), far: arenaAssetPath(row.far), mid: arenaAssetPath(row.mid), near: arenaAssetPath(row.near) });
}
/** The fallback (accepted Earth temperate) set's runtime files — what a battle without world context draws. */
export const ARENA_FALLBACK_ASSETS: ArenaSetAssets = arenaSetAssets(ARENA_SETS.find((s) => s.id === ARENA_FALLBACK_SET_ID)!);


/* ---------- selection ---------- */
export type ArenaKind = 'wild' | 'guardian' | 'duel';
export interface ArenaSelectionContext {
  readonly kind: ArenaKind;
  /** The battle id (the habitat compiler's `contextId`). */
  readonly contextId: string;
  /** The battle seed (uint32-safe integer; never a clock). */
  readonly seed: number;
  /** Duel round (0-based); wild and guardian fights ignore it. */
  readonly round: number;
  /** The battle's worlds: wild → the wild creature's world, guardian → its lair, duel → host (`home`) and visitor. Null = no
   * world context (today's game): the accepted Earth temperate set, labelled as the default. */
  readonly worlds: Readonly<{ home: ArenaWorld; visitor: ArenaWorld }> | null;
  /** The fight is on Earth (seed 133), which has no generator biome (`biomeFor` returns null): with `worlds` null it stays on the
   * accepted temperate set, as before, and the reason names Earth instead of a missing world context (battle2-live-worlds.ts). */
  readonly earth?: boolean;
}
export type ArenaOwner = 'wild-world' | 'lair' | 'host' | 'visitor' | 'default';
export interface ArenaSelection {
  readonly set: ArenaSetRow; readonly assets: ArenaSetAssets;
  /** The world the fight is on (null without world context). Pass it as BOTH habitat worlds so the medium agrees with the plates. */
  readonly world: ArenaWorld | null;
  readonly owner: ArenaOwner; readonly biome: BiomeProfileKeyV1; readonly worldType: ArenaWorldType;
  readonly match: 'biome' | 'kin' | 'fallback' | 'default';
  readonly reason: string;
}

/** FNV-1a 32 — the habitat compiler's hash, so `fightWorld` is its rule exactly. */
const fnv = (s: string): number => { let h = 2166136261; for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619); return h >>> 0; };
/** Home-versus-visitor: wild/guardian fight on `home`; a duel's first host is seeded, then host and visitor alternate by round. */
export function fightWorld(kind: ArenaKind, contextId: string, seed: number, round: number): 'home' | 'visitor' {
  if (kind !== 'duel') return 'home';
  return (round + (fnv(contextId + ':' + seed) % 2)) % 2 === 1 ? 'visitor' : 'home';
}
const pickSeeded = (rows: readonly ArenaSetRow[], world: ArenaWorld): ArenaSetRow => rows.length === 1 ? rows[0]! : rows[Math.floor(mulberry32(fnv(world.key + '#' + world.seed))() * rows.length)]!;

export function selectArena(context: ArenaSelectionContext, sets: readonly ArenaSetRow[] = ARENA_SETS): ArenaSelection {
  if (!context || !['wild', 'guardian', 'duel'].includes(context.kind)) throw new TypeError('arena selection: unknown encounter kind');
  if (typeof context.contextId !== 'string' || !context.contextId) throw new TypeError('arena selection: contextId required');
  if (!Number.isSafeInteger(context.seed)) throw new TypeError('arena selection: seed must be a safe integer');
  if (!Number.isInteger(context.round) || context.round < 0) throw new TypeError('arena selection: round must be a non-negative integer');
  const fallback = sets.find((s) => s.id === ARENA_FALLBACK_SET_ID); if (!fallback) throw new TypeError(`arena selection: fallback set ${ARENA_FALLBACK_SET_ID} missing`);
  const done = (set: ArenaSetRow, world: ArenaWorld | null, owner: ArenaOwner, biome: BiomeProfileKeyV1, match: ArenaSelection['match'], reason: string): ArenaSelection =>
    Object.freeze({ set, assets: arenaSetAssets(set), world, owner, biome, worldType: ARENA_BIOME_WORLD_TYPE[biome], match, reason });
  if (!context.worlds) {
    if (context.earth !== true) return done(fallback, null, 'default', fallback.biome, 'default', `no world context: accepted ${fallback.id} plates`);
    const where = context.kind === 'wild' ? "the wild creature's world" : context.kind === 'guardian' ? "the guardian's lair" : 'the duel world';
    return done(fallback, null, 'default', fallback.biome, 'default', `${where} is Earth (home world, no generator biome): accepted ${fallback.id} plates`);
  }
  const side = fightWorld(context.kind, context.contextId, context.seed, context.round), world = context.worlds[side];
  if (!world || !Object.hasOwn(ARENA_BIOME_WORLD_TYPE, world.biome)) throw new TypeError('arena selection: the fight world needs a live biome');
  const owner: ArenaOwner = context.kind === 'wild' ? 'wild-world' : context.kind === 'guardian' ? 'lair' : side === 'home' ? 'host' : 'visitor';
  const whose = context.kind === 'wild' ? "the wild creature's world" : context.kind === 'guardian' ? "the guardian's lair" : `duel round ${context.round}: the ${side === 'home' ? 'host' : 'visitor'}'s world (seeded first host, then alternating)`;
  const biome = world.biome, type = ARENA_BIOME_WORLD_TYPE[biome];
  const own = sets.filter((s) => s.biome === biome);
  if (own.length) { const set = pickSeeded(own, world); return done(set, world, owner, biome, 'biome', `${whose} ${world.key} (${biome}, ${type}): painted set ${set.id}`); }
  const kin = sets.filter((s) => ARENA_BIOME_WORLD_TYPE[s.biome] === type);
  if (kin.length) { const set = pickSeeded(kin, world); return done(set, world, owner, biome, 'kin', `${whose} ${world.key} (${biome}, ${type}): no ${biome} set yet; nearest kin ${set.id} (${set.biome}, same world type)`); }
  const wet = world.liquid ? `; world liquid ${world.liquid}: the stage's procedural wet arena draws it for a side in ${world.liquid}` : '';
  return done(fallback, world, owner, biome, 'fallback', `${whose} ${world.key} (${biome}, ${type}): no painted ${type} set yet; fallback accepted ${fallback.id} plates${wet}`);
}
