import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{createHash}from'node:crypto';import{createRequire}from'node:module';import{setup,json,PNG}from'./publication.mjs';import{traceSourcePixels}from'./source-trace.mjs';import{rasterPaint}from'../C132_FAINT_GROUND_20261002/render-mesh.mjs';import{createOpaqueSeamSamplingGuard,applyOpaqueSeamSamplingGuard}from'../../port/v2/tools/creature-animation/seam-sampling-guard.mjs';
const{loadCreatureRigV1}=await import('../../port/v2/apps/game/src/creature-rig.ts');const require=createRequire(new URL('../../port/v2/package.json',import.meta.url)),{BufferImageSource,Texture}=require('pixi.js');
const base='audits/C169_NAPE_RECUT_20261002',sha=b=>createHash('sha256').update(b).digest('hex'),read=p=>fs.readFileSync(p),pins=new Map(),pin=p=>{pins.set(p,sha(read(p)));},inputs=json(base+'/inputs.json').rows;
function scan(d,match){for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isDirectory())scan(p,match);else if(match.test(p))pin(p);}}
scan('port/v2/apps/game/src/motion',/\.ts$/);for(const p of ['port/v2/apps/game/src/battle2/choreography.ts','port/v2/apps/game/src/creature-rig.ts','port/v2/apps/game/src/creature-rig-contact.ts'])pin(p);scan('port/v2/tools/creature-animation',/\.(mjs|ts|wasm)$/);for(const p of ['publication.mjs','source-trace.mjs','compare-v2.mjs','inputs.json'])pin(base+'/'+p);for(const p of ['paint-publication.mjs','render-mesh.mjs'])pin('audits/C132_FAINT_GROUND_20261002/'+p);
for(const i of inputs){for(const p of i.inputs){assert.equal(sha(read(p.path)),p.sha256);pin(p.path);}for(const v of ['record.json','binding.json'])pin(base+'/'+i.id+'/fit/'+v);pin(base+'/'+i.id+'/candidate/authoring.json');}
const rows=[];
for(const input of inputs){const results=[],originalTimeline=setup(input).timeline;
 for(const mode of ['original','candidate']){const fit=mode==='original'?input.fit:base+'/'+input.id+'/fit',s=setup(input,fit);assert.deepEqual(s.timeline.tracks,originalTimeline.tracks,'motion tracks unchanged');assert.deepEqual(s.timeline.phases,originalTimeline.phases);assert.equal(s.timeline.durationMs,originalTimeline.durationMs);const heldMs=input.native.stillTime-input.native.turn.offsetMs-input.native.turn.beats.reactionStart,variant={mode,fit,facings:[],qualityAccepted:false};
  const atlasFile=path.join(fit,'parts/atlas',fs.readdirSync(path.join(fit,'parts/atlas')).find(p=>p.endsWith('.png'))),atlasBytes=read(atlasFile),keyed=PNG.sync.read(read(fit+'/parts/keyed.png')),alpha=Uint8Array.from({length:keyed.width*keyed.height},(_,i)=>keyed.data[i*4+3]),texture=new Texture({source:new BufferImageSource({resource:new Uint8Array(s.atlas.data),width:s.atlas.width,height:s.atlas.height})}),master=read(base+'/'+input.id+(mode==='original'?'/original/master.png':'/candidate/master.png'));
  const rig=await loadCreatureRigV1(s.record,s.binding,master,alpha,atlasBytes,async()=>texture);
  try{for(const side of ['left','right']){let maxDrift=0,rowsDense=0,refusal=null;const times=[...Array.from({length:121},(_,i)=>s.timeline.durationMs*i/120),s.timeline.durationMs-.001,s.timeline.durationMs+.001,heldMs];
    for(const ms of times){try{const frame=s.publish(side,ms);maxDrift=Math.max(maxDrift,...frame.publishedContacts.map(c=>c.driftPx));rowsDense++;}catch(e){refusal={elapsedMs:ms,message:String(e).split('\n')[0]};break;}}
    const parity=[];for(const ms of [0,s.timeline.durationMs/2,heldMs]){const frame=s.publish(side,ms);rig.applyPose(frame.resolved);let coordinates=0;for(const part of rig.parts){const actual=part.display.children[0].geometry.getBuffer('aPosition').data,expected=frame.positions[part.id];assert.equal(actual.length,expected.length);assert(Buffer.from(actual.buffer,actual.byteOffset,actual.byteLength).equals(Buffer.from(expected.buffer,expected.byteOffset,expected.byteLength)),'actual CreatureRig publication differs '+part.id);coordinates+=actual.length;}parity.push({elapsedMs:ms,coordinates,byteParity:true});}
    const frame=s.publish(side,heldMs),points=traceSourcePixels(s.record,s.binding,s.atlas,frame.positions),at=json(base+'/'+input.id+'/attribution.json').closestPositiveAlpha[0],matched=points.filter(p=>p.source[0]===at.source[0]&&p.source[1]===at.source[1]);assert.equal(matched.length,1,'same visible source pixel conserved');const point={...matched[0],stage:s.stage(...matched[0].published,side)},knownDistance=side==='right'?Math.hypot(point.stage[0]-input.visibleTipStagePx[0],point.stage[1]-input.visibleTipStagePx[1]):null;if(mode==='original'&&side==='right')assert(knownDistance<.25,'original defect at exact observed native point must reproduce');
    if(mode==='candidate'){const originalAtlasSha=sha(s.atlas.data),guard=createOpaqueSeamSamplingGuard({record:s.record,binding:s.binding,atlas:{width:s.atlas.width,height:s.atlas.height,rgba:s.atlas.data}}),atlas={...s.atlas,data:applyOpaqueSeamSamplingGuard(Uint8Array.from(s.atlas.data),s.atlas.width,s.atlas.height,guard)};assert.equal(sha(s.atlas.data),originalAtlasSha,'raster guard must not mutate source atlas');fs.writeFileSync(base+'/'+input.id+'/candidate-held-v2-'+side+'.png',PNG.sync.write(rasterPaint(s.record,s.binding,atlas,frame.positions,side==='left'?1:-1)),{flag:'wx'});}
    variant.facings.push({side,samples:rowsDense,refusal,maximumPublishedContactDriftPx:maxDrift,actualRuntimeParity:parity,attributedSourcePixel:point,distanceToObservedOriginalTip:knownDistance});
   }}finally{rig.dispose();}results.push(variant);}
 const row={id:input.id,motionChanged:false,results,nativeRun:false,qualityAccepted:false};rows.push(row);fs.writeFileSync(base+'/'+input.id+'/comparison-v2.json',JSON.stringify(row,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({id:input.id,variants:results.map(v=>({mode:v.mode,facings:v.facings.map(f=>({side:f.side,samples:f.samples,refusal:f.refusal,sourcePixel:f.attributedSourcePixel.source,joint:f.attributedSourcePixel.joint,stage:f.attributedSourcePixel.stage}))}))}));
}
for(const[p,s]of pins)assert.equal(sha(read(p)),s,'source drift '+p);
fs.writeFileSync(base+'/comparison-v2.json',JSON.stringify({schema:'cf.c169-runtime-publication-comparison/v1',scope:'Actual contact/skin/ARAP publication plus byte parity to loaded CreatureRigV1 using decoded CPU textures; no browser, GPU, performance or native admission.',rows,sourcePins:[...pins].map(([path,sha256])=>({path,sha256})),sourceUnchanged:true,qualityAccepted:false},null,2)+'\n',{flag:'wx'});
