import fs from'node:fs';import assert from'node:assert/strict';import{createHash}from'node:crypto';import{json,PNG}from'./publication.mjs';import{authoredRegionOwners}from'../../port/v2/tools/creature-animation/authored-region-owners.mjs';import{placeRemainderIslands,MAX_SHARE}from'../G1_AUTO_AUTHOR_20260926/remainder-islands-fit.mjs';
const base='audits/C169_NAPE_RECUT_20261002',sha=b=>createHash('sha256').update(b).digest('hex'),read=p=>fs.readFileSync(p);
const inside=(x,y,p)=>{let yes=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;};
function replay(a,key,w,h){const o=authoredRegionOwners(a.parts,a.remainderPart),poly=a.parts.map(p=>p.polygonPx.map(([x,y])=>[x/w,y/h])),rem=a.parts.findIndex(p=>p.id===a.remainderPart),labels=new Uint8Array(w*h);for(let i=0;i<labels.length;i++){if(!key[i*4+3])continue;const p=poly.findIndex(p=>inside((i%w+.5)/w,(Math.floor(i/w)+.5)/h,p));labels[i]=o.ownerIndex[p<0?rem:p]+1;}return{labels,parts:o.ownerParts};}
function compiled(fit,parts){const p=PNG.sync.read(read(fit+'/parts/ownership.png')),colors=new Map(parts.map((_,i)=>{let k=i+1;return[`${(k*83)%200+35},${(k*137)%200+35},${(k*47)%200+35}`,k];}));return Uint8Array.from({length:p.width*p.height},(_,i)=>p.data[i*4+3]?colors.get(`${p.data[i*4]},${p.data[i*4+1]},${p.data[i*4+2]}`):0);}
const rows=[];assert.equal(MAX_SHARE,.05);
for(const input of json(base+'/inputs.json').rows){const dir=base+'/'+input.id,a=json(dir+'/original/authoring.json'),b=json(dir+'/candidate-v2/authoring.json'),edit=json(dir+'/recut-v2.json'),key=PNG.sync.read(read(input.fit+'/parts/keyed.png')),key2=PNG.sync.read(read(dir+'/fit-v2/parts/keyed.png')),{width:w,height:h}=key;assert.deepEqual(key.data,key2.data);assert.equal(sha(read(dir+'/original/master.png')),sha(read(dir+'/candidate-v2/master.png')));assert.deepEqual(a.landmarksPx,b.landmarksPx);
 const nape=edit.scope.kind==='posterior-patch-to-chest',before=replay(a,key.data,w,h),after=replay(b,key.data,w,h),oldWithout=nape?replay({...a,parts:a.parts.filter(p=>p.id!=='reviewed-nape')},key.data,w,h):before;assert.deepEqual(before.parts,after.parts);assert.deepEqual(before.labels,compiled(input.fit,before.parts));assert.deepEqual(after.labels,compiled(dir+'/fit-v2',after.parts));assert.deepEqual(after.labels,replay(b,key.data,w,h).labels);const rem=before.parts.findIndex(p=>p.id===a.remainderPart)+1;
 if(nape)assert.deepEqual(a.parts.filter(p=>p.id!=='reviewed-nape'),b.parts.filter(p=>!p.id.startsWith('reviewed-nape-')));else assert.deepEqual(a.parts,b.parts.filter(p=>!p.id.startsWith('reviewed-contiguous-')));
 function compare(x,y){let moved={};for(let i=0;i<x.length;i++){assert.equal(Boolean(x[i]),Boolean(y[i]),'source paint deletion/addition');if(x[i]===y[i])continue;const ox=i%w+.5,oy=Math.floor(i/w)+.5,from=before.parts[x[i]-1].joint,to=after.parts[y[i]-1].joint;if(nape){assert.equal(oldWithout.labels[i],rem,'non-patch ownership changed');assert.equal(from,'neck1');assert(['chest','neck0','neck1'].includes(to),'unreviewed nape recipient');assert(inside(ox,oy,edit.scope.originalRegion.polygonPx),'out of reviewed patch');}else{assert(edit.scope.permittedPriorJoints.includes(from),'prior non-ear owner changed');assert(edit.scope.regions.some(p=>p.joint===to&&inside(ox,oy,p.polygonPx)),'outside named contiguous-ear contour');}const k=from+'->'+to;moved[k]=(moved[k]??0)+1;}return moved;}
 const moved=compare(before.labels,after.labels),non=before.labels.findIndex((v,i)=>v&&oldWithout.labels[i]!==rem&&(nape||!edit.scope.regions.some(p=>inside(i%w+.5,Math.floor(i/w)+.5,p.polygonPx)))),bad=Uint8Array.from(after.labels);bad[non]=rem;assert.throws(()=>compare(before.labels,bad),/ownership changed|owner changed|contour/);bad[non]=0;assert.throws(()=>compare(before.labels,bad),/paint deletion/);const cap=placeRemainderIslands(after.labels,w,h,rem),cap0=placeRemainderIslands(before.labels,w,h,rem),row={id:input.id,sourceMasterSha256:sha(read(dir+'/original/master.png')),sourceRgbaChangedChannels:0,paintPixelsRemoved:0,paintPixelsAdded:0,landmarksChanged:false,priorNonPatchOwnersChanged:0,crownAndBillCorrectionsUnchanged:true,independentReplay:true,compiledLabelsEqual:true,moved,originalCap:'PASS',candidateCap:'PASS',unchangedCap:MAX_SHARE,remainingMinorIslands:cap.islands,controls:['frozen original replay equals compiled labels','candidate replay equals compiled labels','deterministic replay','exact keyed RGBA equality','unreviewed ownership theft refused','paint deletion refused'],qualityAccepted:false};rows.push(row);fs.writeFileSync(dir+'/conservation-v2.json',JSON.stringify(row,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({id:input.id,moved,cap:'PASS'}));}
fs.writeFileSync(base+'/conservation-v2.json',JSON.stringify({schema:'cf.c169-contour-conservation/v1',rows},null,2)+'\n',{flag:'wx'});
