import fs from'node:fs';import path from'node:path';import{registerHooks,createRequire}from'node:module';import{resolve}from'../../port/v2/tools/effects-proof/resolve-ts-hook.mjs';registerHooks({resolve});
const {compileBodyCard}=await import('../../port/v2/apps/game/src/motion/body-card.ts');const{withPaintedContactSupports}=await import('../../port/v2/apps/game/src/motion/painted-supports.ts');const{buildTimeline}=await import('../../port/v2/apps/game/src/motion/timeline.ts');const{buildTurnPlan,sampleTurn}=await import('../../port/v2/apps/game/src/battle2/choreography.ts');
const{createPaintPublication}=await import('../C132_FAINT_GROUND_20261002/paint-publication.mjs');
const require=createRequire(new URL('../../port/v2/package.json',import.meta.url));export const{PNG}=require('pngjs');
export const json=p=>JSON.parse(fs.readFileSync(p));
export function setup(input,fit=input.fit){const record=json(fit+'/record.json'),binding=json(fit+'/binding.json'),card=withPaintedContactSupports(compileBodyCard(record,record.genome),record,binding),publication=createPaintPublication(record,binding,card.realm),timeline=buildTimeline(card,'faint',card.identity.seed),seed=json('audits/ARENA_EFFECTS_V42_PROOF_20260912/arena-recipe.json').seed;
 const plans=Object.fromEntries(['left','right'].map(side=>{const other=side==='left'?'right':'left',actor=s=>({side:s,mass:card.massClass.multiplier,card,seed:s==='left'?1:2,label:'C169 source attribution'}),plan=buildTurnPlan({seed,attacker:actor(other),target:actor(side),delivery:'melee',theme:'wild',outcome:'hit',damage:21,targetFaints:true,effect:null,readyMs:600,commandMs:300,arena:{groundLineY:.78,stands:input.native.stands}});return[side,{...plan,beats:input.native.turn.beats}];}));
 const owners=binding.parts.filter(p=>p.kind==='part'),atlasFile=path.join(fit,'parts/atlas',record.id+'.png');const atlas=PNG.sync.read(fs.readFileSync(fs.existsSync(atlasFile)?atlasFile:path.join(fit,'parts/atlas',fs.readdirSync(path.join(fit,'parts/atlas')).find(p=>p.endsWith('.png'))))),keyed=PNG.sync.read(fs.readFileSync(fit+'/parts/keyed.png'));let top=keyed.height;for(let y=0;y<keyed.height&&top===keyed.height;y++)for(let x=0;x<keyed.width;x++)if(keyed.data[(y*keyed.width+x)*4+3]>8){top=y;break;}
 const scales=Object.fromEntries(['left','right'].map(side=>[side,input.native.restFill[side]*input.native.frame.height/(record.geometry.groundLineY-top/record.geometry.height)]));
 const stage=(x,y,side)=>[input.native.stands[side].x*input.native.frame.width+(side==='left'?1:-1)*(x-record.landmarks.root[0])*scales[side],input.native.stands[side].y*input.native.frame.height+(y-record.geometry.groundLineY)*scales[side]];
 return{record,binding,card,timeline,atlas,stage,publication,publish(side,elapsed){const target=sampleTurn(plans[side],plans[side].beats.reactionStart+elapsed).target;return{...publication.publish(target.pose,target.context),target};}};
}
