import fs from'node:fs';import assert from'node:assert/strict';import{createHash}from'node:crypto';
const base='audits/C169_NAPE_RECUT_20261002',read=p=>fs.readFileSync(p),json=p=>JSON.parse(read(p)),sha=b=>createHash('sha256').update(b).digest('hex');
const bands={
 hawk:{shoulder:[[639,482],[674,470],[682,504],[639,504]],lower:[[639,452],[703,452],[718,504],[639,504]]},
 crow:{shoulder:[[660,456],[694,445],[706,477],[660,477]],lower:[[660,420],[724,420],[739,477],[660,477]]},
 'snowy-owl':{shoulder:[[637,447],[686,430],[706,472],[637,472]],lower:[[637,381],[740,381],[758,472],[637,472]]}
};
for(const input of json(base+'/inputs.json').rows){const dir=base+'/'+input.id,old=json(dir+'/original/authoring.json'),candidate=dir+'/candidate';assert(!fs.existsSync(candidate));fs.mkdirSync(candidate);for(const n of ['master.png','subject-source.json','presence.json'])fs.copyFileSync(dir+'/original/'+n,candidate+'/'+n,fs.constants.COPYFILE_EXCL);let parts,scope;
 if(bands[input.id]){const index=old.parts.findIndex(p=>p.id==='reviewed-nape');assert(index>=0);const patch=old.parts[index];assert.equal(patch.joint,'neck1');parts=[...old.parts.slice(0,index),{id:'reviewed-nape-shoulder',joint:'chest',layer:'near',polygonPx:bands[input.id].shoulder},{id:'reviewed-nape-lower',joint:'neck0',layer:'near',polygonPx:bands[input.id].lower},{...patch,id:'reviewed-nape-upper'},...old.parts.slice(index+1)];scope={kind:'nape-only',originalRegion:patch,sourceAttribution:json(dir+'/attribution.json').closestPositiveAlpha[0],reason:'Positive-alpha spike originates at posterior dorsal neck/withers paint, far behind the upper-neck pivot. Source-specific oblique bands assign the posterior shoulder contour to chest, central lower nape to neck0, and retain its short upper collar on neck1. All original non-patch polygons and crown/bill corrections remain exact.',regions:parts.slice(index,index+3)};}
 else{assert.equal(input.id,'wild-pony');const additions=[{id:'reviewed-near-ear-tip-fleck',joint:'earNearTip',layer:'near',polygonPx:[[861,339],[886,339],[886,363],[861,363]]},{id:'reviewed-far-ear-tip-fleck',joint:'earFarTip',layer:'far',polygonPx:[[920,348],[938,348],[938,366],[920,366]]}];parts=[...old.parts.slice(0,-1),...additions,old.parts.at(-1)];scope={kind:'two-small-ear-tip-contours',sourceAttribution:json(dir+'/attribution.json').closestPositiveAlpha[0],reason:'Exact native fleck is existing near-ear-tip source paint at871,353 incorrectly owned by spine. Two small visible pinna-tip contours receive existing ear-tip joints; prior owners and all body/limb polygons stay unchanged.',regions:additions};}
 const next={...old,parts,coverage:{...old.coverage,c169Scope:scope.reason,qualityAccepted:false}};fs.writeFileSync(candidate+'/authoring.json',JSON.stringify(next,null,2)+'\n',{flag:'wx'});fs.writeFileSync(dir+'/recut.json',JSON.stringify({schema:'cf.c169-source-contour-recut/v1',id:input.id,originalAuthoringSha256:sha(read(dir+'/original/authoring.json')),candidateAuthoringSha256:sha(read(candidate+'/authoring.json')),sourceMasterSha256:sha(read(candidate+'/master.png')),scope,landmarksChanged:false,sourcePixelsChanged:false,runtimeChanged:false,unchangedCap:.05,qualityAccepted:false},null,2)+'\n',{flag:'wx'});
}
