import fs from'node:fs';import {createRequire}from'node:module';import {pathToFileURL}from'node:url';
const root=new URL('../../../',import.meta.url).pathname,require=createRequire(root+'port/v2/package.json'),{rolldown}=require('rolldown'),{PNG}=createRequire(require.resolve('free-tex-packer-core'))('pngjs');
const {verifyPartsDirectory}=await import(pathToFileURL(root+'port/v2/tools/creature-animation/verify-parts.mjs')),{partAncestry}=await import(pathToFileURL(root+'port/v2/tools/creature-animation/band-patches.mjs'));
const bundle=await rolldown({input:root+'port/v2/apps/game/src/creature-rig-contact.ts',platform:'node'});await bundle.write({file:'/private/tmp/cf-junction-pose.mjs',format:'es'});await bundle.close();const{poseMatrices}=await import('file:///private/tmp/cf-junction-pose.mjs');
const src=root+'audits/C2_DEFORMING_SEAMS_20260914/',report=JSON.parse(fs.readFileSync(src+'native-hinges-02/report.json')),results=[];
const cross=(a,b,p)=>(b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0]);
for(const spec of JSON.parse(fs.readFileSync(src+'candidate-06/manifest.json')).results){const record=JSON.parse(fs.readFileSync(root+spec.record)),{width:w,height:h}=record.geometry,v=await verifyPartsDirectory(root+spec.base),parts=v.binding.parts.filter(p=>p.kind==='part'),owners=new Uint8Array(w*h),ancestry=partAncestry(parts,'torso');
parts.forEach((p,k)=>{const png=PNG.sync.read(v.sources.get(p.id)),b=p.cutout;for(let y=0;y<b.height;y++)for(let x=0;x<b.width;x++)if(png.data[(y*b.width+x)*4+3]>8)owners[(y+b.y)*w+x+b.x]=k+1;});
const junctions=[];for(let y=1;y<h;y++)for(let x=1;x<w;x++){const ids=[...new Set([owners[(y-1)*w+x-1],owners[(y-1)*w+x],owners[y*w+x],owners[y*w+x-1]])];if(ids.includes(0)||ids.length<3)continue;const ps=ids.map(i=>parts[i-1]),ancestor=ps.find(a=>ps.every(d=>d===a||ancestry.chain(a,d)));if(ancestor)junctions.push({point:[x,y],parts:ps,ancestor:ancestor.id});}
const frames=[];for(const[frame,{pose}]of Object.entries(report.seamGates.rows.find(r=>r.id===spec.id).poses)){const matrices=poseMatrices(record,pose),png=PNG.sync.read(fs.readFileSync(src+'native-hinges-02/'+spec.id+'-full-'+frame+'.png')),missing=new Set(),hits=[];
for(const j of junctions){const [x,y]=j.point,ps=j.parts.map(p=>{const m=matrices[p.joint];return[(m[0]*x/w+m[2]*y/h+m[4])*w+w/2,(m[1]*x/w+m[3]*y/h+m[5])*h+h/2];}),pixels=new Set();for(let n=1;n<ps.length-1;n++){const[a,b,c]=[ps[0],ps[n],ps[n+1]],area=cross(a,b,c);if(Math.abs(area)<1e-8)continue;const sign=Math.sign(area);for(let yy=Math.max(0,Math.floor(Math.min(a[1],b[1],c[1])));yy<Math.min(png.height,Math.ceil(Math.max(a[1],b[1],c[1])));yy++)for(let xx=Math.max(0,Math.floor(Math.min(a[0],b[0],c[0])));xx<Math.min(png.width,Math.ceil(Math.max(a[0],b[0],c[0])));xx++)if([[a,b],[b,c],[c,a]].every(([v,z])=>sign*cross(v,z,[xx+.5,yy+.5])>=0)){const i=yy*png.width+xx;if(png.data[i*4+3]<=8){pixels.add(i);missing.add(i);}}}if(pixels.size)hits.push({point:j.point,parts:j.parts.map(p=>p.id),ancestor:j.ancestor,pixels:pixels.size,samples:[...pixels].slice(0,3).map(i=>[i%png.width,Math.floor(i/png.width)])});}
frames.push({frame,missing:missing.size,junctions:hits});}results.push({id:spec.id,junctions:junctions.length,frames});}
console.log(JSON.stringify(results,null,2));
