// GENERATED by tools/morph/art-library-manifest.mjs (build-shipped-battle2.mjs) — do not edit by hand; re-run the tool.
/** G3: the ONE bundled pin of the on-demand art library manifest (`library/art-library.json`). The manifest authenticates every library file;
 * the service worker carries the same pin (pwa-build.ts). A manifest whose bytes differ is refused before any library file is used. */
export const ART_LIBRARY_MANIFEST_PIN = Object.freeze({ path: 'library/art-library.json', sha256: '8e1cb6d72521ffd84a0700ba4bd2443ef2efd5f15e4fe75a72735bc174567cd3', bytes: 110610, files: 603 });
