// GENERATED by tools/morph/art-library-manifest.mjs (build-shipped-battle2.mjs) — do not edit by hand; re-run the tool.
/** G3: the ONE bundled pin of the on-demand art library manifest (`library/art-library.json`). The manifest authenticates every library file;
 * the service worker carries the same pin (pwa-build.ts). A manifest whose bytes differ is refused before any library file is used. */
export const ART_LIBRARY_MANIFEST_PIN = Object.freeze({ path: 'library/art-library.json', sha256: 'b2c0a01459119c51c9b2bb12cbfc6ae54c90bf4823e4982c4118c67ea744fe18', bytes: 107897, files: 589 });
