// GENERATED by tools/morph/art-library-manifest.mjs (build-shipped-battle2.mjs) — do not edit by hand; re-run the tool.
/** G3: the ONE bundled pin of the on-demand art library manifest (`library/art-library.json`). The manifest authenticates every library file;
 * the service worker carries the same pin (pwa-build.ts). A manifest whose bytes differ is refused before any library file is used. */
export const ART_LIBRARY_MANIFEST_PIN = Object.freeze({ path: 'library/art-library.json', sha256: 'd13b1a921041e253fc031046e64b85d5db10c532914956fefdf815824873e6e4', bytes: 96135, files: 521 });
