// GENERATED by tools/morph/build-card-masters.mjs from its CARD_ARCHETYPES list — do not edit by hand; re-run the tool.
/** One entry per painted archetype that can FIGHT: its source paint-skin fit (and its painted masks' folder when they
 * live outside the fit), relative to the arena proof directory the battle2 wiring resolves against. */
export interface Battle2PartsFit { readonly earthName: string; readonly dir: string; readonly markingsDir?: string; }
export const BATTLE2_PARTS_FITS: readonly Battle2PartsFit[] = Object.freeze([
  Object.freeze({ earthName: 'Crab', dir: '../ANATOMY_COMPLETION_20260917/crab-fits-03/crab/' }),
  Object.freeze({ earthName: 'Coconut Crab', dir: '../ANATOMY_COMPLETION_20260917/crab-fits-03/coconut-crab/' }),
  Object.freeze({ earthName: 'Freshwater Crab', dir: '../ANATOMY_COMPLETION_20260917/crab-fits-03/freshwater-crab/' }),
  Object.freeze({ earthName: 'Mud Crab', dir: '../ANATOMY_COMPLETION_20260917/crab-fits-03/mud-crab/' }),
  Object.freeze({ earthName: 'Vent Crab', dir: '../ANATOMY_COMPLETION_20260917/crab-fits-03/vent-crab/' }),
  Object.freeze({ earthName: 'Civet', dir: '../ANATOMY_COMPLETION_20260917/civet-sentinel-input-01/' }),
  Object.freeze({ earthName: 'Salmon', dir: '../ARCHETYPE_SPRINT_20260922/02-fish/fit-01/', markingsDir: '../ARCHETYPE_SPRINT_20260922/13-fish-markings/' }),
  Object.freeze({ earthName: 'Eagle', dir: '../ARCHETYPE_REPAIRS_20260922/03-biped-bird/fit-12/' }),
  Object.freeze({ earthName: 'Beetle', dir: '../ARCHETYPE_FINISH_20260923/04-insect/fit-04/' }),
  Object.freeze({ earthName: 'Python', dir: '../PYTHON_OPEN_POSE_20260923/candidate-02/fit-01/' }),
  Object.freeze({ earthName: 'Tree Frog', dir: '../ARCHETYPE_FINISH_20260923/06-hopper/fit-05/' }),
  Object.freeze({ earthName: 'Chimpanzee', dir: '../ARCHETYPE_FINISH_20260923/07-primate/fit-02/' }),
  Object.freeze({ earthName: 'Starfish', dir: '../ARCHETYPE_REPAIRS_20260922/08-radial/fit-02/' }),
  Object.freeze({ earthName: 'Tarantula', dir: '../ARCHETYPE_FINISH_20260923/09-arachnid/fit-03/' }),
  Object.freeze({ earthName: 'Octopus', dir: '../ARCHETYPE_REPAIRS_20260922/10-cephalopod/fit-02/' }),
  Object.freeze({ earthName: 'Fruit Bat', dir: '../ARCHETYPE_FINISH_20260923/11-flyer-membrane/fit-02/' }),
  Object.freeze({ earthName: 'Centipede', dir: '../ARCHETYPE_FINISH_20260923/12-myriapod/fit-11/' }),
]);
