import {it,expect}from'vitest';import{BIOME_PROFILE_KEYS_V1}from'@cf/domain-biome-profile';
import{resolvePhysicalHabitat,compileHabitatBattle,containHabitatBody,type ArenaWorld}from'./battle-habitat.js';
const record=(id:string,name:string|null=null)=>({template:{id},identity:{earthName:name}});
const fish=resolvePhysicalHabitat(record('fish')),bird=resolvePhysicalHabitat(record('biped-bird','Pheasant')),land=resolvePhysicalHabitat(record('quadruped','Civet'));
const earth:ArenaWorld={key:'earth-133',biome:'temperate',seed:133,solid:true,atmosphere:true,liquid:'water',surfaceWater:true,signature:'temperate rain',cardHash:'compiled-earth-card'};
const input={contextId:'encounter-42',seed:123,round:0,kind:'wild' as const,home:earth,visitor:{...earth,key:'visitor'},left:fish,right:bird};
it('uses water/air/ground and preserves flightless and amphibious anatomy instead of taxonomic labels',()=>{expect(fish.preferred).toBe('water');expect(bird.preferred).toBe('air');expect(land.preferred).toBe('ground');expect(resolvePhysicalHabitat(record('biped-bird','Ostrich')).allowed).toEqual(['ground']);expect(resolvePhysicalHabitat(record('biped-bird','Penguin')).allowed).toEqual(['ground','water']);expect(resolvePhysicalHabitat(record('hopper','Frog')).realm).toBe('amphibious');});
it('reads procedural physical habitat before size/sapience display realms and retains exotic liquid chemistry',()=>{expect(resolvePhysicalHabitat(record('fish'),{kingdom:'fauna',habitat:10,loco:4,size:6}).realm).toBe('aquatic');expect(resolvePhysicalHabitat(record('fish'),{kingdom:'fauna',habitat:13,loco:4}).liquid).toBe('ammonia');expect(()=>resolvePhysicalHabitat(record('unknown'))).toThrow('source declaration');});
it('replays exactly, records home/card/seed, and alternates duel hosts by round without a clock',()=>{const a=compileHabitatBattle(input);expect(a).toEqual(compileHabitatBattle(input));expect(a.status).toBe('READY');if(a.status!=='READY')throw Error('fixture');expect(a.left.medium).toBe('water');expect(a.right.medium).toBe('air');expect(a.interaction).toBe('surface-ranged');expect(a.worldKey).toBe(earth.key);const x=compileHabitatBattle({...input,kind:'duel'}),y=compileHabitatBattle({...input,kind:'duel',round:1});expect(x.worldKey).not.toBe(y.worldKey);});
it('refuses dry fish, airless flight, incompatible liquids and impossible deep-water interfaces',()=>{for(const change of[{liquid:null},{atmosphere:false},{liquid:'ammonia'},{surfaceWater:false}])expect(compileHabitatBattle({...input,home:{...earth,...change}}).status).toBe('UNSUPPORTED');expect(compileHabitatBattle({...input,left:land,home:{...earth,solid:false}}).status).toBe('UNSUPPORTED');});
it('all 43 biome identities use explicit world capabilities rather than an Earth-only placement switch',()=>{for(const biome of BIOME_PROFILE_KEYS_V1){const a=compileHabitatBattle({...input,home:{...earth,biome}});expect(a.status).toBe('READY');if(a.status==='READY')expect(a.biome).toBe(biome);expect(compileHabitatBattle({...input,home:{...earth,biome,liquid:null}}).status).toBe('UNSUPPORTED');} });
it('contains painted extents and refuses oversized organisms instead of clipping them at the medium boundary',()=>{const band={minY:.57,maxY:.86};expect(containHabitatBody(band,.1,.2)-.1).toBeCloseTo(.57);expect(()=>containHabitatBody(band,.7,.4)).toThrow('cannot fit');expect(()=>containHabitatBody(band,NaN,.2)).toThrow();});

it('unknown named Earth anatomy needs a source declaration; random Earth genes cannot assign a whale to dry land',()=>{expect(()=>resolvePhysicalHabitat(record('quadruped','Unlisted whale'),{habitat:1,loco:0})).toThrow('source declaration');expect(resolvePhysicalHabitat({...record('quadruped','Unlisted whale'),habitat:{realm:'aquatic',source:'authored species habitat'}}).preferred).toBe('water');});

it('never interprets flora genome indices as fauna habitats',()=>{expect(()=>resolvePhysicalHabitat(record('plant-herb'),{kingdom:'flora',habitat:10,loco:4})).toThrow('non-fauna');expect(resolvePhysicalHabitat({...record('plant-herb'),habitat:{realm:'aquatic',source:'aquatic plant painter'}},{kingdom:'flora'}).preferred).toBe('water');});
