// GENERATED by tools/morph/creature-finish-source-pins.mjs.
// Supplementary labels pins; full original rig admission is still mandatory.
// Derived rows reproduce reviewed ownership from original pinned binding/atlas; no anatomy or alpha change.
import {isBattle2MasterPin, type Battle2MasterPinV1} from './battle2-master-pins.generated.js';
const PINS = [
  {
    "creatureId": "bass",
    "recordSha256": "57472e87b4113f7ae16c7f7a8e73889417960625115eb583dacaa7c77cc66a6f",
    "bindingSha256": "19ebb545859ff56ef0039f87d3a13db8dce4c6ac56f6ac3f4994d3aae15af663",
    "atlasSha256": "ae063590ba4b573f1b1fbf1b5b58a53216d66f1d6f27f7dc73f40c50635739c1",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/08-bass/fit-05/labels.png",
    "labelsPngSha256": "99f22a00de556ce6f7f2578c6184900d802db8fed0f0ae19a3d4cdc4a447f1e1",
    "source": "fit-labels"
  },
  {
    "creatureId": "beetle",
    "recordSha256": "252e61a95fcbe11020fe4b71cbfde421f6d2601250d7ac4da12cf64fbefbcbb9",
    "bindingSha256": "43f1c495f0a2edf73024f499c02e45ef22405dcddbb4a45468c51ebfc16948f2",
    "atlasSha256": "380f4a36492e964eb94c835ff5659db7d15d50c28f97ec7a63c2974a4d1521aa",
    "labelsPath": "audits/ARCHETYPE_FINISH_20260923/04-insect/fit-04/labels.png",
    "labelsPngSha256": "07186d15f8df2f202e4cff8799598f68325116d8c4748e4bece9c7653cae78e4",
    "source": "fit-labels"
  },
  {
    "creatureId": "centipede",
    "recordSha256": "2a79a3ea57a5140e538b5e265c560b457e50996bc82d8bfe7007340da0ea916d",
    "bindingSha256": "376f63769db24aae3e20c92b47c25d45d2dca9b409cff52069922467d44ada76",
    "atlasSha256": "979bc56d1662543762d4e25e09d83d1c77098ea36333c3b1053edb0d1e9d6341",
    "labelsPath": "audits/ARCHETYPE_FINISH_20260923/12-myriapod/fit-11/labels.png",
    "labelsPngSha256": "637ea64a967c55876c31acb7c0aa2096e4a863cf73a9ae9cca8d76057313b477",
    "source": "fit-labels"
  },
  {
    "creatureId": "chimpanzee",
    "recordSha256": "bd2e7c9e6f88d92b5a82fd64f5f12c281a6aed73d04d1a76171d56e0b92b4643",
    "bindingSha256": "9b05fd21d4426cb54472ef94388fdc0d8bb4e22e3a5ed3c81d792ba0a9a70876",
    "atlasSha256": "b00b3da86d0a31906a9f6894109f9298a06587959f7459628f33419e87386484",
    "labelsPath": "audits/ARCHETYPE_FINISH_20260923/07-primate/fit-02/labels.png",
    "labelsPngSha256": "60192171eaa2af8a72771581340a034cc203e2a69bac86059f35589a48de8009",
    "source": "fit-labels"
  },
  {
    "creatureId": "civet",
    "recordSha256": "c89cec5b79a58697ac469fb905bac39efc6a927116314ae30097779305349527",
    "bindingSha256": "65ff9709ee1f1a8cbc0f2afee0a2c547724728afdff18da757bfaa5b0d694178",
    "atlasSha256": "f8303ad0cf3a04797cd6df501571ff7b2b54d8796f0af86cd25a755e2d890d79",
    "labelsPath": "audits/G5_DERIVED_LABELS_20260926/civet/labels.png",
    "labelsPngSha256": "da39e0a76713f5adee819751c96db00ffebad52288b3d113a84baf218ced2132",
    "source": "reviewed-derived-ownership",
    "receiptPath": "audits/G5_DERIVED_LABELS_20260926/civet/receipt.json",
    "receiptSha256": "657f2fcd70529278caf24973efa2030ad11af8adf10167167e54de4502eeca21"
  },
  {
    "creatureId": "coconut-crab",
    "recordSha256": "848352d4d30b8351a37202a90cf7690a1d98a4e0af45c1bf8c70961ef072e1f9",
    "bindingSha256": "7ac8b5345f1155a97acb9de087b0c3ba0b34320d73419bad673752e04e9e34f7",
    "atlasSha256": "b1bb0a484e5fc531aee512b2fd92fe4ff6797f2a5bb3e3ec3e6ad2c1386722e2",
    "labelsPath": "audits/ANATOMY_COMPLETION_20260917/crab-fits-03/coconut-crab/labels.png",
    "labelsPngSha256": "234df901e16b674429a14ceeec4edb89ec3ec742f73027ec50cf23700ad3e4d7",
    "source": "fit-labels"
  },
  {
    "creatureId": "cougar",
    "recordSha256": "5ce958847878fb5cf8845b4ff14996707015885caa201daa726eddb16eb45730",
    "bindingSha256": "143262b0ac4f68efc1388828c68a74b784b711868828220e572ed23c1d3f55d0",
    "atlasSha256": "cb2be21a26aa37efc196c9cc576f353ea8b9f2ab5da94d18654c5783a1b8b420",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/cougar-repair-03/fit-03/labels.png",
    "labelsPngSha256": "56cb5cb87b39d1146db824e39add6426bb0083c5775775dc25d072b8521dc5c2",
    "source": "fit-labels"
  },
  {
    "creatureId": "crab",
    "recordSha256": "3f9041a69889c156c051ad23946e6f33f87675b46212b9536b3c828b7c9b49da",
    "bindingSha256": "227ec4b53559c38424ed8b243d88b2caf664e2804ba7f65986afb69f8482009b",
    "atlasSha256": "7d4ebb89db341e158a74f919d4e608691ce4b48a714cb116ba142ee2bfe73d15",
    "labelsPath": "audits/ANATOMY_COMPLETION_20260917/crab-fits-03/crab/labels.png",
    "labelsPngSha256": "2f8752420492af502902f818cfd35fc8085719ab2752e09ae2aad92218067075",
    "source": "fit-labels"
  },
  {
    "creatureId": "dragonfly",
    "recordSha256": "d7bd0ab92be377a8c4234798fc015e514cea37260cb51949ec48ef42e82cf182",
    "bindingSha256": "cf7dee0366903619597d9bdba350ba1d9539f7e07c955cabeb445b12a7bc8d7b",
    "atlasSha256": "63b70c5c7b4dc673f190d9f495eacd31f91f7c33d49f41d8c4200b840ec51c1e",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/dragonfly-repair-03/fit-03/labels.png",
    "labelsPngSha256": "ace081d5deb8c9728f500458a054453a6249cda18814fc82d16da508092a7e71",
    "source": "fit-labels"
  },
  {
    "creatureId": "eagle",
    "recordSha256": "0cf4254cf34f46d28603ab9aa3bc9a94209a930a2a1430d526525dda75646257",
    "bindingSha256": "fa7d2e1661090f54298ceb8e2b6ee7a34dfd16d61fc47aa03ba64d3d2f9b74a0",
    "atlasSha256": "b77d7b20a1dd776f53ee92c4a8e253af37a70214501a571a57d0ed40bb301137",
    "labelsPath": "audits/ARCHETYPE_REPAIRS_20260922/03-biped-bird/fit-12/labels.png",
    "labelsPngSha256": "66f75a3c56760f750b5d023b54eab085ed3a5e646902ef559f9dda4fd4271ab6",
    "source": "fit-labels"
  },
  {
    "creatureId": "eel",
    "recordSha256": "855a29c87b445f5bea8b401a2c5806f340392111ceea3a42a5d44998763bfbd5",
    "bindingSha256": "16e668748f842e1c1376e28617b42ef4a65d75cec124b4884c92c27cd1376384",
    "atlasSha256": "ec6b20bf2d42112db1fb5d1987aa43a8b3a3eeff37a8548183833b3a30264537",
    "labelsPath": "audits/G5_DERIVED_LABELS_20260926/eel/labels.png",
    "labelsPngSha256": "1b07c0600205a24f8d42a025f2d909b4374b156718a39fa2da268a0b32eac0c3",
    "source": "reviewed-derived-ownership",
    "receiptPath": "audits/G5_DERIVED_LABELS_20260926/eel/receipt.json",
    "receiptSha256": "46bb5f83d2c17e2ee84cee22337fc368b1e99c38e6395e7d5d3cb4e6107e3ca1"
  },
  {
    "creatureId": "freshwater-crab",
    "recordSha256": "c72fcc04fd3d2e5d2a9b71d8c76e10231c40596ac32a37bf605c5091dfeb4f50",
    "bindingSha256": "075341dac4101bf8b0d641424cb7a7514277f9044a71b96a2b546228850a5f40",
    "atlasSha256": "61e3f21fc2ad035d06975af33c03188c1ffee6d107a2ed8e714821b6cda49d4c",
    "labelsPath": "audits/ANATOMY_COMPLETION_20260917/crab-fits-03/freshwater-crab/labels.png",
    "labelsPngSha256": "286942e6b23d96b9307a6f3ce62f23dc2cc7548f1d480561ac1bbacd0884b48e",
    "source": "fit-labels"
  },
  {
    "creatureId": "fruit-bat",
    "recordSha256": "115c88bb84b97c4afc4a6f39f1c853187e30e9acac1b78295a372c1a8d4b9c70",
    "bindingSha256": "6dc9b7b6c1798e9de7e89cae43d2cdec98061cfcd0cd83d3f1428addc3fca254",
    "atlasSha256": "675a84500f3b80f151f78e843cec0e63106e0290040a940b538d694abb6689fd",
    "labelsPath": "audits/ARCHETYPE_FINISH_20260923/11-flyer-membrane/fit-02/labels.png",
    "labelsPngSha256": "833871cbbd4239542d6fbf890f32301a26b8d5f72deefe000d880179764f82cb",
    "source": "fit-labels"
  },
  {
    "creatureId": "goose",
    "recordSha256": "86c7761a3e34812f6cbba7e3d71c770e23e501757ed013659cef2898d1afaeb7",
    "bindingSha256": "0055d4e685d6007d46d9ab165feaacc885360358d92caf939e6596b218aa319a",
    "atlasSha256": "d97cb07ab477784d24779e13b10bc5a5fadb62beefff35882d9befe91c7c12ea",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/bird-motion-02/goose-fit-04/labels.png",
    "labelsPngSha256": "169735e054c8d410a9d31fcb4ba8d35e411af90fab13c004d643d26e6d8d59ef",
    "source": "fit-labels"
  },
  {
    "creatureId": "gull",
    "recordSha256": "2fc89e79923c4967704e334638211b93c12e0f43b0e96578f07520f38d72c1a3",
    "bindingSha256": "572559fa7d1ae3aa0eab86298c0b3ee7ff5bc990e682463e22590cdb66056f9a",
    "atlasSha256": "95775e5b9dc0614d3033480742553debb9fe93b9a32aac1b88efbea15d6e670d",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/12-gull/fit-03/labels.png",
    "labelsPngSha256": "030ed5cc891734fc383746e73a0d82fb79a3aa083f75ddeefd07d8ed70208df9",
    "source": "fit-labels"
  },
  {
    "creatureId": "heron",
    "recordSha256": "8dd66abe0ad34a3811b4296cb9327ef4aaa02c8779867b6b27d66f51d87ad40e",
    "bindingSha256": "42966abe805f0056a5ce0166db9037ba4ec60c5e7273a71d7b096f427d0d4a44",
    "atlasSha256": "ad743f3bad22bcae1918ed63fa2025cdf62ea50b986be73ebe838b3c30f5ee7b",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/16-heron/fit-01/labels.png",
    "labelsPngSha256": "a0b49bcc1bd0088e56b5e02e5381a0cc0318b0e5bf4edf23288542edd800ade3",
    "source": "fit-labels"
  },
  {
    "creatureId": "ibex",
    "recordSha256": "415a9d545e973bdd3a0b2bef63bf6cebc5fc3716e693d36ca8c2517ad5772054",
    "bindingSha256": "e8d716ebe191fd517cd1ba2f9cb5a8c5c0d41fc9743fa841f6a171cc376b3668",
    "atlasSha256": "b5c7a17da4c02b91b90e21dd5dd4514932feb73687dfaea34ec708c32101494f",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/18-ibex/fit-02/labels.png",
    "labelsPngSha256": "1bae9560418b52e9583ae4c4e13fb5745dc1c064d3549685b1f75dd63fdd0288",
    "source": "fit-labels"
  },
  {
    "creatureId": "impala",
    "recordSha256": "0dd2db4971d8f63300747b432300d8527f4831b95e84581e61622c981252d0e8",
    "bindingSha256": "2ebff0b32398c0db0b0a524792e95fe49a924c5a935a91961d33b7c0d3cafc83",
    "atlasSha256": "c09bdef8a344c344d57dd2092b2a8ecc24668f99d643ca04c0d32ca2d0c9ae95",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/interior-root-repair-05/impala-fit-02/labels.png",
    "labelsPngSha256": "5c3af48c71510d30ccad33d15d8b6eda279b0ee3ce4f1a2395fdd8c4786e88af",
    "source": "fit-labels"
  },
  {
    "creatureId": "jellyfish",
    "recordSha256": "e7a05163b2e8456dffb745cabc4cda5dad0741236bd41abcd518f388c7982c92",
    "bindingSha256": "7f8af5d588864538fc68f3ed5ecb7077dadcd1d5260182acde94074b81a39238",
    "atlasSha256": "7e21aa49d9b42a8580d792455806a8ae6b2969f267318826aadf745fb52b87cb",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/jellyfish-repair-03/fit-06/labels.png",
    "labelsPngSha256": "67d05b4d70e7d33c6bc8ecff0777430f94f0f4625bd8b42d0522ae006acf8d9f",
    "source": "fit-labels"
  },
  {
    "creatureId": "marmot",
    "recordSha256": "14be1b8cf07df153db3023091a35f5ddec59b15bc0e29868fee2084321faf574",
    "bindingSha256": "098b64ad873e6980637eabfc7e00d4ec3b5a9d4598aa0ce06a7f1d08cae366d5",
    "atlasSha256": "b6cafb130de63a4830593e093bd8ac484d7b84a0ee8d75210fcb5ce196d9428e",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/quadruped-repair-04/marmot-fit-02/labels.png",
    "labelsPngSha256": "18366bee7fb2829c3def587db9be787b70081f66dd8cc1bf07f323a5e0c2382d",
    "source": "fit-labels"
  },
  {
    "creatureId": "mud-crab",
    "recordSha256": "5fc648200c7f53dbb289ed3ae47400642bc4a32a95544695e7be6a91d28098c3",
    "bindingSha256": "6d89da7ba04b98fd5c4d45ef38acbe4a44e28dd2e903d0cc057a6cd5792b4c04",
    "atlasSha256": "4502aafee3ba0e9cd82dd6e5bfa173dd098bf7f917d5c6792bcc2386bb070251",
    "labelsPath": "audits/ANATOMY_COMPLETION_20260917/crab-fits-03/mud-crab/labels.png",
    "labelsPngSha256": "0f53dbfb39d02ed4371fb01fb55845cc7a71eec5edf025365eb5a11ef3329756",
    "source": "fit-labels"
  },
  {
    "creatureId": "octopus",
    "recordSha256": "4b50bdd43ffb5336095978470ebd00fe90843dbd0c916a1d8ef6f36f6cbdfc62",
    "bindingSha256": "47db6334446e930e64c5b2cd1ed56d40a2476efa54c3fb2eec07f5a076dd868a",
    "atlasSha256": "9b3be6b71f6736f6640009923c58c2b9fe3a9bf796c8cbdd411a5973795f762e",
    "labelsPath": "audits/ARCHETYPE_REPAIRS_20260922/10-cephalopod/fit-02/labels.png",
    "labelsPngSha256": "1108a8dac4d7686c83359121eb9b159486f89bfff92a97a3c60861abeed1331a",
    "source": "fit-labels"
  },
  {
    "creatureId": "pike",
    "recordSha256": "8ed1cd8707d55059e47d97790051ad7d022b58239431bc1a7ce5f48dde2ea63e",
    "bindingSha256": "ef6b5351f1c3abd80b82583405f0f1c3396117708a383a7f3bbd4207611ff021",
    "atlasSha256": "ebfbe34d8d689d6a522cb41225ea07333c507adaf696bf0eae8a99d0b687bf4f",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/20-pike/fit-02/labels.png",
    "labelsPngSha256": "915d74261a74eca04e027fa348baf100c2485168b09f46301b95ea2c7a51e09b",
    "source": "fit-labels"
  },
  {
    "creatureId": "python-open",
    "recordSha256": "4f7838d0ecbb2e101604a465f0b6578be24681c3284c74838ba91ec4f8199f8f",
    "bindingSha256": "c7b15647514f8261f662d85d6e9fc13168a64d5822d943009df863941082f80b",
    "atlasSha256": "7db569301d8a4d8c460f74e0f6932c75b976d45a8a75d58e2ac5a0808dc5ee78",
    "labelsPath": "audits/PYTHON_OPEN_POSE_20260923/candidate-02/fit-01/labels.png",
    "labelsPngSha256": "be1fa59cf243258db7107f96991e0cec04085c6547c03fb84c970e89dcf0130c",
    "source": "fit-labels"
  },
  {
    "creatureId": "racer",
    "recordSha256": "0684609c899122caecd4e07b6241dd817fc79057d5f039882e04794b96a7fabc",
    "bindingSha256": "18ae7570b53930120056da21feb29b896023b0168ac24a2d4083b456519d906e",
    "atlasSha256": "0a84839efb0850384cfed4527eb45945de805e9f482a1b9d0bfbe8d690421fe3",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/21-racer/fit-02/labels.png",
    "labelsPngSha256": "5c6d2b215392ce97b6a0f9fa004f17a68d5b3ef0923c26f66340aaed9f2b33cc",
    "source": "fit-labels"
  },
  {
    "creatureId": "rat",
    "recordSha256": "b3205972ae64d874561d4b4b30a91739db281df8c9f3ca8b74611a3c03256600",
    "bindingSha256": "a1190f0e1cc04dbdfdd67f4988138fa8fc7b400d0fac5c3019021e0d6ce63ad8",
    "atlasSha256": "2ed28cfe59d6fba7ccb1746a47710f5f75f61762f744be83471357721dda7667",
    "labelsPath": "audits/G5_DERIVED_LABELS_20260926/rat/labels.png",
    "labelsPngSha256": "9205f57215cb3631e592b8bcda5ffa335365cda028aa1c117d11e454d984212e",
    "source": "reviewed-derived-ownership",
    "receiptPath": "audits/G5_DERIVED_LABELS_20260926/rat/receipt.json",
    "receiptSha256": "5ef387e6620f9112ef5ce318bc0c95679959ee609666a4feb9fc75878f449df1"
  },
  {
    "creatureId": "reef-shark",
    "recordSha256": "d931cae45f1b8835989df6350e0a36d5eeee864a7b7c8ac849de7325a3deaef6",
    "bindingSha256": "f2c36daa87e4fec41c4047058edd177697432bffc65136cd47a2690f0592e000",
    "atlasSha256": "a7d09dbb6a76929d0b3aeb38ff98b42fa4fe1ac315785b294d353f25f34e734b",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/19-reef-shark/fit-06/labels.png",
    "labelsPngSha256": "b09ed706fdd131e3206114213f471a03040125f890f3f30d3d5de5d90f2eb908",
    "source": "fit-labels"
  },
  {
    "creatureId": "river-otter",
    "recordSha256": "73f1abf6f01c0c07185c791d986178ac971a095e78008683a10bbc9923de456c",
    "bindingSha256": "0396cb91968d0eb25414cf5c0e132b088c4f3765dd076c69d9abf63905632340",
    "atlasSha256": "a5d61152a9fe1ace7a07d3f834a5c16b0e060921e9d36b93746f530d9254671f",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/13-river-otter/fit-02/labels.png",
    "labelsPngSha256": "ea72693a20b3100eb285cb4713e2de667619986fcd71a97b94b4efe8146bb46d",
    "source": "fit-labels"
  },
  {
    "creatureId": "salamander",
    "recordSha256": "85d54574c6c0308b8a1ce87eda755ce1106f652104b16fc15e4f9d2364c5a149",
    "bindingSha256": "db731fe504b30ed0ac48e127559ed2a28238c812ae13946a8ba15bed95758aff",
    "atlasSha256": "35a2660949a0dffb50d467105ba9d64d020c8c1f31fe2a78431cdb30732a3f70",
    "labelsPath": "audits/G5_DERIVED_LABELS_20260926/salamander/labels.png",
    "labelsPngSha256": "56052d9264e158d7c6080dc39310675ba07b30ff9c44890d9ea5f60352496520",
    "source": "reviewed-derived-ownership",
    "receiptPath": "audits/G5_DERIVED_LABELS_20260926/salamander/receipt.json",
    "receiptSha256": "4fb30b325a33ee6c2f1658ebafdf5745f4c8671c4dd81b932d2038cbb6e545fa"
  },
  {
    "creatureId": "salmon",
    "recordSha256": "8927c6e58e0f94bceb5d69b48010909decc0a8fc793f9d3cb4bab947fd1cbbb0",
    "bindingSha256": "ff59bbd9a70ec16b26b7ba288c03f69f1900c50ccb87b358a0c19a5523a4d036",
    "atlasSha256": "5aaa0e3364d85357c81120245a9bcf0707456fe59ca28a71d38fde1eae52894b",
    "labelsPath": "audits/ARCHETYPE_SPRINT_20260922/02-fish/fit-01/labels.png",
    "labelsPngSha256": "64076272f5ed1b9e78e3afbae099f958b6730524b0dbe6891f4f8f4dd844b368",
    "source": "fit-labels"
  },
  {
    "creatureId": "starfish",
    "recordSha256": "3ae8ce3a4f7d46cdd5b5ba0934125de689e379e8d4c99972e9e400879fb1815f",
    "bindingSha256": "198ade30a94d9d4bf9d200ae87a1b303f3bbc5281d7c4c7187ce678ef93c2f04",
    "atlasSha256": "f3db8ab96f2490e93bd7b96bb75abd4a0bd4f2d5797a9635e38c47cd1dad4ae2",
    "labelsPath": "audits/ARCHETYPE_REPAIRS_20260922/08-radial/fit-02/labels.png",
    "labelsPngSha256": "7e5c10d96ef98da4260f60d14d885a5bb0357a1d171e88a7f4de020848643f87",
    "source": "fit-labels"
  },
  {
    "creatureId": "sturgeon",
    "recordSha256": "126685c83a39b9b47366f4cff46c59e939850d32c9e4b4247196f3389d7a4834",
    "bindingSha256": "6e5299858d7b36fba5ef215a49bc6489b9968570d27f63b32767fa60870d0c07",
    "atlasSha256": "6158e30a1b37f1d55bf2d46689b261303052a2e2a7777a06b372eadc2280a65a",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/sturgeon-facing-04/fit-02/labels.png",
    "labelsPngSha256": "2e7e03d6aa463d2a611c395b1753d6f3a36280cb8a8f24d06afe017ce2e311bf",
    "source": "fit-labels"
  },
  {
    "creatureId": "tang",
    "recordSha256": "30413e80512958358dfa48232ab1fc721614187038fef50051c93c6fd6dd4374",
    "bindingSha256": "d0dfd3f511dd0f35bc217b13e6b8b5c95692af04dba2d6ddb312cab388ed5272",
    "atlasSha256": "fec9e0c26ab84e500b9b2ab4fab4c9466e2e32db9f6eb716bbacdb51950a9f85",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/10-tang/fit-06/labels.png",
    "labelsPngSha256": "443f4d643b590ece80eafc7c8db3205bea0876bbb3d6983346144384f07f10b9",
    "source": "fit-labels"
  },
  {
    "creatureId": "tarantula",
    "recordSha256": "a5ba389dc6f25c4ab1fba27236a0ae762f644b0fd5ec0926f9e212e35a4e67cc",
    "bindingSha256": "e1636b71eb674a33a152e98540e36e7bc7a6a3e9a2b84524fab86b3d6f9b6694",
    "atlasSha256": "00852a20606dda93f40d6bda50597fa8c920802755d0be93448d0b622adf1cf1",
    "labelsPath": "audits/ARCHETYPE_FINISH_20260923/09-arachnid/fit-03/labels.png",
    "labelsPngSha256": "4a04124fcc308c96121eb658d7f2db3becb55c4a4b54901ba72a4d50bc62ff84",
    "source": "fit-labels"
  },
  {
    "creatureId": "tree-frog",
    "recordSha256": "734a702093874b6ec01d96fb767a5ac8d5c5b299f016d21dfdff45e964a2b473",
    "bindingSha256": "8d3926656a74f1398cafc1a3c6102dba2337509dc5fb2403a75a14f142660b5d",
    "atlasSha256": "f72f94efa9e4de5012186be9f4450e128a03dc7f8d343c4753e6395877363b42",
    "labelsPath": "audits/ARCHETYPE_FINISH_20260923/06-hopper/fit-05/labels.png",
    "labelsPngSha256": "03f28532d7c074afebf5c5803df3ac913aaf16bb5efd67fd49e2a75ba4fb65ae",
    "source": "fit-labels"
  },
  {
    "creatureId": "vent-crab",
    "recordSha256": "c3629f4aff1b9222d776b1207fb65e37728c495ec3a63c8d94ff103a1c20ea2d",
    "bindingSha256": "d0c46782a73d9cc94a28ae258dd940af078787a287e2d8b7b5fc96fa9f9673dd",
    "atlasSha256": "89f839d7a6e195d6bf25ef5cd04a91fc0ae08022bd38078a3333422e2a024288",
    "labelsPath": "audits/ANATOMY_COMPLETION_20260917/crab-fits-03/vent-crab/labels.png",
    "labelsPngSha256": "ea38a3aa433bc98aa3568a534e43d8090c60dead8b26f57f59c4969385042166",
    "source": "fit-labels"
  },
  {
    "creatureId": "wall-lizard",
    "recordSha256": "c703ef919ba6ff779a96dfa72ed0d43f833895b597f08e2b99d27acaebb2e611",
    "bindingSha256": "a624d65b17ff50c0163de0fcde416180278e60ae038ea92a9bf6d3a7b77b7794",
    "atlasSha256": "d524998b70a7ff5cb485f2b073e4a8adbb627935461d641764db0178e0406c1c",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/quadruped-repair-04/lizard-fit-03/labels.png",
    "labelsPngSha256": "45db669c40b134630df60fc99ff33b50233d715727b93f6f2fc9dcaec2caaf98",
    "source": "fit-labels"
  },
  {
    "creatureId": "wolf",
    "recordSha256": "fe6a2f027be301e8e84629b668642e1f2022ca32df05cd62325951e01345d87c",
    "bindingSha256": "7df5d302db951426d54655769944a4b8249a52d7e020dfdb81aa1626c6d350d6",
    "atlasSha256": "3888b35dc716d271e44f68213506de897ecdc0285e09084e0f27a08983c0c870",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/11-wolf/fit-03/labels.png",
    "labelsPngSha256": "abe41912a83f5277e05b4bbe5aaa5cab051823586b77b1a453dda58b7ca0d7d3",
    "source": "fit-labels"
  }
] as const;
export function creatureFinishLabelsPinV1(pin: Battle2MasterPinV1) {
 if (!isBattle2MasterPin(pin)) throw Error('finish labels: untrusted rig pin');
 const row=PINS.find(p=>p.creatureId===pin.creatureId);
 if (!row || row.recordSha256!==pin.recordSha256 || row.bindingSha256!==pin.bindingSha256 || row.atlasSha256!==pin.atlasSha256) throw Error('finish labels: stale or missing source pin');
 return Object.freeze({...row});
}
