// GENERATED by tools/morph/creature-finish-source-pins.mjs.
// Supplementary labels pins; full original rig admission is still mandatory.
import {isBattle2MasterPin, type Battle2MasterPinV1} from './battle2-master-pins.generated.js';
const PINS = [
  {
    "creatureId": "bass",
    "recordSha256": "a5a134a3a158c856a7620a5bfb7c2d7eab08dd010cc3a4f79d1e12d74ded5043",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/08-bass/fit-05/labels.png",
    "labelsPngSha256": "99f22a00de556ce6f7f2578c6184900d802db8fed0f0ae19a3d4cdc4a447f1e1"
  },
  {
    "creatureId": "beetle",
    "recordSha256": "6ccea5117da3296e2e8e0967ee83a95d5790650c89f0754277daa6dcba19f0a9",
    "labelsPath": "audits/ARCHETYPE_FINISH_20260923/04-insect/fit-04/labels.png",
    "labelsPngSha256": "07186d15f8df2f202e4cff8799598f68325116d8c4748e4bece9c7653cae78e4"
  },
  {
    "creatureId": "centipede",
    "recordSha256": "1e450966e4d95383a5219914f27d2fbc8e4047200598e4bd3d6bc50a48fda7c6",
    "labelsPath": "audits/ARCHETYPE_FINISH_20260923/12-myriapod/fit-11/labels.png",
    "labelsPngSha256": "637ea64a967c55876c31acb7c0aa2096e4a863cf73a9ae9cca8d76057313b477"
  },
  {
    "creatureId": "chimpanzee",
    "recordSha256": "a0bc1dfa21c92a723e15786c4500dd807911ef1d7838ceca734ad669aa68f857",
    "labelsPath": "audits/ARCHETYPE_FINISH_20260923/07-primate/fit-02/labels.png",
    "labelsPngSha256": "60192171eaa2af8a72771581340a034cc203e2a69bac86059f35589a48de8009"
  },
  {
    "creatureId": "civet",
    "recordSha256": "c89cec5b79a58697ac469fb905bac39efc6a927116314ae30097779305349527",
    "labelsPath": "audits/ANATOMY_COMPLETION_20260917/civet-sentinel-input-01/labels.png",
    "labelsPngSha256": null
  },
  {
    "creatureId": "coconut-crab",
    "recordSha256": "848352d4d30b8351a37202a90cf7690a1d98a4e0af45c1bf8c70961ef072e1f9",
    "labelsPath": "audits/ANATOMY_COMPLETION_20260917/crab-fits-03/coconut-crab/labels.png",
    "labelsPngSha256": "234df901e16b674429a14ceeec4edb89ec3ec742f73027ec50cf23700ad3e4d7"
  },
  {
    "creatureId": "cougar",
    "recordSha256": "a011ebc38f3fd54430ccfc90cd94178b213bf507beebff8e415ffc693397cb6a",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/cougar-repair-03/fit-03/labels.png",
    "labelsPngSha256": "56cb5cb87b39d1146db824e39add6426bb0083c5775775dc25d072b8521dc5c2"
  },
  {
    "creatureId": "crab",
    "recordSha256": "3f9041a69889c156c051ad23946e6f33f87675b46212b9536b3c828b7c9b49da",
    "labelsPath": "audits/ANATOMY_COMPLETION_20260917/crab-fits-03/crab/labels.png",
    "labelsPngSha256": "2f8752420492af502902f818cfd35fc8085719ab2752e09ae2aad92218067075"
  },
  {
    "creatureId": "dragonfly",
    "recordSha256": "d7bd0ab92be377a8c4234798fc015e514cea37260cb51949ec48ef42e82cf182",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/dragonfly-repair-03/fit-03/labels.png",
    "labelsPngSha256": "ace081d5deb8c9728f500458a054453a6249cda18814fc82d16da508092a7e71"
  },
  {
    "creatureId": "eagle",
    "recordSha256": "600e7cde066fa25bcafecd85c82879f23b880ac29ac79b6c667984c4a9fe9db5",
    "labelsPath": "audits/ARCHETYPE_REPAIRS_20260922/03-biped-bird/fit-12/labels.png",
    "labelsPngSha256": "66f75a3c56760f750b5d023b54eab085ed3a5e646902ef559f9dda4fd4271ab6"
  },
  {
    "creatureId": "eel",
    "recordSha256": "855a29c87b445f5bea8b401a2c5806f340392111ceea3a42a5d44998763bfbd5",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/27-eel/fit-02/labels.png",
    "labelsPngSha256": null
  },
  {
    "creatureId": "freshwater-crab",
    "recordSha256": "c72fcc04fd3d2e5d2a9b71d8c76e10231c40596ac32a37bf605c5091dfeb4f50",
    "labelsPath": "audits/ANATOMY_COMPLETION_20260917/crab-fits-03/freshwater-crab/labels.png",
    "labelsPngSha256": "286942e6b23d96b9307a6f3ce62f23dc2cc7548f1d480561ac1bbacd0884b48e"
  },
  {
    "creatureId": "fruit-bat",
    "recordSha256": "589afa4484013fe422c85608f342403b2e3d5a20dbb1e1ee2150599afa68aee0",
    "labelsPath": "audits/ARCHETYPE_FINISH_20260923/11-flyer-membrane/fit-02/labels.png",
    "labelsPngSha256": "833871cbbd4239542d6fbf890f32301a26b8d5f72deefe000d880179764f82cb"
  },
  {
    "creatureId": "goose",
    "recordSha256": "010e51ae7afe4f5e9a79051ef1dd5a260d3fcfbcc72deb0bba5754bcb5b3eff6",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/bird-motion-02/goose-fit-04/labels.png",
    "labelsPngSha256": "169735e054c8d410a9d31fcb4ba8d35e411af90fab13c004d643d26e6d8d59ef"
  },
  {
    "creatureId": "gull",
    "recordSha256": "9c2b13f2d6dfebaa68a7069975fdc8cb2715690253e704865ab25ce2462794ae",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/12-gull/fit-03/labels.png",
    "labelsPngSha256": "030ed5cc891734fc383746e73a0d82fb79a3aa083f75ddeefd07d8ed70208df9"
  },
  {
    "creatureId": "heron",
    "recordSha256": "586233ae2b9bf20b7de4ed9e534d7968ed841ee7ab4730f1aac0c17673767c88",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/16-heron/fit-01/labels.png",
    "labelsPngSha256": "a0b49bcc1bd0088e56b5e02e5381a0cc0318b0e5bf4edf23288542edd800ade3"
  },
  {
    "creatureId": "ibex",
    "recordSha256": "98ad5f34352615b8f94891b95f6da623c44dd178a3241b479dde625351478b80",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/18-ibex/fit-02/labels.png",
    "labelsPngSha256": "1bae9560418b52e9583ae4c4e13fb5745dc1c064d3549685b1f75dd63fdd0288"
  },
  {
    "creatureId": "impala",
    "recordSha256": "c58dd32f5343053c92ef32e770367d3944b276ba073e95234b481a8bc50b2d67",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/interior-root-repair-05/impala-fit-02/labels.png",
    "labelsPngSha256": "5c3af48c71510d30ccad33d15d8b6eda279b0ee3ce4f1a2395fdd8c4786e88af"
  },
  {
    "creatureId": "jellyfish",
    "recordSha256": "5a970d35d5a9da8715b51f685e70bae55420aa77a850776c158b9e9c7752a6df",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/jellyfish-repair-03/fit-06/labels.png",
    "labelsPngSha256": "67d05b4d70e7d33c6bc8ecff0777430f94f0f4625bd8b42d0522ae006acf8d9f"
  },
  {
    "creatureId": "marmot",
    "recordSha256": "1b6d32c306b23aa9eafbe1dd29536d54898d242a6c08f63b42d32d621b84800c",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/quadruped-repair-04/marmot-fit-02/labels.png",
    "labelsPngSha256": "18366bee7fb2829c3def587db9be787b70081f66dd8cc1bf07f323a5e0c2382d"
  },
  {
    "creatureId": "mud-crab",
    "recordSha256": "5fc648200c7f53dbb289ed3ae47400642bc4a32a95544695e7be6a91d28098c3",
    "labelsPath": "audits/ANATOMY_COMPLETION_20260917/crab-fits-03/mud-crab/labels.png",
    "labelsPngSha256": "0f53dbfb39d02ed4371fb01fb55845cc7a71eec5edf025365eb5a11ef3329756"
  },
  {
    "creatureId": "octopus",
    "recordSha256": "efc022ee48645c35083eb5cd50c57776d00f552b3b49a972faff21e48221190a",
    "labelsPath": "audits/ARCHETYPE_REPAIRS_20260922/10-cephalopod/fit-02/labels.png",
    "labelsPngSha256": "1108a8dac4d7686c83359121eb9b159486f89bfff92a97a3c60861abeed1331a"
  },
  {
    "creatureId": "pike",
    "recordSha256": "f97368d0825cd8d7baff2063540766c609299e5d9cd7e3e5021415847b54a203",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/20-pike/fit-02/labels.png",
    "labelsPngSha256": "915d74261a74eca04e027fa348baf100c2485168b09f46301b95ea2c7a51e09b"
  },
  {
    "creatureId": "python-open",
    "recordSha256": "391ea2ad4dbe52b9685bc62d58036f0357948680537f3315f65d58da43cc56b0",
    "labelsPath": "audits/PYTHON_OPEN_POSE_20260923/candidate-02/fit-01/labels.png",
    "labelsPngSha256": "be1fa59cf243258db7107f96991e0cec04085c6547c03fb84c970e89dcf0130c"
  },
  {
    "creatureId": "racer",
    "recordSha256": "410dcd1115efb8959bc5c6cca509dcd1a354f525758c481073e793ff469d42d3",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/21-racer/fit-02/labels.png",
    "labelsPngSha256": "5c6d2b215392ce97b6a0f9fa004f17a68d5b3ef0923c26f66340aaed9f2b33cc"
  },
  {
    "creatureId": "rat",
    "recordSha256": "b3205972ae64d874561d4b4b30a91739db281df8c9f3ca8b74611a3c03256600",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/29-rat/fit-03/labels.png",
    "labelsPngSha256": null
  },
  {
    "creatureId": "reef-shark",
    "recordSha256": "687bc604480eb28a39bd3dbc52eefb37c55e914876eaaad918dbd04639e1b5c1",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/19-reef-shark/fit-06/labels.png",
    "labelsPngSha256": "b09ed706fdd131e3206114213f471a03040125f890f3f30d3d5de5d90f2eb908"
  },
  {
    "creatureId": "river-otter",
    "recordSha256": "65ca954e86b9a90a87bd3167f25de40ab14e771bd847353f51d64d96595f7209",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/13-river-otter/fit-02/labels.png",
    "labelsPngSha256": "ea72693a20b3100eb285cb4713e2de667619986fcd71a97b94b4efe8146bb46d"
  },
  {
    "creatureId": "salamander",
    "recordSha256": "85d54574c6c0308b8a1ce87eda755ce1106f652104b16fc15e4f9d2364c5a149",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/26-salamander/fit-05/labels.png",
    "labelsPngSha256": null
  },
  {
    "creatureId": "salmon",
    "recordSha256": "831cba7ef4a1d20f50822763391ed37a1db9550e4018851567a008e4cadac519",
    "labelsPath": "audits/ARCHETYPE_SPRINT_20260922/02-fish/fit-01/labels.png",
    "labelsPngSha256": "64076272f5ed1b9e78e3afbae099f958b6730524b0dbe6891f4f8f4dd844b368"
  },
  {
    "creatureId": "starfish",
    "recordSha256": "cc76a9b0ffb7c199052adccfecaa032f50c0b40bdd1d13c7b958849ca86186ff",
    "labelsPath": "audits/ARCHETYPE_REPAIRS_20260922/08-radial/fit-02/labels.png",
    "labelsPngSha256": "7e5c10d96ef98da4260f60d14d885a5bb0357a1d171e88a7f4de020848643f87"
  },
  {
    "creatureId": "sturgeon",
    "recordSha256": "126685c83a39b9b47366f4cff46c59e939850d32c9e4b4247196f3389d7a4834",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/sturgeon-facing-04/fit-02/labels.png",
    "labelsPngSha256": "2e7e03d6aa463d2a611c395b1753d6f3a36280cb8a8f24d06afe017ce2e311bf"
  },
  {
    "creatureId": "tang",
    "recordSha256": "5734a3fd8735d7cf2bb662649404c77041518b6452e82d0f75426f5b377caaf1",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/10-tang/fit-06/labels.png",
    "labelsPngSha256": "443f4d643b590ece80eafc7c8db3205bea0876bbb3d6983346144384f07f10b9"
  },
  {
    "creatureId": "tarantula",
    "recordSha256": "a7ae1dd18c295f658139b79662bf9e5d71073a32046e41dcf67070e415911e8d",
    "labelsPath": "audits/ARCHETYPE_FINISH_20260923/09-arachnid/fit-03/labels.png",
    "labelsPngSha256": "4a04124fcc308c96121eb658d7f2db3becb55c4a4b54901ba72a4d50bc62ff84"
  },
  {
    "creatureId": "tree-frog",
    "recordSha256": "e6dcf6498e7ad2d0220f9e3c995c08e20fb13d7678e29bd1ed2e8065ae5383b2",
    "labelsPath": "audits/ARCHETYPE_FINISH_20260923/06-hopper/fit-05/labels.png",
    "labelsPngSha256": "03f28532d7c074afebf5c5803df3ac913aaf16bb5efd67fd49e2a75ba4fb65ae"
  },
  {
    "creatureId": "vent-crab",
    "recordSha256": "c3629f4aff1b9222d776b1207fb65e37728c495ec3a63c8d94ff103a1c20ea2d",
    "labelsPath": "audits/ANATOMY_COMPLETION_20260917/crab-fits-03/vent-crab/labels.png",
    "labelsPngSha256": "ea38a3aa433bc98aa3568a534e43d8090c60dead8b26f57f59c4969385042166"
  },
  {
    "creatureId": "wall-lizard",
    "recordSha256": "d272c23cf4a06c98273395b56e3b311d8513037f4607d358d89dbe3315645650",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/quadruped-repair-04/lizard-fit-03/labels.png",
    "labelsPngSha256": "45db669c40b134630df60fc99ff33b50233d715727b93f6f2fc9dcaec2caaf98"
  },
  {
    "creatureId": "wolf",
    "recordSha256": "f6cce15e091d745afa02e2e408d754053fbe9512bbf97345f796e51e92223929",
    "labelsPath": "audits/ART_BATTLE_FOCUS_20260925/11-wolf/fit-03/labels.png",
    "labelsPngSha256": "abe41912a83f5277e05b4bbe5aaa5cab051823586b77b1a453dda58b7ca0d7d3"
  }
] as const;
export function creatureFinishLabelsPinV1(pin: Battle2MasterPinV1) {
 if (!isBattle2MasterPin(pin)) throw Error('finish labels: untrusted rig pin');
 const row=PINS.find(p=>p.creatureId===pin.creatureId);
 if (!row || !row.labelsPngSha256 || row.recordSha256!==pin.recordSha256 || row.labelsPath!==pin.recordPath.replace(/record\.json$/, 'labels.png')) throw Error('finish labels: stale or missing source pin');
 return Object.freeze({...row});
}
