// App wiring for the painted individual on the card (morph system; Nick 2026-09-22 option 3: every device). Every
// archetype's sealed card masters, labels, receipts and records are SHIPPED as app assets (`?url` imports from `assets/painted-cards/`, inside the v2 subtree the preview
// snapshot archives — a production build carries them; the explicit import map is GENERATED by tools/morph/build-card-masters.mjs, markings included; nothing here depends on the dev-only proof-asset fetch), so the painted card works wherever the
// app runs. The species-art loader asks this source first; the painter tier answers for every other species.
import { CARD_ARCHETYPES } from './morph/card-archetypes.js';
import { PaintedCardSource, type PaintedCardAssets } from './morph/painted-card-source.js';
export { CARD_ASSET_URLS } from './painted-cards.assets.js';
import { CARD_ASSET_URLS } from './painted-cards.assets.js';
export function cardAssetUrl(repoRelative: string): string {
  for (const [dir, files] of CARD_ASSET_URLS) if (repoRelative.startsWith(dir)) { const u = files[repoRelative.slice(dir.length)]; if (u) return u; }
  throw new Error('painted cards: no shipped asset for ' + repoRelative);
}
export const shippedCardAssets = (fetchImpl: typeof fetch = fetch): PaintedCardAssets => ({
  json: async (p) => { const r = await fetchImpl(cardAssetUrl(p)); if (!r.ok) throw new Error(`painted card asset ${p}: HTTP ${r.status}`); return r.json(); },
  bytes: async (p) => { const r = await fetchImpl(cardAssetUrl(p)); if (!r.ok) throw new Error(`painted card asset ${p}: HTTP ${r.status}`); return new Uint8Array(await r.arrayBuffer()); },
});
export function createPaintedCardsForApp(fetchImpl: typeof fetch = fetch): PaintedCardSource {
  for (const a of CARD_ARCHETYPES) if (!CARD_ASSET_URLS.has(a.dir)) throw new Error('painted cards: archetype without shipped assets: ' + a.earthName);
  return new PaintedCardSource({ assets: shippedCardAssets(fetchImpl), registry: CARD_ARCHETYPES });
}
