// GENERATED by tools/morph/build-card-masters.mjs from its CARD_ARCHETYPES list — do not edit by hand; re-run the tool.
import a0_0 from '../assets/painted-cards/crab/card/card.json?url';
import a0_1 from '../assets/painted-cards/crab/record.json?url';
import a0_2 from '../assets/painted-cards/crab/card/master-512.png?url';
import a0_3 from '../assets/painted-cards/crab/card/labels-512.png?url';
import a0_4 from '../assets/painted-cards/crab/markings.json?url';
import a0_5 from '../assets/painted-cards/crab/markings/striped.png?url';
import a0_6 from '../assets/painted-cards/crab/markings/spotted.png?url';
import a0_7 from '../assets/painted-cards/crab/markings/banded.png?url';
import a0_8 from '../assets/painted-cards/crab/markings/mottled.png?url';
import a0_9 from '../assets/painted-cards/crab/markings/marbled.png?url';
import a0_10 from '../assets/painted-cards/crab/markings/eye-spotted.png?url';
import a1_0 from '../assets/painted-cards/coconut-crab/card/card.json?url';
import a1_1 from '../assets/painted-cards/coconut-crab/record.json?url';
import a1_2 from '../assets/painted-cards/coconut-crab/card/master-512.png?url';
import a1_3 from '../assets/painted-cards/coconut-crab/card/labels-512.png?url';
import a2_0 from '../assets/painted-cards/freshwater-crab/card/card.json?url';
import a2_1 from '../assets/painted-cards/freshwater-crab/record.json?url';
import a2_2 from '../assets/painted-cards/freshwater-crab/card/master-512.png?url';
import a2_3 from '../assets/painted-cards/freshwater-crab/card/labels-512.png?url';
import a3_0 from '../assets/painted-cards/mud-crab/card/card.json?url';
import a3_1 from '../assets/painted-cards/mud-crab/record.json?url';
import a3_2 from '../assets/painted-cards/mud-crab/card/master-512.png?url';
import a3_3 from '../assets/painted-cards/mud-crab/card/labels-512.png?url';
import a4_0 from '../assets/painted-cards/vent-crab/card/card.json?url';
import a4_1 from '../assets/painted-cards/vent-crab/record.json?url';
import a4_2 from '../assets/painted-cards/vent-crab/card/master-512.png?url';
import a4_3 from '../assets/painted-cards/vent-crab/card/labels-512.png?url';
import a5_0 from '../assets/painted-cards/civet-sentinel-input-01/card/card.json?url';
import a5_1 from '../assets/painted-cards/civet-sentinel-input-01/record.json?url';
import a5_2 from '../assets/painted-cards/civet-sentinel-input-01/card/master-512.png?url';
import a5_3 from '../assets/painted-cards/civet-sentinel-input-01/card/labels-512.png?url';
import a5_4 from '../assets/painted-cards/civet-sentinel-input-01/markings.json?url';
import a5_5 from '../assets/painted-cards/civet-sentinel-input-01/markings/striped.png?url';
import a5_6 from '../assets/painted-cards/civet-sentinel-input-01/markings/spotted.png?url';
import a5_7 from '../assets/painted-cards/civet-sentinel-input-01/markings/banded.png?url';
import a5_8 from '../assets/painted-cards/civet-sentinel-input-01/markings/mottled.png?url';
import a5_9 from '../assets/painted-cards/civet-sentinel-input-01/markings/marbled.png?url';
import a5_10 from '../assets/painted-cards/civet-sentinel-input-01/markings/eye-spotted.png?url';
import a6_0 from '../assets/painted-cards/salmon/card/card.json?url';
import a6_1 from '../assets/painted-cards/salmon/record.json?url';
import a6_2 from '../assets/painted-cards/salmon/card/master-512.png?url';
import a6_3 from '../assets/painted-cards/salmon/card/labels-512.png?url';
import a6_4 from '../assets/painted-cards/salmon/markings.json?url';
import a6_5 from '../assets/painted-cards/salmon/markings/striped.png?url';
import a6_6 from '../assets/painted-cards/salmon/markings/spotted.png?url';
import a6_7 from '../assets/painted-cards/salmon/markings/banded.png?url';
import a6_8 from '../assets/painted-cards/salmon/markings/mottled.png?url';
import a6_9 from '../assets/painted-cards/salmon/markings/marbled.png?url';
import a6_10 from '../assets/painted-cards/salmon/markings/eye-spotted.png?url';
import a7_0 from '../assets/painted-cards/eagle/card/card.json?url';
import a7_1 from '../assets/painted-cards/eagle/record.json?url';
import a7_2 from '../assets/painted-cards/eagle/card/master-512.png?url';
import a7_3 from '../assets/painted-cards/eagle/card/labels-512.png?url';
import a8_0 from '../assets/painted-cards/beetle/card/card.json?url';
import a8_1 from '../assets/painted-cards/beetle/record.json?url';
import a8_2 from '../assets/painted-cards/beetle/card/master-512.png?url';
import a8_3 from '../assets/painted-cards/beetle/card/labels-512.png?url';
import a9_0 from '../assets/painted-cards/python/card/card.json?url';
import a9_1 from '../assets/painted-cards/python/record.json?url';
import a9_2 from '../assets/painted-cards/python/card/master-512.png?url';
import a9_3 from '../assets/painted-cards/python/card/labels-512.png?url';
import a10_0 from '../assets/painted-cards/tree-frog/card/card.json?url';
import a10_1 from '../assets/painted-cards/tree-frog/record.json?url';
import a10_2 from '../assets/painted-cards/tree-frog/card/master-512.png?url';
import a10_3 from '../assets/painted-cards/tree-frog/card/labels-512.png?url';
import a11_0 from '../assets/painted-cards/chimpanzee/card/card.json?url';
import a11_1 from '../assets/painted-cards/chimpanzee/record.json?url';
import a11_2 from '../assets/painted-cards/chimpanzee/card/master-512.png?url';
import a11_3 from '../assets/painted-cards/chimpanzee/card/labels-512.png?url';
import a12_0 from '../assets/painted-cards/starfish/card/card.json?url';
import a12_1 from '../assets/painted-cards/starfish/record.json?url';
import a12_2 from '../assets/painted-cards/starfish/card/master-512.png?url';
import a12_3 from '../assets/painted-cards/starfish/card/labels-512.png?url';
import a13_0 from '../assets/painted-cards/tarantula/card/card.json?url';
import a13_1 from '../assets/painted-cards/tarantula/record.json?url';
import a13_2 from '../assets/painted-cards/tarantula/card/master-512.png?url';
import a13_3 from '../assets/painted-cards/tarantula/card/labels-512.png?url';
import a14_0 from '../assets/painted-cards/octopus/card/card.json?url';
import a14_1 from '../assets/painted-cards/octopus/record.json?url';
import a14_2 from '../assets/painted-cards/octopus/card/master-512.png?url';
import a14_3 from '../assets/painted-cards/octopus/card/labels-512.png?url';
import a15_0 from '../assets/painted-cards/fruit-bat/card/card.json?url';
import a15_1 from '../assets/painted-cards/fruit-bat/record.json?url';
import a15_2 from '../assets/painted-cards/fruit-bat/card/master-512.png?url';
import a15_3 from '../assets/painted-cards/fruit-bat/card/labels-512.png?url';
import a16_0 from '../assets/painted-cards/centipede/card/card.json?url';
import a16_1 from '../assets/painted-cards/centipede/record.json?url';
import a16_2 from '../assets/painted-cards/centipede/card/master-512.png?url';
import a16_3 from '../assets/painted-cards/centipede/card/labels-512.png?url';
import a17_0 from '../assets/painted-cards/bass/card/card.json?url';
import a17_1 from '../assets/painted-cards/bass/record.json?url';
import a17_2 from '../assets/painted-cards/bass/card/master-512.png?url';
import a17_3 from '../assets/painted-cards/bass/card/labels-512.png?url';
import a17_4 from '../assets/painted-cards/bass/markings.json?url';
import a17_5 from '../assets/painted-cards/bass/markings/striped.png?url';
import a17_6 from '../assets/painted-cards/bass/markings/spotted.png?url';
import a17_7 from '../assets/painted-cards/bass/markings/banded.png?url';
import a17_8 from '../assets/painted-cards/bass/markings/mottled.png?url';
import a17_9 from '../assets/painted-cards/bass/markings/marbled.png?url';
import a17_10 from '../assets/painted-cards/bass/markings/eye-spotted.png?url';
import a18_0 from '../assets/painted-cards/tang/card/card.json?url';
import a18_1 from '../assets/painted-cards/tang/record.json?url';
import a18_2 from '../assets/painted-cards/tang/card/master-512.png?url';
import a18_3 from '../assets/painted-cards/tang/card/labels-512.png?url';
import a18_4 from '../assets/painted-cards/tang/markings.json?url';
import a18_5 from '../assets/painted-cards/tang/markings/striped.png?url';
import a18_6 from '../assets/painted-cards/tang/markings/spotted.png?url';
import a18_7 from '../assets/painted-cards/tang/markings/banded.png?url';
import a18_8 from '../assets/painted-cards/tang/markings/mottled.png?url';
import a18_9 from '../assets/painted-cards/tang/markings/marbled.png?url';
import a18_10 from '../assets/painted-cards/tang/markings/eye-spotted.png?url';
import a19_0 from '../assets/painted-cards/dragonfly/card/card.json?url';
import a19_1 from '../assets/painted-cards/dragonfly/record.json?url';
import a19_2 from '../assets/painted-cards/dragonfly/card/master-512.png?url';
import a19_3 from '../assets/painted-cards/dragonfly/card/labels-512.png?url';
import a19_4 from '../assets/painted-cards/dragonfly/markings.json?url';
import a19_5 from '../assets/painted-cards/dragonfly/markings/striped.png?url';
import a19_6 from '../assets/painted-cards/dragonfly/markings/spotted.png?url';
import a19_7 from '../assets/painted-cards/dragonfly/markings/banded.png?url';
import a19_8 from '../assets/painted-cards/dragonfly/markings/mottled.png?url';
import a19_9 from '../assets/painted-cards/dragonfly/markings/marbled.png?url';
import a19_10 from '../assets/painted-cards/dragonfly/markings/eye-spotted.png?url';
import a20_0 from '../assets/painted-cards/sturgeon/card/card.json?url';
import a20_1 from '../assets/painted-cards/sturgeon/record.json?url';
import a20_2 from '../assets/painted-cards/sturgeon/card/master-512.png?url';
import a20_3 from '../assets/painted-cards/sturgeon/card/labels-512.png?url';
import a20_4 from '../assets/painted-cards/sturgeon/markings.json?url';
import a20_5 from '../assets/painted-cards/sturgeon/markings/striped.png?url';
import a20_6 from '../assets/painted-cards/sturgeon/markings/spotted.png?url';
import a20_7 from '../assets/painted-cards/sturgeon/markings/banded.png?url';
import a20_8 from '../assets/painted-cards/sturgeon/markings/mottled.png?url';
import a20_9 from '../assets/painted-cards/sturgeon/markings/marbled.png?url';
import a20_10 from '../assets/painted-cards/sturgeon/markings/eye-spotted.png?url';
import a21_0 from '../assets/painted-cards/wolf/card/card.json?url';
import a21_1 from '../assets/painted-cards/wolf/record.json?url';
import a21_2 from '../assets/painted-cards/wolf/card/master-512.png?url';
import a21_3 from '../assets/painted-cards/wolf/card/labels-512.png?url';
import a21_4 from '../assets/painted-cards/wolf/markings.json?url';
import a21_5 from '../assets/painted-cards/wolf/markings/striped.png?url';
import a21_6 from '../assets/painted-cards/wolf/markings/spotted.png?url';
import a21_7 from '../assets/painted-cards/wolf/markings/banded.png?url';
import a21_8 from '../assets/painted-cards/wolf/markings/mottled.png?url';
import a21_9 from '../assets/painted-cards/wolf/markings/marbled.png?url';
import a21_10 from '../assets/painted-cards/wolf/markings/eye-spotted.png?url';
import a22_0 from '../assets/painted-cards/impala/card/card.json?url';
import a22_1 from '../assets/painted-cards/impala/record.json?url';
import a22_2 from '../assets/painted-cards/impala/card/master-512.png?url';
import a22_3 from '../assets/painted-cards/impala/card/labels-512.png?url';
import a22_4 from '../assets/painted-cards/impala/markings.json?url';
import a22_5 from '../assets/painted-cards/impala/markings/striped.png?url';
import a22_6 from '../assets/painted-cards/impala/markings/spotted.png?url';
import a22_7 from '../assets/painted-cards/impala/markings/banded.png?url';
import a22_8 from '../assets/painted-cards/impala/markings/mottled.png?url';
import a22_9 from '../assets/painted-cards/impala/markings/marbled.png?url';
import a22_10 from '../assets/painted-cards/impala/markings/eye-spotted.png?url';
import a23_0 from '../assets/painted-cards/river-otter/card/card.json?url';
import a23_1 from '../assets/painted-cards/river-otter/record.json?url';
import a23_2 from '../assets/painted-cards/river-otter/card/master-512.png?url';
import a23_3 from '../assets/painted-cards/river-otter/card/labels-512.png?url';
import a23_4 from '../assets/painted-cards/river-otter/markings.json?url';
import a23_5 from '../assets/painted-cards/river-otter/markings/striped.png?url';
import a23_6 from '../assets/painted-cards/river-otter/markings/spotted.png?url';
import a23_7 from '../assets/painted-cards/river-otter/markings/banded.png?url';
import a23_8 from '../assets/painted-cards/river-otter/markings/mottled.png?url';
import a23_9 from '../assets/painted-cards/river-otter/markings/marbled.png?url';
import a23_10 from '../assets/painted-cards/river-otter/markings/eye-spotted.png?url';
import a24_0 from '../assets/painted-cards/heron/card/card.json?url';
import a24_1 from '../assets/painted-cards/heron/record.json?url';
import a24_2 from '../assets/painted-cards/heron/card/master-512.png?url';
import a24_3 from '../assets/painted-cards/heron/card/labels-512.png?url';
import a24_4 from '../assets/painted-cards/heron/markings.json?url';
import a24_5 from '../assets/painted-cards/heron/markings/striped.png?url';
import a24_6 from '../assets/painted-cards/heron/markings/spotted.png?url';
import a24_7 from '../assets/painted-cards/heron/markings/banded.png?url';
import a24_8 from '../assets/painted-cards/heron/markings/mottled.png?url';
import a24_9 from '../assets/painted-cards/heron/markings/marbled.png?url';
import a24_10 from '../assets/painted-cards/heron/markings/eye-spotted.png?url';
import a25_0 from '../assets/painted-cards/jellyfish/card/card.json?url';
import a25_1 from '../assets/painted-cards/jellyfish/record.json?url';
import a25_2 from '../assets/painted-cards/jellyfish/card/master-512.png?url';
import a25_3 from '../assets/painted-cards/jellyfish/card/labels-512.png?url';
import a25_4 from '../assets/painted-cards/jellyfish/markings.json?url';
import a25_5 from '../assets/painted-cards/jellyfish/markings/striped.png?url';
import a25_6 from '../assets/painted-cards/jellyfish/markings/spotted.png?url';
import a25_7 from '../assets/painted-cards/jellyfish/markings/banded.png?url';
import a25_8 from '../assets/painted-cards/jellyfish/markings/mottled.png?url';
import a25_9 from '../assets/painted-cards/jellyfish/markings/marbled.png?url';
import a25_10 from '../assets/painted-cards/jellyfish/markings/eye-spotted.png?url';
/** Repo-relative shipped archetype dir → its shipped asset URLs by file (card, record, and the painted masks when it has them). */
export const CARD_ASSET_URLS: ReadonlyMap<string, Readonly<Record<string, string>>> = new Map([
  ['port/v2/apps/game/assets/painted-cards/crab/', { 'card/card.json': a0_0, 'record.json': a0_1, 'card/master-512.png': a0_2, 'card/labels-512.png': a0_3, 'markings.json': a0_4, 'markings/striped.png': a0_5, 'markings/spotted.png': a0_6, 'markings/banded.png': a0_7, 'markings/mottled.png': a0_8, 'markings/marbled.png': a0_9, 'markings/eye-spotted.png': a0_10 }],
  ['port/v2/apps/game/assets/painted-cards/coconut-crab/', { 'card/card.json': a1_0, 'record.json': a1_1, 'card/master-512.png': a1_2, 'card/labels-512.png': a1_3 }],
  ['port/v2/apps/game/assets/painted-cards/freshwater-crab/', { 'card/card.json': a2_0, 'record.json': a2_1, 'card/master-512.png': a2_2, 'card/labels-512.png': a2_3 }],
  ['port/v2/apps/game/assets/painted-cards/mud-crab/', { 'card/card.json': a3_0, 'record.json': a3_1, 'card/master-512.png': a3_2, 'card/labels-512.png': a3_3 }],
  ['port/v2/apps/game/assets/painted-cards/vent-crab/', { 'card/card.json': a4_0, 'record.json': a4_1, 'card/master-512.png': a4_2, 'card/labels-512.png': a4_3 }],
  ['port/v2/apps/game/assets/painted-cards/civet-sentinel-input-01/', { 'card/card.json': a5_0, 'record.json': a5_1, 'card/master-512.png': a5_2, 'card/labels-512.png': a5_3, 'markings.json': a5_4, 'markings/striped.png': a5_5, 'markings/spotted.png': a5_6, 'markings/banded.png': a5_7, 'markings/mottled.png': a5_8, 'markings/marbled.png': a5_9, 'markings/eye-spotted.png': a5_10 }],
  ['port/v2/apps/game/assets/painted-cards/salmon/', { 'card/card.json': a6_0, 'record.json': a6_1, 'card/master-512.png': a6_2, 'card/labels-512.png': a6_3, 'markings.json': a6_4, 'markings/striped.png': a6_5, 'markings/spotted.png': a6_6, 'markings/banded.png': a6_7, 'markings/mottled.png': a6_8, 'markings/marbled.png': a6_9, 'markings/eye-spotted.png': a6_10 }],
  ['port/v2/apps/game/assets/painted-cards/eagle/', { 'card/card.json': a7_0, 'record.json': a7_1, 'card/master-512.png': a7_2, 'card/labels-512.png': a7_3 }],
  ['port/v2/apps/game/assets/painted-cards/beetle/', { 'card/card.json': a8_0, 'record.json': a8_1, 'card/master-512.png': a8_2, 'card/labels-512.png': a8_3 }],
  ['port/v2/apps/game/assets/painted-cards/python/', { 'card/card.json': a9_0, 'record.json': a9_1, 'card/master-512.png': a9_2, 'card/labels-512.png': a9_3 }],
  ['port/v2/apps/game/assets/painted-cards/tree-frog/', { 'card/card.json': a10_0, 'record.json': a10_1, 'card/master-512.png': a10_2, 'card/labels-512.png': a10_3 }],
  ['port/v2/apps/game/assets/painted-cards/chimpanzee/', { 'card/card.json': a11_0, 'record.json': a11_1, 'card/master-512.png': a11_2, 'card/labels-512.png': a11_3 }],
  ['port/v2/apps/game/assets/painted-cards/starfish/', { 'card/card.json': a12_0, 'record.json': a12_1, 'card/master-512.png': a12_2, 'card/labels-512.png': a12_3 }],
  ['port/v2/apps/game/assets/painted-cards/tarantula/', { 'card/card.json': a13_0, 'record.json': a13_1, 'card/master-512.png': a13_2, 'card/labels-512.png': a13_3 }],
  ['port/v2/apps/game/assets/painted-cards/octopus/', { 'card/card.json': a14_0, 'record.json': a14_1, 'card/master-512.png': a14_2, 'card/labels-512.png': a14_3 }],
  ['port/v2/apps/game/assets/painted-cards/fruit-bat/', { 'card/card.json': a15_0, 'record.json': a15_1, 'card/master-512.png': a15_2, 'card/labels-512.png': a15_3 }],
  ['port/v2/apps/game/assets/painted-cards/centipede/', { 'card/card.json': a16_0, 'record.json': a16_1, 'card/master-512.png': a16_2, 'card/labels-512.png': a16_3 }],
  ['port/v2/apps/game/assets/painted-cards/bass/', { 'card/card.json': a17_0, 'record.json': a17_1, 'card/master-512.png': a17_2, 'card/labels-512.png': a17_3, 'markings.json': a17_4, 'markings/striped.png': a17_5, 'markings/spotted.png': a17_6, 'markings/banded.png': a17_7, 'markings/mottled.png': a17_8, 'markings/marbled.png': a17_9, 'markings/eye-spotted.png': a17_10 }],
  ['port/v2/apps/game/assets/painted-cards/tang/', { 'card/card.json': a18_0, 'record.json': a18_1, 'card/master-512.png': a18_2, 'card/labels-512.png': a18_3, 'markings.json': a18_4, 'markings/striped.png': a18_5, 'markings/spotted.png': a18_6, 'markings/banded.png': a18_7, 'markings/mottled.png': a18_8, 'markings/marbled.png': a18_9, 'markings/eye-spotted.png': a18_10 }],
  ['port/v2/apps/game/assets/painted-cards/dragonfly/', { 'card/card.json': a19_0, 'record.json': a19_1, 'card/master-512.png': a19_2, 'card/labels-512.png': a19_3, 'markings.json': a19_4, 'markings/striped.png': a19_5, 'markings/spotted.png': a19_6, 'markings/banded.png': a19_7, 'markings/mottled.png': a19_8, 'markings/marbled.png': a19_9, 'markings/eye-spotted.png': a19_10 }],
  ['port/v2/apps/game/assets/painted-cards/sturgeon/', { 'card/card.json': a20_0, 'record.json': a20_1, 'card/master-512.png': a20_2, 'card/labels-512.png': a20_3, 'markings.json': a20_4, 'markings/striped.png': a20_5, 'markings/spotted.png': a20_6, 'markings/banded.png': a20_7, 'markings/mottled.png': a20_8, 'markings/marbled.png': a20_9, 'markings/eye-spotted.png': a20_10 }],
  ['port/v2/apps/game/assets/painted-cards/wolf/', { 'card/card.json': a21_0, 'record.json': a21_1, 'card/master-512.png': a21_2, 'card/labels-512.png': a21_3, 'markings.json': a21_4, 'markings/striped.png': a21_5, 'markings/spotted.png': a21_6, 'markings/banded.png': a21_7, 'markings/mottled.png': a21_8, 'markings/marbled.png': a21_9, 'markings/eye-spotted.png': a21_10 }],
  ['port/v2/apps/game/assets/painted-cards/impala/', { 'card/card.json': a22_0, 'record.json': a22_1, 'card/master-512.png': a22_2, 'card/labels-512.png': a22_3, 'markings.json': a22_4, 'markings/striped.png': a22_5, 'markings/spotted.png': a22_6, 'markings/banded.png': a22_7, 'markings/mottled.png': a22_8, 'markings/marbled.png': a22_9, 'markings/eye-spotted.png': a22_10 }],
  ['port/v2/apps/game/assets/painted-cards/river-otter/', { 'card/card.json': a23_0, 'record.json': a23_1, 'card/master-512.png': a23_2, 'card/labels-512.png': a23_3, 'markings.json': a23_4, 'markings/striped.png': a23_5, 'markings/spotted.png': a23_6, 'markings/banded.png': a23_7, 'markings/mottled.png': a23_8, 'markings/marbled.png': a23_9, 'markings/eye-spotted.png': a23_10 }],
  ['port/v2/apps/game/assets/painted-cards/heron/', { 'card/card.json': a24_0, 'record.json': a24_1, 'card/master-512.png': a24_2, 'card/labels-512.png': a24_3, 'markings.json': a24_4, 'markings/striped.png': a24_5, 'markings/spotted.png': a24_6, 'markings/banded.png': a24_7, 'markings/mottled.png': a24_8, 'markings/marbled.png': a24_9, 'markings/eye-spotted.png': a24_10 }],
  ['port/v2/apps/game/assets/painted-cards/jellyfish/', { 'card/card.json': a25_0, 'record.json': a25_1, 'card/master-512.png': a25_2, 'card/labels-512.png': a25_3, 'markings.json': a25_4, 'markings/striped.png': a25_5, 'markings/spotted.png': a25_6, 'markings/banded.png': a25_7, 'markings/mottled.png': a25_8, 'markings/marbled.png': a25_9, 'markings/eye-spotted.png': a25_10 }],
]);
