// GENERATED by tools/morph/build-card-masters.mjs from its CARD_ARCHETYPES list — do not edit by hand; re-run the tool.
import a0_0 from '../assets/painted-cards/crab/card/card.json?url';
import a0_1 from '../assets/painted-cards/crab/record.json?url';
import a0_2 from '../assets/painted-cards/crab/card/master-512.png?url';
import a0_3 from '../assets/painted-cards/crab/card/labels-512.png?url';
import a0_4 from '../assets/painted-cards/crab/markings.json?url';
import a0_5 from '../assets/painted-cards/crab/markings/striped.png?url';
import a0_6 from '../assets/painted-cards/crab/markings/spotted.png?url';
import a0_7 from '../assets/painted-cards/crab/markings/banded.png?url';
import a0_8 from '../assets/painted-cards/crab/markings/mottled.png?url';
import a0_9 from '../assets/painted-cards/crab/markings/marbled.png?url';
import a0_10 from '../assets/painted-cards/crab/markings/eye-spotted.png?url';
import a1_0 from '../assets/painted-cards/coconut-crab/card/card.json?url';
import a1_1 from '../assets/painted-cards/coconut-crab/record.json?url';
import a1_2 from '../assets/painted-cards/coconut-crab/card/master-512.png?url';
import a1_3 from '../assets/painted-cards/coconut-crab/card/labels-512.png?url';
import a2_0 from '../assets/painted-cards/freshwater-crab/card/card.json?url';
import a2_1 from '../assets/painted-cards/freshwater-crab/record.json?url';
import a2_2 from '../assets/painted-cards/freshwater-crab/card/master-512.png?url';
import a2_3 from '../assets/painted-cards/freshwater-crab/card/labels-512.png?url';
import a3_0 from '../assets/painted-cards/mud-crab/card/card.json?url';
import a3_1 from '../assets/painted-cards/mud-crab/record.json?url';
import a3_2 from '../assets/painted-cards/mud-crab/card/master-512.png?url';
import a3_3 from '../assets/painted-cards/mud-crab/card/labels-512.png?url';
import a4_0 from '../assets/painted-cards/vent-crab/card/card.json?url';
import a4_1 from '../assets/painted-cards/vent-crab/record.json?url';
import a4_2 from '../assets/painted-cards/vent-crab/card/master-512.png?url';
import a4_3 from '../assets/painted-cards/vent-crab/card/labels-512.png?url';
import a5_0 from '../assets/painted-cards/civet-sentinel-input-01/card/card.json?url';
import a5_1 from '../assets/painted-cards/civet-sentinel-input-01/record.json?url';
import a5_2 from '../assets/painted-cards/civet-sentinel-input-01/card/master-512.png?url';
import a5_3 from '../assets/painted-cards/civet-sentinel-input-01/card/labels-512.png?url';
import a5_4 from '../assets/painted-cards/civet-sentinel-input-01/markings.json?url';
import a5_5 from '../assets/painted-cards/civet-sentinel-input-01/markings/striped.png?url';
import a5_6 from '../assets/painted-cards/civet-sentinel-input-01/markings/spotted.png?url';
import a5_7 from '../assets/painted-cards/civet-sentinel-input-01/markings/banded.png?url';
import a5_8 from '../assets/painted-cards/civet-sentinel-input-01/markings/mottled.png?url';
import a5_9 from '../assets/painted-cards/civet-sentinel-input-01/markings/marbled.png?url';
import a5_10 from '../assets/painted-cards/civet-sentinel-input-01/markings/eye-spotted.png?url';
import a6_0 from '../assets/painted-cards/salmon/card/card.json?url';
import a6_1 from '../assets/painted-cards/salmon/record.json?url';
import a6_2 from '../assets/painted-cards/salmon/card/master-512.png?url';
import a6_3 from '../assets/painted-cards/salmon/card/labels-512.png?url';
import a6_4 from '../assets/painted-cards/salmon/markings.json?url';
import a6_5 from '../assets/painted-cards/salmon/markings/striped.png?url';
import a6_6 from '../assets/painted-cards/salmon/markings/spotted.png?url';
import a6_7 from '../assets/painted-cards/salmon/markings/banded.png?url';
import a6_8 from '../assets/painted-cards/salmon/markings/mottled.png?url';
import a6_9 from '../assets/painted-cards/salmon/markings/marbled.png?url';
import a6_10 from '../assets/painted-cards/salmon/markings/eye-spotted.png?url';
import a7_0 from '../assets/painted-cards/eagle/card/card.json?url';
import a7_1 from '../assets/painted-cards/eagle/record.json?url';
import a7_2 from '../assets/painted-cards/eagle/card/master-512.png?url';
import a7_3 from '../assets/painted-cards/eagle/card/labels-512.png?url';
import a8_0 from '../assets/painted-cards/beetle/card/card.json?url';
import a8_1 from '../assets/painted-cards/beetle/record.json?url';
import a8_2 from '../assets/painted-cards/beetle/card/master-512.png?url';
import a8_3 from '../assets/painted-cards/beetle/card/labels-512.png?url';
import a9_0 from '../assets/painted-cards/python/card/card.json?url';
import a9_1 from '../assets/painted-cards/python/record.json?url';
import a9_2 from '../assets/painted-cards/python/card/master-512.png?url';
import a9_3 from '../assets/painted-cards/python/card/labels-512.png?url';
import a10_0 from '../assets/painted-cards/tree-frog/card/card.json?url';
import a10_1 from '../assets/painted-cards/tree-frog/record.json?url';
import a10_2 from '../assets/painted-cards/tree-frog/card/master-512.png?url';
import a10_3 from '../assets/painted-cards/tree-frog/card/labels-512.png?url';
import a11_0 from '../assets/painted-cards/chimpanzee/card/card.json?url';
import a11_1 from '../assets/painted-cards/chimpanzee/record.json?url';
import a11_2 from '../assets/painted-cards/chimpanzee/card/master-512.png?url';
import a11_3 from '../assets/painted-cards/chimpanzee/card/labels-512.png?url';
import a12_0 from '../assets/painted-cards/starfish/card/card.json?url';
import a12_1 from '../assets/painted-cards/starfish/record.json?url';
import a12_2 from '../assets/painted-cards/starfish/card/master-512.png?url';
import a12_3 from '../assets/painted-cards/starfish/card/labels-512.png?url';
import a13_0 from '../assets/painted-cards/tarantula/card/card.json?url';
import a13_1 from '../assets/painted-cards/tarantula/record.json?url';
import a13_2 from '../assets/painted-cards/tarantula/card/master-512.png?url';
import a13_3 from '../assets/painted-cards/tarantula/card/labels-512.png?url';
import a14_0 from '../assets/painted-cards/octopus/card/card.json?url';
import a14_1 from '../assets/painted-cards/octopus/record.json?url';
import a14_2 from '../assets/painted-cards/octopus/card/master-512.png?url';
import a14_3 from '../assets/painted-cards/octopus/card/labels-512.png?url';
import a15_0 from '../assets/painted-cards/fruit-bat/card/card.json?url';
import a15_1 from '../assets/painted-cards/fruit-bat/record.json?url';
import a15_2 from '../assets/painted-cards/fruit-bat/card/master-512.png?url';
import a15_3 from '../assets/painted-cards/fruit-bat/card/labels-512.png?url';
import a16_0 from '../assets/painted-cards/centipede/card/card.json?url';
import a16_1 from '../assets/painted-cards/centipede/record.json?url';
import a16_2 from '../assets/painted-cards/centipede/card/master-512.png?url';
import a16_3 from '../assets/painted-cards/centipede/card/labels-512.png?url';
/** Repo-relative shipped archetype dir → its shipped asset URLs by file (card, record, and the painted masks when it has them). */
export const CARD_ASSET_URLS: ReadonlyMap<string, Readonly<Record<string, string>>> = new Map([
  ['port/v2/apps/game/assets/painted-cards/crab/', { 'card/card.json': a0_0, 'record.json': a0_1, 'card/master-512.png': a0_2, 'card/labels-512.png': a0_3, 'markings.json': a0_4, 'markings/striped.png': a0_5, 'markings/spotted.png': a0_6, 'markings/banded.png': a0_7, 'markings/mottled.png': a0_8, 'markings/marbled.png': a0_9, 'markings/eye-spotted.png': a0_10 }],
  ['port/v2/apps/game/assets/painted-cards/coconut-crab/', { 'card/card.json': a1_0, 'record.json': a1_1, 'card/master-512.png': a1_2, 'card/labels-512.png': a1_3 }],
  ['port/v2/apps/game/assets/painted-cards/freshwater-crab/', { 'card/card.json': a2_0, 'record.json': a2_1, 'card/master-512.png': a2_2, 'card/labels-512.png': a2_3 }],
  ['port/v2/apps/game/assets/painted-cards/mud-crab/', { 'card/card.json': a3_0, 'record.json': a3_1, 'card/master-512.png': a3_2, 'card/labels-512.png': a3_3 }],
  ['port/v2/apps/game/assets/painted-cards/vent-crab/', { 'card/card.json': a4_0, 'record.json': a4_1, 'card/master-512.png': a4_2, 'card/labels-512.png': a4_3 }],
  ['port/v2/apps/game/assets/painted-cards/civet-sentinel-input-01/', { 'card/card.json': a5_0, 'record.json': a5_1, 'card/master-512.png': a5_2, 'card/labels-512.png': a5_3, 'markings.json': a5_4, 'markings/striped.png': a5_5, 'markings/spotted.png': a5_6, 'markings/banded.png': a5_7, 'markings/mottled.png': a5_8, 'markings/marbled.png': a5_9, 'markings/eye-spotted.png': a5_10 }],
  ['port/v2/apps/game/assets/painted-cards/salmon/', { 'card/card.json': a6_0, 'record.json': a6_1, 'card/master-512.png': a6_2, 'card/labels-512.png': a6_3, 'markings.json': a6_4, 'markings/striped.png': a6_5, 'markings/spotted.png': a6_6, 'markings/banded.png': a6_7, 'markings/mottled.png': a6_8, 'markings/marbled.png': a6_9, 'markings/eye-spotted.png': a6_10 }],
  ['port/v2/apps/game/assets/painted-cards/eagle/', { 'card/card.json': a7_0, 'record.json': a7_1, 'card/master-512.png': a7_2, 'card/labels-512.png': a7_3 }],
  ['port/v2/apps/game/assets/painted-cards/beetle/', { 'card/card.json': a8_0, 'record.json': a8_1, 'card/master-512.png': a8_2, 'card/labels-512.png': a8_3 }],
  ['port/v2/apps/game/assets/painted-cards/python/', { 'card/card.json': a9_0, 'record.json': a9_1, 'card/master-512.png': a9_2, 'card/labels-512.png': a9_3 }],
  ['port/v2/apps/game/assets/painted-cards/tree-frog/', { 'card/card.json': a10_0, 'record.json': a10_1, 'card/master-512.png': a10_2, 'card/labels-512.png': a10_3 }],
  ['port/v2/apps/game/assets/painted-cards/chimpanzee/', { 'card/card.json': a11_0, 'record.json': a11_1, 'card/master-512.png': a11_2, 'card/labels-512.png': a11_3 }],
  ['port/v2/apps/game/assets/painted-cards/starfish/', { 'card/card.json': a12_0, 'record.json': a12_1, 'card/master-512.png': a12_2, 'card/labels-512.png': a12_3 }],
  ['port/v2/apps/game/assets/painted-cards/tarantula/', { 'card/card.json': a13_0, 'record.json': a13_1, 'card/master-512.png': a13_2, 'card/labels-512.png': a13_3 }],
  ['port/v2/apps/game/assets/painted-cards/octopus/', { 'card/card.json': a14_0, 'record.json': a14_1, 'card/master-512.png': a14_2, 'card/labels-512.png': a14_3 }],
  ['port/v2/apps/game/assets/painted-cards/fruit-bat/', { 'card/card.json': a15_0, 'record.json': a15_1, 'card/master-512.png': a15_2, 'card/labels-512.png': a15_3 }],
  ['port/v2/apps/game/assets/painted-cards/centipede/', { 'card/card.json': a16_0, 'record.json': a16_1, 'card/master-512.png': a16_2, 'card/labels-512.png': a16_3 }],
]);
