/* AUTO-GENERATED by tools/lift-hdart.mjs. ⚠ DO NOT EDIT. */
import type { ArtCanvas } from './speciescanvas.js';
export const PRESERVED_FULL_VISTA_SOURCE_SHA256: string;
export function renderPreservedGenericVistaV1(options: Record<string, unknown>, profiles: Readonly<Record<string, unknown>>): ArtCanvas;
export function renderPreservedGasDeckVistaV1(options: Record<string, unknown>): ArtCanvas;
export function renderPreservedAbyssVistaV1(options: Record<string, unknown>): ArtCanvas;
export function renderPreservedReefVistaV1(options: Record<string, unknown>): ArtCanvas;
