/* AUTO-GENERATED by tools/lift-hdart.mjs. ⚠ DO NOT EDIT. */
export const PRESERVED_BIOME_VISTA_ECOLOGY_SOURCE_SHA256: string;
export type PreservedBiomeVistaRandomFactoryV1 = (seed: number) => () => number;
export function applyPreservedBiomeVistaEcologyV1(
  context: Record<string, unknown>, width: number, height: number, horizon: number,
  options: Readonly<{ wb: string; pal: string; nightize: boolean }>, seed: number,
  profiles: Readonly<Record<string, Readonly<{ weather: string; hazard: string | null }>>>,
  randomFactory: PreservedBiomeVistaRandomFactoryV1,
): void;
