/* florarost.ts — the wave-11 plant roster.
   Split from floraoverrides2.ts (which holds the painter) purely for size.
   Every key was read out of the catalog, never recalled — and the shadow
   check guarantees none of these re-covers a wave-2 species. */
import { plantBody, type PlantSpec, type PainterF } from './floraoverrides2.js';

const T = (spec: PlantSpec): PainterF => (c, g, p, n) => plantBody(c, g, p, spec, n);

export const FLORA2_SPEC: Record<string, PainterF> = {
  /* ── FRUIT TREES: a canopy carrying its fruit ── */
  'Apple': T({ hue: '#4e7c3b', habit: 'tree', leaf: 'broad', fruit: 'pome', fhue: '#c8342e' }),
  'Crabapple': T({ hue: '#6e7a3e', habit: 'tree', leaf: 'broad', fruit: 'pome', fhue: '#b03a34' }),
  'Pear': T({ hue: '#38703e', habit: 'tree', leaf: 'broad', fruit: 'pear', fhue: '#c9c05a' }),
  'Peach': T({ hue: '#62893a', habit: 'tree', leaf: 'lance', fruit: 'drupe', fhue: '#e0975a' }),
  'Apricot': T({ hue: '#6c8f40', habit: 'tree', leaf: 'heart', fruit: 'drupe', fhue: '#e0a047' }),
  'Plum': T({ hue: '#4e6f43', habit: 'tree', leaf: 'broad', fruit: 'drupe', fhue: '#6b3f7a' }),
  'Beach Plum': T({ hue: '#6b7f5e', habit: 'shrub', leaf: 'broad', fruit: 'drupe', fhue: '#5d3a6e' }),
  'Cherry': T({ hue: '#3d6634', habit: 'tree', leaf: 'lance', fruit: 'drupe', fhue: '#b8262f' }),
  'Wild Cherry': T({ hue: '#49673a', habit: 'tree', leaf: 'lance', fruit: 'drupe', fhue: '#8e2028' }),
  'Chokecherry': T({ hue: '#47602c', habit: 'shrub', leaf: 'lance', fruit: 'cluster', fhue: '#4a1f2c' }),
  'Persimmon': T({ hue: '#2f5f30', habit: 'tree', leaf: 'broad', fruit: 'crown', fhue: '#e07a22' }),
  'Fig': T({ hue: '#437642', habit: 'tree', leaf: 'palmate', fruit: 'fig', fhue: '#6a4a6e' }),
  'Wild Fig': T({ hue: '#5e7c52', habit: 'tree', leaf: 'palmate', fruit: 'fig', fhue: '#5d4260' }),
  'Olive': T({ hue: '#9aa478', habit: 'tree', leaf: 'lance', fruit: 'drupe', fhue: '#4a5a34' }),
  'Pomegranate': T({ hue: '#76983f', habit: 'tree', leaf: 'lance', fruit: 'crown', fhue: '#c0353a' }),
  'Papaya': T({ hue: '#6ba14a', habit: 'palm', leaf: 'palmate', fruit: 'melon', fhue: '#d98a2b' }),
  'Mountain Papaya': T({ hue: '#58906f', habit: 'palm', leaf: 'palmate', fruit: 'melon', fhue: '#c8a02b' }),
  'Mango': T({ hue: '#2b5c24', habit: 'tree', leaf: 'lance', fruit: 'pear', fhue: '#d9962b' }),
  'Wild Mango': T({ hue: '#336b2d', habit: 'tree', leaf: 'lance', fruit: 'pear', fhue: '#b8862b' }),
  'Guava': T({ hue: '#5c8545', habit: 'tree', leaf: 'broad', fruit: 'pome', fhue: '#a8b054' }),
  'Wild Guava': T({ hue: '#718353', habit: 'shrub', leaf: 'broad', fruit: 'pome', fhue: '#94a04c' }),
  'Avocado': T({ hue: '#31653c', habit: 'tree', leaf: 'broad', fruit: 'pear', fhue: '#3e5230' }),
  'Lychee': T({ hue: '#2a5a3b', habit: 'tree', leaf: 'pinnate', fruit: 'cluster', fhue: '#c43a2c' }),
  'Rambutan': T({ hue: '#355536', habit: 'tree', leaf: 'pinnate', fruit: 'hairy', fhue: '#c43a2c' }),
  'Mangosteen': T({ hue: '#1f4d2c', habit: 'tree', leaf: 'broad', fruit: 'pome', fhue: '#54263c' }),
  'Durian': T({ hue: '#3b5b2a', habit: 'tree', leaf: 'broad', fruit: 'spiky', fhue: '#9a8a3a', thorns: true }),
  'Jackfruit': T({ hue: '#2c5029', habit: 'tree', leaf: 'broad', fruit: 'melon', fhue: '#9a8a34' }),
  'Breadfruit': T({ hue: '#276b45', habit: 'tree', leaf: 'palmate', fruit: 'melon', fhue: '#7a8a44' }),
  'Breadnut': T({ hue: '#35754a', habit: 'tree', leaf: 'palmate', fruit: 'nut', fhue: '#7a6a44' }),
  'Soursop': T({ hue: '#1f5437', habit: 'tree', leaf: 'broad', fruit: 'melon', fhue: '#5a7a44' }),
  'Starfruit': T({ hue: '#779d4d', habit: 'tree', leaf: 'pinnate', fruit: 'star', fhue: '#d0c044' }),
  'Jujube': T({ hue: '#86a83c', habit: 'tree', leaf: 'broad', fruit: 'drupe', fhue: '#8a3a2c' }),
  'Tamarind': T({ hue: '#7ba85e', habit: 'tree', leaf: 'pinnate', fruit: 'pod', fhue: '#7a5230' }),
  'Carob': T({ hue: '#355a42', habit: 'tree', leaf: 'pinnate', fruit: 'pod', fhue: '#5a3a24' }),
  'Mesquite': T({ hue: '#869567', habit: 'tree', leaf: 'pinnate', fruit: 'pod', fhue: '#8a7040', thorns: true }),
  'Marula': T({ hue: '#4f7a4a', habit: 'tree', leaf: 'pinnate', fruit: 'drupe', fhue: '#c8b04a' }),
  'Neem': T({ hue: '#559339', habit: 'tree', leaf: 'pinnate', fruit: 'drupe', fhue: '#9aa84a' }),
  'Curry Leaf': T({ hue: '#2d7137', habit: 'shrub', leaf: 'pinnate', fruit: 'berry', fhue: '#2c2c2c' }),
  'Sea Buckthorn': T({ hue: '#b3b7a5', habit: 'shrub', leaf: 'lance', fruit: 'cluster', fhue: '#e09a20', thorns: true }),
  'Sea Grape': T({ hue: '#5c8a58', habit: 'shrub', leaf: 'broad', fruit: 'cluster', fhue: '#7a3a5a' }),
  /* ── CITRUS ── */
  'Orange': T({ hue: '#26692f', habit: 'tree', leaf: 'broad', fruit: 'citrus', fhue: '#e0821f' }),
  'Lemon': T({ hue: '#448438', habit: 'tree', leaf: 'broad', fruit: 'citrus', fhue: '#ddc72c' }),
  'Lime': T({ hue: '#4e9b45', habit: 'tree', leaf: 'broad', fruit: 'citrus', fhue: '#8fb52c' }),
  /* ── NUT AND SPICE TREES ── */
  'Chestnut': T({ hue: '#557c30', habit: 'tree', leaf: 'lance', fruit: 'spiky', fhue: '#7a8a3a' }),
  'Walnut': T({ hue: '#466d2d', habit: 'tree', leaf: 'pinnate', fruit: 'nut', fhue: '#5c4028' }),
  'Hazelnut': T({ hue: '#5c7940', habit: 'shrub', leaf: 'heart', fruit: 'nut', flower: 'catkin', fhue: '#8a6a3a' }),
  'Brazil Nut': T({ hue: '#1f6138', habit: 'tree', leaf: 'broad', fruit: 'nut', fhue: '#4e3820', tall: true }),
  'Cashew': T({ hue: '#607335', habit: 'tree', leaf: 'broad', fruit: 'pear', fhue: '#d9a02b' }),
  'Cacao': T({ hue: '#205b2c', habit: 'tree', leaf: 'broad', fruit: 'pod', fhue: '#8a4a24' }),
  'Coffee': T({ hue: '#145730', habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#a8302c' }),
  /* the bark IS the spice — it had been rendering grass-green */
  'Cinnamon': T({ hue: '#3d6948', habit: 'tree', leaf: 'lance', fruit: 'berry', fhue: '#8a5a34', bark: '#a1552a' }),
  'Clove': T({ hue: '#2a5e48', habit: 'tree', leaf: 'lance', flower: 'spike', fhue: '#7a4a2c' }),
  'Nutmeg': T({ hue: '#264f41', habit: 'tree', leaf: 'broad', fruit: 'drupe', fhue: '#c8a860' }),
  'Camphor Tree': T({ hue: '#568e4d', habit: 'tree', leaf: 'broad', fruit: 'berry', fhue: '#2c3a2c' }),
  'Tea Tree': T({ hue: '#8d9a84', habit: 'shrub', leaf: 'needle', flower: 'head', fhue: '#e8e4d0', dense: true }),
  'Tea': T({ hue: '#1d6245', habit: 'shrub', leaf: 'broad', flower: 'head', fhue: '#f0ecd8', dense: true }),
  'Yerba Mate': T({ hue: '#32694f', habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#a02c2c' }),
  'Eucalyptus': T({ hue: '#8aa79b', habit: 'tree', leaf: 'lance', flower: 'head', fhue: '#e0e0d0', tall: true }),
  'Yew': T({ hue: '#1c3a26', habit: 'tree', leaf: 'needle', fruit: 'berry', fhue: '#c02c2c' }),
  'Cedar': T({ hue: '#2c4636', habit: 'tree', leaf: 'needle', fruit: 'cone', tall: true }),
  'Redwood': T({ hue: '#334c40', habit: 'tree', leaf: 'needle', fruit: 'cone', tall: true }),
  'Oak': T({ hue: '#526a31', habit: 'tree', leaf: 'palmate', fruit: 'nut', fhue: '#8a6a3a' }),
  'Acorn': T({ hue: '#577127', habit: 'tree', leaf: 'palmate', fruit: 'nut', fhue: '#8a6a3a' }),
  'Hemlock': T({ hue: '#3a4935', habit: 'tree', leaf: 'needle', fruit: 'cone', tall: true }),
  'Pinyon Pine': T({ hue: '#5e7f5f', habit: 'tree', leaf: 'needle', fruit: 'cone' }),
  'Pine Nuts': T({ hue: '#4f7059', habit: 'tree', leaf: 'needle', fruit: 'cone' }),
  'Spruce Tips': T({ hue: '#729a8d', habit: 'tree', leaf: 'needle', fruit: 'cone', tall: true }),
  'Juniper': T({ hue: '#405d4c', habit: 'shrub', leaf: 'scale', fruit: 'berry', fhue: '#5a6a8a' }),
  'Juniper Berries': T({ hue: '#5d7d74', habit: 'shrub', leaf: 'scale', fruit: 'berry', fhue: '#4a5a7a' }),
  'Willow': T({ hue: '#849c4e', habit: 'tree', leaf: 'lance', flower: 'catkin', fhue: '#d8d0a0' }),
  'Arctic Willow': T({ hue: '#83947a', habit: 'shrub', leaf: 'lance', flower: 'catkin', fhue: '#d0c898' }),
  'Birch Sap': T({ hue: '#8bb04a', habit: 'tree', leaf: 'heart', flower: 'catkin', fhue: '#c8c090' }),
  'Maple Sap': T({ hue: '#6f8b33', habit: 'tree', leaf: 'palmate', fruit: 'pod', fhue: '#a8763a' }),
  'Baobab': T({ hue: '#698c4e', habit: 'tree', leaf: 'palmate', fruit: 'melon', fhue: '#9a8a5a' }),
  'Acacia': T({ hue: '#9fa891', habit: 'tree', leaf: 'pinnate', flower: 'head', fhue: '#e0c840', thorns: true }),
  'Tamarisk': T({ hue: '#93a2ab', habit: 'shrub', leaf: 'needle', flower: 'spike', fhue: '#d09ab8', dense: true }),
  'Mangrove Leaves': T({ hue: '#296e57', habit: 'tree', leaf: 'broad', fruit: 'pod', fhue: '#6a7a4a' }),
  'Water Hemlock': T({ hue: '#639745', habit: 'herb', leaf: 'pinnate', flower: 'umbel', fhue: '#eef0e0' }),
  'Oleander': T({ hue: '#3f6d5b', habit: 'shrub', leaf: 'lance', flower: 'head', fhue: '#e07a9a' }),
  'Calotropis': T({ hue: '#aeb28e', habit: 'shrub', leaf: 'broad', flower: 'star', fhue: '#c8b8e0' }),
  'Bay Laurel': T({ hue: '#28432a', habit: 'shrub', leaf: 'lance', fruit: 'berry', fhue: '#2c2c3a', dense: true }),
  /* ── PALMS AND TROPICAL MONOCOTS ── */
  'Coconut': T({ hue: '#48854a', habit: 'palm', leaf: 'frond', fruit: 'melon', fhue: '#7a6042', tall: true }),
  'Date Palm': T({ hue: '#819f81', habit: 'palm', leaf: 'frond', fruit: 'cluster', fhue: '#8a5a2c', tall: true }),
  'Date': T({ hue: '#6e8a72', habit: 'palm', leaf: 'frond', fruit: 'cluster', fhue: '#7a4a26', tall: true }),
  'Date Plum': T({ hue: '#437735', habit: 'tree', leaf: 'broad', fruit: 'drupe', fhue: '#9a6a3a' }),
  'Nipa Palm Fruit': T({ hue: '#43855a', habit: 'palm', leaf: 'frond', fruit: 'cluster', fhue: '#8a7a4a' }),
  'Banana': T({ hue: '#63a23e', habit: 'palm', leaf: 'broad', fruit: 'cluster', fhue: '#d8c440', pseudostem: true }),
  'Plantain': T({ hue: '#4a8e3e', habit: 'palm', leaf: 'broad', fruit: 'cluster', fhue: '#c8b84a', pseudostem: true }),
  'Pandanus Fruit': T({ hue: '#649279', habit: 'palm', leaf: 'blade', fruit: 'melon', fhue: '#d07a2c' }),
  'Rattan': T({ hue: '#528353', habit: 'vine', leaf: 'frond', thorns: true }),
  'Bromeliad': T({ hue: '#8e9b77', habit: 'rosette', leaf: 'blade', flower: 'spike', fhue: '#d0342c' }),
  'Air Plant': T({ hue: '#bcc2bd', habit: 'rosette', leaf: 'blade', flower: 'spike', fhue: '#a86ac8' }),
  'Canopy Vine': T({ hue: '#377d3f', habit: 'vine', leaf: 'heart' }),
  'Ivy': T({ hue: '#1f4738', habit: 'vine', leaf: 'palmate' }),
  'Beach Morning Glory': T({ hue: '#519358', habit: 'vine', leaf: 'heart', flower: 'bell', fhue: '#c07ad0' }),
  'Passionflower': T({ hue: '#49924d', habit: 'vine', leaf: 'palmate', flower: 'star', fhue: '#b07ad8' }),
  'Passionfruit': T({ hue: '#397f32', habit: 'vine', leaf: 'palmate', fruit: 'pome', fhue: '#6a3a5a' }),
  'Grape': T({ hue: '#76863d', habit: 'vine', leaf: 'palmate', fruit: 'cluster', fhue: '#5a3a7a' }),
  'Red Grape': T({ hue: '#8f5238', habit: 'vine', leaf: 'palmate', fruit: 'cluster', fhue: '#7a2c44' }),
  'White Grape': T({ hue: '#9aa84a', habit: 'vine', leaf: 'palmate', fruit: 'cluster', fhue: '#c8cc7a' }),
  'Black Grape': T({ hue: '#4e5935', habit: 'vine', leaf: 'palmate', fruit: 'cluster', fhue: '#3a2444' }),
  /* ── BERRY SHRUBS ── */
  'Blackberry': T({ hue: '#3c752a', habit: 'shrub', leaf: 'pinnate', fruit: 'cluster', fhue: '#2c1c30', thorns: true }),
  'Raspberry': T({ hue: '#7a9462', habit: 'shrub', leaf: 'pinnate', fruit: 'cluster', fhue: '#b02c44', thorns: true }),
  'Mulberry': T({ hue: '#78a541', habit: 'tree', leaf: 'heart', fruit: 'cluster', fhue: '#40203a' }),
  'Elderberry': T({ hue: '#4b6b35', habit: 'shrub', leaf: 'pinnate', fruit: 'cluster', fhue: '#2c2440' }),
  'Blueberry': T({ hue: '#507855', habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#3a4a80' }),
  'Wild Blueberry': T({ hue: '#5b804e', habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#34446e' }),
  'Mountain Blueberry': T({ hue: '#5a7566', habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#3e5090' }),
  'Arctic Blueberry': T({ hue: '#717851', habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#44548a' }),
  'Bilberry': T({ hue: '#608743', habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#38406e' }),
  'Huckleberry': T({ hue: '#48613c', habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#3a2c48', creep: true }),
  'Lingonberry': T({ hue: '#2c5433', habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#b02c30', creep: true }),
  'Cranberry': T({ hue: '#3f5841', habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#a8232c', creep: true }),
  'Mountain Cranberry': T({ hue: '#425e51', habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#9c2028', creep: true }),
  'Cloudberry': T({ hue: '#6c8d56', habit: 'herb', leaf: 'palmate', fruit: 'cluster', fhue: '#e0a040' }),
  'Crowberry': T({ hue: '#2b4831', habit: 'shrub', leaf: 'needle', fruit: 'berry', fhue: '#20202c', creep: true }),
  'Bearberry': T({ hue: '#416346', habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#b03028', creep: true }),
  'Serviceberry': T({ hue: '#6b876c', habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#5a2c48' }),
  'Gooseberry': T({ hue: '#699448', habit: 'shrub', leaf: 'palmate', fruit: 'berry', fhue: '#8aa040', thorns: true }),
  'Indian Gooseberry': T({ hue: '#80a056', habit: 'tree', leaf: 'pinnate', fruit: 'berry', fhue: '#9ab048' }),
  'Currant': T({ hue: '#56803f', habit: 'shrub', leaf: 'palmate', fruit: 'cluster', fhue: '#8a1c2c' }),
  'Rose Hip': T({ hue: '#43773b', habit: 'shrub', leaf: 'pinnate', fruit: 'pome', fhue: '#c03428', thorns: true }),
  'Cliff Rose': T({ hue: '#899279', habit: 'shrub', leaf: 'pinnate', flower: 'head', fhue: '#f0e8d0' }),
  'Desert Rose': T({ hue: '#30604e', habit: 'succulent', leaf: 'broad', flower: 'head', fhue: '#d8506a' }),
  'Heather': T({ hue: '#4c5944', habit: 'shrub', leaf: 'needle', flower: 'spike', fhue: '#c07ab0' }),
  'Bog Myrtle': T({ hue: '#6c7d64', habit: 'shrub', leaf: 'lance', flower: 'catkin', fhue: '#a89050' }),
  'Sagebrush': T({ hue: '#9ba797', habit: 'shrub', leaf: 'lance', flower: 'spike', fhue: '#b8b490', dense: true }),
  'Desert Sage': T({ hue: '#aeb3a4', habit: 'shrub', leaf: 'lance', flower: 'spike', fhue: '#9aa8c0', dense: true }),
  'Coastal Sage': T({ hue: '#909a87', habit: 'shrub', leaf: 'lance', flower: 'spike', fhue: '#a8b0b8', dense: true }),
  'Sage': T({ hue: '#9db583', habit: 'shrub', leaf: 'broad', flower: 'spike', fhue: '#9aa4c8', dense: true }),
  'Saltbush': T({ hue: '#91a3a1', habit: 'shrub', leaf: 'broad', fhue: '#a8b0a0' }),
  'Creosote Bush': T({ hue: '#606e42', habit: 'shrub', leaf: 'pinnate', flower: 'head', fhue: '#d8c840' }),
  'Rabbitbrush': T({ hue: '#a8aa8f', habit: 'shrub', leaf: 'lance', flower: 'head', fhue: '#d8c440' }),
  'Ephedra': T({ hue: '#899c4d', habit: 'shrub', leaf: 'needle', fruit: 'berry', fhue: '#c04030' }),
  'Mormon Tea': T({ hue: '#9aa66f', habit: 'shrub', leaf: 'needle', fruit: 'berry', fhue: '#b83c30' }),
  'Labrador Tea': T({ hue: '#4c6649', habit: 'shrub', leaf: 'lance', flower: 'umbel', fhue: '#f0ece0' }),
  'Bog Rosemary': T({ hue: '#7d8f8f', habit: 'shrub', leaf: 'needle', flower: 'bell', fhue: '#e0b0c0' }),
  'Marsh Rosemary': T({ hue: '#849885', habit: 'shrub', leaf: 'needle', flower: 'bell', fhue: '#d0a8c0' }),
  'Sea Lavender': T({ hue: '#9fa8a8', habit: 'herb', leaf: 'lance', flower: 'umbel', fhue: '#a890d0', leafArr: 'basal' }),
  /* ── GRASSES AND GRAINS ── */
  'Wheat': T({ hue: '#c9a94e', habit: 'grass', leaf: 'blade', fruit: 'grain', fhue: '#d8bc60' }),
  'Barley': T({ hue: '#d4b96a', habit: 'grass', leaf: 'blade', fruit: 'grain', fhue: '#d0b458' }),
  'Rye': T({ hue: '#b9a468', habit: 'grass', leaf: 'blade', fruit: 'grain', fhue: '#c8ac50' }),
  'Wild Rye': T({ hue: '#889f70', habit: 'grass', leaf: 'blade', fruit: 'grain', fhue: '#c0a44c' }),
  'Oats': T({ hue: '#dcc481', habit: 'grass', leaf: 'blade', fruit: 'panicle', fhue: '#dcc46c' }),
  'Rice': T({ hue: '#7fa63c', habit: 'grass', leaf: 'blade', fruit: 'panicle', fhue: '#e0d8b0' }),
  'Wild Rice': T({ hue: '#6b955f', habit: 'grass', leaf: 'blade', fruit: 'grain', fhue: '#584a30' }),
  'Millet': T({ hue: '#b8b055', habit: 'grass', leaf: 'blade', fruit: 'club', fhue: '#d8c058' }),
  'Sorghum': T({ hue: '#a8823f', habit: 'cane', leaf: 'blade', fruit: 'club', fhue: '#b06840', tall: true }),
  'Buckwheat': T({ hue: '#7c914f', habit: 'herb', leaf: 'heart', flower: 'umbel', fhue: '#f0e8e0' }),
  'Amaranth': T({ hue: '#8c3f4a', habit: 'herb', leaf: 'broad', flower: 'spike', fhue: '#a82c50' }),
  'Quinoa': T({ hue: '#8e9251', habit: 'herb', leaf: 'palmate', flower: 'spike', fhue: '#c04a3a' }),
  'Bamboo Shoots': T({ hue: '#c2c07a', habit: 'cane', leaf: 'lance', tall: true }),
  'Papyrus': T({ hue: '#9c9053', habit: 'cane', leaf: 'frond', tall: true }),
  'Papyrus Shoots': T({ hue: '#819746', habit: 'cane', leaf: 'frond' }),
  'Tussock Grass': T({ hue: '#a58a5a', habit: 'grass', leaf: 'blade' }),
  'Meadow Grass': T({ hue: '#6fa545', habit: 'grass', leaf: 'blade', flower: 'spike', fhue: '#c8c090' }),
  'Saltgrass': T({ hue: '#89ac92', habit: 'grass', leaf: 'blade' }),
  'Scurvy Grass': T({ hue: '#5aa15e', habit: 'rosette', leaf: 'heart', flower: 'umbel', fhue: '#f0f0e8' }),
  'Cattail': T({ hue: '#74805a', habit: 'cane', leaf: 'blade', flower: 'spike', fhue: '#5a4028', tall: true }),
  'Sweet Flag': T({ hue: '#8aa84a', habit: 'cane', leaf: 'blade', flower: 'spike', fhue: '#9a9a50' }),
  'Rush Shoots': T({ hue: '#4f7a61', habit: 'grass', leaf: 'blade' }),
  /* ★ WAVE 58 — LEGUMES get the trifoliate (three-leaflet) leaf. */
  'Alfalfa': T({ hue: '#558953', habit: 'herb', leaf: 'trefoil', flower: 'spike', fhue: '#8a6ac0', leafArr: 'alternate' }),
  'Clover': T({ hue: '#4e9a4b', habit: 'rosette', leaf: 'trefoil', flower: 'head', fhue: '#e0b0c8' }),
  /* ── CROPS AND ROOTS ── */
  'Potato': T({ hue: '#56743b', habit: 'herb', leaf: 'pinnate', flower: 'star', fhue: '#e8e0f0' }),
  'Sweet Potato': T({ hue: '#3e6738', habit: 'vine', leaf: 'heart', flower: 'bell', fhue: '#c890d8' }),
  'Cassava': T({ hue: '#38612f', habit: 'shrub', leaf: 'palmate', root: 'forked' }),
  'Taro': T({ hue: '#46715a', habit: 'rosette', leaf: 'arrow' }),
  'Wild Taro': T({ hue: '#39574b', habit: 'rosette', leaf: 'arrow' }),
  'Wild Yam': T({ hue: '#4a7f40', habit: 'vine', leaf: 'heart', root: 'rhizome' }),
  'Arrowroot': T({ hue: '#6c9d57', habit: 'rosette', leaf: 'arrow', root: 'rhizome' }),
  'Beet': T({ hue: '#4d5d32', habit: 'rosette', leaf: 'broad', fhue: '#8a2c48' }),
  'Sea Beet': T({ hue: '#415b35', habit: 'rosette', leaf: 'broad' }),
  'Prairie Turnip': T({ hue: '#929a77', habit: 'rosette', leaf: 'palmate', flower: 'spike', fhue: '#a898d0', root: 'taproot' }),
  'Onion': T({ hue: '#6f8f78', habit: 'grass', leaf: 'blade', flower: 'umbel', fhue: '#d8c8e8' }),
  'Wild Onion': T({ hue: '#608957', habit: 'grass', leaf: 'blade', flower: 'umbel', fhue: '#d0c0e0' }),
  'Garlic': T({ hue: '#7b9184', habit: 'grass', leaf: 'blade', flower: 'umbel', fhue: '#e8e0e8' }),
  'Wild Garlic': T({ hue: '#64a24e', habit: 'rosette', leaf: 'lance', flower: 'umbel', fhue: '#e0dce8' }),
  'Wild Chive': T({ hue: '#719790', habit: 'grass', leaf: 'blade', flower: 'head', fhue: '#c8a0d8' }),
  'Sea Kale': T({ hue: '#85a0a1', habit: 'rosette', leaf: 'crinkle', flower: 'umbel', fhue: '#f0f0e8' }),
  'Watercress': T({ hue: '#36734b', habit: 'rosette', leaf: 'pinnate', flower: 'umbel', fhue: '#f0f0e8' }),
  'Brooklime': T({ hue: '#559660', habit: 'herb', leaf: 'broad', flower: 'star', fhue: '#6a90d8' }),
  'Water Spinach': T({ hue: '#6aae53', habit: 'vine', leaf: 'lance', flower: 'bell', fhue: '#e0d0e8' }),
  'Arrowhead': T({ hue: '#4b9556', habit: 'rosette', leaf: 'arrow', flower: 'star', fhue: '#f0f0f0' }),
  'Pickerelweed': T({ hue: '#3f7a53', habit: 'rosette', leaf: 'arrow', flower: 'spike', fhue: '#6a7ad0' }),
  'Cucumber': T({ hue: '#69953c', habit: 'vine', leaf: 'palmate', fruit: 'melon', fhue: '#3a6a30' }),
  'Melon': T({ hue: '#7ca14b', habit: 'vine', leaf: 'palmate', fruit: 'melon', fhue: '#c8c060' }),
  'Wild Melon': T({ hue: '#8a9c64', habit: 'vine', leaf: 'palmate', fruit: 'melon', fhue: '#8aa040' }),
  'Desert Melon': T({ hue: '#9ea67a', habit: 'vine', leaf: 'palmate', fruit: 'melon', fhue: '#a8b050' }),
  'Pigeon Pea': T({ hue: '#667e48', habit: 'shrub', leaf: 'pinnate', fruit: 'pod', fhue: '#8a9a3a' }),
  'Beach Pea': T({ hue: '#7d9b8f', habit: 'vine', leaf: 'pinnate', fruit: 'pod', fhue: '#7a8a4a' }),
  'Peanut': T({ hue: '#5e9342', habit: 'herb', leaf: 'pinnate', fruit: 'nut', fhue: '#c8a870' }),
  'Castor Bean': T({ hue: '#7a4a3c', habit: 'shrub', leaf: 'palmate', fruit: 'pod', fhue: '#a83030', thorns: true }),
  /* ⚠ this was geometrically the SAME asset as Beach Morning Glory, tinted —
     a duplicate the look-alike gate cannot see because colour separates them.
     The pendulous peppercorn spike is the real difference. */
  'Black Pepper': T({ hue: '#2c5f3b', habit: 'vine', leaf: 'lance', fruit: 'cluster', pendulous: true, fhue: '#2f4a30' }),
  'Chili Pepper': T({ hue: '#508235', habit: 'shrub', leaf: 'lance', fruit: 'drupe', fhue: '#c8202c' }),
  'Wild Chili': T({ hue: '#43662d', habit: 'shrub', leaf: 'lance', fruit: 'drupe', fhue: '#b81c28' }),
  /* ★ WAVE 58 — BRASSICAS. Four-petal cross flowers in a corymb + slender
     siliques held out from the stem (see PlantSpec.flower:'cross' / pods). */
  'Wild Mustard': T({ hue: '#7f9b3a', habit: 'herb', leaf: 'broad', flower: 'cross', fhue: '#e8d030', leafArr: 'alternate', toothed: true, pods: true }),
  'Mustard': T({ hue: '#92a642', habit: 'herb', leaf: 'broad', flower: 'cross', fhue: '#e0c828', leafArr: 'alternate', toothed: true, pods: true }),
  'Canola': T({ hue: '#7b996f', habit: 'herb', leaf: 'broad', flower: 'cross', fhue: '#e8d83a', leafArr: 'alternate', toothed: true, pods: true }),
  'Sesame': T({ hue: '#638d64', habit: 'herb', leaf: 'broad', flower: 'bell', fhue: '#e8d0d8', toothed: true, pods: true }),
  'Wild Sesame': T({ hue: '#6b5a63', habit: 'herb', leaf: 'broad', fruit: 'pod', fhue: '#b8a880', toothed: true, leafArr: 'opposite' }),
  'Flax': T({ hue: '#86a4b0', habit: 'herb', leaf: 'lance', flower: 'star', fhue: '#7a9ad8' }),
  'Fenugreek': T({ hue: '#89a85e', habit: 'herb', leaf: 'trefoil', fruit: 'pod', fhue: '#c8b870', leafArr: 'alternate' }),
  'Anise': T({ hue: '#8fb84a', habit: 'herb', leaf: 'pinnate', flower: 'umbel', fhue: '#f0f0e0' }),
  'Star Anise': T({ hue: '#2d5443', habit: 'tree', leaf: 'broad', fruit: 'star', fhue: '#7a5232' }),
  /* ── HERBS ── */
  /* ★ WAVE 58 — THE MINTS ARE A FAMILY, NOT NINE TINTS OF ONE SPIKE. Gold pass
     4 failed every one of them for the same three absent Lamiaceae cues; they
     now carry toothed opposite leaves, a square reddish stem, and flowers in
     whorls up the stem (see PlantSpec.toothed/square/whorl). */
  'Mint': T({ hue: '#4fa05a', habit: 'herb', leaf: 'broad', flower: 'spike', fhue: '#c0a8e0', leafArr: 'opposite', toothed: true, square: true, whorl: true }),
  'Wild Mint': T({ hue: '#579554', habit: 'herb', leaf: 'broad', flower: 'spike', fhue: '#b8a0d8', leafArr: 'opposite', toothed: true, square: true, whorl: true }),
  'Mountain Mint': T({ hue: '#7f987a', habit: 'herb', leaf: 'broad', flower: 'head', fhue: '#e0e0f0', leafArr: 'opposite', toothed: true, square: true, whorl: true, flowerN: 3 }),
  'Alpine Mint': T({ hue: '#92a68e', habit: 'herb', leaf: 'broad', flower: 'spike', fhue: '#d0d0e8', leafArr: 'opposite', toothed: true, square: true, whorl: true, stem: 'mat' }),
  'Swamp Mint': T({ hue: '#387f49', habit: 'herb', leaf: 'broad', flower: 'spike', fhue: '#a8a0d0', leafArr: 'opposite', toothed: true, square: true, whorl: true }),
  'Water Mint': T({ hue: '#3d6a55', habit: 'herb', leaf: 'broad', flower: 'head', fhue: '#b0a8d8', leafArr: 'opposite', toothed: true, square: true, whorl: true, flowerN: 1 }),
  'Desert Mint': T({ hue: '#b0b899', habit: 'herb', leaf: 'broad', flower: 'spike', fhue: '#c8c0e0', leafArr: 'opposite', toothed: true, square: true, whorl: true }),
  'Holy Basil': T({ hue: '#6a4b52', habit: 'herb', leaf: 'broad', flower: 'spike', fhue: '#a890c8', leafArr: 'opposite', toothed: true, square: true, whorl: true }),
  'Thyme': T({ hue: '#7f9167', habit: 'herb', leaf: 'needle', flower: 'head', fhue: '#c090c8' }),
  /* ★ WAVE 22 — thyme is a low WOODY sub-shrub that mats over rock, not an
     erect herb like the mints it kept colliding with. Drawing it as a shrub is
     both the truer plant and what pulls it clear of Water Mint. */
  'Wild Thyme': T({ hue: '#6e8860', habit: 'shrub', leaf: 'needle', flower: 'head', fhue: '#b888c0' }),
  'Mountain Thyme': T({ hue: '#97a383', habit: 'herb', leaf: 'needle', flower: 'head', fhue: '#c8a0d0', stem: 'mat', flowerN: 5 }),
  'Oregano': T({ hue: '#758750', habit: 'herb', leaf: 'broad', flower: 'head', fhue: '#e0d0e8', leafArr: 'opposite', toothed: true, square: true, whorl: true, flowerN: 3 }),
  'Rosemary': T({ hue: '#556d4c', habit: 'shrub', leaf: 'needle', flower: 'spike', fhue: '#90a8d8', dense: true }),
  'Lavender': T({ hue: '#a8af9a', habit: 'shrub', leaf: 'needle', flower: 'spike', fhue: '#9878c8', dense: true }),
  'Fennel': T({ hue: '#a3bc4f', habit: 'herb', leaf: 'pinnate', flower: 'umbel', fhue: '#e0d840' }),
  'Sea Fennel': T({ hue: '#8fb188', habit: 'herb', leaf: 'pinnate', flower: 'umbel', fhue: '#d0d048' }),
  /* ★ WAVE 58 — NETTLES: toothed heart leaves in opposite pairs + drooping
     green axil tassels (PlantSpec.tassel), replacing the terminal bead spike. */
  'Nettle': T({ hue: '#3a6d2e', habit: 'herb', leaf: 'heart', flower: 'none', fhue: '#a8b070', leafArr: 'opposite', toothed: true, tassel: true }),
  'Rainforest Nettle': T({ hue: '#2d5f2f', habit: 'herb', leaf: 'heart', flower: 'none', fhue: '#98a068', leafArr: 'opposite', toothed: true, tassel: true }),
  'Riverbank Nettle': T({ hue: '#4d7634', habit: 'herb', leaf: 'heart', flower: 'none', fhue: '#90a070', leafArr: 'opposite', toothed: true, tassel: true }),
  'Dandelion': T({ hue: '#6e8d35', habit: 'rosette', leaf: 'lance', flower: 'head', fhue: '#e8c828' }),
  'Chicory': T({ hue: '#9dac8b', habit: 'herb', leaf: 'lance', flower: 'head', fhue: '#7a90d8', stem: 'bare', leafArr: 'basal', flowerN: 6 }),
  'Yarrow': T({ hue: '#899f7c', habit: 'herb', leaf: 'pinnate', flower: 'umbel', fhue: '#f0efe4' }),
  /* ★ WAVE 58 — CONEFLOWERS: raised bristly disc-cone + backswept rays (flower:'cone'). */
  'Chamomile': T({ hue: '#7da85e', habit: 'herb', leaf: 'pinnate', flower: 'cone', fhue: '#f4f0dc', leafArr: 'alternate' }),
  'Echinacea': T({ hue: '#52693f', habit: 'herb', leaf: 'lance', flower: 'cone', fhue: '#c87ab0', leafArr: 'alternate' }),
  'Goldenrod': T({ hue: '#627d3d', habit: 'herb', leaf: 'lance', flower: 'spike', fhue: '#e0c430' }),
  'Black-Eyed Susan': T({ hue: '#5b6a37', habit: 'herb', leaf: 'lance', flower: 'cone', fhue: '#e8b820', leafArr: 'alternate' }),
  'Bergamot': T({ hue: '#5d7451', habit: 'herb', leaf: 'broad', flower: 'firework', fhue: '#c85a6a', toothed: true, square: true, leafArr: 'opposite' }),
  'Milkweed': T({ hue: '#7b8c78', habit: 'herb', leaf: 'broad', flower: 'umbel', fhue: '#d8a0b0' }),
  'Wormwood': T({ hue: '#b8baa8', habit: 'herb', leaf: 'pinnate', flower: 'spike', fhue: '#c0c090' }),
  'Mugwort': T({ hue: '#8f8f83', habit: 'herb', leaf: 'palmate', flower: 'spike', fhue: '#b8b898' }),
  'Valerian': T({ hue: '#587746', habit: 'herb', leaf: 'pinnate', flower: 'umbel', fhue: '#f0e0e8', root: 'rhizome' }),
  'Arnica': T({ hue: '#9c9f8d', habit: 'rosette', leaf: 'broad', flower: 'head', fhue: '#e8b830' }),
  'Angelica': T({ hue: '#5d8e4d', habit: 'herb', leaf: 'pinnate', flower: 'umbel', fhue: '#e8ecd8' }),
  'Fireweed': T({ hue: '#5b7c59', habit: 'herb', leaf: 'lance', flower: 'spike', fhue: '#d0509a' }),
  'Ginseng': T({ hue: '#4d7447', habit: 'herb', leaf: 'palmate', fruit: 'cluster', fhue: '#c02c2c', root: 'forked' }),
  'Ginger': T({ hue: '#4e9441', habit: 'rosette', leaf: 'lance', flower: 'spike', fhue: '#e0c060', root: 'rhizome' }),
  'Wild Ginger': T({ hue: '#35563b', habit: 'rosette', leaf: 'heart', flower: 'bell', fhue: '#8a4a4a' }),
  'African Ginger': T({ hue: '#427947', habit: 'rosette', leaf: 'lance', flower: 'spike', fhue: '#d8b858' }),
  'Turmeric': T({ hue: '#72a550', habit: 'rosette', leaf: 'broad', flower: 'spike', fhue: '#e0a828', root: 'rhizome' }),
  'Cardamom': T({ hue: '#2f6a46', habit: 'rosette', leaf: 'lance', fruit: 'pod', fhue: '#a8b850' }),
  'Wood Sorrel': T({ hue: '#8cbe55', habit: 'rosette', leaf: 'palmate', flower: 'star', fhue: '#f0e8b0' }),
  'Sorrel': T({ hue: '#67a13d', habit: 'rosette', leaf: 'lance', flower: 'spike', fhue: '#b04a3a' }),
  'Mountain Sorrel': T({ hue: '#75a269', habit: 'rosette', leaf: 'heart', flower: 'spike', fhue: '#c05a44' }),
  'Alpine Sorrel': T({ hue: '#83a295', habit: 'rosette', leaf: 'heart', flower: 'spike', fhue: '#b85040' }),
  'Arctic Sorrel': T({ hue: '#828e5b', habit: 'rosette', leaf: 'heart', flower: 'spike', fhue: '#a84c40' }),
  'Wild Rhubarb': T({ hue: '#466c40', habit: 'rosette', leaf: 'crinkle', flower: 'spike', fhue: '#c05070' }),
  'Monkshood': T({ hue: '#324b3a', habit: 'herb', leaf: 'palmate', flower: 'bell', fhue: '#4a3a9a' }),
  'Belladonna': T({ hue: '#45513a', habit: 'herb', leaf: 'broad', fruit: 'berry', fhue: '#241c28' }),
  'Buttercup': T({ hue: '#608c38', habit: 'herb', leaf: 'palmate', flower: 'star', fhue: '#f0d020' }),
  'Bitterroot': T({ hue: '#929c94', habit: 'rosette', leaf: 'lance', flower: 'head', fhue: '#e07ab0' }),
  'Glasswort': T({ hue: '#6f9d7b', habit: 'succulent', leaf: 'scale', fhue: '#8aa060' }),
  'Sea Purslane': T({ hue: '#89ab9e', habit: 'succulent', leaf: 'pad', flower: 'star', fhue: '#d890b8' }),
  'Samphire': T({ hue: '#7cae8c', habit: 'succulent', leaf: 'scale', fhue: '#7a9a58' }),
  /* ── SUCCULENTS ── */
  'Aloe': T({ hue: '#7ea376', habit: 'rosette', leaf: 'lance', flower: 'spike', fhue: '#e05a2c' }),
  'Agave': T({ hue: '#96b2a5', habit: 'rosette', leaf: 'lance', flower: 'spike', fhue: '#d8c840', thorns: true }),
  'Yucca': T({ hue: '#799e84', habit: 'rosette', leaf: 'blade', flower: 'bell', fhue: '#f0ece0' }),
  'Prickly Pear': T({ hue: '#8eaa7e', habit: 'succulent', leaf: 'pad', flower: 'head', fhue: '#e8c430', thorns: true }),
  'Barrel Cactus Fruit': T({ hue: '#729650', habit: 'succulent', leaf: 'scale', flower: 'head', fruit: 'berry', fhue: '#e0b028', thorns: true }),
  /* ── FERNS AND NON-VASCULAR ── */
  'Sword Fern': T({ hue: '#316a3b', habit: 'fern', leaf: 'frond' }),
  'Licorice Fern': T({ hue: '#5a9d4b', habit: 'fern', leaf: 'frond' }),
  'Cave Fern': T({ hue: '#244f3b', habit: 'fern', leaf: 'frond' }),
  'Maidenhair Fern': T({ hue: '#9cc784', habit: 'fern', leaf: 'frond' }),
  'Hardy Fern': T({ hue: '#4c7f4c', habit: 'fern', leaf: 'frond' }),
  'Fiddlehead Fern': T({ hue: '#76bb56', habit: 'fern', leaf: 'frond' }),
  'Tree Fern Shoots': T({ hue: '#6b894b', habit: 'fern', leaf: 'frond', tall: true }),
  'Lichen': T({ hue: '#aebfaf', habit: 'rosette', leaf: 'scale' }),
  /* ── AQUATIC ── */
  'Kelp': T({ hue: '#6b5a2c', habit: 'aquatic', leaf: 'blade', tall: true }),
  'Giant Kelp': T({ hue: '#7a5620', habit: 'aquatic', leaf: 'blade', tall: true }),
  'Sugar Kelp': T({ hue: '#8a6a2a', habit: 'aquatic', leaf: 'broad', flowerN: 1 }),
  'Bull Kelp': T({ hue: '#5a4620', habit: 'aquatic', leaf: 'blade', tall: true }),
  'Sargassum': T({ hue: '#9c8949', habit: 'aquatic', leaf: 'lance' }),
  'Bladderwrack': T({ hue: '#87763a', habit: 'aquatic', leaf: 'scale' }),
  'Dulse': T({ hue: '#8c2f33', habit: 'aquatic', leaf: 'broad', flowerN: 4 }),
  'Wakame': T({ hue: '#4a5424', habit: 'aquatic', leaf: 'frond' }),
  'Red Algae': T({ hue: '#74283f', habit: 'aquatic', leaf: 'frond' }),
  'Coralline Algae': T({ hue: '#d19aa4', habit: 'aquatic', leaf: 'scale' }),
  'Sea Grapes Algae': T({ hue: '#5fbf5a', habit: 'aquatic', leaf: 'blade' }),
  'Duckweed': T({ hue: '#a6d24a', habit: 'aquatic', leaf: 'pad' }),
  'Seagrass': T({ hue: '#4d8a5f', habit: 'aquatic', leaf: 'blade' }),
  'Water Lily': T({ hue: '#436f4c', habit: 'aquatic', leaf: 'pad', flower: 'star', fhue: '#f0e0f0' }),
  'Lotus': T({ hue: '#6c9a86', habit: 'aquatic', leaf: 'pad', flower: 'star', fhue: '#f0c0d8' }),
  'Lotus Root': T({ hue: '#5f8a76', habit: 'aquatic', leaf: 'pad', flower: 'star', fhue: '#e8b8d0' }),
  /* ── FLOWERS ── */
  'Sunflower': T({ hue: '#5c8234', habit: 'herb', leaf: 'heart', flower: 'head', fhue: '#e8c020', tall: true }),
  'Poppy': T({ hue: '#88a488', habit: 'herb', leaf: 'pinnate', flower: 'head', fhue: '#d02c2c' }),
  'Violet': T({ hue: '#3a6d42', habit: 'rosette', leaf: 'heart', flower: 'star', fhue: '#7a4ac0' }),
  'Foxglove': T({ hue: '#77886b', habit: 'herb', leaf: 'lance', flower: 'bell', fhue: '#c86ab0' }),
  'Gentian': T({ hue: '#356044', habit: 'herb', leaf: 'lance', flower: 'bell', fhue: '#3a4ac0' }),
  'Edelweiss': T({ hue: '#c3c6b4', habit: 'rosette', leaf: 'lance', flower: 'star', fhue: '#f0f0e8' }),
  'Purple Saxifrage': T({ hue: '#4f6153', habit: 'rosette', leaf: 'scale', flower: 'star', fhue: '#a850c0' }),
  'Steppe Tulip': T({ hue: '#889790', habit: 'herb', leaf: 'blade', flower: 'bell', fhue: '#d83a4a' }),
  'Vanilla Orchid': T({ hue: '#498a52', habit: 'vine', leaf: 'lance', flower: 'star', fhue: '#e8e0b8' }),
  'Orchid Pods': T({ hue: '#598861', habit: 'herb', leaf: 'lance', fruit: 'pod', fhue: '#5a4a2c' }),
  'Roselle': T({ hue: '#8a4438', habit: 'shrub', leaf: 'palmate', flower: 'head', fhue: '#c02c4a' }),
  'Daisy': T({ hue: '#639654', habit: 'herb', leaf: 'lance', flower: 'head', fhue: '#f4f2e8' }),
  /* ★ WAVE 18 — the last of the unrouted flora, each read off its own row */
  "Angel's Trumpet": T({ hue: '#4a6a3c', habit: 'shrub', leaf: 'broad', flower: 'trumpet', fhue: '#f0d8a8', dense: true }),
  'Tree Tomato': T({ hue: '#5e5940', habit: 'tree', leaf: 'heart', fruit: 'berry', fhue: '#c8402a' }),
  "Solomon's Seal": T({ hue: '#6b936b', habit: 'herb', leaf: 'lance', flower: 'bell', fhue: '#f2f4ea', stem: 'arch' }),
  "Miner's Lettuce": T({ hue: '#8fc07e', habit: 'herb', leaf: 'perfoliate', flower: 'star', fhue: '#f4f6ef', leafArr: 'alternate', flowerN: 3 }),
  "Devil's Claw": T({ hue: '#848c70', habit: 'herb', leaf: 'broad', fruit: 'pod', fhue: '#4a3a26' }),
  'Licorice Root': T({ hue: '#6b873f', habit: 'herb', leaf: 'pinnate', flower: 'spike', fhue: '#a9a6d8', root: 'taproot' }),
  'Pampas Herb': T({ hue: '#c2b48a', habit: 'grass', leaf: 'blade', flower: 'catkin', fhue: '#efeade', tall: true }),
  'Plantain Herb': T({ hue: '#698154', habit: 'rosette', leaf: 'lance', flower: 'spike', fhue: '#8f9a6a' }),
  'Sea Rocket': T({ hue: '#9ab39a', habit: 'herb', leaf: 'broad', flower: 'cross', fhue: '#c9b6d8', leafArr: 'alternate', toothed: true, pods: true }),
};
