/* florarost.ts — the wave-11 plant roster.
   Split from floraoverrides2.ts (which holds the painter) purely for size.
   Every key was read out of the catalog, never recalled — and the shadow
   check guarantees none of these re-covers a wave-2 species. */
import { plantBody, type PlantSpec, type PainterF } from './floraoverrides2.js';

const T = (spec: PlantSpec): PainterF => (c, g, p, n) => plantBody(c, g, p, spec, n);

export const FLORA2_SPEC: Record<string, PainterF> = {
  /* ── FRUIT TREES: a canopy carrying its fruit ── */
  'Apple': T({ habit: 'tree', leaf: 'broad', fruit: 'pome', fhue: '#c8342e' }),
  'Crabapple': T({ habit: 'tree', leaf: 'broad', fruit: 'pome', fhue: '#b03a34' }),
  'Pear': T({ habit: 'tree', leaf: 'broad', fruit: 'pome', fhue: '#c9c05a' }),
  'Peach': T({ habit: 'tree', leaf: 'lance', fruit: 'drupe', fhue: '#e0975a' }),
  'Apricot': T({ habit: 'tree', leaf: 'heart', fruit: 'drupe', fhue: '#e0a047' }),
  'Plum': T({ habit: 'tree', leaf: 'broad', fruit: 'drupe', fhue: '#6b3f7a' }),
  'Beach Plum': T({ habit: 'shrub', leaf: 'broad', fruit: 'drupe', fhue: '#5d3a6e' }),
  'Cherry': T({ habit: 'tree', leaf: 'lance', fruit: 'drupe', fhue: '#b8262f' }),
  'Wild Cherry': T({ habit: 'tree', leaf: 'lance', fruit: 'drupe', fhue: '#8e2028' }),
  'Chokecherry': T({ habit: 'shrub', leaf: 'lance', fruit: 'cluster', fhue: '#4a1f2c' }),
  'Persimmon': T({ habit: 'tree', leaf: 'broad', fruit: 'pome', fhue: '#d97722' }),
  'Fig': T({ habit: 'tree', leaf: 'palmate', fruit: 'fig', fhue: '#6a4a6e' }),
  'Wild Fig': T({ habit: 'tree', leaf: 'palmate', fruit: 'fig', fhue: '#5d4260' }),
  'Olive': T({ habit: 'tree', leaf: 'lance', fruit: 'drupe', fhue: '#4a5a34' }),
  'Pomegranate': T({ habit: 'tree', leaf: 'lance', fruit: 'pome', fhue: '#a8232c' }),
  'Papaya': T({ habit: 'palm', leaf: 'palmate', fruit: 'melon', fhue: '#d98a2b' }),
  'Mountain Papaya': T({ habit: 'palm', leaf: 'palmate', fruit: 'melon', fhue: '#c8a02b' }),
  'Mango': T({ habit: 'tree', leaf: 'lance', fruit: 'drupe', fhue: '#d9962b' }),
  'Wild Mango': T({ habit: 'tree', leaf: 'lance', fruit: 'drupe', fhue: '#b8862b' }),
  'Guava': T({ habit: 'tree', leaf: 'broad', fruit: 'pome', fhue: '#a8b054' }),
  'Wild Guava': T({ habit: 'shrub', leaf: 'broad', fruit: 'pome', fhue: '#94a04c' }),
  'Avocado': T({ habit: 'tree', leaf: 'broad', fruit: 'drupe', fhue: '#3e5230' }),
  'Lychee': T({ habit: 'tree', leaf: 'pinnate', fruit: 'cluster', fhue: '#b83a3a' }),
  'Rambutan': T({ habit: 'tree', leaf: 'pinnate', fruit: 'cluster', fhue: '#c43a2c' }),
  'Mangosteen': T({ habit: 'tree', leaf: 'broad', fruit: 'pome', fhue: '#54263c' }),
  'Durian': T({ habit: 'tree', leaf: 'broad', fruit: 'melon', fhue: '#8a7a34', thorns: true }),
  'Jackfruit': T({ habit: 'tree', leaf: 'broad', fruit: 'melon', fhue: '#9a8a34' }),
  'Breadfruit': T({ habit: 'tree', leaf: 'palmate', fruit: 'melon', fhue: '#7a8a44' }),
  'Breadnut': T({ habit: 'tree', leaf: 'palmate', fruit: 'nut', fhue: '#7a6a44' }),
  'Soursop': T({ habit: 'tree', leaf: 'broad', fruit: 'melon', fhue: '#5a7a44' }),
  'Starfruit': T({ habit: 'tree', leaf: 'pinnate', fruit: 'pome', fhue: '#d0c044' }),
  'Jujube': T({ habit: 'tree', leaf: 'broad', fruit: 'drupe', fhue: '#8a3a2c' }),
  'Tamarind': T({ habit: 'tree', leaf: 'pinnate', fruit: 'pod', fhue: '#7a5230' }),
  'Carob': T({ habit: 'tree', leaf: 'pinnate', fruit: 'pod', fhue: '#5a3a24' }),
  'Mesquite': T({ habit: 'tree', leaf: 'pinnate', fruit: 'pod', fhue: '#8a7040', thorns: true }),
  'Marula': T({ habit: 'tree', leaf: 'pinnate', fruit: 'drupe', fhue: '#c8b04a' }),
  'Neem': T({ habit: 'tree', leaf: 'pinnate', fruit: 'drupe', fhue: '#9aa84a' }),
  'Curry Leaf': T({ habit: 'shrub', leaf: 'pinnate', fruit: 'berry', fhue: '#2c2c2c' }),
  'Sea Buckthorn': T({ habit: 'shrub', leaf: 'lance', fruit: 'cluster', fhue: '#e09a20', thorns: true }),
  'Sea Grape': T({ habit: 'shrub', leaf: 'broad', fruit: 'cluster', fhue: '#7a3a5a' }),
  /* ── CITRUS ── */
  'Orange': T({ habit: 'tree', leaf: 'broad', fruit: 'citrus', fhue: '#e0821f' }),
  'Lemon': T({ habit: 'tree', leaf: 'broad', fruit: 'citrus', fhue: '#ddc72c' }),
  'Lime': T({ habit: 'tree', leaf: 'broad', fruit: 'citrus', fhue: '#8fb52c' }),
  /* ── NUT AND SPICE TREES ── */
  'Chestnut': T({ habit: 'tree', leaf: 'lance', fruit: 'nut', fhue: '#6a4526' }),
  'Walnut': T({ habit: 'tree', leaf: 'pinnate', fruit: 'nut', fhue: '#5c4028' }),
  'Hazelnut': T({ habit: 'shrub', leaf: 'heart', fruit: 'nut', flower: 'catkin', fhue: '#8a6a3a' }),
  'Brazil Nut': T({ habit: 'tree', leaf: 'broad', fruit: 'nut', fhue: '#4e3820', tall: true }),
  'Cashew': T({ habit: 'tree', leaf: 'broad', fruit: 'drupe', fhue: '#d9a02b' }),
  'Cacao': T({ habit: 'tree', leaf: 'broad', fruit: 'pod', fhue: '#8a4a24' }),
  'Coffee': T({ habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#a8302c' }),
  'Cinnamon': T({ habit: 'tree', leaf: 'lance', fruit: 'berry', fhue: '#8a5a34' }),
  'Clove': T({ habit: 'tree', leaf: 'lance', flower: 'spike', fhue: '#7a4a2c' }),
  'Nutmeg': T({ habit: 'tree', leaf: 'broad', fruit: 'drupe', fhue: '#c8a860' }),
  'Camphor Tree': T({ habit: 'tree', leaf: 'broad', fruit: 'berry', fhue: '#2c3a2c' }),
  'Tea Tree': T({ habit: 'shrub', leaf: 'needle', flower: 'head', fhue: '#e8e4d0' }),
  'Tea': T({ habit: 'shrub', leaf: 'broad', flower: 'head', fhue: '#f0ecd8' }),
  'Yerba Mate': T({ habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#a02c2c' }),
  'Eucalyptus': T({ habit: 'tree', leaf: 'lance', flower: 'head', fhue: '#e0e0d0', tall: true }),
  'Yew': T({ habit: 'tree', leaf: 'needle', fruit: 'berry', fhue: '#c02c2c' }),
  'Cedar': T({ habit: 'tree', leaf: 'needle', fruit: 'cone', tall: true }),
  'Redwood': T({ habit: 'tree', leaf: 'needle', fruit: 'cone', tall: true }),
  'Oak': T({ habit: 'tree', leaf: 'palmate', fruit: 'nut', fhue: '#8a6a3a' }),
  'Acorn': T({ habit: 'tree', leaf: 'palmate', fruit: 'nut', fhue: '#8a6a3a' }),
  'Hemlock': T({ habit: 'tree', leaf: 'needle', fruit: 'cone', tall: true }),
  'Pinyon Pine': T({ habit: 'tree', leaf: 'needle', fruit: 'cone' }),
  'Pine Nuts': T({ habit: 'tree', leaf: 'needle', fruit: 'cone' }),
  'Spruce Tips': T({ habit: 'tree', leaf: 'needle', fruit: 'cone', tall: true }),
  'Juniper': T({ habit: 'shrub', leaf: 'scale', fruit: 'berry', fhue: '#5a6a8a' }),
  'Juniper Berries': T({ habit: 'shrub', leaf: 'scale', fruit: 'berry', fhue: '#4a5a7a' }),
  'Willow': T({ habit: 'tree', leaf: 'lance', flower: 'catkin', fhue: '#d8d0a0' }),
  'Arctic Willow': T({ habit: 'shrub', leaf: 'lance', flower: 'catkin', fhue: '#d0c898' }),
  'Birch Sap': T({ habit: 'tree', leaf: 'heart', flower: 'catkin', fhue: '#c8c090' }),
  'Maple Sap': T({ habit: 'tree', leaf: 'palmate', fruit: 'pod', fhue: '#a8763a' }),
  'Baobab': T({ habit: 'tree', leaf: 'palmate', fruit: 'melon', fhue: '#9a8a5a' }),
  'Acacia': T({ habit: 'tree', leaf: 'pinnate', flower: 'head', fhue: '#e0c840', thorns: true }),
  'Tamarisk': T({ habit: 'shrub', leaf: 'scale', flower: 'spike', fhue: '#d09ab8' }),
  'Mangrove Leaves': T({ habit: 'tree', leaf: 'broad', fruit: 'pod', fhue: '#6a7a4a' }),
  'Water Hemlock': T({ habit: 'herb', leaf: 'pinnate', flower: 'umbel', fhue: '#eef0e0' }),
  'Oleander': T({ habit: 'shrub', leaf: 'lance', flower: 'head', fhue: '#e07a9a' }),
  'Calotropis': T({ habit: 'shrub', leaf: 'broad', flower: 'star', fhue: '#c8b8e0' }),
  'Bay Laurel': T({ habit: 'shrub', leaf: 'lance', fruit: 'berry', fhue: '#2c2c3a' }),
  /* ── PALMS AND TROPICAL MONOCOTS ── */
  'Coconut': T({ habit: 'palm', leaf: 'frond', fruit: 'melon', fhue: '#7a6042', tall: true }),
  'Date Palm': T({ habit: 'palm', leaf: 'frond', fruit: 'cluster', fhue: '#8a5a2c', tall: true }),
  'Date': T({ habit: 'palm', leaf: 'frond', fruit: 'cluster', fhue: '#7a4a26', tall: true }),
  'Date Plum': T({ habit: 'tree', leaf: 'broad', fruit: 'drupe', fhue: '#9a6a3a' }),
  'Nipa Palm Fruit': T({ habit: 'palm', leaf: 'frond', fruit: 'cluster', fhue: '#8a7a4a' }),
  'Banana': T({ habit: 'palm', leaf: 'frond', fruit: 'cluster', fhue: '#d8c440' }),
  'Plantain': T({ habit: 'palm', leaf: 'frond', fruit: 'cluster', fhue: '#c8b84a' }),
  'Pandanus Fruit': T({ habit: 'palm', leaf: 'blade', fruit: 'melon', fhue: '#d07a2c' }),
  'Rattan': T({ habit: 'vine', leaf: 'frond', thorns: true }),
  'Bromeliad': T({ habit: 'rosette', leaf: 'blade', flower: 'spike', fhue: '#d0342c' }),
  'Air Plant': T({ habit: 'rosette', leaf: 'blade', flower: 'spike', fhue: '#a86ac8' }),
  'Canopy Vine': T({ habit: 'vine', leaf: 'heart' }),
  'Ivy': T({ habit: 'vine', leaf: 'palmate' }),
  'Beach Morning Glory': T({ habit: 'vine', leaf: 'heart', flower: 'bell', fhue: '#c07ad0' }),
  'Passionflower': T({ habit: 'vine', leaf: 'palmate', flower: 'star', fhue: '#b07ad8' }),
  'Passionfruit': T({ habit: 'vine', leaf: 'palmate', fruit: 'pome', fhue: '#6a3a5a' }),
  'Grape': T({ habit: 'vine', leaf: 'palmate', fruit: 'cluster', fhue: '#5a3a7a' }),
  'Red Grape': T({ habit: 'vine', leaf: 'palmate', fruit: 'cluster', fhue: '#7a2c44' }),
  'White Grape': T({ habit: 'vine', leaf: 'palmate', fruit: 'cluster', fhue: '#c8cc7a' }),
  'Black Grape': T({ habit: 'vine', leaf: 'palmate', fruit: 'cluster', fhue: '#3a2444' }),
  'Kiwi Fruit': T({ habit: 'vine', leaf: 'heart', fruit: 'drupe', fhue: '#7a6a3a' }),
  /* ── BERRY SHRUBS ── */
  'Blackberry': T({ habit: 'shrub', leaf: 'pinnate', fruit: 'cluster', fhue: '#2c1c30', thorns: true }),
  'Raspberry': T({ habit: 'shrub', leaf: 'pinnate', fruit: 'cluster', fhue: '#b02c44', thorns: true }),
  'Mulberry': T({ habit: 'tree', leaf: 'heart', fruit: 'cluster', fhue: '#40203a' }),
  'Elderberry': T({ habit: 'shrub', leaf: 'pinnate', fruit: 'cluster', fhue: '#2c2440' }),
  'Blueberry': T({ habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#3a4a80' }),
  'Wild Blueberry': T({ habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#34446e' }),
  'Mountain Blueberry': T({ habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#3e5090' }),
  'Arctic Blueberry': T({ habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#44548a' }),
  'Bilberry': T({ habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#38406e' }),
  'Huckleberry': T({ habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#3a2c48' }),
  'Lingonberry': T({ habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#b02c30' }),
  'Cranberry': T({ habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#a8232c' }),
  'Mountain Cranberry': T({ habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#9c2028' }),
  'Cloudberry': T({ habit: 'herb', leaf: 'palmate', fruit: 'cluster', fhue: '#e0a040' }),
  'Crowberry': T({ habit: 'shrub', leaf: 'needle', fruit: 'berry', fhue: '#20202c' }),
  'Bearberry': T({ habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#b03028' }),
  'Serviceberry': T({ habit: 'shrub', leaf: 'broad', fruit: 'berry', fhue: '#5a2c48' }),
  'Gooseberry': T({ habit: 'shrub', leaf: 'palmate', fruit: 'berry', fhue: '#8aa040', thorns: true }),
  'Indian Gooseberry': T({ habit: 'tree', leaf: 'pinnate', fruit: 'berry', fhue: '#9ab048' }),
  'Currant': T({ habit: 'shrub', leaf: 'palmate', fruit: 'cluster', fhue: '#8a1c2c' }),
  'Wild Strawberry': T({ habit: 'rosette', leaf: 'pinnate', fruit: 'drupe', fhue: '#c02c30' }),
  'Rose Hip': T({ habit: 'shrub', leaf: 'pinnate', fruit: 'pome', fhue: '#c03428', thorns: true }),
  'Cliff Rose': T({ habit: 'shrub', leaf: 'pinnate', flower: 'head', fhue: '#f0e8d0' }),
  'Desert Rose': T({ habit: 'succulent', leaf: 'broad', flower: 'head', fhue: '#d8506a' }),
  'Heather': T({ habit: 'shrub', leaf: 'needle', flower: 'spike', fhue: '#c07ab0' }),
  'Bog Myrtle': T({ habit: 'shrub', leaf: 'lance', flower: 'catkin', fhue: '#a89050' }),
  'Sagebrush': T({ habit: 'shrub', leaf: 'lance', flower: 'spike', fhue: '#b8b490' }),
  'Desert Sage': T({ habit: 'shrub', leaf: 'lance', flower: 'spike', fhue: '#9aa8c0' }),
  'Coastal Sage': T({ habit: 'shrub', leaf: 'lance', flower: 'spike', fhue: '#a8b0b8' }),
  'Sage': T({ habit: 'shrub', leaf: 'lance', flower: 'spike', fhue: '#9aa4c8' }),
  'Saltbush': T({ habit: 'shrub', leaf: 'broad', fhue: '#a8b0a0' }),
  'Creosote Bush': T({ habit: 'shrub', leaf: 'pinnate', flower: 'head', fhue: '#d8c840' }),
  'Rabbitbrush': T({ habit: 'shrub', leaf: 'lance', flower: 'head', fhue: '#d8c440' }),
  'Ephedra': T({ habit: 'shrub', leaf: 'needle', fruit: 'berry', fhue: '#c04030' }),
  'Mormon Tea': T({ habit: 'shrub', leaf: 'needle', fruit: 'berry', fhue: '#b83c30' }),
  'Labrador Tea': T({ habit: 'shrub', leaf: 'lance', flower: 'umbel', fhue: '#f0ece0' }),
  'Bog Rosemary': T({ habit: 'shrub', leaf: 'needle', flower: 'bell', fhue: '#e0b0c0' }),
  'Marsh Rosemary': T({ habit: 'shrub', leaf: 'needle', flower: 'bell', fhue: '#d0a8c0' }),
  'Sea Lavender': T({ habit: 'herb', leaf: 'lance', flower: 'umbel', fhue: '#a890d0' }),
  /* ── GRASSES AND GRAINS ── */
  'Wheat': T({ habit: 'grass', leaf: 'blade', fruit: 'grain', fhue: '#d8bc60' }),
  'Barley': T({ habit: 'grass', leaf: 'blade', fruit: 'grain', fhue: '#d0b458' }),
  'Rye': T({ habit: 'grass', leaf: 'blade', fruit: 'grain', fhue: '#c8ac50' }),
  'Wild Rye': T({ habit: 'grass', leaf: 'blade', fruit: 'grain', fhue: '#c0a44c' }),
  'Oats': T({ habit: 'grass', leaf: 'blade', fruit: 'grain', fhue: '#dcc46c' }),
  'Rice': T({ habit: 'grass', leaf: 'blade', fruit: 'grain', fhue: '#e0d8b0' }),
  'Wild Rice': T({ habit: 'grass', leaf: 'blade', fruit: 'grain', fhue: '#584a30' }),
  'Millet': T({ habit: 'grass', leaf: 'blade', fruit: 'grain', fhue: '#d8c058' }),
  'Sorghum': T({ habit: 'grass', leaf: 'blade', fruit: 'grain', fhue: '#b06840' }),
  'Corn': T({ habit: 'cane', leaf: 'blade', fruit: 'grain', fhue: '#e8c840', tall: true }),
  'Buckwheat': T({ habit: 'herb', leaf: 'heart', flower: 'umbel', fhue: '#f0e8e0' }),
  'Amaranth': T({ habit: 'herb', leaf: 'broad', flower: 'spike', fhue: '#a82c50' }),
  'Quinoa': T({ habit: 'herb', leaf: 'palmate', flower: 'spike', fhue: '#c04a3a' }),
  'Bamboo Shoots': T({ habit: 'cane', leaf: 'lance', tall: true }),
  'Papyrus': T({ habit: 'cane', leaf: 'frond', tall: true }),
  'Papyrus Shoots': T({ habit: 'cane', leaf: 'frond' }),
  'Tussock Grass': T({ habit: 'grass', leaf: 'blade' }),
  'Meadow Grass': T({ habit: 'grass', leaf: 'blade', flower: 'spike', fhue: '#c8c090' }),
  'Saltgrass': T({ habit: 'grass', leaf: 'blade' }),
  'Scurvy Grass': T({ habit: 'rosette', leaf: 'heart', flower: 'umbel', fhue: '#f0f0e8' }),
  'Cattail': T({ habit: 'cane', leaf: 'blade', flower: 'spike', fhue: '#5a4028', tall: true }),
  'Sweet Flag': T({ habit: 'cane', leaf: 'blade', flower: 'spike', fhue: '#9a9a50' }),
  'Rush Shoots': T({ habit: 'grass', leaf: 'blade' }),
  'Alfalfa': T({ habit: 'herb', leaf: 'pinnate', flower: 'spike', fhue: '#8a6ac0' }),
  'Clover': T({ habit: 'rosette', leaf: 'palmate', flower: 'head', fhue: '#e0b0c8' }),
  /* ── CROPS AND ROOTS ── */
  'Potato': T({ habit: 'herb', leaf: 'pinnate', flower: 'star', fhue: '#e8e0f0' }),
  'Sweet Potato': T({ habit: 'vine', leaf: 'heart', flower: 'bell', fhue: '#c890d8' }),
  'Cassava': T({ habit: 'shrub', leaf: 'palmate' }),
  'Taro': T({ habit: 'rosette', leaf: 'heart' }),
  'Wild Taro': T({ habit: 'rosette', leaf: 'heart' }),
  'Wild Yam': T({ habit: 'vine', leaf: 'heart' }),
  'Arrowroot': T({ habit: 'rosette', leaf: 'broad' }),
  'Carrot': T({ habit: 'rosette', leaf: 'pinnate', flower: 'umbel', fhue: '#f0f0e0' }),
  'Beet': T({ habit: 'rosette', leaf: 'broad', fhue: '#8a2c48' }),
  'Sea Beet': T({ habit: 'rosette', leaf: 'broad' }),
  'Prairie Turnip': T({ habit: 'rosette', leaf: 'palmate', flower: 'spike', fhue: '#a898d0' }),
  'Onion': T({ habit: 'grass', leaf: 'blade', flower: 'umbel', fhue: '#d8c8e8' }),
  'Wild Onion': T({ habit: 'grass', leaf: 'blade', flower: 'umbel', fhue: '#d0c0e0' }),
  'Garlic': T({ habit: 'grass', leaf: 'blade', flower: 'umbel', fhue: '#e8e0e8' }),
  'Wild Garlic': T({ habit: 'grass', leaf: 'blade', flower: 'umbel', fhue: '#e0dce8' }),
  'Wild Chive': T({ habit: 'grass', leaf: 'blade', flower: 'head', fhue: '#c8a0d8' }),
  'Sea Kale': T({ habit: 'rosette', leaf: 'broad', flower: 'umbel', fhue: '#f0f0e8' }),
  'Sea Lettuce': T({ habit: 'aquatic', leaf: 'broad' }),
  'Watercress': T({ habit: 'rosette', leaf: 'pinnate', flower: 'umbel', fhue: '#f0f0e8' }),
  'Brooklime': T({ habit: 'herb', leaf: 'broad', flower: 'star', fhue: '#6a90d8' }),
  'Water Spinach': T({ habit: 'vine', leaf: 'lance', flower: 'bell', fhue: '#e0d0e8' }),
  'Arrowhead': T({ habit: 'rosette', leaf: 'heart', flower: 'star', fhue: '#f0f0f0' }),
  'Pickerelweed': T({ habit: 'rosette', leaf: 'heart', flower: 'spike', fhue: '#6a7ad0' }),
  'Cucumber': T({ habit: 'vine', leaf: 'palmate', fruit: 'melon', fhue: '#3a6a30' }),
  'Melon': T({ habit: 'vine', leaf: 'palmate', fruit: 'melon', fhue: '#c8c060' }),
  'Wild Melon': T({ habit: 'vine', leaf: 'palmate', fruit: 'melon', fhue: '#8aa040' }),
  'Desert Melon': T({ habit: 'vine', leaf: 'palmate', fruit: 'melon', fhue: '#a8b050' }),
  'Watermelon': T({ habit: 'vine', leaf: 'palmate', fruit: 'melon', fhue: '#2c6a34' }),
  'Pigeon Pea': T({ habit: 'shrub', leaf: 'pinnate', fruit: 'pod', fhue: '#8a9a3a' }),
  'Beach Pea': T({ habit: 'vine', leaf: 'pinnate', fruit: 'pod', fhue: '#7a8a4a' }),
  'Peanut': T({ habit: 'herb', leaf: 'pinnate', fruit: 'nut', fhue: '#c8a870' }),
  'Castor Bean': T({ habit: 'shrub', leaf: 'palmate', fruit: 'pod', fhue: '#a83030', thorns: true }),
  'Black Pepper': T({ habit: 'vine', leaf: 'heart', fruit: 'cluster', fhue: '#3a2c24' }),
  'Chili Pepper': T({ habit: 'shrub', leaf: 'lance', fruit: 'drupe', fhue: '#c8202c' }),
  'Wild Chili': T({ habit: 'shrub', leaf: 'lance', fruit: 'drupe', fhue: '#b81c28' }),
  'Wild Mustard': T({ habit: 'herb', leaf: 'palmate', flower: 'umbel', fhue: '#e8d030' }),
  'Mustard': T({ habit: 'herb', leaf: 'palmate', flower: 'umbel', fhue: '#e0c828' }),
  'Canola': T({ habit: 'herb', leaf: 'lance', flower: 'umbel', fhue: '#e8d83a' }),
  'Sesame': T({ habit: 'herb', leaf: 'lance', fruit: 'pod', fhue: '#c8b890' }),
  'Wild Sesame': T({ habit: 'herb', leaf: 'lance', fruit: 'pod', fhue: '#b8a880' }),
  'Flax': T({ habit: 'herb', leaf: 'lance', flower: 'star', fhue: '#7a9ad8' }),
  'Hemp': T({ habit: 'herb', leaf: 'palmate', tall: true }),
  'Fenugreek': T({ habit: 'herb', leaf: 'palmate', fruit: 'pod', fhue: '#c8b870' }),
  'Anise': T({ habit: 'herb', leaf: 'pinnate', flower: 'umbel', fhue: '#f0f0e0' }),
  'Star Anise': T({ habit: 'tree', leaf: 'broad', fruit: 'pod', fhue: '#8a5a34' }),
  /* ── HERBS ── */
  'Mint': T({ habit: 'herb', leaf: 'lance', flower: 'spike', fhue: '#c0a8e0' }),
  'Wild Mint': T({ habit: 'herb', leaf: 'lance', flower: 'spike', fhue: '#b8a0d8' }),
  'Mountain Mint': T({ habit: 'herb', leaf: 'lance', flower: 'spike', fhue: '#e0e0f0' }),
  'Alpine Mint': T({ habit: 'herb', leaf: 'lance', flower: 'spike', fhue: '#d0d0e8' }),
  'Swamp Mint': T({ habit: 'herb', leaf: 'lance', flower: 'spike', fhue: '#a8a0d0' }),
  'Water Mint': T({ habit: 'herb', leaf: 'lance', flower: 'head', fhue: '#b0a8d8' }),
  'Desert Mint': T({ habit: 'herb', leaf: 'lance', flower: 'spike', fhue: '#c8c0e0' }),
  'Holy Basil': T({ habit: 'herb', leaf: 'broad', flower: 'spike', fhue: '#a890c8' }),
  'Thyme': T({ habit: 'herb', leaf: 'needle', flower: 'head', fhue: '#c090c8' }),
  'Wild Thyme': T({ habit: 'herb', leaf: 'needle', flower: 'head', fhue: '#b888c0' }),
  'Mountain Thyme': T({ habit: 'herb', leaf: 'needle', flower: 'head', fhue: '#c8a0d0' }),
  'Oregano': T({ habit: 'herb', leaf: 'broad', flower: 'umbel', fhue: '#e0d0e8' }),
  'Rosemary': T({ habit: 'shrub', leaf: 'needle', flower: 'spike', fhue: '#90a8d8' }),
  'Lavender': T({ habit: 'shrub', leaf: 'needle', flower: 'spike', fhue: '#9878c8' }),
  'Fennel': T({ habit: 'herb', leaf: 'pinnate', flower: 'umbel', fhue: '#e0d840' }),
  'Sea Fennel': T({ habit: 'herb', leaf: 'pinnate', flower: 'umbel', fhue: '#d0d048' }),
  'Nettle': T({ habit: 'herb', leaf: 'heart', flower: 'catkin', fhue: '#a8b070' }),
  'Rainforest Nettle': T({ habit: 'herb', leaf: 'heart', flower: 'catkin', fhue: '#98a068' }),
  'Riverbank Nettle': T({ habit: 'herb', leaf: 'heart', flower: 'catkin', fhue: '#90a070' }),
  'Dandelion': T({ habit: 'rosette', leaf: 'lance', flower: 'head', fhue: '#e8c828' }),
  'Chicory': T({ habit: 'herb', leaf: 'lance', flower: 'head', fhue: '#7a90d8' }),
  'Yarrow': T({ habit: 'herb', leaf: 'pinnate', flower: 'umbel', fhue: '#f0efe4' }),
  'Chamomile': T({ habit: 'herb', leaf: 'pinnate', flower: 'head', fhue: '#f4f0dc' }),
  'Echinacea': T({ habit: 'herb', leaf: 'lance', flower: 'head', fhue: '#c87ab0' }),
  'Goldenrod': T({ habit: 'herb', leaf: 'lance', flower: 'spike', fhue: '#e0c430' }),
  'Black-Eyed Susan': T({ habit: 'herb', leaf: 'lance', flower: 'head', fhue: '#e8b820' }),
  'Bergamot': T({ habit: 'herb', leaf: 'lance', flower: 'head', fhue: '#c85a6a' }),
  'Milkweed': T({ habit: 'herb', leaf: 'broad', flower: 'umbel', fhue: '#d8a0b0' }),
  'Wormwood': T({ habit: 'herb', leaf: 'pinnate', flower: 'spike', fhue: '#c0c090' }),
  'Mugwort': T({ habit: 'herb', leaf: 'palmate', flower: 'spike', fhue: '#b8b898' }),
  'Valerian': T({ habit: 'herb', leaf: 'pinnate', flower: 'umbel', fhue: '#f0e0e8' }),
  'Arnica': T({ habit: 'rosette', leaf: 'broad', flower: 'head', fhue: '#e8b830' }),
  'Angelica': T({ habit: 'herb', leaf: 'pinnate', flower: 'umbel', fhue: '#e8ecd8' }),
  'Fireweed': T({ habit: 'herb', leaf: 'lance', flower: 'spike', fhue: '#d0509a' }),
  'Ginseng': T({ habit: 'herb', leaf: 'palmate', fruit: 'cluster', fhue: '#c02c2c' }),
  'Ginger': T({ habit: 'rosette', leaf: 'lance', flower: 'spike', fhue: '#e0c060' }),
  'Wild Ginger': T({ habit: 'rosette', leaf: 'heart', flower: 'bell', fhue: '#8a4a4a' }),
  'African Ginger': T({ habit: 'rosette', leaf: 'lance', flower: 'spike', fhue: '#d8b858' }),
  'Turmeric': T({ habit: 'rosette', leaf: 'broad', flower: 'spike', fhue: '#e0a828' }),
  'Cardamom': T({ habit: 'rosette', leaf: 'lance', fruit: 'pod', fhue: '#a8b850' }),
  'Wood Sorrel': T({ habit: 'rosette', leaf: 'palmate', flower: 'star', fhue: '#f0e8b0' }),
  'Sorrel': T({ habit: 'rosette', leaf: 'lance', flower: 'spike', fhue: '#b04a3a' }),
  'Mountain Sorrel': T({ habit: 'rosette', leaf: 'heart', flower: 'spike', fhue: '#c05a44' }),
  'Alpine Sorrel': T({ habit: 'rosette', leaf: 'heart', flower: 'spike', fhue: '#b85040' }),
  'Arctic Sorrel': T({ habit: 'rosette', leaf: 'heart', flower: 'spike', fhue: '#a84c40' }),
  'Wild Rhubarb': T({ habit: 'rosette', leaf: 'palmate', flower: 'spike', fhue: '#c05070' }),
  'Monkshood': T({ habit: 'herb', leaf: 'palmate', flower: 'bell', fhue: '#4a3a9a' }),
  'Belladonna': T({ habit: 'herb', leaf: 'broad', fruit: 'berry', fhue: '#241c28' }),
  'Buttercup': T({ habit: 'herb', leaf: 'palmate', flower: 'star', fhue: '#f0d020' }),
  'Bitterroot': T({ habit: 'rosette', leaf: 'lance', flower: 'head', fhue: '#e07ab0' }),
  'Glasswort': T({ habit: 'succulent', leaf: 'scale', fhue: '#8aa060' }),
  'Sea Purslane': T({ habit: 'succulent', leaf: 'pad', flower: 'star', fhue: '#d890b8' }),
  'Samphire': T({ habit: 'succulent', leaf: 'scale', fhue: '#7a9a58' }),
  /* ── SUCCULENTS ── */
  'Aloe': T({ habit: 'rosette', leaf: 'lance', flower: 'spike', fhue: '#e05a2c' }),
  'Agave': T({ habit: 'rosette', leaf: 'lance', flower: 'spike', fhue: '#d8c840', thorns: true }),
  'Yucca': T({ habit: 'rosette', leaf: 'blade', flower: 'bell', fhue: '#f0ece0' }),
  'Prickly Pear': T({ habit: 'succulent', leaf: 'pad', flower: 'head', fhue: '#e8c430', thorns: true }),
  'Barrel Cactus Fruit': T({ habit: 'succulent', leaf: 'scale', flower: 'head', fruit: 'berry', fhue: '#e0b028', thorns: true }),
  /* ── FERNS AND NON-VASCULAR ── */
  'Sword Fern': T({ habit: 'fern', leaf: 'frond' }),
  'Licorice Fern': T({ habit: 'fern', leaf: 'frond' }),
  'Cave Fern': T({ habit: 'fern', leaf: 'frond' }),
  'Maidenhair Fern': T({ habit: 'fern', leaf: 'frond' }),
  'Hardy Fern': T({ habit: 'fern', leaf: 'frond' }),
  'Fiddlehead Fern': T({ habit: 'fern', leaf: 'frond' }),
  'Tree Fern Shoots': T({ habit: 'fern', leaf: 'frond', tall: true }),
  'Lichen': T({ habit: 'rosette', leaf: 'scale' }),
  /* ── AQUATIC ── */
  'Kelp': T({ habit: 'aquatic', leaf: 'blade', tall: true }),
  'Giant Kelp': T({ habit: 'aquatic', leaf: 'blade', tall: true }),
  'Sugar Kelp': T({ habit: 'aquatic', leaf: 'blade' }),
  'Bull Kelp': T({ habit: 'aquatic', leaf: 'blade', tall: true }),
  'Sargassum': T({ habit: 'aquatic', leaf: 'lance' }),
  'Bladderwrack': T({ habit: 'aquatic', leaf: 'blade' }),
  'Dulse': T({ habit: 'aquatic', leaf: 'broad' }),
  'Wakame': T({ habit: 'aquatic', leaf: 'frond' }),
  'Red Algae': T({ habit: 'aquatic', leaf: 'frond' }),
  'Coralline Algae': T({ habit: 'aquatic', leaf: 'scale' }),
  'Sea Grapes Algae': T({ habit: 'aquatic', leaf: 'blade' }),
  'Duckweed': T({ habit: 'aquatic', leaf: 'pad' }),
  'Seagrass': T({ habit: 'aquatic', leaf: 'blade' }),
  'Water Lily': T({ habit: 'aquatic', leaf: 'pad', flower: 'star', fhue: '#f0e0f0' }),
  'Lotus': T({ habit: 'aquatic', leaf: 'pad', flower: 'star', fhue: '#f0c0d8' }),
  'Lotus Root': T({ habit: 'aquatic', leaf: 'pad', flower: 'star', fhue: '#e8b8d0' }),
  /* ── FLOWERS ── */
  'Sunflower': T({ habit: 'herb', leaf: 'heart', flower: 'head', fhue: '#e8c020', tall: true }),
  'Poppy': T({ habit: 'herb', leaf: 'pinnate', flower: 'head', fhue: '#d02c2c' }),
  'Violet': T({ habit: 'rosette', leaf: 'heart', flower: 'star', fhue: '#7a4ac0' }),
  'Foxglove': T({ habit: 'herb', leaf: 'lance', flower: 'bell', fhue: '#c86ab0' }),
  'Gentian': T({ habit: 'herb', leaf: 'lance', flower: 'bell', fhue: '#3a4ac0' }),
  'Edelweiss': T({ habit: 'rosette', leaf: 'lance', flower: 'star', fhue: '#f0f0e8' }),
  'Purple Saxifrage': T({ habit: 'rosette', leaf: 'scale', flower: 'star', fhue: '#a850c0' }),
  'Steppe Tulip': T({ habit: 'herb', leaf: 'blade', flower: 'bell', fhue: '#d83a4a' }),
  'Vanilla Orchid': T({ habit: 'vine', leaf: 'lance', flower: 'star', fhue: '#e8e0b8' }),
  'Orchid Pods': T({ habit: 'herb', leaf: 'lance', fruit: 'pod', fhue: '#5a4a2c' }),
  'Roselle': T({ habit: 'shrub', leaf: 'palmate', flower: 'head', fhue: '#c02c4a' }),
  'Daisy': T({ habit: 'herb', leaf: 'lance', flower: 'head', fhue: '#f4f2e8' }),
  /* ★ WAVE 18 — the last of the unrouted flora, each read off its own row */
  "Angel's Trumpet": T({ habit: 'shrub', leaf: 'broad', flower: 'bell', fhue: '#f6e6cf' }),
  'Tree Tomato': T({ habit: 'tree', leaf: 'heart', fruit: 'berry', fhue: '#c8402a' }),
  "Solomon's Seal": T({ habit: 'herb', leaf: 'broad', flower: 'bell', fhue: '#f2f4ea' }),
  "Miner's Lettuce": T({ habit: 'herb', leaf: 'pad', flower: 'head', fhue: '#f4f6ef' }),
  "Devil's Claw": T({ habit: 'herb', leaf: 'broad', fruit: 'pod', fhue: '#4a3a26' }),
  'Licorice Root': T({ habit: 'herb', leaf: 'pinnate', flower: 'spike', fhue: '#a9a6d8' }),
  'Pampas Herb': T({ habit: 'grass', leaf: 'blade', flower: 'catkin', fhue: '#efeade', tall: true }),
  'Plantain Herb': T({ habit: 'rosette', leaf: 'lance', flower: 'spike', fhue: '#8f9a6a' }),
  'Sea Rocket': T({ habit: 'herb', leaf: 'broad', flower: 'head', fhue: '#c9b6d8' }),
};
