/* AUTO-GENERATED by tools/lift-hdart.mjs. ⚠ DO NOT EDIT. */
export function hdPortraitFauna(g: Record<string, unknown>): string;
export function hdPortraitFlora(g: Record<string, unknown>): string;
export function hdPortraitFungi(g: Record<string, unknown>): string;
export function hdPortraitMicrobe(g: Record<string, unknown>): string;
export function hdPortraitFaunaCanvas(g: Record<string, unknown>): HTMLCanvasElement;
export function hdPortraitFloraCanvas(g: Record<string, unknown>): HTMLCanvasElement;
export function hdPortraitFungiCanvas(g: Record<string, unknown>): HTMLCanvasElement;
export function hdPortraitMicrobeCanvas(g: Record<string, unknown>): HTMLCanvasElement;
