/* AUTO-GENERATED by tools/lift-hdart.mjs. ⚠ DO NOT EDIT. */
import type { ArtCanvas } from './speciescanvas.js';
export function hdPortraitFaunaCanvas(g: Record<string, unknown>): ArtCanvas;
export function hdPortraitFloraCanvas(g: Record<string, unknown>): ArtCanvas;
export function hdPortraitFungiCanvas(g: Record<string, unknown>): ArtCanvas;
export function hdPortraitMicrobeCanvas(g: Record<string, unknown>): ArtCanvas;
