/* AUTO-GENERATED by tools/lift-hdart.mjs. ⚠ DO NOT EDIT. */
import type { ArtCanvas } from './speciescanvas.js';
export function hdPortraitFaunaCanvas(g: Record<string, unknown>): ArtCanvas;
export function hdPortraitFloraCanvas(g: Record<string, unknown>): ArtCanvas;
export function hdPortraitFungiCanvas(g: Record<string, unknown>): ArtCanvas;
export function hdPortraitMicrobeCanvas(g: Record<string, unknown>): ArtCanvas;
export function hdBeastBare(g: Record<string, unknown>, seed?: number): ArtCanvas;
export function _hdPlantBare(seed: number, species: Record<string, unknown>): ArtCanvas;
export function hdFloraBare(g: Record<string, unknown>, seed?: number): ArtCanvas;
export function _hdCamo(canvas: ArtCanvas, color: string, alpha: number): ArtCanvas;
export function _hdStampPlant(...args: unknown[]): void;
export function _hdPlaceBeast(...args: unknown[]): void;
export function _hdHash(x: number, y: number, seed: number): number;
export function _hdFbm(x: number, y: number, seed: number, octaves: number): number;
export function _hdSm(value: number): number;
export const HD_PALS: Readonly<Record<string, Record<string, unknown>>>;
