import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire,registerHooks} from 'node:module';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
import {keyAndDespill} from '../../tools/local-image-generation/kit-contact-math.mjs';
import {resolve as resolveTs} from '../../port/v2/tools/effects-proof/resolve-ts-hook.mjs';
registerHooks({resolve:resolveTs});
const dir=import.meta.dirname,root=path.resolve(dir,'../..'),req=createRequire(path.join(root,'port/v2/package.json')),sharp=createRequire(req.resolve('free-tex-packer-core'))('sharp');
const {parseEffectSequenceAnchors}=await import(pathToFileURL(path.join(root,'port/v2/apps/game/src/effects/anchors.ts')).href);
const sha=b=>createHash('sha256').update(b).digest('hex'),size=1024,origin=[.2,.55],contact=[.8,.55],request=JSON.parse(fs.readFileSync(path.join(dir,'requests.json')));
const theme=process.argv[2],variant=process.argv[3];assert(request.rows.some(r=>r.theme===theme),'Unknown theme');assert(!variant||['neutral','material','shards'].includes(variant),'Unknown variant');const sourceDir=path.join(dir,theme),out=variant?path.join(sourceDir,variant):sourceDir,registrations=JSON.parse(fs.readFileSync(path.join(sourceDir,'registration.json'))),rows=[];
const write=(name,data)=>fs.writeFileSync(path.join(out,name),data,{flag:'wx'});for(const d of ['keyed','registered'])fs.mkdirSync(path.join(out,d),{recursive:true});
for(const phase of ['launch','travel','impact']){
 const master=variant?'../'+phase+(fs.existsSync(path.join(sourceDir,phase+'-'+variant+'-master.png'))?'-'+variant:'')+'-master.png':phase+'-master.png',bytes=fs.readFileSync(path.join(out,master)),{data,info}=await sharp(bytes).ensureAlpha().raw().toBuffer({resolveWithObject:true});assert.equal(info.width,info.height);assert(info.width>=384);
 const keyed=keyAndDespill(new Uint8ClampedArray(data),info.width,info.height),png=await sharp(Buffer.from(keyed.rgba),{raw:{width:info.width,height:info.height,channels:4}}).png().toBuffer();write('keyed/'+phase+'.png',png);
 const f=registrations[phase],target=phase==='impact'?contact:origin,scaled=Math.round(size*f.canvasScale),ratio=scaled/info.width,left=Math.round(size*target[0]-scaled*f.sourceAnchor[0]),top=Math.round(size*target[1]-scaled*f.sourceAnchor[1]);
 assert(left>=0&&top>=0&&left+scaled<=size&&top+scaled<=size,'Full master canvas must fit without cropping: '+phase);
 const small=await sharp(png).resize(scaled,scaled,{kernel:'lanczos3'}).png().toBuffer(),registered=await sharp({create:{width:size,height:size,channels:4,background:'#00000000'}}).composite([{input:small,left,top}]).png().toBuffer();write('registered/'+phase+'.png',registered);
 const raw=await sharp(registered).raw().toBuffer();let minX=size,minY=size,maxX=-1,maxY=-1,count=0;for(let y=0;y<size;y++)for(let x=0;x<size;x++)if(raw[(y*size+x)*4+3]>0){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);count++;}assert(count>0);
 const alphaBoundsPixels={x:minX,y:minY,width:maxX-minX+1,height:maxY-minY+1},mapped=f.sourceAnchor.map((v,i)=>(v*scaled+[left,top][i])/size),residual=mapped.map((v,i)=>(v-target[i])*size);assert(residual.every(n=>Math.abs(n)<=.51));
 rows.push({phase,master,masterSha256:sha(bytes),masterCanvas:{width:info.width,height:info.height},keyedImage:'keyed/'+phase+'.png',keyedSha256:sha(png),registeredImage:'registered/'+phase+'.png',registeredSha256:sha(registered),alphaBoundsPixels,alphaPositivePixels:count,keyer:keyed.receipt,registration:{sourceAnchor:f.sourceAnchor,targetAnchor:target,fullCanvasPixels:scaled,uniformScale:ratio,left,top,residualPixels:residual,method:'Measured from full-size master; uniform downscale and translation, no cropping, rotation or paint retouch'}});
 assert.equal(sha(fs.readFileSync(path.join(out,master))),sha(bytes));
}
const requestRow=request.rows.find(r=>r.theme===theme),anchors={schema:'cf.effect-sequence-anchors/v1',sequenceId:theme+'-c132-v43',theme,abilityId:requestRow.abilityId,abilityName:requestRow.abilityName,canvasSize:{width:size,height:size},phaseOrder:['launch','travel','impact'],originAnchor:origin,contactAnchor:contact,phases:rows.map(r=>({phase:r.phase,image:r.registeredImage,keyedImage:r.registeredImage,imageSha256:r.registeredSha256,canvasSize:{width:size,height:size},originAnchor:origin,contactAnchor:contact,alphaBoundsPixels:r.alphaBoundsPixels})),qualityAccepted:false};
assert(parseEffectSequenceAnchors(anchors).ok);write('anchors.json',JSON.stringify(anchors,null,2)+'\n');
write('intake.json',JSON.stringify({schema:'cf.c132-effect-intake/v1',theme,status:'MECHANICAL_INTAKE_ONLY',originalsUnchanged:true,qualityAccepted:false,rows},null,2)+'\n');
const panels=[];for(let i=0;i<rows.length;i++)panels.push({input:await sharp(path.join(out,rows[i].registeredImage)).resize(512).flatten({background:'#24282b'}).png().toBuffer(),left:i*512,top:40});
const labels=Buffer.from('<svg width="1536" height="40"><rect width="1536" height="40" fill="#24282b"/>'+rows.map((r,i)=>`<text x="${i*512+20}" y="27" font-family="sans-serif" font-size="20" fill="white">${theme.toUpperCase()} ${r.phase.toUpperCase()}</text>`).join('')+'</svg>');panels.push({input:labels,left:0,top:0});write('review-sheet.png',await sharp({create:{width:1536,height:552,channels:4,background:'#24282b'}}).composite(panels).png().toBuffer());
console.log(JSON.stringify({theme,status:'MECHANICAL_INTAKE_ONLY',unresolved:rows.map(r=>({phase:r.phase,...r.keyer})),anchors:'anchors.json'}));
