import{readFileSync}from'node:fs';import{expect,it}from'vitest';
import{compileProceduralQuadrupedProofV43}from'../apps/game/src/landfall-conditioning.js';
import{planFor}from'../packages/art/src/proceduraloverrides.js';import{speciesGenomePalette}from'../packages/art/src/speciesoverrides.js';
const read=(n:string)=>JSON.parse(readFileSync('../../'+n,'utf8')),root='audits/PROCEDURAL_BATTLE_ITERATION_20260916/painter-01/procedural-3/',record=read(root+'record.json'),genome=read(root+'genome.json'),p=speciesGenomePalette(genome),source={genome,identity:record.identity,material:record.materials.surface,palette:{base:p.base,lit:p.lit,dark:p.dark},plan:planFor(genome) as any},snapshot=read('audits/ART_KIT_ENGINE_FIRST_20260912/canonical-snapshot.json'),kit=readFileSync('../../ART_KIT.md','utf8');
const compile=(s=source)=>compileProceduralQuadrupedProofV43(snapshot,kit,s);
it('compiles actual procedural identity/material/proportions without changing kit blocks or pretending to be runtime-ready',()=>{const a=compile();expect(compile()).toEqual(a);expect(a.qualityAccepted).toBe(false);expect(a.animationReady).toBe(false);expect(a.subject).toContain('rosettes');expect(a.subject).toContain('leg length 0.075');expect(a.systemCard).toContain('not an Earth resident');expect(a.systemCard).not.toContain('Civet:');expect(a.prompt).toContain('exactly four legs');const frozen=kit.split('## 2. Frozen style')[1]!.split('```text\n')[1]!.split('\n```')[0]!;expect(a.prompt).toContain(frozen);expect(a.prompt.indexOf('SUBJECT\n')).toBeLessThan(a.prompt.indexOf('ACCURACY\n'));expect(a.prompt.indexOf('ACCURACY\n')).toBeLessThan(a.prompt.indexOf('LAYOUT\n'));expect(a.prompt).not.toContain('One Earth Fox');expect(a.prompt).not.toContain('fine pointed muzzle');});
it('refuses identity/paint-material corruption rather than changing named anatomy or imposing fur',()=>{expect(()=>compile({...source,identity:{...source.identity,earthName:'Civet'}})).toThrow('identity');expect(()=>compile({...source,genome:{...genome,seed:3}})).toThrow('identity');expect(()=>compile({...source,material:'translucent'})).toThrow('material');expect(()=>compile({...source,palette:{...source.palette,base:'rgb(999,0,0)'}})).toThrow('palette');});
it('refuses a key-colour conflict without mutating its genome palette',()=>{const changed={...source,palette:{...source.palette,base:'rgb(210,30,200)'}};expect(()=>compile(changed)).toThrow('conflicts with magenta key');expect(changed.palette.base).toBe('rgb(210,30,200)');});
it('does not claim support for unobserved extra limbs, tails or non-quadruped plans',()=>{expect(()=>compile({...source,plan:{...source.plan,kind:'fish'}})).toThrow('unsupported');expect(()=>compile({...source,plan:{...source.plan,spec:{...source.plan.spec,alien:{...source.plan.spec.alien,legPairs:4}}}})).toThrow('unsupported');expect(()=>compile({...source,plan:{...source.plan,spec:{...source.plan.spec,tail:'plume'}}})).toThrow('unsupported');});
