/** D15 Stages 1–2: the ORIGINAL creature sources and combat set. Outcomes: every cue a creature can play passes the measured loudness gate
 * at every size; the sources are the project's own (never the placeholder's bytes) and deterministic; the battle stage's turn sink
 * renders the original combat set through its real path; the provenance rows in AUDIO_LICENSES.md are exactly the generator's manifest
 * (regenerate with CF_REGENERATE_AUDIO_LEDGER=1). Every check carries a control. */
import { readFileSync, writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { makeGenome } from '@cf/domain-genome';
import type { AudioVoiceRequest } from '@cf/audio';
import { admitLoudnessV1 } from '../apps/game/src/soundkit/loudness.js';
import { CREATURE_CUES } from '../apps/game/src/soundkit/cues.js';
import { deriveCue, sha256Hex } from '../apps/game/src/soundkit/derive.js';
import { compileVoiceCard, VOICE_ARCHETYPES } from '../apps/game/src/soundkit/voice-card.js';
import { synthesizePlaceholderLibrary } from '../apps/game/src/soundkit/placeholder-archetype.js';
import { ORIGINAL_ARCHETYPES, ORIGINAL_SOURCE_GENERATOR, originalSourceLibraryV1, originalSourceManifestV1 } from '../apps/game/src/soundkit/original-voices.js';
import { COMBAT_CUE_IDS_V1, ORIGINAL_COMBAT_GENERATOR, ORIGINAL_THEMES, renderCombatCueV1 } from '../apps/game/src/soundkit/original-combat.js';
import { createTurnCueSink } from '../apps/game/src/soundkit/turn-audio.js';
import { synthesizeBattleCue } from '../apps/game/src/soundkit/battle-synth.js';

const bytes = (x: Float32Array) => new Uint8Array(x.buffer, x.byteOffset, x.byteLength);
const LEDGER = new URL('../../../AUDIO_LICENSES.md', import.meta.url);
const BEGIN = '<!-- ORIGINAL-SOURCES:BEGIN (generated by tests/soundkit-original-sources.test.ts; CF_REGENERATE_AUDIO_LEDGER=1) -->', END = '<!-- ORIGINAL-SOURCES:END -->';

describe('original creature sources', () => {
  it('every creature cue of every ORIGINAL archetype passes the measured loudness gate at tiny, dog-sized and titanic sizes', () => {
    const lib = originalSourceLibraryV1(); let checked = 0;
    for (const archetype of ORIGINAL_ARCHETYPES) for (const size of [0, 2, 5]) {
      const r = compileVoiceCard({ template: { id: archetype }, identity: { speciesVisualKey: `probe:${archetype}`, seed: 3000 + size } }, { ...(makeGenome(3000 + size, 'fauna', 0.5) as unknown as Record<string, unknown>), size } as never);
      if (!r.ok) throw new Error(`${archetype}: ${JSON.stringify(r)}`);
      for (const cue of CREATURE_CUES) { const d = deriveCue(r.card, cue, lib.sources, r.card.seed), a = admitLoudnessV1(d.samples, d.sampleRate, 'creature');
        expect(a.ok, `${archetype} size ${size} ${cue}: ${a.ok ? '' : a.reason}`).toBe(true); checked++; }
    }
    expect(checked).toBe(ORIGINAL_ARCHETYPES.length * 3 * CREATURE_CUES.length);
  }, 300_000);
  it('the original sets are the project\'s own bytes (never the placeholder\'s) and render identically twice; the manifest names a seed and hash per source', () => {
    const a = originalSourceLibraryV1().sources, b = originalSourceLibraryV1().sources, ph = synthesizePlaceholderLibrary().sources;
    for (const archetype of ORIGINAL_ARCHETYPES) {
      const call = (a[archetype]!.call as readonly Float32Array[])[0]!;
      expect(sha256Hex(bytes(call))).toBe(sha256Hex(bytes((b[archetype]!.call as readonly Float32Array[])[0]!)));
      expect(sha256Hex(bytes(call)), `${archetype}: an original call must not be the placeholder's`).not.toBe(sha256Hex(bytes((ph[archetype]!.call as readonly Float32Array[])[0]!)));
    }
    const rows = originalSourceManifestV1();
    expect(rows.length).toBeGreaterThan(ORIGINAL_ARCHETYPES.length * 11);
    for (const r of rows) { expect(r.sha256).toMatch(/^[0-9a-f]{64}$/); expect(Number.isInteger(r.seed)).toBe(true); expect(r.samples).toBeGreaterThan(0); }
  }, 120_000);
  it('an archetype without an original set yet is served by the labelled placeholder and listed as such (the library says which)', () => {
    const lib = originalSourceLibraryV1(), pending = VOICE_ARCHETYPES.filter((x) => !ORIGINAL_ARCHETYPES.includes(x));
    expect(lib.original).toEqual(ORIGINAL_ARCHETYPES);
    for (const x of pending) expect(sha256Hex(bytes((lib.sources[x]!.call as readonly Float32Array[])[0]!))).toBe(sha256Hex(bytes((synthesizePlaceholderLibrary().sources[x]!.call as readonly Float32Array[])[0]!)));
  }, 120_000);
});

describe('original combat set', () => {
  it('every original battle and ability cue passes the combat gate and stays inside its length cap; a pending theme is flagged', () => {
    let original = 0;
    for (const id of COMBAT_CUE_IDS_V1) {
      const c = renderCombatCueV1(id, 7, { amount: 25 });
      if (!c.original) { expect(c.flags.some((f) => f.startsWith('original-pending')), id).toBe(true); continue; }
      const a = admitLoudnessV1(c.samples, c.sampleRate, 'combat'); expect(a.ok, `${id}: ${a.ok ? '' : a.reason}`).toBe(true);
      expect(c.samples.length / c.sampleRate).toBeLessThanOrEqual(id.endsWith(':impact') || id === 'battle:hitstop-thump' ? 0.6 : 1.4); original++;
    }
    expect(original).toBeGreaterThanOrEqual(16 + ORIGINAL_THEMES.length * 3);
    // damage-tick is pitched by amount
    expect(sha256Hex(bytes(renderCombatCueV1('battle:damage-tick', 7, { amount: 5 }).samples))).not.toBe(sha256Hex(bytes(renderCombatCueV1('battle:damage-tick', 7, { amount: 90 }).samples)));
  }, 120_000);
  it('OUTCOME: the battle stage\'s turn sink renders the ORIGINAL cue through its real path; control: an injected placeholder renderer gives different bytes', () => {
    const played: Float32Array[] = [];
    const ctx = { currentTime: 0, createBuffer: (_c: number, n: number, _r: number) => { const buf = new Float32Array(n); return { copyToChannel: (s: Float32Array) => { buf.set(s); played.push(buf); } }; },
      createBufferSource: () => ({ buffer: null, connect() {}, start() {}, stop() {}, disconnect() {}, onended: null }), createGain: () => ({ gain: { setValueAtTime() {} }, connect() {}, disconnect() {} }) };
    const runtime = { playVoice: (r: AudioVoiceRequest) => { r.create(ctx as never, { voiceId: 'v' } as never); return { kind: 'started' as const, voiceId: 'v' }; } };
    createTurnCueSink({ runtime, seed: 7 }).play({ cueId: 'battle:hitstop-thump', atMs: 0, source: 'battle', beat: 'impact' }, 0);
    expect(sha256Hex(bytes(played[0]!))).toBe(sha256Hex(bytes(renderCombatCueV1('battle:hitstop-thump', 7).samples)));
    createTurnCueSink({ runtime, seed: 7, synthesize: synthesizeBattleCue }).play({ cueId: 'battle:hitstop-thump', atMs: 0, source: 'battle', beat: 'impact' }, 0);
    expect(sha256Hex(bytes(played[1]!))).not.toBe(sha256Hex(bytes(played[0]!)));
  });
});

describe('provenance ledger', () => {
  it('AUDIO_LICENSES.md carries exactly the generator manifest: one row per original source (seed + sha256), "original, CC0 by the project"', () => {
    const rows = originalSourceManifestV1(), table = [BEGIN, '',
      `Generator \`${ORIGINAL_SOURCE_GENERATOR}\` (\`port/v2/apps/game/src/soundkit/organic.ts\` + \`original-voices.ts\`) and \`${ORIGINAL_COMBAT_GENERATOR}\` (\`original-combat.ts\`). Rights: **original, CC0 by the project**. Rendered at runtime from the seed; 0 audio bytes ship. Each hash is the SHA-256 of the rendered Float32 little-endian PCM at 48 kHz.`, '',
      '| owner | source | take | seed | samples | sha256 |', '|---|---|---:|---:|---:|---|',
      ...rows.map((r) => `| ${r.archetype} | ${r.key} | ${r.take} | ${r.seed} | ${r.samples} | \`${r.sha256}\` |`), '', END].join('\n');
    let text = readFileSync(LEDGER, 'utf8');
    if (process.env.CF_REGENERATE_AUDIO_LEDGER === '1') {
      text = text.includes(BEGIN) ? text.slice(0, text.indexOf(BEGIN)) + table + text.slice(text.indexOf(END) + END.length)
        : text.replace('## 1. Rights rule', `## D15 original procedural sources — shipped (rendered at runtime)\n\n${table}\n\n## 1. Rights rule`);
      writeFileSync(LEDGER, text);
    }
    expect(text.slice(text.indexOf(BEGIN), text.indexOf(END) + END.length)).toBe(table);
  }, 120_000);
});
