import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {compileLibraryMaster as canonicalCompile} from '../../port/v2/tools/painted-creature/compile-library-master.mjs';
import {compileLibraryMaster as specializedCompile} from './compiler.audit.mjs';
const base='audits/C213_CREATURE_SUPPLY_20261002',sha=b=>createHash('sha256').update(b).digest('hex');
const corrections={
 Zebra:'Keep the real tufted tail fully continuous from its bare upper half to its dark tuft, clear of the hind legs. Preserve bold black-white stripes across body, belly and all legs and the stiff upright brush mane; not a flowing horse mane. Separate the true upper foreleg contours where visible.',
 Kudu:'Keep both true huge rounded dish ears fully readable from crown attachments to complete tips, naturally separated from the towering corkscrew horns. Preserve the 6–10 thin white vertical flank stripes and real dewlap/beard; do not turn fringe into an extra leg.',
 Impala:'Show each actual slender foreleg through its full ankle and cloven hoof with clear separation from the other leg. Preserve the real black hind-hoof tufts and dark rump stripes, not extra appendages; retain lyre-shaped ringed horns.',
 Eland:'Show both true ear outlines and the continuous natural tail root/shaft/tuft clear of the hind leg. Preserve the ox-like shoulder hump and real throat dewlap rather than removing them as unexplained paint. Separate real foreleg contours.',
 Gazelle:'Show both actual ear attachments and full tips without moving them away from the crown; keep the complete natural short tail tip clear of hind legs. Retain the dark flank band between tan back and white belly, delicate legs and ringed lyre horns.',
 Hartebeest:'Use a slight natural head turn only enough to reveal both real ears from their actual crown attachments. Preserve the extremely long narrow face, steeply sloping back and bracket horns rising from their real bony pedestal; do not invent or relocate an ear.',
 Oryx:'Make the actual near ear tip fully visible beside, not fused into, the horn base. Preserve both unshortened long straight rapier horns, black face mask and leg markings. Zoom out rather than clipping horns.',
 Gaur:'Use the true tall muscular shoulder ridge, not a round spherical hump. Distinguish both foreleg roots, wrists and full hooves in a natural stance. All four lower legs retain white stockings and the real grey forehead lies between the upcurving horns.',
 Deer:'Preserve its actual short tail continuously from root to visible tip, clear of hind legs, without lengthening it to match a reference. Retain branched sweeping antlers and large cupped ears; only real anatomical segments may be visible.',
 Antelope:'Keep all four real leg contours separate through their complete hooves, both natural ears visible, and the true short flicking tail clear of limbs. Retain unbranched ringed horns and tan flank/white belly. No extra limb from a fringe or tail.',
 Reindeer:'Correct the earlier moose-like antlers: real reindeer antlers are tall branching beams with a forward-sweeping brow shovel over the face, not giant bilateral moose paddles. Show actual ear bases where visible, pale neck mane, broad splayed hooves and complete natural short tail.',
 Caribou:'Correct the earlier moose-like antlers: tall sweeping branched beams with a forward brow shovel, not massive moose paddle fans. Preserve the leaner leggy wild form, white neck ruff and broad splayed snowshoe hooves. Both real ear contours remain connected and distinct where visible.',
 Yak:'Preserve the real long flank-hair curtain, low head, humped shoulders and bushy tail plume. A slight natural head turn may expose the actual far ear; never add it. Separate all four hoof contacts and visible ankle contours without shaving the coat or inventing hidden upper legs.',
 Takin:'Keep a stocky goat-antelope body on genuinely short thick legs, golden shaggy coat, humped shoulders and Roman-nosed muzzle. Expose the actual far forefoot and its visible ankle outline naturally, without changing the leg length or removing coat. Horns sweep outward then back.',
 Sheep:'Retain thick woolly fleece, narrow bare face and bare lower legs. Paint the canonical short drooping tail, not the earlier long wool-covered tail; preserve its actual connected root. Separate the visible foreleg contours without creating false gaps inside the fleece.',
 'Wild Sheep':'Preserve a short coarse hair coat rather than woolly fleece, muscular body and massive curling horns. Separate the real far foreleg ankle and complete hoof, and show actual ear edges only where visible around the horns; never infer a hidden ear or relocate it.',
 'Dromedary Camel':'Preserve exactly one hump, a curved long neck, true knobbly knee pads and broad two-toed padded feet. Show the complete real tail from root to tuft clear of hind legs, and naturally connected full limbs rather than thread-thin sticks. Camel feet are padded, not horse hooves.',
 'Bactrian Camel':'Preserve exactly two separate humps, real shaggy neck/chest/hump hair, curved neck and broad padded feet. Show the complete true tail shaft and tuft clear of legs. Distinguish visible leg contours without erasing the chest coat or inventing hidden upper parts.'
};
const specialists=Object.keys(JSON.parse(fs.readFileSync(base+'/specialized-layouts.json'))),names=[...Object.keys(corrections),'Gibbon',...specialists],coveragePath='audits/GENERATED_GALLERY_20260927/coverage.json',coverage=JSON.parse(fs.readFileSync(coveragePath)),accepted=new Set(coverage.families.flatMap(f=>f.names??[]));
const priorPilots=execFileSync('rg',['--files','-g','pilot*.json','audits'],{encoding:'utf8'}).trim().split('\n'),prior=new Map();for(const f of priorPilots){const d=JSON.parse(fs.readFileSync(f)),rows=Array.isArray(d)?d:d.subjects||d.rows||d.pilot||d.creatures||[];if(!Array.isArray(rows))continue;for(const r of rows)if(r.name)prior.set(r.name,[...(prior.get(r.name)||[]),f]);}
const oldPilot='audits/G2_C110_20260927/pilot.json',oldSummary='audits/G1_AUTO_AUTHOR_20260926/auto-g2c110/summary.json',oldNotes='audits/G2_C110_20260927/visual-notes.json',p=JSON.parse(fs.readFileSync(oldPilot)),scores=JSON.parse(fs.readFileSync(oldSummary)),notes=JSON.parse(fs.readFileSync(oldNotes));
const composition='COMPOSITION PRIORITY: whole natural specimen fits within the central HALF of a native 1254-square pure magenta canvas with roughly 300 pixels clear around all tips. Zoom out to preserve real proportions. No crop, ground, shadow, branch, prop, text or framing marks.';
const hoof='SOURCE VISIBILITY: use a quiet natural grounded stance with four true leg chains and four distinct complete feet. Separate near/far silhouettes from their actual visible shoulder/hip emergence through the real joints, not merely the toe tips. Preserve true short tails, shaggy hair, horns, ears and feet; never remove anatomy, expose fictitious hidden segments or lengthen a part to match a generic rig. A very slight natural head turn may reveal both existing ears, with body still facing RIGHT in side profile. If genuine occlusion remains, keep it rather than inventing a part.';
const rows=[];
for(const[i,name]of names.entries()){
 if(accepted.has(name))throw Error('Accepted duplicate '+name);if(!corrections[name]&&prior.has(name))throw Error('New-source inventory changed '+name);
 const id=String(i+1).padStart(2,'0')+'-'+name.toLowerCase().replaceAll(' ','-'),packet=base+'/'+id,isSpecial=specialists.includes(name),c=await(isSpecial?specializedCompile:canonicalCompile)(name,packet),request=JSON.parse(fs.readFileSync(packet+'/request.json')),canonical=fs.readFileSync(packet+'/prompt.txt','utf8');if(sha(canonical)!==request.promptSha256)throw Error('Canonical prompt hash');
 let repairReason=null,appendix='';if(corrections[name]){const prev=p.find(r=>r.name===name),s=scores.find(r=>r.id===prev.id);if(s.verdict!=='REFUSE')throw Error('Prior refusal missing');repairReason={previousId:prev.id,previousMaster:prev.master,previousSummary:oldSummary,reasons:s.reasons,previousVisual:notes[name],correction:corrections[name]};appendix=hoof+'\nTARGETED SOURCE CORRECTION: '+corrections[name];}
 else if(name==='Gibbon')appendix='BIOLOGICAL PRIORITY: a real tailless gibbon, with arms far longer than the legs and long hooked hands. Use a quiet natural terrestrial resting stance with both arms lowered and both feet visible, actual hand/foot contact where natural; no human heroic pose, generic quadruped paws, tail, supporting branch or prop. Keep the two arm chains and two leg chains separate where anatomy permits. Do not infer hidden fingers.';
 const prompt=composition+'\n'+appendix+'\n\n'+canonical+'\n\n'+appendix+'\n'+composition+'\n';
 fs.writeFileSync(packet+'/prompt.canonical.txt',canonical,{flag:'wx'});fs.writeFileSync(packet+'/prompt.txt.tmp',prompt,{flag:'wx'});fs.renameSync(packet+'/prompt.txt.tmp',packet+'/prompt.txt');
 const purpose=corrections[name]?'TARGETED_SOURCE_REPAINT':'NEW_SOURCE_IDENTITY';fs.writeFileSync(packet+'/request.json.tmp',JSON.stringify({...request,basePromptSha256:request.promptSha256,promptSha256:sha(prompt),batchCompilerSha256:sha(fs.readFileSync(import.meta.filename)),purpose,repairReason,priorPilotPaths:prior.get(name)??[],auditCompilerExtension:isSpecial,sourceCorrection:appendix,compositionCheck:composition,admission:'SOURCE_CANDIDATE_ONLY; no presence, fit, reference pool or native admission'},null,2)+'\n',{flag:'wx'});fs.renameSync(packet+'/request.json.tmp',packet+'/request.json');rows.push({id,name,family:c.family,packet,master:packet+'/master.png',purpose,repairReason});console.log(id,c.family);
}
fs.writeFileSync(base+'/pilot.json',JSON.stringify(rows,null,2)+'\n',{flag:'wx'});
const evidence=[oldPilot,oldSummary,oldNotes,coveragePath].map(path=>{const b=fs.readFileSync(path);return{path,sha256:sha(b),bytes:b.length};});
fs.writeFileSync(base+'/selection.json',JSON.stringify({schema:'cf.g2-selection/v1',coveredAtSelection:210,total:24,targetedSourceRepaints:18,newSourceIdentities:6,priorRequestedNames:prior.size,specialists,evidence,scope:'Unaccepted hoofed source gaps first, six previously unrequested canonical identities including five second-reference candidates. Nineteen unchanged canonical compiler routes; five explicit audit-only painting-layout routes. Prawn replaces biologically incompatible Krill. No source implies template admission.',rows},null,2)+'\n',{flag:'wx'});
