import{Application,Container,Graphics,Sprite,Texture,Text}from'pixi.js';
import{loadCreatureRigV1}from'../../apps/game/src/creature-rig.ts';
import{compileBodyCard,buildTimeline,createGsapPlayer}from'../../apps/game/src/motion/index.ts';
import{bodyPresentationMs}from'../../apps/game/src/battle-presentation-clock.ts';
import{blendCreaturePoses,closedLoopPose}from'../../apps/game/src/motion-pose-blend.ts';
import{compileHabitatBattle,resolvePhysicalHabitat}from'../../apps/game/src/battle-habitat.ts';
import{createSourceJoinProbe,assessSourceJoinContinuity}from'../quadruped-proof/source-join-continuity.mjs';
import{primeRecorder}from'../quadruped-proof/capture-contract.mjs';
import{compileClearing,encounterBeat,ease}from'./recipe.mjs';
import{mouthOffset,partTip}from'./contact.mjs';
import{compileAnatomyAttack}from'../../apps/game/src/anatomy-attacks.ts';
import{abilityOf}from'@cf/domain-combatcore';
const state={status:'LOADING'};window.cfClearing={state};
const get=async n=>{const r=await fetch(n);if(!r.ok)throw Error('Missing scene asset '+n);return r;},json=async n=>(await get(n)).json(),bytes=async n=>new Uint8Array(await(await get(n)).arrayBuffer()),b64=b=>{let s='';const a=new Uint8Array(b);for(let i=0;i<a.length;i+=8192)s+=String.fromCharCode(...a.subarray(i,i+8192));return btoa(s);};
const image=async n=>{const b=await bytes(n),bmp=await createImageBitmap(new Blob([b])),c=new OffscreenCanvas(bmp.width,bmp.height),ctx=c.getContext('2d');ctx.drawImage(bmp,0,0);return{bytes:b,canvas:c,rgba:ctx.getImageData(0,0,c.width,c.height).data};};
try{
 const W=1600,H=900,app=new Application();await app.init({width:W,height:H,resolution:1,background:0x24302b,antialias:true,autoStart:false,preference:'webgl'});document.body.append(app.canvas);
 const world=await json('world.json'),assets={};for(const id of['far','mid','near','tree','shrub','impact'])assets[id]=await image(id+'.png');
 const actors=[];for(const[id,name,homeX,height,direction]of[['rosette','ROSETTE',.21,.35,1],['crystal','GLASSHORN',.39,.28,1],['broad','THICKET PROWLER',.80,.37,-1]]){
  const record=await json(id+'-record.json'),binding=await json(id+'-binding.json'),paint=await image(id+'-keyed.png'),atlas=await image(id+'-atlas.png'),master=await bytes(id+'-master.png'),rig=await loadCreatureRigV1(record,binding,master,Uint8Array.from({length:paint.canvas.width*paint.canvas.height},(_,i)=>paint.rgba[i*4+3]),atlas.bytes),card=compileBodyCard(record,record.genome),attackPlan=compileAnatomyAttack(card,'ground',actors.length+1,undefined,await json(id+'-weapons.json')),ability=abilityOf(record.genome),clips={};
  for(const action of['idle','approach','melee','hit']){const tl=action==='melee'?attackPlan.timeline:buildTimeline(card,action,record.identity.seed);let p={};const player=createGsapPlayer(tl,{setJoint(n,rotation,dx,dy){p[n]={rotation,dx,dy};}},{now:()=>0});clips[action]={tl,sample(ms){p={};player.seek(ms);return p;}};}
  const positions=()=>Object.fromEntries(binding.paintSkin.parts.map(p=>[p.id,rig.parts.find(r=>r.id===p.id).display.children[0].geometry.getBuffer('aPosition').data]));
  const bounds=()=>{let x0=Infinity,y0=Infinity,x1=-Infinity,y1=-Infinity;for(const p of Object.values(positions()))for(let i=0;i<p.length;i+=2){x0=Math.min(x0,p[i]);y0=Math.min(y0,p[i+1]);x1=Math.max(x1,p[i]);y1=Math.max(y1,p[i+1]);}return{x0,y0,x1,y1};};rig.applyPose({});const rest=bounds(),weaponPart=binding.parts.find(p=>p.kind==='part'&&p.joint===attackPlan.attack.contactJoint);if(!weaponPart)throw Error('Painted weapon part missing');rig.applyPose(clips.melee.sample(attackPlan.contactMs));const contactTip=partTip(positions()[weaponPart.id]);rig.applyPose({});const scale=H*height/(rest.y1-rest.y0),holder=new Container();holder.addChild(rig.root);rig.root.scale.set(direction*scale,scale);rig.root.position.set(-(rest.x0+rest.x1)/2*direction*scale,-rest.y1*scale);
  actors.push({id,name,record,binding,rig,card,attackPlan,ability,contactTip,clips,positions,bounds,rest,scale,direction,holder,homeX,physical:resolvePhysicalHabitat(record,record.genome),probe:createSourceJoinProbe({record,binding,atlas:{rgba:atlas.rgba,width:atlas.canvas.width,height:atlas.canvas.height}})});
 }
 const pair=compileHabitatBattle({contextId:'painted-clearing-squad',seed:301,round:0,kind:'wild',home:world,visitor:world,left:actors[0].physical,right:actors[2].physical});if(pair.status!=='READY')throw Error(pair.reason);
 const scene=new Container();app.stage.addChild(scene);const far=new Sprite(Texture.from(assets.far.canvas));scene.addChild(far);const treeLayer=new Container();scene.addChild(treeLayer);const mid=new Sprite(Texture.from(assets.mid.canvas));mid.width=W+80;mid.height=H;mid.x=-40;scene.addChild(mid);
 const ripples=new Graphics();scene.addChild(ripples);const shadowLayer=new Graphics();scene.addChild(shadowLayer);scene.addChild(actors[1].holder,actors[0].holder,actors[2].holder);const near=new Sprite(Texture.from(assets.near.canvas));near.width=W+80;near.height=H;near.x=-40;scene.addChild(near);const shrubLayer=new Container();scene.addChild(shrubLayer);
 const fx=new Sprite(Texture.from(assets.impact.canvas));fx.anchor.set(.8,.55);fx.scale.set(.85);scene.addChild(fx);const rain=new Graphics();scene.addChild(rain);
 const hud=new Container();app.stage.addChild(hud);const top=new Graphics().rect(0,0,W,95).fill({color:0x0f2022,alpha:.84});hud.addChild(top);
 const title=new Text({text:'THE RAINWOOD CLEARING',style:{fontFamily:'Georgia',fontSize:27,fill:0xf5ecd2}});title.position.set(34,16);hud.addChild(title);
 const subtitle=new Text({text:'',style:{fontFamily:'Arial',fontSize:16,fill:0xbdd0bc}});subtitle.position.set(35,57);hud.addChild(subtitle);
 const banner=new Text({text:'',style:{fontFamily:'Georgia',fontSize:27,fill:0xffdf9e}});banner.anchor.set(.5);banner.position.set(W/2,133);hud.addChild(banner);
 const cards=actors.map(a=>({meleeMs:a.clips.melee.tl.durationMs,contactMs:a.attackPlan.contactMs})),bars=new Graphics(),labels=[];hud.addChild(bars);
 for(const a of actors){const label=new Text({text:a.name,style:{fontFamily:'Arial',fontSize:17,fill:0xf4edcf}});hud.addChild(label);labels.push(label);}
 const number=new Text({text:'',style:{fontFamily:'Arial',fontWeight:'bold',fontSize:38,fill:0xffe3a3}});hud.addChild(number);
 const footnote=new Text({text:'Anatomy attack study · existing Wild effect · seeded painted clearing',style:{fontFamily:'Arial',fontSize:15,fill:0xc7d1ba}});footnote.position.set(28,H-28);hud.addChild(footnote);
 let recipe,holds,clock=0,playing=true,startTime=null,updates={},last={};
 function choose(seed){recipe=compileClearing({seed,world,actors:actors.map(a=>({id:a.id,recordHash:a.record.recipeHash,physical:a.physical}))});holds=recipe.turns.map(turn=>({atMs:turn.startMs+1350+cards[turn.actor].contactMs,durationMs:actors[turn.actor].clips.melee.tl.hitstopMs}));
  for(const layer of[treeLayer,shrubLayer])layer.removeChildren().forEach(c=>c.destroy());
  for(const p of recipe.scenery.trees){const s=new Sprite(Texture.from(assets.tree.canvas));s.anchor.set(.5,1);s.height=p.height*H;s.scale.x=Math.abs(s.scale.y)*(p.flip?-1:1);s.position.set(p.x*W,H*.76);treeLayer.addChild(s);}
  for(const p of recipe.scenery.shrubs){const s=new Sprite(Texture.from(assets.shrub.canvas));s.anchor.set(.5,1);s.height=p.height*H;s.scale.x=s.scale.y;s.position.set(p.x*W,H*.99);shrubLayer.addChild(s);}
  far.width=W*recipe.scenery.farScale;far.height=H*recipe.scenery.farScale;far.position.set((W-far.width)/2+recipe.scenery.farOffset,H-far.height);subtitle.text='Temperate · rain · encounter '+seed+' · three combatants';clock=0;startTime=null;updates=Object.fromEntries(actors.map(a=>[a.id,[]]));stageAt(0);return recipe;
 }
 function stageAt(ms,measure=false,legacyFollowthrough=false){clock=ms;const turnIndex=Math.min(2,Math.floor(ms/6000)),bodyMs=bodyPresentationMs(ms,holds),localBody=bodyMs-bodyPresentationMs(turnIndex*6000,holds),b=encounterBeat(recipe,turnIndex*6000+localBody,cards),rawT=ms-b.turn.startMs,hitAge=ms-holds[turnIndex].atMs,atImpact=hitAge>=0&&hitAge<holds[turnIndex].durationMs;
  const bounds=[];for(let i=0;i<actors.length;i++){const a=actors[i],at=performance.now();let p=closedLoopPose(a.clips.idle.sample,bodyMs+i*337,a.clips.idle.tl.durationMs),action='idle',age=0,weight=0;
   if(i===b.turn.actor&&b.phase==='approach'){action='approach';age=b.t-b.approachStart;weight=ease(age/100);}
   else if(i===b.turn.actor&&b.t>=b.attackStart&&b.t<=b.attackEnd){action='melee';age=b.t-b.attackStart;weight=Math.min(ease(age/90),ease((b.attackEnd-b.t)/130));}
   else if(i===b.turn.actor&&b.phase==='return'){action='approach';age=b.t-b.attackEnd;weight=1-ease(age/450);}
   else if(i===b.turn.target&&b.t>=b.impact&&b.t<b.impact+a.clips.hit.tl.durationMs){action='hit';age=b.t-b.impact;weight=Math.min(ease(age/50),ease((a.clips.hit.tl.durationMs-age)/120));}
   if(weight>0){const c=a.clips[action];p=blendCreaturePoses(p,action==='approach'?closedLoopPose(c.sample,age,c.tl.bodyMs):c.sample(age),weight);}
   a.rig.applyPose(p);if(measure)updates[a.id].push(performance.now()-at);bounds.push(a.bounds());a.holder.position.set(a.homeX*W,recipe.groundLineY*H);a.rig.root.tint=i===b.turn.target&&hitAge>=0&&hitAge<90?0xffdbaa:0xffffff;
  }
  const attack=actors[b.turn.actor],target=actors[b.turn.target],tb=bounds[b.turn.target];
  const mouth=a=>mouthOffset(a.positions().jaw,a.rig.root.x,a.scale,a.direction),targetMouth=target.holder.x+mouth(target);
  const strikingPart=attack.binding.parts.find(p=>p.kind==='part'&&p.joint===attack.attackPlan.attack.contactJoint);if(!strikingPart)throw Error('No painted contact part for '+attack.attackPlan.attack.contactJoint);
  const tip=partTip(attack.positions()[strikingPart.id]),attackFront=attack.rig.root.x+(legacyFollowthrough?tip.x:attack.contactTip.x)*attack.direction*attack.scale;
  const targetContact=targetMouth-target.direction*12,desiredX=targetContact-attackFront;
  attack.holder.x=attack.homeX*W+(desiredX-attack.homeX*W)*b.travel;
  const flight=b.phase==='attack'?Math.sin(Math.PI*Math.min(1,(b.t-b.attackStart)/cards[b.turn.actor].meleeMs))*24:0;attack.holder.y-=flight;
  const contact={x:targetContact,y:attack.holder.y+attack.rig.root.y+tip.y*attack.scale};
  ripples.clear();for(const p of recipe.scenery.rain.slice(0,24)){const phase=(ms*.00055*p.speed+p.y)%1,rx=W*(.17+p.x*.66),ry=H*(.79+p.y*.12);ripples.ellipse(rx,ry,2+phase*13,1+phase*2).stroke({color:0xbdd2c6,alpha:(1-phase)*.14,width:1});}
  shadowLayer.clear();for(let i=0;i<actors.length;i++){const a=actors[i],w=(a.rest.x1-a.rest.x0)*a.scale*.30;shadowLayer.ellipse(a.holder.x,recipe.groundLineY*H+3,w,10).fill({color:0x14201a,alpha:i===b.turn.actor?.28-.08*b.travel:.28});}
  const push=.025*b.travel;scene.scale.set(1+push);scene.position.set(-W/2*push+(hitAge>=0&&hitAge<150?Math.sin(hitAge*.11)*(1-hitAge/150)*4:0),-H*.60*push);far.x=(W-far.width)/2+recipe.scenery.farOffset-b.travel*attack.direction*6;mid.x=-40+recipe.scenery.midOffset-b.travel*attack.direction*12;near.x=-40-b.travel*attack.direction*20;
  fx.visible=hitAge>=0&&hitAge<holds[turnIndex].durationMs+240;fx.position.set(contact.x,contact.y);const effectScale=Math.min(.65,Math.min(attack.scale*(attack.rest.y1-attack.rest.y0),target.scale*(target.rest.y1-target.rest.y0))/650);fx.scale.set(effectScale*attack.direction,effectScale);fx.alpha=1;
  rain.clear();for(const p of recipe.scenery.rain){const y=((p.y+ms*.00020*p.speed)%1)*H,x=p.x*W-y*.12;rain.moveTo(x,y).lineTo(x-3,y+p.length*H).stroke({color:0xd7e5cf,alpha:.22,width:1});}
  banner.text=b.phase==='approach'||b.phase==='attack'?attack.name+'  ·  '+attack.attackPlan.attack.label.toUpperCase():'';
  bars.clear();for(let i=0;i<actors.length;i++){const a=actors[i],x=i===2?W-310:30+i*320,y=H-88;labels[i].position.set(x,y-26);const damage=recipe.turns.reduce((n,tr,k)=>n+(tr.target===i&&ms>=holds[k].atMs?tr.damage:0),0);bars.roundRect(x,y,270,10,5).fill({color:0x18261f,alpha:.9}).roundRect(x,y,270*Math.max(.1,(100-damage)/100),10,5).fill(i===2?0xc88e62:0x9ab884);}
  const timing=ease((rawT-650)/500);if(b.phase==='approach')bars.rect(W/2-90,160,180,4).fill({color:0x18261f,alpha:.7}).rect(W/2-90,160,180*timing,4).fill(0xe3cf8c);
  number.text=hitAge>=0&&hitAge<750?'−'+b.turn.damage:'';number.position.set(contact.x,contact.y-55-Math.max(0,hitAge)*.06);number.alpha=hitAge<400?1:Math.max(0,1-(hitAge-400)/350);app.renderer.render(app.stage);
  const faceOrder=(targetMouth-(attack.holder.x+mouth(attack)))*attack.direction;
  last={beat:b,contact,faceOrder,contactGap:Math.abs((attack.holder.x+attack.rig.root.x+partTip(attack.positions()[strikingPart.id]).x*attack.direction*attack.scale-targetMouth)*attack.direction-12),atImpact,bounds};return last;
 }
 function snapshot(ms){stageAt(ms);return actors.map(a=>({xy:[a.holder.x,a.holder.y],parts:Object.fromEntries(Object.entries(a.positions()).map(([id,v])=>[id,Array.from(v)]))}));}
 async function gates(){let samples=0,maxGap=0,failures=[];for(let i=0;i<=1080;i++){const ms=i*1000/60,s=stageAt(ms);for(let n=0;n<actors.length;n++){const a=actors[n],seams=assessSourceJoinContinuity(a.probe,a.positions());maxGap=Math.max(maxGap,seams.maxGapPx);samples++;if(seams.status!=='PASS')failures.push({ms,id:a.id,reason:'seam'});if(n===s.beat.turn.actor&&s.faceOrder < -35)failures.push({ms,id:a.id,reason:'attacker passed through target face',faceOrder:s.faceOrder});const b=s.bounds[n],x=[b.x0,b.x1].map(x=>a.holder.x+a.rig.root.x+x*a.direction*a.scale),y0=a.holder.y+a.rig.root.y+b.y0*a.scale,y1=a.holder.y+a.rig.root.y+b.y1*a.scale;if(Math.min(...x)<0||Math.max(...x)>W||y0<95||y1>H*.9)failures.push({ms,id:a.id,reason:'body outside encounter',x,y0,y1});}}
  const freeze=holds.map(h=>JSON.stringify(snapshot(h.atMs+1))===JSON.stringify(snapshot(h.atMs+h.durationMs-1))),contacts=holds.map(h=>stageAt(h.atMs+1).contactGap),same=JSON.stringify(recipe)===JSON.stringify(compileClearing({seed:recipe.encounterSeed,world,actors:recipe.actors}));
  let legacyFaceOrder=Infinity;for(const [i,h]of holds.entries())if(actors[recipe.turns[i].actor].attackPlan.attack.verb==='claw')for(let age=0;age<=180;age+=10)legacyFaceOrder=Math.min(legacyFaceOrder,stageAt(h.atMs+h.durationMs+age,false,true).faceOrder);const legacyFollowthroughRefused=legacyFaceOrder < -35;
  return {status:!failures.length&&freeze.every(Boolean)&&contacts.every(n=>n<1)&&same&&legacyFollowthroughRefused?'PASS':'FAIL',legacyFollowthroughRefused,legacyFaceOrder,samples,maxSourceGapPx:maxGap,failures:failures.slice(0,12),hitstopAllActors:freeze,contactGapPx:contacts,replayRecipeIdentical:same,recipe,attacks:actors.map(a=>({id:a.id,verb:a.attackPlan.attack.verb,contactJoint:a.attackPlan.attack.contactJoint,contactMs:a.attackPlan.contactMs,timelineHash:a.attackPlan.timeline.hash,repertoire:a.attackPlan.repertoire,ability:a.ability})),impactTimes:holds.map(h=>h.atMs+h.durationMs/2),scope:'Three painted grounded-family actors; published weapon/skin contact diagnostic, not anatomical bite or planted-paw certification'};
 }
 async function capture(){playing=false;const stream=app.canvas.captureStream(0),track=stream.getVideoTracks()[0],chunks=[],rec=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp9',videoBitsPerSecond:8000000}),stopped=new Promise(r=>rec.onstop=r);rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};let started=false;rec.onstart=()=>started=true;rec.start();await primeRecorder({started:()=>started,paint:()=>stageAt(0),requestFrame:()=>track.requestFrame(),schedule:requestAnimationFrame,now:()=>performance.now()});updates=Object.fromEntries(actors.map(a=>[a.id,[]]));let start;const frames=[],cpu=[];await new Promise((resolve,reject)=>{const tick=now=>{try{start??=now;const ms=now-start,at=performance.now();stageAt(Math.min(ms,18000),true);cpu.push(performance.now()-at);track.requestFrame();frames.push(now);if(ms>=18000)resolve();else requestAnimationFrame(tick);}catch(e){reject(e);}};requestAnimationFrame(tick);});await new Promise(r=>setTimeout(r,120));track.requestFrame();rec.stop();await stopped;stream.getTracks().forEach(t=>t.stop());const p95=a=>a.sort((x,y)=>x-y)[Math.floor(a.length*.95)];return{fps:(frames.length-1)*1000/(frames.at(-1)-frames[0]),frames:frames.length,wholeFrameP95Ms:p95(cpu),creatureP95Ms:Object.fromEntries(Object.entries(updates).map(([id,a])=>[id,p95(a)])),video:b64(await new Blob(chunks).arrayBuffer())};}
 window.cfClearing={state,gates,capture,snapshot,choose,still(ms){playing=false;stageAt(ms);return app.canvas.toDataURL('image/png').split(',')[1];},play(){playing=true;startTime=null;},pause(){playing=false;}};choose(301);state.status='READY';
 function tick(now){if(playing){startTime??=now-clock;stageAt((now-startTime)%18000);}requestAnimationFrame(tick);}requestAnimationFrame(tick);
 document.querySelector('#restart')?.addEventListener('click',()=>{choose(recipe.encounterSeed);playing=true;});
 for(const b of document.querySelectorAll('[data-seed]'))b.addEventListener('click',()=>{choose(Number(b.dataset.seed));playing=true;});
}catch(e){state.status='FAIL';state.error=String(e.stack??e);const p=document.createElement('p');p.textContent=state.error;document.body.append(p);}
