import fs from'node:fs';import path from'node:path';import os from'node:os';import http from'node:http';import{execFileSync}from'node:child_process';import{createHash}from'node:crypto';import{rolldown}from'rolldown';import{openChromiumCdp}from'../browsercdp.mjs';import{acquireWorkspaceLock}from'../workspacelock.mjs';
import{inspectEncounterCapture}from'./capture.mjs';
const [outArg]=process.argv.slice(2),out=path.resolve(outArg);if(fs.existsSync(out))throw Error('New output required');fs.mkdirSync(out,{recursive:true});const sha=b=>createHash('sha256').update(b).digest('hex');
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'cf-family-native-')),sources=new Map(),report={status:'RUNNING',diagnostic:true,source:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),scope:'Seeded painted temperate clearing, three actual painted rigs, shared motion. Dirty diagnostic, no production or universal acceptance.'},remember=p=>sources.set(p,{path:p,sha256:sha(fs.readFileSync(p))}),save=()=>fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');let release,server,browser;
try{release=acquireWorkspaceLock('real painted family native review');const bundle=await rolldown({input:path.join(import.meta.dirname,'native-entry.mjs'),platform:'browser',plugins:[{name:'read-only-producer',transform(_,id){if(path.isAbsolute(id)&&fs.existsSync(id)&&fs.statSync(id).isFile())remember(id);}}]});try{await bundle.write({dir:scratch,format:'es',entryFileNames:'bundle.js'});}finally{await bundle.close();}
 const declarationsFile='audits/ANATOMY_ATTACKS_20260916/weapon-declarations.json',declarations=JSON.parse(fs.readFileSync(declarationsFile));remember(declarationsFile);for(const[id,d]of Object.entries(declarations))fs.writeFileSync(path.join(scratch,id+'-weapons.json'),JSON.stringify(d));
 const assets={};for(const[id,dirArg]of[['rosette','audits/PAINTED_VARIATION_MOTION_20260916/rig-approved-05'],['crystal','audits/PAINTED_VARIATION_MOTION_20260916/rig-crystalline-02'],['broad','audits/PAINTED_VARIATION_MOTION_20260916/rig-broad-02']]){const dir=path.resolve(dirArg),record=JSON.parse(fs.readFileSync(path.join(dir,'record.json'))),manifest=JSON.parse(fs.readFileSync(path.join(dir,'parts/manifest.json')));for(const[n,p]of Object.entries({'record.json':path.join(dir,'record.json'),'binding.json':path.join(dir,'binding.json'),'keyed.png':path.join(dir,'parts/keyed.png'),'atlas.png':path.join(dir,'parts/atlas',manifest.creatureId+'.png'),'master.png':path.resolve(record.source)}))assets[id+'-'+n]=p;}
 assets['far.png']='audits/ARENA_EFFECTS_V42_PROOF_20260912/arena-far.png';assets['mid.png']='audits/ARENA_V1_ACCEPTANCE_20260912/arena-mid-despilled.png';assets['near.png']='audits/ARENA_EFFECTS_V42_PROOF_20260912/keyed/arena-near.png';
 const effectFile='audits/WILD_V43_PROOF_20260913/wild-anchors.json',effect=JSON.parse(fs.readFileSync(effectFile)).phases.find(p=>p.phase==='impact');remember(effectFile);assets['impact.png']=path.join(path.dirname(effectFile),effect.image);if(sha(fs.readFileSync(assets['impact.png']))!==effect.imageSha256)throw Error('Effect hash mismatch');
 const {createRequire}=await import('node:module'),require=createRequire(import.meta.url),sharp=createRequire(require.resolve('free-tex-packer-core'))('sharp'),{keyAndDespill}=await import('../../../../tools/local-image-generation/kit-contact-math.mjs');
 for(const[id,name]of[['tree','persimmon'],['shrub','devils-club']]){const p='audits/ART_KIT_ENGINE_FIRST_20260912/masters/'+name+'.png';remember(p);const{data,info}=await sharp(fs.readFileSync(p)).ensureAlpha().raw().toBuffer({resolveWithObject:true});const keyed=keyAndDespill(new Uint8ClampedArray(data),info.width,info.height);await sharp(Buffer.from(keyed.rgba),{raw:{width:info.width,height:info.height,channels:4}}).png().toFile(path.join(scratch,id+'.png'));}
for(const[n,p]of Object.entries(assets)){remember(p);fs.copyFileSync(p,path.join(scratch,n));}
 const snapshotFile='audits/ART_KIT_ENGINE_FIRST_20260912/canonical-snapshot.json',snapshot=JSON.parse(fs.readFileSync(snapshotFile));remember(snapshotFile);const cardFile='audits/ART_KIT_ENGINE_FIRST_20260912/family-compiled-inputs.json',compiled=JSON.parse(fs.readFileSync(cardFile));remember(cardFile);const world={key:snapshot.request.worldKey,biome:snapshot.request.biomeKey,seed:snapshot.roster.planetSeed,solid:true,atmosphere:true,liquid:snapshot.request.options.water==='liquid'?'water':null,surfaceWater:snapshot.request.options.water==='liquid',signature:snapshot.request.options.wx,cardHash:sha(Buffer.from(JSON.stringify(compiled.systemCard))),groundLineY:.78};fs.writeFileSync(path.join(scratch,'world.json'),JSON.stringify(world));fs.writeFileSync(path.join(out,'world.json'),JSON.stringify(world,null,2)+'\n');
 fs.writeFileSync(path.join(scratch,'index.html'),'<meta name="viewport" content="width=device-width,initial-scale=1"><title>Seeded painted biome battle</title><style>body{margin:0;background:#12241e;color:#eee7cd;font:15px system-ui}nav{padding:12px;display:flex;gap:12px;align-items:center;flex-wrap:wrap}button{padding:9px 14px;background:#355547;color:inherit;border:1px solid #86a38d;border-radius:6px;cursor:pointer}canvas{display:block;width:100%;height:auto}p{padding:0 14px}</style><nav><strong>Seeded temperate encounter</strong><button data-seed="301">Clearing 301</button><button data-seed="927">Clearing 927</button><button id="restart">Replay battle</button></nav><script type="module" src="bundle.js"></script>');
 server=http.createServer((req,res)=>{const n=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';if(n.includes('/')||!fs.existsSync(path.join(scratch,n))){res.writeHead(404).end();return;}res.setHeader('Content-Type',n.endsWith('.js')?'text/javascript':n.endsWith('.json')?'application/json':n.endsWith('.html')?'text/html':'image/png');res.end(fs.readFileSync(path.join(scratch,n)));});await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await openChromiumCdp({label:'Painted family native review',userDataPrefix:'cf-family-review',commandTimeoutMs:60000});report.browser=browser.browser;
 const{targetId}=await browser.send('Target.createTarget',{url:'about:blank'}),{sessionId}=await browser.send('Target.attachToTarget',{targetId,flatten:true}),send=(m,p={})=>browser.send(m,p,sessionId),evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};await send('Page.enable');await send('Runtime.enable');await send('Emulation.setDeviceMetricsOverride',{width:1400,height:800,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:'http://127.0.0.1:'+server.address().port});
 const deadline=performance.now()+60000;for(;;){const s=await evaluate('window.cfClearing?.state');if(s?.status==='FAIL')throw Error(s.error);if(s?.status==='READY')break;if(performance.now()>deadline)throw Error('Readiness timeout');await new Promise(r=>setTimeout(r,100));}
 await evaluate('window.cfClearing.pause()');report.gates=await evaluate('window.cfClearing.gates()');save();if(report.gates.status!=='PASS')throw Error('Actual family gates failed');
 for(const [name,ms]of[['ready',500],['run-up',1150],['first-strike',1750],['second-turn',7750],['third-turn',13750]])fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(await evaluate('window.cfClearing.still('+ms+')'),'base64'));
 for(const [i,ms]of report.gates.impactTimes.entries())fs.writeFileSync(path.join(out,'impact-'+(i+1)+'.png'),Buffer.from(await evaluate('window.cfClearing.still('+ms+')'),'base64'));
 report.alternateRecipe=await evaluate('window.cfClearing.choose(927)');fs.writeFileSync(path.join(out,'alternate-clearing.png'),Buffer.from(await evaluate('window.cfClearing.still(500)'),'base64'));await evaluate('window.cfClearing.choose(301)');report.capture=await evaluate('window.cfClearing.capture()');fs.writeFileSync(path.join(out,'biome-battle-18s.webm'),Buffer.from(report.capture.video,'base64'));delete report.capture.video;const media=JSON.parse(execFileSync('/opt/homebrew/bin/ffprobe',['-v','error','-count_frames','-show_entries','format=duration:stream=codec_type,nb_read_frames,width,height','-of','json',path.join(out,'biome-battle-18s.webm')],{encoding:'utf8'}));report.capture.encodedMedia=media;save();report.capture.validation=inspectEncounterCapture(media,report.capture);report.status='DIAGNOSTIC_PASS';
}catch(e){report.status='FAIL';report.error=String(e.stack??e);process.exitCode=1;}finally{report.sources=[...sources.values()];for(const r of report.sources)if(sha(fs.readFileSync(r.path))!==r.sha256){report.status='FAIL';report.error='source changed: '+r.path;process.exitCode=1;}save();if(report.status==='DIAGNOSTIC_PASS'){fs.cpSync(scratch,path.join(out,'preview'),{recursive:true});}await browser?.close();if(server)await new Promise(r=>server.close(r));release?.();fs.rmSync(scratch,{recursive:true,force:true});}console.log(JSON.stringify({status:report.status,error:report.error,rest:report.gates?.restChanged,capture:report.capture}));
