import test from'node:test';import assert from'node:assert/strict';import{compileClearing,encounterBeat}from'./recipe.mjs';
const input={seed:301,world:{key:'source-earth',cardHash:'compiled-source-card',biome:'temperate',solid:true,groundLineY:.78},actors:['a','b','c'].map(id=>({id,recordHash:id,physical:{allowed:['ground']}}))};
test('same encounter replays exactly; distinct seeds alter composition and every actor has a turn',()=>{const a=compileClearing(input);assert.deepEqual(a,compileClearing(input));assert.notDeepEqual(a.scenery,compileClearing({...input,seed:927}).scenery);assert.deepEqual(a.turns.map(t=>t.actor).sort(),[0,1,2]);for(const t of a.turns)assert.notEqual(t.actor,t.target);});
test('dry fish, foreign biome templates, duplicate actors and missing cards refuse',()=>{for(const bad of[{...input,world:{...input.world,biome:'abyssal'}},{...input,world:{...input.world,cardHash:''}},{...input,actors:[input.actors[0],input.actors[0],input.actors[2]]},{...input,actors:input.actors.map(a=>({...a,physical:{allowed:['water']}}))}])assert.throws(()=>compileClearing(bad));});
test('run-up and return are bounded, return to home, and seek matches frame playback',()=>{const r=compileClearing(input),cards=Array(3).fill({meleeMs:700,contactMs:300});assert.equal(encounterBeat(r,0,cards).travel,0);assert.equal(encounterBeat(r,1700,cards).travel,1);assert.equal(encounterBeat(r,3000,cards).travel,0);assert.equal(encounterBeat(r,12000,cards).phase,'ready');assert.throws(()=>encounterBeat(r,-1,cards));});

test('impact follows the anatomy motion contact time, not settling duration',()=>{const r=compileClearing(input),cards=Array(3).fill({meleeMs:1200,contactMs:230});assert.equal(encounterBeat(r,1580,cards).impact,1580);assert.notEqual(encounterBeat(r,1580,cards).impact,1350+1200*.42);});

test('missing anatomical contact time cannot silently use the old percentage estimate',()=>{assert.throws(()=>encounterBeat(compileClearing(input),1700,Array(3).fill({meleeMs:700})),/contact phase/);});
