import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';import {createHash} from 'node:crypto';
const require=createRequire(import.meta.url),sharp=createRequire(require.resolve('free-tex-packer-core'))('sharp'),base=path.resolve(process.argv[2]??''),root=path.resolve(import.meta.dirname,'../../../..');if(process.argv.length!==3)throw Error('Usage: review-sheet.mjs R9_PACKET');
const layers=[],sources=[],W=2000,H=3300,sha=b=>createHash('sha256').update(b).digest('hex');
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;');const label=(s,x,y,size=23)=>layers.push({input:Buffer.from(`<svg width="${W}" height="42"><text x="0" y="30" font-family="sans-serif" font-size="${size}" fill="#edf2ec">${esc(s)}</text></svg>`),left:x,top:y});
async function read(file){const b=await fs.readFile(file);sources.push({file:path.relative(root,file),sha256:sha(b)});return b;}
async function bbox(b){const {data,info}=await sharp(b).ensureAlpha().raw().toBuffer({resolveWithObject:true});let left=info.width,top=info.height,right=0,bottom=0;for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++)if(data[(y*info.width+x)*4+3]){left=Math.min(left,x);top=Math.min(top,y);right=Math.max(right,x);bottom=Math.max(bottom,y);}return {left,top,width:right-left+1,height:bottom-top+1};}
label('R9 / Q1 — texture candidates, original paint preserved',30,10,32);label('Native numbers qualify geometry; visual acceptance remains Nick’s review.',30,53,22);
label('Painter · 1× source pixels',150,92);label('Finished · 1× source pixels',670,92);label('Painter pincer · 3×',1200,92);label('Finished pincer · 3×',1570,92);
for(const [i,id]of ['crab','freshwater-crab','mud-crab','vent-crab','coconut-crab'].entries()){
 const dir=path.join(root,'audits/ANATOMY_COMPLETION_20260917/crab-fits-03',id),record=JSON.parse(await fs.readFile(path.join(dir,'record.json'))),original=await read(path.resolve(root,record.source)),finished=await read(path.join(base,'finish-01',id+'-finished.png')),box=await bbox(original),y=145+i*390;
 label(id,20,y,20);const p=record.landmarks.clawNearPalm,tip=record.landmarks.clawNearDactylTip,w=record.geometry.width,h=record.geometry.height;
 const cx=Math.round((p[0]+tip[0])/2*w),cy=Math.round((p[1]+tip[1])/2*h),crop={left:Math.max(0,cx-52),top:Math.max(0,cy-47),width:104,height:94};
 for(const [b,x]of [[original,150],[finished,670]])layers.push({input:await sharp(b).extract(box).png().toBuffer(),left:x,top:y+55});
 for(const [b,x]of [[original,1200],[finished,1570]])layers.push({input:await sharp(b).extract(crop).resize(312,282,{kernel:'nearest'}).png().toBuffer(),left:x,top:y+55});
}
label('Q1 — separate source-painted open-gape candidates; not adopted',30,2110,27);
for(const [i,id]of ['crab','coconut-crab'].entries()){const bytes=await read(path.join(base,'q1-01',id+'-master.png')),box=await bbox(bytes);label(id+' · open-gape source',30+i*950,2150);layers.push({input:await sharp(bytes).extract(box).png().toBuffer(),left:30+i*950,top:2200});const record=JSON.parse(await fs.readFile(path.join(base,'q1-01',id+'-record.json'))),p=record.landmarks.clawNearPalm;layers.push({input:await sharp(bytes).extract({left:Math.round(p[0]*880)-48,top:Math.round(p[1]*880)-48,width:104,height:96}).resize(312,288,{kernel:'nearest'}).png().toBuffer(),left:570+i*950,top:2185});}
const arenaFile=path.join(root,'audits/ARENA_V1_ACCEPTANCE_20260912/arena-template-v1.png'),arena=await read(arenaFile),a=await sharp(arena).resize(1100,550,{fit:'fill'}).png().toBuffer(),crab=await read(path.join(base,'finish-01/crab-finished.png')),box=await bbox(crab),sprite=await sharp(crab).extract(box).resize({width:220}).png().toBuffer();const composite=await sharp(a).composite([{input:sprite,left:330,top:350}]).png().toBuffer();await fs.writeFile(path.join(base,'arena-scale-composite.png'),composite,{flag:'wx'});label('Accepted Earth-temperate arena · finished Crab at 220 px body width',30,2620,25);layers.push({input:composite,left:30,top:2670});label('Review composite only; no battle integration claim.',1180,2710,20);
// SVG labels are clipped to their remaining row width to avoid spilling the sheet.
for(const l of layers)if(l.input.subarray(0,4).toString()==='<svg')l.input=Buffer.from(l.input.toString().replace(`width="${W}"`,`width="${W-l.left}"`));
await fs.writeFile(path.join(base,'review-sheet.png'),await sharp({create:{width:W,height:H,channels:4,background:'#18282d'}}).composite(layers).png().toBuffer(),{flag:'wx'});await fs.writeFile(path.join(base,'sheet-receipt.json'),JSON.stringify({subjectCount:7,maximumSubjectsPerSheet:12,painterScale:1,cropScale:3,arenaCrabWidthPx:220,arenaScaleScope:'review battle scale, not an integrated battle capture',sources},null,2)+'\n',{flag:'wx'});
