import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {compileLibraryMaster,controlledLibraryLayout} from '../../port/v2/tools/painted-creature/compile-library-master.mjs';
const base='audits/G2_C163_FAMILY_ORIGINALS_20261002',sha=b=>createHash('sha256').update(b).digest('hex');
const names=['Mara','Salamander','Wall Lizard','Gorilla','Chimpanzee','Orangutan','Capuchin','Howler Monkey','Spider Monkey','Macaque','Baboon','Lemur','Centipede','Giant Centipede','Millipede','Octopus','Squid','Cuttlefish','Giant Octopus','Deep-Sea Octopus','Fruit Bat','Bat','Insect-Eating Bat','Vampire Bat'];
const common='Strict side profile facing RIGHT, head right and tail left. Exactly one anatomically accurate adult with FOUR natural legs, two forelegs and two hindlegs, each visibly attached to the correct body region. Offset the near and far legs in a quiet natural planted walking stride so their shafts and every foot are separately readable against the background; do not invent, elongate, cross or detach a limb to expose it. Preserve the real species posture, natural bend of elbows and knees, exact toes and natural tail shape. The true tail is continuous from its body attachment through its full natural tip, visually clear of feet; do not lengthen a short tail. Preserve all canonical identity features and natural pigment patterns. No mammalian external ears, fur, hooves or invented horns. No scenery, floor, cast shadow, labels or props. Every natural structure must remain inside the frame with at least 8 percent clear margin.';
const overrides={Salamander:common+' Preserve smooth amphibian skin, naturally low sprawling limbs and a complete laterally flattened swimming tail. No scales, claws, external ears or larval external gills on this adult. Preserve the canonical black-and-yellow fire-salamander markings.', 'Wall Lizard':common+' Preserve the natural lizard sprawl, bent elbows and knees, species-correct scales, head and complete tail length. Retain natural toe pads, claws, dewlaps, crests and colour bands only where this species has them. Do not turn the legs into straight mammalian pillars.'};
const composition='FINAL COMPOSITION CHECK: the 1254 by 1254 canvas is mostly empty pure magenta. Zoom the complete specimen OUT. Every arm, leg, wing, antenna, tail, tentacle and other part must fit within the central rectangle x=314 through x=940, y=314 through y=940. The rectangle is only an invisible placement guide: DO NOT paint a frame, line, ruler, label or grid. Make the entire animal smaller, never shorten its natural appendages to fit. Preserve detailed painted surfaces.';
const once=(s,a,b)=>{if(s.split(a).length!==2)throw Error('Unique exact edit required');return s.replace(a,b);};
const rows=[];for(const [i,name] of names.entries()){
 const id=String(i+1).padStart(2,'0')+'-'+name.toLowerCase().replaceAll(' ','-'),packet=base+'/'+id,c=await compileLibraryMaster(name,packet),r=JSON.parse(fs.readFileSync(packet+'/request.json')),sub=JSON.parse(fs.readFileSync(packet+'/subject-source.json'));let prompt=fs.readFileSync(packet+'/prompt.txt','utf8');if(sha(prompt)!==r.promptSha256)throw Error('Canonical prompt hash');
 if(overrides[name]){const old=controlledLibraryLayout(c.family,name).layout,layout=overrides[name],start=prompt.indexOf('\nSUBJECT\n'),end=prompt.indexOf('\n\nACCURACY\n'),section=prompt.slice(start,end);prompt=once(prompt,section,once(section,old,layout));prompt=once(prompt,'\n\nLAYOUT\n'+old+'\n\nTECHNICAL OUTPUT\n','\n\nLAYOUT\n'+layout+'\n\nTECHNICAL OUTPUT\n');}
 const identity='SPECIES AND ANATOMY PRIORITY: '+sub.species.mustRead.join('; ')+'.';prompt=composition+'\n\n'+identity+'\n\n'+prompt+'\n\n'+identity+'\n'+composition+'\n';
 fs.writeFileSync(packet+'/prompt.txt.tmp',prompt,{flag:'wx'});fs.renameSync(packet+'/prompt.txt.tmp',packet+'/prompt.txt');fs.writeFileSync(packet+'/request.json.tmp',JSON.stringify({...r,basePromptSha256:r.promptSha256,promptSha256:sha(prompt),batchCompilerSha256:sha(fs.readFileSync(import.meta.filename)),purpose:'NEW_ORIGINAL',layoutOverride:overrides[name]??null,layoutOverridePrecedent:overrides[name]?'audits/G2_C132_QUADRUPEDS_20261001/compile.mjs':null,compositionCheck:composition,admission:'GENERATED_CANDIDATE_ONLY; no semantic presence, rig admission or motion claim'},null,2)+'\n',{flag:'wx'});fs.renameSync(packet+'/request.json.tmp',packet+'/request.json');rows.push({id,name,family:c.family,packet,master:packet+'/master.png',purpose:'NEW_ORIGINAL'});console.log(id,c.family);
}fs.writeFileSync(base+'/pilot.json',JSON.stringify(rows,null,2)+'\n',{flag:'wx'});
fs.writeFileSync(base+'/selection.json',JSON.stringify({schema:'cf.g2-selection/v1',newOriginals:24,coverageSource:'audits/GENERATED_GALLERY_20260927/coverage.json',coveredAtSelection:184,priorPilotNames:469,excluded:'Untouched turtles, sloth and pinnipeds require appropriate shell/flipper/material support; no substitute mammal anatomy. Accepted and prior pilot subjects excluded.',rows},null,2)+'\n',{flag:'wx'});
