import{Application,Container,Graphics,Sprite,Texture,Text}from'pixi.js';
import{loadCreatureRigV1,readCreatureRigRuntimeDiagnostics}from'../../apps/game/src/creature-rig.ts';
import{compileBodyCard,buildTimeline,createGsapPlayer}from'../../apps/game/src/motion/index.ts';
import{bodyPresentationMs}from'../../apps/game/src/battle-presentation-clock.ts';
import{blendCreaturePoses,closedLoopPose}from'../../apps/game/src/motion-pose-blend.ts';
import{compileHabitatBattle,resolvePhysicalHabitat,containHabitatBody}from'../../apps/game/src/battle-habitat.ts';
import{createSourceJoinProbe,assessSourceJoinContinuity}from'../quadruped-proof/source-join-continuity.mjs';
import{primeRecorder}from'../quadruped-proof/capture-contract.mjs';
const state={status:'LOADING'};window.cfHabitatReview={state};const json=n=>fetch(n).then(r=>r.json()),bytes=n=>fetch(n).then(r=>r.arrayBuffer()),b64=b=>{let s='';const a=new Uint8Array(b);for(let i=0;i<a.length;i+=8192)s+=String.fromCharCode(...a.subarray(i,i+8192));return btoa(s);};
const image=async n=>{const b=await bytes(n),bmp=await createImageBitmap(new Blob([b])),c=new OffscreenCanvas(bmp.width,bmp.height);c.getContext('2d').drawImage(bmp,0,0);return{bytes:new Uint8Array(b),canvas:c,rgba:c.getContext('2d').getImageData(0,0,c.width,c.height).data};};
try{
 const W=1400,H=800,app=new Application();await app.init({width:W,height:H,resolution:1,background:0x142c39,antialias:true,autoStart:false,preference:'webgl'});document.body.append(app.canvas);const world=await json('world.json'),actors=[];
 for(const id of['fish','bird']){const record=await json(id+'-record.json'),binding=await json(id+'-binding.json'),paint=await image(id+'-keyed.png'),atlas=await image(id+'-atlas.png'),master=new Uint8Array(await bytes(id+'-master.png')),rig=await loadCreatureRigV1(record,binding,master,Uint8Array.from({length:paint.canvas.width*paint.canvas.height},(_,i)=>paint.rgba[i*4+3]),atlas.bytes),card=compileBodyCard(record),clips={};
  for(const action of['approach','melee','hit']){const tl=buildTimeline(card,action,record.identity.seed);let pose={};const player=createGsapPlayer(tl,{setJoint(j,rotation,dx,dy){pose[j]={rotation,dx,dy};}},{now:()=>0});clips[action]={tl,sample(ms){pose={};player.seek(ms);return pose;}};}
  const probe=createSourceJoinProbe({record,binding,atlas:{rgba:atlas.rgba,width:atlas.canvas.width,height:atlas.canvas.height}});actors.push({id,record,binding,rig,card,clips,probe,positions:()=>Object.fromEntries(binding.paintSkin.parts.map(p=>[p.id,rig.parts.find(r=>r.id===p.id).display.children[0].geometry.getBuffer('aPosition').data]))});
 }
 const recipe=compileHabitatBattle({contextId:'earth-water-air-trial',seed:133,round:0,kind:'wild',home:world,visitor:world,left:resolvePhysicalHabitat(actors[0].record),right:resolvePhysicalHabitat(actors[1].record)});if(recipe.status!=='READY')throw Error(recipe.reason);
 const scene=new Container();app.stage.addChild(scene);const bg=await image('far.png'),sky=new Sprite(Texture.from(bg.canvas));sky.width=W;sky.height=H;scene.addChild(sky);
 const waterCanvas=new OffscreenCanvas(W,H),wc=waterCanvas.getContext('2d'),gradient=wc.createLinearGradient(0,H*recipe.surfaceY,0,H);gradient.addColorStop(0,'rgba(24,83,101,.90)');gradient.addColorStop(1,'rgba(12,38,49,.98)');wc.fillStyle=gradient;wc.fillRect(0,H*recipe.surfaceY,W,H);const water=new Sprite(Texture.from(waterCanvas));scene.addChild(water);
 const rays=new Graphics();for(let i=0;i<8;i++)rays.poly([i*210,418,i*210+35,418,i*210+230,760,i*210+125,760]).fill({color:0xa7dcc2,alpha:.038});scene.addChild(rays);
 const floor=new Graphics().poly([0,745,120,725,230,747,350,729,480,753,680,736,850,750,1030,728,1210,747,1400,734,1400,800,0,800]).fill(0x182d2b);scene.addChild(floor);
 for(const a of actors)scene.addChild(a.rig.root);
 const particles=new Graphics(),surface=new Graphics(),effects=new Graphics();scene.addChild(particles,surface,effects);
 const title=new Text({text:'EARTH · WATER / AIR ENCOUNTER',style:{fontFamily:'Georgia',fontSize:25,fill:0xf8edd3}});title.position.set(35,22);app.stage.addChild(title);
 const banner=new Text({text:'',style:{fontFamily:'Georgia',fontSize:26,fill:0xffdda0}});banner.anchor.set(.5);banner.position.set(700,83);app.stage.addChild(banner);
 const damage=new Text({text:'',style:{fontFamily:'Arial',fontWeight:'bold',fontSize:35,fill:0xffecbe}});app.stage.addChild(damage);
 const footer=new Text({text:'Habitat / motion study · procedural water presentation · bird artwork pending review',style:{fontFamily:'Arial',fontSize:17,fill:0xc9dbdc}});footer.position.set(32,771);app.stage.addChild(footer);
 let seed=recipe.seed;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};const bubbles=Array.from({length:35},()=>({x:rand()*W,y:rand()*280,speed:8+rand()*18,r:1+rand()*2.4}));
 const smooth=x=>{x=Math.max(0,Math.min(1,x));return x*x*(3-2*x);},bump=(t,start,duration)=>{const p=(t-start)/duration;return p<0||p>1?0:Math.sin(Math.PI*p)**2;};
 const localBounds=a=>{let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const p of Object.values(a.positions()))for(let i=0;i<p.length;i+=2){minX=Math.min(minX,p[i]);maxX=Math.max(maxX,p[i]);minY=Math.min(minY,p[i+1]);maxY=Math.max(maxY,p[i+1]);}return{minX,minY,maxX,maxY};};
 let rigUpdates={fish:[],bird:[]};const samples=[];function stageAt(ms,collect=false){
  const turn=ms<5000?0:1,t=ms%5000,attackStart=1500,impactAt=2050,holds=actors.map((a,i)=>({atMs:i*5000+impactAt,durationMs:a.clips.melee.tl.hitstopMs})),bodyMs=bodyPresentationMs(ms,holds),turnStartMs=bodyPresentationMs(turn*5000,holds),animT=bodyMs-turnStartMs;effects.clear();particles.clear();surface.clear();
  for(const b of bubbles){const y=recipe.surfaceY*H+28+((b.y-ms*b.speed/1000)%280+280)%280;particles.circle(b.x+Math.sin(ms/1100+b.x)*4,y,b.r).stroke({color:0x99c9c7,width:1,alpha:.3});}
  surface.moveTo(0,recipe.surfaceY*H);for(let x=0;x<=W;x+=8)surface.lineTo(x,recipe.surfaceY*H+Math.sin(x*.018+ms*.0018)*2);surface.stroke({color:0xc4e3d3,width:2,alpha:.75});
  banner.text=t>1250&&t<2520?(turn===0?'WILD · SURFACE STRIKE':'WILD · DOWNDRAFT'):'';
  const centres=[];for(let i=0;i<actors.length;i++){const a=actors[i],lane=i===0?recipe.left:recipe.right,move=a.clips.approach;
   const updateStart=performance.now();let p=closedLoopPose(move.sample,bodyMs,move.tl.bodyMs);const active=i===turn,clip=a.clips[active?'melee':'hit'],start=active?attackStart:impactAt,age=animT-start;
   if(age>=0&&age<=clip.tl.durationMs){const envelope=Math.min(smooth(age/90),smooth((clip.tl.durationMs-age)/120));p=blendCreaturePoses(p,clip.sample(age),envelope);}
   a.rig.applyPose(p);rigUpdates[a.id].push(performance.now()-updateStart);const bound=localBounds(a),scale=i===0?280:260,height=(bound.maxY-bound.minY)*scale/H;
   const approach=bump(animT,1200,1550),wantedX=(i===0?.28:.72)*W+(i===0?1:-1)*approach*(active?180:12),wantedY=i===0?.71-approach*.035:.28+approach*.07;
   const centre=containHabitatBody(lane.band,wantedY,height);a.rig.root.scale.set(scale);a.rig.root.position.set(wantedX-(bound.minX+bound.maxX)/2*scale,centre*H-(bound.minY+bound.maxY)/2*scale);
   a.rig.root.tint=i!==turn&&t>=impactAt&&t<impactAt+100?0xffd9bb:i===0?0xb9e5df:0xffffff;centres.push({x:wantedX,y:centre*H});
   if(collect){const top=centre-height/2,bottom=centre+height/2,seams=assessSourceJoinContinuity(a.probe,a.positions());samples.push({ms,id:a.id,medium:lane.medium,top,bottom,status:top>=lane.band.minY-1e-6&&bottom<=lane.band.maxY+1e-6&&seams.status==='PASS'?'PASS':'FAIL',gap:seams.maxGapPx});}
  }
  const travel=(t-1750)/300;if(travel>=0&&travel<=1){const from=centres[turn],to=centres[1-turn],x=from.x+(to.x-from.x)*travel,y=from.y+(to.y-from.y)*travel;effects.moveTo(x-(to.x-from.x)*.13,y-(to.y-from.y)*.13).lineTo(x,y).stroke({color:0xdcc997,width:7,alpha:.8});effects.circle(x,y,7).fill(0xf5df9c);}
  const hit=t-impactAt;if(hit>=0&&hit<330){const c=centres[1-turn],r=18+hit*.17;effects.circle(c.x,c.y,r).stroke({color:0xf7e8b0,width:3,alpha:1-hit/330});for(let n=0;n<9;n++){const an=n*Math.PI*2/9;effects.moveTo(c.x+Math.cos(an)*r,c.y+Math.sin(an)*r).lineTo(c.x+Math.cos(an)*(r+14),c.y+Math.sin(an)*(r+14)).stroke({color:0xdcc997,width:2,alpha:1-hit/330});}}
  const c=centres[1-turn];damage.text=hit>=0&&hit<700?'24':'';damage.position.set(c.x+24,c.y-55-Math.max(0,hit)*.06);damage.alpha=1-Math.max(0,hit-350)/350;
  scene.position.set(hit>=0&&hit<140?Math.sin(hit*.12)*(1-hit/140)*4:0,0);app.renderer.render(app.stage);
 }
 async function gates(){samples.length=0;for(let ms=0;ms<=10000;ms+=1000/60)stageAt(ms,true);const failed=samples.filter(x=>x.status!=='PASS');const frozenByTurn=actors.map((a,i)=>{const start=i*5000+2050;return JSON.stringify(window.cfHabitatReview.bodySnapshot(start+1))===JSON.stringify(window.cfHabitatReview.bodySnapshot(start+a.clips.melee.tl.hitstopMs-1));}),frozen=frozenByTurn.every(Boolean);let negative=false;try{containHabitatBody(recipe.left.band,.1,.7);}catch{negative=true;}return{status:failed.length===0&&negative&&frozen?'PASS':'FAIL',samples:samples.length,failures:failed.slice(0,10),maximumGapPx:Math.max(...samples.map(x=>x.gap)),oversizedNegativeRefused:negative,hitstopBothBodiesIdentical:frozen,hitstopByTurn:frozenByTurn,recipe,cards:actors.map(a=>a.card),runtime:actors.map(a=>readCreatureRigRuntimeDiagnostics(a.rig)),scope:'actual per-frame full mesh bounds and seams; no automatic visual acceptance'};}
 async function capture(){const stream=app.canvas.captureStream(0),track=stream.getVideoTracks()[0],chunks=[],rec=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp9',videoBitsPerSecond:6000000}),stopped=new Promise(r=>rec.onstop=r);rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};let started=false;rec.onstart=()=>started=true;rec.start();await primeRecorder({started:()=>started,paint:()=>stageAt(0),requestFrame:()=>track.requestFrame(),schedule:requestAnimationFrame,now:()=>performance.now()});rigUpdates={fish:[],bird:[]};const frames=[],cpu=[];let start;try{await new Promise((resolve,reject)=>{const tick=now=>{try{start??=now;const ms=now-start,at=performance.now();stageAt(Math.min(ms,10000));track.requestFrame();cpu.push(performance.now()-at);frames.push(now);if(ms>=10000)resolve();else requestAnimationFrame(tick);}catch(e){reject(e);}};requestAnimationFrame(tick);});}finally{await new Promise(r=>setTimeout(r,120));track.requestFrame();rec.stop();await stopped;stream.getTracks().forEach(t=>t.stop());}cpu.sort((a,b)=>a-b);const perCreatureUpdateP95Ms=Object.fromEntries(Object.entries(rigUpdates).map(([id,values])=>{values.sort((a,b)=>a-b);return[id,values[Math.floor(values.length*.95)]];}));return{perCreatureUpdateP95Ms,frames:frames.length,fps:(frames.length-1)*1000/(frames.at(-1)-frames[0]),wholeFrameCpuP95Ms:cpu[Math.floor(cpu.length*.95)],video:b64(await new Blob(chunks).arrayBuffer())};}
 window.cfHabitatReview={state,gates,capture,bodySnapshot(ms){stageAt(ms);return actors.map(a=>({xy:[a.rig.root.x,a.rig.root.y],positions:Object.fromEntries(Object.entries(a.positions()).map(([k,v])=>[k,Array.from(v)]))}));},still(ms){stageAt(ms);return app.canvas.toDataURL('image/png').split(',')[1];}};state.status='READY';stageAt(0);
}catch(e){state.status='FAIL';state.error=String(e.stack??e);}
