import{makeGenome}from'../../packages/domain/genome/src/index.ts';import{planFor}from'../../packages/art/src/proceduraloverrides.ts';
import{installSpeciesCanvasFactory}from'../../packages/art/src/speciescanvas.ts';import{resolveProceduralCanvas}from'../../packages/art/src/speciesoverrides.ts';import{speciesVisualKey}from'../../packages/art/src/speciesidentity.ts';
import{sealRecord,hashBytes,hashJSON,admitRecord}from'../creature-animation/quadruped-template.mjs';import{resolvePhysicalHabitat}from'../../apps/game/src/battle-habitat.ts';
window.cfProcedural={state:{status:'RUNNING'}};const need=(x,m)=>{if(!x)throw Error(m);},png=async c=>new Uint8Array(await(await c.convertToBlob({type:'image/png'})).arrayBuffer()),b64=b=>{let s='';for(let i=0;i<b.length;i+=8192)s+=String.fromCharCode(...b.subarray(i,i+8192));return btoa(s);};
try{
 installSpeciesCanvasFactory((w,h)=>new OffscreenCanvas(w,h));const candidates=[],bodies=new Set(),selection={range:[10000,15000],scanned:0,skipped:{otherPainter:0,extraLegs:0,tailCaptureUnsupported:0,nonLand:0,duplicateBody:0}};
 for(let seed=10000;seed<15000&&candidates.length<3;seed++){selection.scanned++;const genome=makeGenome(seed,'fauna',1),plan=planFor(genome);if(plan?.kind!=='quad'){selection.skipped.otherPainter++;continue;}if(plan.spec.alien.legPairs!==2){selection.skipped.extraLegs++;continue;}if(plan.spec.tail!=='banded'){selection.skipped.tailCaptureUnsupported++;continue;}const physical=resolvePhysicalHabitat({template:{id:'quadruped'},identity:{earthName:null}},genome);if(physical.preferred!=='ground'){selection.skipped.nonLand++;continue;}if(bodies.has(genome.body)){selection.skipped.duplicateBody++;continue;}bodies.add(genome.body);candidates.push({genome,plan,physical});}
 need(candidates.length===3,'bounded seed range did not provide three candidates');const artifacts={},rows=[];
 for(let index=0;index<candidates.length;index++){const {genome,plan,physical}=candidates[index],id='procedural-'+(index+1),row={id,seed:genome.seed,body:genome.body,skin:genome.skin,plan,physical,status:'RUNNING'};rows.push(row);artifacts[id+'/genome.json']=genome;let drawn,ink;
 try{const observed=resolveProceduralCanvas(genome,(geometry,canvas)=>{drawn=geometry;ink=canvas;},true),plain=resolveProceduralCanvas(genome);need(drawn?.partMasks&&ink,'winning painter emitted no masks');const a=observed.getContext('2d').getImageData(0,0,440,440).data,b=plain.getContext('2d').getImageData(0,0,440,440).data;let changed=0;for(let i=0;i<a.length;i++)changed+=a[i]!==b[i];row.normalPainterChangedChannels=changed;need(changed===0,'observation changed ordinary paint');const original=await png(ink),rgba=ink.getContext('2d').getImageData(0,0,ink.width,ink.height).data,alpha=Uint8Array.from({length:ink.width*ink.height},(_,i)=>rgba[i*4+3]);artifacts[id+'/master.png']=b64(original);
 const landmarks=Object.fromEntries(Object.entries(drawn.landmarks).map(([n,p])=>[n,[(p[0]*drawn.width+drawn.width*.5)/ink.width,(p[1]*drawn.width+drawn.width*.5)/ink.height]]));const record=await sealRecord({kind:drawn.kind,identity:{speciesVisualKey:speciesVisualKey(genome),seed:genome.seed,ownerId:'resolveProceduralCanvas:quad/'+drawn.ownerId,earthName:null},template:{id:'quadruped',version:1},geometry:{cutoutAssetHash:await hashBytes(original),width:ink.width,height:ink.height,groundLineY:(drawn.groundLineY+.5)/2,depthLayers:[{id:'far',order:0},{id:'near',order:1}]},landmarks,materials:drawn.materials,clipSetId:'quadruped-land-v1',genome,habitat:{realm:physical.realm,source:physical.source},source:'audits/PROCEDURAL_BATTLE_ITERATION_20260916/painter-01/'+id+'/master.png'});await admitRecord(record,original,alpha);
 const masks=drawn.partMasks;let owned=0;for(let i=0;i<alpha.length;i++){need(!!alpha[i]===!!masks.labels[i],'paint ownership');owned+=alpha[i]>0;}const labels=new OffscreenCanvas(ink.width,ink.height),pixels=new Uint8ClampedArray(alpha.length*4);for(let i=0;i<alpha.length;i++)pixels.set([masks.labels[i],0,0,255],i*4);labels.getContext('2d').putImageData(new ImageData(pixels,ink.width,ink.height),0,0);const labelBytes=await png(labels),body={schema:'cf.painter-part-intake/v1',recordRecipeHash:record.recipeHash,cutoutSha256:record.geometry.cutoutAssetHash,labelsFile:'labels.png',labelsSha256:await hashBytes(labelBytes),parts:masks.parts};artifacts[id+'/record.json']=record;artifacts[id+'/labels.png']=b64(labelBytes);artifacts[id+'/declaration.json']={...body,declarationHash:await hashJSON(body)};Object.assign(row,{status:'PASS',material:record.materials.surface,paintedPixels:owned,parts:masks.parts.length,recordRecipeHash:record.recipeHash});
 }catch(e){row.status='FAIL';row.error=String(e.stack??e);}}
 window.cfProcedural={state:{status:'DONE'},report:{status:rows.every(r=>r.status==='PASS')?'PASS':'FAIL',scope:'three real generated genomes within current four-leg/banded-tail observation coverage, not universal generation',selection,rows},artifacts};
}catch(e){window.cfProcedural={state:{status:'FAIL',error:String(e.stack??e)}};}
