/** Inspect exactly the single retained candidate; no candidate regeneration. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {createFamilyContactSolver,observedContactSupports} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/apps/game/src/creature-rig-contact.ts';
import {familyContractForRecord} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/creature-animation/family-contracts.mjs';
import {createSkeletonPoseProgram} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/creature-animation/skeleton-pose.mjs';
import {createTwoBoneChain,transformPoint} from '/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/creature-animation/kinematics.ts';
const base='/Users/nick/Projects/celestial-frontier-openai-mac/audits/ARCHETYPE_FINISH_20260923/09-arachnid',inputs=[],sha=b=>createHash('sha256').update(b).digest('hex');
const read=n=>{const file=path.join(base,n),bytes=fs.readFileSync(file);inputs.push({file,sha256:sha(bytes)});return JSON.parse(bytes.toString());};
const previous=read('planar-feasibility-01.json'),record=read('fit-02/record.json'),binding=read('fit-02/binding.json');assert.equal(record.recipeHash,previous.recordRecipeHash);assert.equal(binding.bindingHash,previous.bindingHash);assert.equal(previous.candidates.length,1);
const template=familyContractForRecord(record),program=createSkeletonPoseProgram(template,record.landmarks),solver=createFamilyContactSolver(record,observedContactSupports(record,binding)),active=solver.chains.filter(c=>template.contactStance.hind.includes(c.id));
const delta=previous.candidates[0],pose=structuredClone(previous.input);pose.root={rotation:0,...pose.root,dx:(pose.root?.dx??0)+delta.x/program.bodyLength,dy:(pose.root?.dy??0)+delta.y/program.bodyLength};
const baseline=program.evaluate(previous.input),translated=program.evaluate(pose),chains=[];
for(let i=0;i<active.length;i++){const c=active[i],cross=(c.support.x-c.root.x)*(c.joint.y-c.root.y)-(c.support.y-c.root.y)*(c.joint.x-c.root.x),rigid=createTwoBoneChain({root:c.root,joint:c.joint,end:c.support,bend:cross<0?-1:1}),h=transformPoint(baseline[c.hip],c.root),actual=transformPoint(translated[c.hip],c.root),direct={x:h.x+delta.x,y:h.y+delta.y},r=previous.reach[i],preDistance=Math.hypot(r.center.x-delta.x,r.center.y-delta.y),actualDistance=Math.hypot(c.support.x-actual.x,c.support.y-actual.y),directDistance=Math.hypot(c.support.x-direct.x,c.support.y-direct.y),min=Math.abs(rigid.lengths.upper-rigid.lengths.lower),max=rigid.lengths.upper+rigid.lengths.lower;let refusal=null;
 try{rigid.solve(actual,c.support);}catch(e){refusal=String(e);}
 chains.push({id:c.id,preDistance,directDistance,actualDistance,min,max,preOuterExcess:preDistance-max,actualOuterExcess:actualDistance-max,actualOuterExcessPx:(actualDistance-max)*record.geometry.width,rootBefore:h,rootByDirectAddition:direct,rootByActualMatrices:actual,rootArithmeticDifference:{x:actual.x-direct.x,y:actual.y-direct.y},refusal});
}
const failed=chains.filter(c=>c.refusal);assert.equal(failed.length,1);assert(failed[0].preDistance<=failed[0].max);assert(failed[0].actualDistance>failed[0].max);
const report={schema:'cf.planar-candidate-boundary-diagnosis/v1',status:'STRICT_BOUNDARY_ROUNDOFF_CONFIRMED',scope:'One existing retained candidate, all four existing two-bone chains once; no candidate generation, pose search, policy integration, guard changes or publication.',recordRecipeHash:record.recipeHash,bindingHash:binding.bindingHash,delta,deltaNorm:Math.hypot(delta.x,delta.y),deltaPx:{x:delta.x*record.geometry.width,y:delta.y*record.geometry.height,norm:Math.hypot(delta.x,delta.y)*record.geometry.width},bound:previous.bound,boundPx:previous.boundPx,chains,inputs:inputs.map(r=>({...r,unchanged:sha(fs.readFileSync(r.file))===r.sha256}))};assert(report.inputs.every(r=>r.unchanged));fs.writeFileSync(path.join(base,'planar-feasibility-02.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(report));
