import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {admitReviewedExternalEarAbsence} from './ear-absence-policy.mjs';
import {admitReviewedPresence} from '../../port/v2/tools/painted-creature/reviewed-presence.mjs';
import {familyContract} from '../../port/v2/tools/creature-animation/family-contracts.mjs';
import {resolveAnatomyInventory} from '../../port/v2/tools/creature-animation/anatomy-inventory.mjs';
const base='audits/C136_SPRAWLER_REFERENCES_20261002',sha=b=>createHash('sha256').update(b).digest('hex'),load=(packet,review)=>({masterBytes:fs.readFileSync(packet+'/master.png'),subjectBytes:fs.readFileSync(packet+'/subject-source.json'),promptBytes:fs.readFileSync(packet+'/prompt.txt'),review:JSON.parse(fs.readFileSync(review))});
const original=load('audits/G2_C132_QUADRUPEDS_20261001/15-iguana',base+'/reviews/15-iguana.json'),checks=[];
const check=(name,run,expect)=>{let actual='PASS';try{run();}catch{actual='REFUSE';}checks.push({name,expected:expect,actual});if(actual!==expect)throw Error('Unexpected policy outcome: '+name);};
for(const row of JSON.parse(fs.readFileSync(base+'/reviewed-presence.json')))check('exact original '+row.id,()=>admitReviewedExternalEarAbsence(load('audits/G2_C132_QUADRUPEDS_20261001/'+row.id,row.review)),'PASS');
const mutate=(name,fn)=>check(name,()=>{const x={...original,review:structuredClone(original.review)};fn(x);admitReviewedExternalEarAbsence(x);},'REFUSE');
for(const key of ['masterBytes','subjectBytes','promptBytes'])mutate('changed '+key,x=>x[key]=Buffer.concat([x[key],Buffer.from(' ')]));
mutate('different canonical name',x=>x.review.name='Cat');
mutate('profile assertion changed',x=>x.review.profileId='felid');
mutate('profile hash changed',x=>x.review.profileSha256='0'.repeat(64));
mutate('modified canonical species with rebound bytes',x=>{const s=JSON.parse(x.subjectBytes);s.species.mustRead.push('invented ear rule');x.subjectBytes=Buffer.from(JSON.stringify(s));x.review.subjectSha256=sha(x.subjectBytes);});
mutate('unreviewed juvenile context',x=>x.review.context.lifeStage='juvenile');
mutate('non-grounded context',x=>x.review.context.pose='swimming');
mutate('absent mandatory limb',x=>x.review.review.decisions[0].group='foreNear');
mutate('extra tail absence',x=>x.review.review.decisions.push({group:'tail',decision:'ABSENT'}));
mutate('hidden external ear is not absence',x=>x.review.review.decisions[0].decision='HIDDEN');
mutate('ear opening is not a pinna',x=>x.review.review.decisions[0].anatomicalMeaning='all-ear-anatomy');
mutate('missing visual observation',x=>x.review.review.observation='');
mutate('blank reviewer',x=>x.review.review.reviewer='');
mutate('blank painting observation',x=>x.review.review.decisions[0].paintingObservation='');
mutate('blanket class scope',x=>x.review.scope='all-reptiles');
check('mammal with internally consistent subject still refuses',()=>{const x=load('audits/C132_REFERENCES_20261001/04-cat/candidate-02',base+'/reviews/15-iguana.json'),s=JSON.parse(x.subjectBytes);Object.assign(x.review,{name:s.name,masterSha256:sha(x.masterBytes),subjectSha256:sha(x.subjectBytes),promptSha256:sha(x.promptBytes),profileId:s.profile.id,profileSha256:sha(JSON.stringify(s.profile))});admitReviewedExternalEarAbsence(x);},'REFUSE');
check('production policy remains tail-only',()=>admitReviewedPresence(original),'REFUSE');
check('ear absence preserves mandatory geometry',()=>{const before=familyContract('quadruped'),after=resolveAnatomyInventory(before,admitReviewedExternalEarAbsence(original));for(const k of ['legs','proportions','bounds'])if(JSON.stringify(before[k])!==JSON.stringify(after[k]))throw Error('Changed mandatory '+k);for(const joint of ['root','pelvis','spine','chest','neck','head','jaw','tail0','tail1','tail2','tail3',...before.joints.filter(j=>!j.startsWith("ear"))])if(!after.joints.includes(joint))throw Error('Lost mandatory '+joint);},'PASS');
check('manual packets declare exactly the remaining inventory',()=>{const inv=resolveAnatomyInventory(familyContract('quadruped'),admitReviewedExternalEarAbsence(original));for(const row of JSON.parse(fs.readFileSync(base+'/pilot.json'))){const a=JSON.parse(fs.readFileSync(row.packet+'/authoring.json'));if(JSON.stringify(Object.keys(a.landmarksPx).sort())!==JSON.stringify([...inv.joints].sort()))throw Error('Manual inventory mismatch');}},'PASS');
fs.writeFileSync(base+'/policy-checks.json',JSON.stringify({scope:'Pure admission proposal and mutation controls only; no intake/static/native run.',productionChanged:false,pass:checks.every(c=>c.expected===c.actual),checks},null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({checks:checks.length,pass:true,productionChanged:false}));
