import fs from'node:fs';import path from'node:path';import{createRequire}from'node:module';import{createHash}from'node:crypto';
import{buildPaintSkin}from'../../port/v2/tools/creature-animation/build-paint-skin.mjs';import{splitObservedSurfaces}from'../../port/v2/tools/creature-animation/split-observed-surfaces.mjs';import{familyContractForRecord,familyContactChains}from'../../port/v2/tools/creature-animation/family-contracts.mjs';import{hashJSON}from'../../port/v2/tools/creature-animation/quadruped-template.mjs';import{createSourceJoinProbe}from'../../port/v2/tools/quadruped-proof/source-join-continuity.mjs';
const req=createRequire(path.resolve('port/v2/package.json')),sharp=createRequire(req.resolve('free-tex-packer-core'))('sharp'),base=path.dirname(new URL(import.meta.url).pathname),hash=b=>createHash('sha256').update(b).digest('hex'),four='audits/VISION_P1_FOUR_CRABS_20260920',subjects=[{id:'coconut-crab',dir:'audits/VISION_P1_COCONUT_20260920/hidden-01/fit-04'},...['crab','freshwater-crab','mud-crab'].map(id=>({id,dir:four+'/intake-02/'+id+(id==='freshwater-crab'?'-fit-03':'-fit-01')})),{id:'vent-crab',dir:four+'/intake-01/vent-crab-fit-01'}],series=[];
for(const subject of subjects){const record=JSON.parse(fs.readFileSync(subject.dir+'/record.json')),original=JSON.parse(fs.readFileSync(subject.dir+'/binding.json')),manifest=JSON.parse(fs.readFileSync(subject.dir+'/parts/manifest.json')),atlasFile=subject.dir+'/parts/atlas/'+manifest.creatureId+'.png',atlas=await sharp(atlasFile).ensureAlpha().raw().toBuffer({resolveWithObject:true}),seen=new Map();
 for(const[boundaryStep,interiorStep]of[[24,56],[24,80],[24,128],[24,256],[32,56],[48,56]]){const key=subject.id+'-b'+boundaryStep+'-i'+interiorStep;let dir=subject.dir,binding=original,receipt=null;
  if(boundaryStep!==24||interiorStep!==56){if(subject.id==='coconut-crab'&&boundaryStep===24){dir='audits/VISION_P1_ANIMATION_20260920/cpu-'+interiorStep;binding=JSON.parse(fs.readFileSync(dir+'/binding.json'));}else{dir=path.relative(process.cwd(),path.join(base,'candidates',key));if(fs.existsSync(dir+'/binding.json')){binding=JSON.parse(fs.readFileSync(dir+'/binding.json'));}else{fs.mkdirSync(dir,{recursive:true});fs.copyFileSync(subject.dir+'/record.json',dir+'/record.json');if(!fs.existsSync(dir+'/parts'))fs.symlinkSync(path.relative(path.resolve(dir),path.resolve(subject.dir+'/parts')),dir+'/parts','dir');
 const built=await buildPaintSkin(subject.dir+'/parts',{seamBridges:{groups:[]}},record,{boundaryStep,interiorStep,includeTopology:true}),{bindingHash,...body}=built.binding;body.sourceJoinTopology={remainderPartId:'body'};const input={...body,bindingHash:await hashJSON(body)},probe=createSourceJoinProbe({record,binding:input,atlas:{rgba:atlas.data,width:atlas.info.width,height:atlas.info.height}}),split=await splitObservedSurfaces(input,record,probe,{fixedJoints:['root'],contactEndpoints:familyContactChains(familyContractForRecord(record)).map(c=>c.end),shapeJoints:original.parts.filter(p=>p.joint!=='root').map(p=>p.joint)});binding=split.binding;receipt=split.receipt;fs.writeFileSync(dir+'/binding.json',JSON.stringify(binding,null,2)+'\n');fs.writeFileSync(dir+'/receipt.json',JSON.stringify({boundaryStep,interiorStep,source:subject.dir,partsUnchanged:true,atlasSha256:hash(fs.readFileSync(atlasFile)),surfaces:receipt},null,2)+'\n');}}}
 const identity=hash(fs.readFileSync(dir+'/binding.json')),alias=seen.get(identity);if(!alias)seen.set(identity,key);const row={subject:subject.id,key,boundaryStep,interiorStep,fieldVertices:binding.paintSkin.vertices.length,parts:binding.parts.length,dir,bindingSha256:identity,recordSha256:hash(fs.readFileSync(dir+'/record.json')),atlasSha256:hash(fs.readFileSync(atlasFile)),...(alias?{aliasOf:alias}:{}),...(subject.id==='coconut-crab'&&boundaryStep===24&&interiorStep===56?{retainedNative:'audits/VISION_P1_COCONUT_20260920/hidden-01/native-02'}:{})};series.push(row);console.log(JSON.stringify({key,vertices:row.fieldVertices,alias}));
 }
}
fs.writeFileSync(base+'/series.json',JSON.stringify({scope:'Only boundary/interior tessellation; no part, mask, atlas, landmark, raw clip, solver or threshold edits',subjects,rows:series},null,2)+'\n');
