/** One same-path native run per distinct binding; aliases never re-run. */
import fs from'node:fs';import path from'node:path';import{spawnSync}from'node:child_process';import{gzipSync}from'node:zlib';
const base=path.dirname(new URL(import.meta.url).pathname),series=JSON.parse(fs.readFileSync(base+'/series.json')),results=[];fs.mkdirSync(base+'/native',{recursive:true});
for(const row of series.rows){if(row.aliasOf){const prior=results.find(p=>p.key===row.aliasOf);if(!prior)throw Error('Alias predecessor missing');results.push({...row,metrics:prior.metrics,evidence:prior.evidence,measuredOnceAs:prior.key});continue;}let dir=row.retainedNative??path.relative(process.cwd(),base+'/native/'+row.key);
 if(!row.retainedNative){if(fs.existsSync(dir))throw Error('Native output already exists; inspect before explicit continuation');const log=base+'/native/'+row.key+'.log',fd=fs.openSync(log,'wx');let result;try{result=spawnSync(process.execPath,['port/v2/tools/animation-completion/native-runner.mjs',row.dir,'port/v2/apps/game/src',dir,'melee:pinch'],{stdio:['ignore',fd,fd],timeout:240000});}finally{fs.closeSync(fd);}fs.writeFileSync(log+'.gz',gzipSync(fs.readFileSync(log)));fs.unlinkSync(log);if(result.error)throw result.error;}
 const reportFile=dir+'/report.json',report=JSON.parse(fs.readFileSync(reportFile)),g=report.gates,c=report.capture,metrics={status:report.status,approachP95Ms:g?.rows?.find(r=>r.id==='approach')?.updateP95Ms??null,fullFilmP95Ms:c?.rigUpdateP95Ms??null,maxGapPx:g?Math.max(...(g.rows??[]).map(r=>r.maxGapPx??0),g.presentation?.maxGapPx??0):null,maxPlantedDriftPx:g?.contacts?.maxPaintContactDriftPx??null,restChanged:g?.restChanged??null,finalRestChanged:g?.finalRestChanged??null,geometryFailures:g?.rows?.filter(r=>r.failure)??[],presentationFailure:g?.presentation?.failure??null,rootContinuity:g?.rootContinuity??null,error:report.error??null};
 const result={...row,evidence:dir,sourceHead:report.source,metrics};results.push(result);fs.writeFileSync(base+'/native-results.json',JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify({key:row.key,vertices:row.fieldVertices,...metrics,geometryFailures:metrics.geometryFailures.map(r=>({id:r.id,failure:r.failure}))}));
 if(g&&(g.restChanged!==0||g.finalRestChanged!==0)){fs.writeFileSync(base+'/S2_STOP.json',JSON.stringify({reason:'exact-rest red',key:row.key,metrics},null,2)+'\n');throw Error('S2 exact-rest red');}
 if(!g)throw Error('Native instrument did not produce gates; retained for diagnosis');
 if(!row.retainedNative){fs.writeFileSync(reportFile+'.gz',gzipSync(fs.readFileSync(reportFile)));fs.writeFileSync(dir+'/summary.json',JSON.stringify({key:row.key,sourceHead:report.source,browser:report.browser,metrics},null,2)+'\n');fs.unlinkSync(reportFile);}
}
fs.writeFileSync(base+'/native-results.json',JSON.stringify(results,null,2)+'\n');
