/** Read-only 60Hz native-schedule root ledger. Renderer/CPU not inferred. */
import fs from'node:fs';import assert from'node:assert/strict';import{createHash}from'node:crypto';import{gzipSync}from'node:zlib';
import{compileBodyCard}from'../../port/v2/apps/game/src/motion/body-card.ts';
import{buildTimeline}from'../../port/v2/apps/game/src/motion/timeline.ts';
import{actionsFor}from'../../port/v2/apps/game/src/motion/family-actions.ts';
import{createGsapPlayer}from'../../port/v2/apps/game/src/motion/gsap-adapter.ts';
import{createFamilyContactSolver,observedContactSupports}from'../../port/v2/apps/game/src/creature-rig-contact.ts';
import{createCreatureRigPerformance}from'../../port/v2/apps/game/src/creature-rig-performance.ts';
import{blendCreaturePoses,closedLoopPose}from'../../port/v2/apps/game/src/motion-pose-blend.ts';
import{createFullRowSchedule}from'../../port/v2/tools/animation-completion/review-schedule.mjs';
import{createStageTravel,assessRootContinuity}from'../../port/v2/apps/game/src/creature-stage-travel.ts';
import{createSkeletonPoseProgram}from'../../port/v2/tools/creature-animation/skeleton-pose.mjs';
import{familyContractForRecord}from'../../port/v2/tools/creature-animation/family-contracts.mjs';
const base='audits/VISION_P1_CONSOLIDATED_20260920',out=process.argv[2],sha=b=>createHash('sha256').update(b).digest('hex');if(fs.existsSync(out))throw Error('New ledger output required');fs.mkdirSync(out);
const native=fs.readFileSync('port/v2/tools/animation-completion/native-entry.mjs','utf8'),start='const smooth=x=>',end='const presentationOwner=';assert.equal(native.split(start).length,2);assert.equal(native.split(end).length,2);const presentationSource=start+native.split(start)[1].split(end)[0];
const subjects=['crab','coconut-crab','freshwater-crab','mud-crab','vent-crab'].map(id=>({id:'painter-'+id,dir:'audits/ANATOMY_COMPLETION_20260917/crab-fits-03/'+id})).concat([{id:'painted-coconut-crab',dir:'audits/VISION_P1_COCONUT_20260920/hidden-01/fit-04'}]);
const ledger={schema:'cf.root-continuity-ledger/v1',sampleHz:60,nativeSourceSha256:sha(native),scope:'All full native rows with transitions; same GSAP, performance owner, contact solver, persistent stage travel; root kinematics only, no CPU/pixel claim.',subjects:[],controls:[]};
for(const subject of subjects)for(const mutant of[false,true]){
 const read=n=>JSON.parse(fs.readFileSync(subject.dir+'/'+n)),record=read('record.json'),binding=read('binding.json'),card=compileBodyCard(record,record.genome),timelines={},players={},stops=[],mutations=[];
 for(const id of new Set(['idle','approach','melee:pinch','hit',...Object.keys(actionsFor(card.template.id,card.anatomy))])){const tl=structuredClone(buildTimeline(card,id,record.identity.seed));if(mutant&&id==='faint'){const k=tl.root.dy.reduce((a,b)=>Math.abs(a.value)>Math.abs(b.value)?a:b);mutations.push({action:id,keyBefore:{...k},rule:'Double peak key that begins faint recovery; all times, other keys, joint tracks unchanged'});k.value*=2;mutations[0].keyAfter={...k};}timelines[id]=tl;let p={};const owner=createGsapPlayer(tl,{setJoint(j,rotation,dx,dy){p[j]={rotation,dx,dy};}},{now:()=>0});stops.push(()=>owner.stop());players[id]={sample(ms){p={};owner.seek(ms);return p;}};}
 const makePresentation=new Function('players','timelines','idleId','closedLoopPose','blendCreaturePoses','createFullRowSchedule',presentationSource+'return {presentedPose,schedule,durationMs,isGait};'),{presentedPose,schedule,durationMs,isGait}=makePresentation(players,timelines,'idle',closedLoopPose,blendCreaturePoses,createFullRowSchedule),contact=createFamilyContactSolver(record,observedContactSupports(record,binding)),program=createSkeletonPoseProgram(familyContractForRecord(record),record.landmarks),direction=Math.sign(record.landmarks.leg0NearRoot[0]-record.landmarks.leg0FarRoot[0]),stageTravel=createStageTravel(schedule.rows.flatMap(({id,startMs,endMs})=>isGait(id)?[{startMs,endMs,distance:direction*contact.stride*(endMs-startMs)/timelines[id].durationMs}]:[])),rig={recipeHash:record.recipeHash,templateId:record.template.id,applyPose(){}},owner=createCreatureRigPerformance(record,rig,[{id:'presentation',durationMs,loop:false,dispose(){},seek(ms,target){for(const[j,k]of Object.entries(presentedPose(ms).p))target.setJoint(j,k.rotation,k.dx,k.dy);}}]);owner.play('presentation',0,0);
 const samples=[],rows=Object.fromEntries(schedule.rows.map(r=>[r.id,{...r,samples:0,maximumStep:0,maximumStepPx:0,maximumStepScale:0,worstMs:null}]));let failure=null;
 try{for(let i=0;i<=Math.ceil(durationMs*60/1000);i++){const ms=Math.min(durationMs,i*1000/60),shown=presentedPose(ms),pose=owner.update(ms,p=>contact.resolve(p,{...shown.phase,realm:card.realm,...shown.phase.actionId.startsWith('melee:')?{travel:'stage'}:{}}).pose),localX=(pose.root?.dx??0)*program.bodyLength,offset=stageTravel(ms)-(/^approach:(walk|trot|gallop|crawl|scuttle)$/.test(shown.phase.actionId)?localX:0),sample={ms,action:shown.name,gait:isGait(shown.name),x:offset+localX,y:(pose.root?.dy??0)*program.bodyLength};samples.push(sample);const row=rows[shown.name];row.samples++;if(samples.length>1){const prev=samples.at(-2),step=Math.hypot(sample.x-prev.x,sample.y-prev.y);if(step>row.maximumStep)Object.assign(row,{maximumStep:step,maximumStepPx:step*record.geometry.height,maximumStepScale:step/card.scaleLength,worstMs:ms,fromAction:prev.action});}}}catch(e){failure=String(e.stack??e);}finally{stops.forEach(s=>s());}
 const result={...subject,mutant,mutations,recordSha256:sha(fs.readFileSync(subject.dir+'/record.json')),bindingSha256:sha(fs.readFileSync(subject.dir+'/binding.json')),width:record.geometry.width,height:record.geometry.height,stride:contact.stride,scaleLength:card.scaleLength,durationMs,rows:Object.values(rows),failure,oldGuard:samples.length>1?assessRootContinuity(samples,contact.stride):null,samplesFile:subject.id+(mutant?'-mutant':'')+'-samples.jsonl.gz'};fs.writeFileSync(out+'/'+result.samplesFile,gzipSync(samples.map(x=>JSON.stringify(x)).join('\n')+'\n'));(mutant?ledger.controls:ledger.subjects).push(result);fs.writeFileSync(out+'/ledger.json',JSON.stringify(ledger,null,2)+'\n');console.log(JSON.stringify({id:subject.id,mutant,failure,max:result.oldGuard?.maximumStep,rows:result.rows.map(r=>[r.id,r.maximumStepPx,r.maximumStepScale])}));
 if(!mutant){assert.equal(failure,null,'Production path must complete');if(subject.id==='painted-coconut-crab'){const prior=JSON.parse(fs.readFileSync(subject.dir.replace('/fit-04','/native-02')+'/report.json'));assert(Math.abs(result.oldGuard.maximumStep-prior.gates.rootContinuity.maximumStep)<1e-12,'Ledger must reproduce native Coconut maximum');}}
}
console.log('Ledger complete');
