import fs from 'node:fs';import {gzipSync} from 'node:zlib';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {createRequire} from 'node:module';import {fixture,contactRows,supportResiduals,hashes} from '../ANATOMY_SINGLE_RUN_20260919/R3-S/offline.ts';
import {createSourceJoinProbe,assessSourceJoinContinuity} from '../../port/v2/tools/quadruped-proof/source-join-continuity.mjs';
const out='audits/VISION_P1_CONSOLIDATED_20260920/shared-controls',base='audits/ANATOMY_COMPLETION_20260917',order=['crab','coconut-crab','freshwater-crab','mud-crab','vent-crab','civet'],result={status:'RUNNING',baseHead:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),signedProducer:true,sourceState:'Signed consolidated painted-contact-range producer; retained five crabs and Civet, unchanged inputs; no native/CPU certification.',runtime:process.version,subjects:[],unrun:[],scope:'One ordered actual source-bound GSAP/performance/contact/compiled-field/ARAP and Float32-part static sweep. Stops at first shared red, no retry. CPU and native pixel parity not inferred.'};
fs.mkdirSync(out);
const req=createRequire(process.cwd()+'/port/v2/package.json'),{PNG}=createRequire(req.resolve('free-tex-packer-core'))('pngjs');
for(const subject of order){const folder=subject==='civet'?'../ANATOMY_SINGLE_RUN_20260919/R3-S/civet-input-01':'crab-fits-03/'+subject,f=fixture(folder),row={subject,status:'PASS',rows:[],maxPaintDriftPx:0,maxEndpointError:0,maxGapPx:0,exactRestGeometry:null};result.subjects.push(row);let action=null,ms=null;const samples=[];const logSample=pose=>{const contacts=supportResiduals(f,pose);row.maxCovariancePx=Math.max(row.maxCovariancePx??0,...contacts.map(c=>Math.hypot(...c.modelToTriangleResidualPx)));row.maxArapPublicationPx=Math.max(row.maxArapPublicationPx??0,...contacts.map(c=>Math.hypot(...c.arapResidualPx)));assert(row.maxCovariancePx<=1e-6,'exact triangle covariance <=1e-6 px');samples.push(JSON.stringify({action,ms,contacts}));row.lastResiduals=contacts;};
 try{
 const manifest=JSON.parse(fs.readFileSync(base+'/'+folder+'/parts/manifest.json')),atlas=PNG.sync.read(fs.readFileSync(base+'/'+folder+'/parts/atlas/'+manifest.creatureId+'.png')),probe=createSourceJoinProbe({record:f.record,binding:f.binding,atlas:{width:atlas.width,height:atlas.height,rgba:atlas.data}});
 f.rig.applyPose({});const rest=structuredClone(f.positions);
 const oldReport=JSON.parse(fs.readFileSync(base+'/'+(subject==='civet'?'civet-sentinel-native-01':subject+'-native-04')+'/report.json')),ids=oldReport.gates.rows.map(r=>r.id);
 for(const id of ids){action=id;f.player(id);const rr={id,samples:0,maxPaintDriftPx:0,maxEndpointError:0,maxGapPx:0};row.rows.push(rr);
  for(let i=0;i<=120;i++){ms=f.timelines[id].durationMs*i/120;const pose=f.action(id,ms),contacts=contactRows(f,pose),seams=assessSourceJoinContinuity(probe,f.positions);logSample(pose);rr.maxEndpointError=Math.max(rr.maxEndpointError,f.lastContact.maxError);rr.maxGapPx=Math.max(rr.maxGapPx,seams.maxGapPx);rr.maxPaintDriftPx=Math.max(rr.maxPaintDriftPx,...contacts.map(c=>c.driftPx),0);row.maxEndpointError=Math.max(row.maxEndpointError,rr.maxEndpointError);row.maxGapPx=Math.max(row.maxGapPx,rr.maxGapPx);row.maxPaintDriftPx=Math.max(row.maxPaintDriftPx,rr.maxPaintDriftPx);rr.samples++;
   assert(f.lastContact.maxError<=1e-8,'endpoint gate');assert(seams.status==='PASS','source join gate');
   const bad=contacts.find(c=>c.driftPx>.25);if(bad){row.paintFailure=bad;throw Error('Actual painted support '+bad.joint+' drift '+bad.driftPx+' px >0.25');}
  }
  f.rig.applyPose({});assert.deepEqual(f.positions,rest,'exact rest geometry');row.exactRestGeometry=true;
 }
 action='presentation';row.presentation={samples:0};for(let i=0;i<=600;i++){ms=i*1000/60;const pose=f.presentation(ms),contacts=contactRows(f,pose),seams=assessSourceJoinContinuity(probe,f.positions);logSample(pose);assert(seams.status==='PASS','source join gate');const bad=contacts.find(c=>c.driftPx>.25);if(bad){row.paintFailure=bad;throw Error('Actual painted support '+bad.joint+' drift '+bad.driftPx+' px >0.25');}row.presentation.samples++;}
 f.rig.applyPose({});assert.deepEqual(f.positions,rest,'final exact rest geometry');
 if(subject!=='civet'){const prior=JSON.parse(fs.readFileSync('audits/ANATOMY_SINGLE_RUN_20260919/R2c-prime/'+subject+'-static.json'));assert.deepEqual(row.rows,prior.rows,'five-crab bit-identical R2c-prime rows');assert.deepEqual(row.presentation,prior.presentation,'same presentation sample count');row.r2cRowsBitIdentical=true;}
 }catch(e){row.status='SHARED_PATH_RED';row.failure={action,ms,error:String(e.stack??e)};row.solver=f.lastContact??null;row.arapStats={...f.scratch.stats};row.rawPose=action&&action!=='presentation'?f.player(action).sample(ms):null;result.status='S2_STOP';result.unrun=order.slice(order.indexOf(subject)+1);}
 finally{f.close();fs.writeFileSync(out+'/'+subject+'-support-samples.jsonl.gz',gzipSync(samples.join('\n')+'\n'),{flag:'wx'});fs.writeFileSync(out+'/'+subject+'-static.json',JSON.stringify(row,null,2)+'\n',{flag:'wx'});}
 console.log(JSON.stringify({subject,status:row.status,rows:row.rows.map(r=>({id:r.id,samples:r.samples,drift:r.maxPaintDriftPx})),failure:row.failure}));if(result.status==='S2_STOP')break;
}
if(result.status==='RUNNING')result.status='PASS_STATIC';result.inputs=[...hashes].map(([path,sha256])=>({path,sha256}));fs.writeFileSync(out+'/static.json',JSON.stringify(result,null,2)+'\n',{flag:'wx'});if(result.status!=='PASS_STATIC')process.exitCode=1;
