/* Capture-environment hooks for the Descriptors domain module.

   The verbatim body calls five app-layer names as FREE identifiers. In ESM
   they resolve through the global scope, so consumers install faithful
   stand-ins BEFORE calling any descriptor. Two kinds live here:

   1. VERBATIM CARRIES (apphooks.verbatim.js, machine-extracted): the side
      cache _cardFactsSet, Nick's cradle roster _EARTH_NAMES/_earthNamePass
      (it mutates g._earthName — that lands in captured output), and the pure
      GAL_KIND derivation.

   2. CAPTURE STUBS (here): the six *Thumb functions. The fixtures were
      captured under jsdom, whose canvas stub pins every drawn thumb to the
      constant "data:image/png;base64," — reproducing THAT constant is the
      parity contract, not drawing art. planetThumb has one real side effect
      the capture environment performed: drawing a gas planet runs
      surfaceColor, which caches P._pal = gasPalette(P) onto the MEMOIZED
      planet object — the systemSol fingerprint encodes exactly that
      mutation, so the stub replays it with a single surfaceColor call.

   Phase 2+ replaces these with the real app implementations; the domain
   body never changes either way. */
import { surfaceColor } from '@cf/domain-planetgen';
import { _cardFactsSet, GAL_KIND, GAL_SPRITE_SEEDS, _EARTH_NAMES as _EARTH_NAMES_V1 } from './apphooks.verbatim.js';

/* ★ D-CAT-1 — THE DEDUPED v2 ROSTER (approved deviation, 2026-08-02).

   Four organisms appeared in TWO kingdoms each, so the catalogue carried 1,014
   records for 1,010 real organisms and the external audit flagged all four as
   canonical-ownership blockers. Nick's call: collapse them, deliberately, as a
   v2 roster change.

   ⚠ WHY IT IS HERE AND NOT IN THE VERBATIM FILE. apphooks.verbatim.js is
   auto-lifted byte-for-byte from main.js v1.8.9, carries a sha256 and a
   DO-NOT-EDIT banner, and is regenerated by tools/lift-apphooks.mjs. An edit
   there would break the parity contract and be silently reverted by the next
   lift. The verbatim body is untouched; the deviation lives in this owned
   wrapper, and re-lifting cannot undo it.

   ⚠ WHAT IT COSTS, ACCEPTED KNOWINGLY. Earth names are handed out by
       i = (g.seed >>> 0) % pool.length
   so changing a pool's length reassigns the Earth name of every generated
   species in every world, and old share codes will name different creatures.
   That is the deliberate part. It is not a defect to be repaired by putting
   the duplicates back.

   WHICH KINGDOM KEEPS EACH, and why:
     · Tardigrade      → FAUNA.   It is an animal. The audit's own words:
                                  "keep one authoritative animal record".
     · Reindeer Lichen → FUNGI.   A lichen is a fungal symbiosis and is filed
                                  with the fungi by convention.
     · Snow Algae      → MICROBE. A microalga; the snow bloom IS the microbe
                                  presentation.
     · Green Algae     → FLORA.   Kept as the macroalga a player can actually
                                  see and harvest; the microbe kingdom already
                                  carries Cyanobacteria and Diatom for the
                                  microscopic case. */
const _DEDUPE: Readonly<Record<string, readonly string[]>> = {
  microbe: ['Tardigrade', 'Green Algae'],
  flora: ['Reindeer Lichen', 'Snow Algae'],
};

export const _EARTH_NAMES: Readonly<Record<'fauna' | 'flora' | 'fungi' | 'microbe', readonly string[]>> =
  Object.freeze(Object.fromEntries(
    Object.entries(_EARTH_NAMES_V1 as Record<string, readonly string[]>).map(([k, names]) => {
      const drop = _DEDUPE[k];
      return [k, Object.freeze(drop ? names.filter((n) => !drop.includes(n)) : names.slice())];
    }),
  )) as Readonly<Record<'fauna' | 'flora' | 'fungi' | 'microbe', readonly string[]>>;

/** the verbatim name pass, re-pointed at the deduped roster. The ALGORITHM is
    unchanged — same modulo, same linear probe, same mutation of g._earthName —
    so this is a data deviation and not a behavioural one. */
export function _earthNamePass(list: Array<Record<string, unknown>>): void {
  const used: Record<string, Set<number>> = {
    fauna: new Set(), flora: new Set(), fungi: new Set(), microbe: new Set(),
  };
  for (const g of list) {
    const kingdom = String(g.kingdom ?? 'fauna');
    const pool = _EARTH_NAMES[kingdom as 'fauna'] ?? _EARTH_NAMES.fauna;
    const u = used[kingdom] ?? used.fauna!;
    let i = ((g.seed as number) >>> 0) % pool.length, guard = 0;
    while (u.has(i) && guard++ < pool.length) i = (i + 1) % pool.length;
    u.add(i);
    g._earthName = pool[i];
  }
}

/** jsdom's canvas.toDataURL() output at capture — every fixture thumb value. */
export const CAPTURE_THUMB = 'data:image/png;base64,';

const flatNoise = (() => 0.5) as unknown as Parameters<typeof surfaceColor>[3];

function planetThumb(P: { type?: string; _pal?: unknown }): string {
  /* replay the capture's one observable side effect (gas palette cache);
     surfaceColor itself guards `if(!P._pal)`, so this is idempotent */
  if (P && P.type === 'gas' && !P._pal) surfaceColor(P as never, 0, 0, flatNoise);
  return CAPTURE_THUMB;
}
const starThumb = (): string => CAPTURE_THUMB;
const galaxyThumb = (): string => CAPTURE_THUMB;
const moonThumb = (): string => CAPTURE_THUMB;
const cometThumb = (): string => CAPTURE_THUMB;
const beltThumb = (): string => CAPTURE_THUMB;

/** Install the capture-environment hooks on globalThis (idempotent; never
    overwrites an existing binding, so a future app layer wins by default). */
export function installCaptureHooks(): void {
  const g = globalThis as Record<string, unknown>;
  const hooks: Record<string, unknown> = {
    _cardFactsSet, _earthNamePass, GAL_KIND,
    planetThumb, starThumb, galaxyThumb, moonThumb, cometThumb, beltThumb,
    /* ★ found by the real-input tests, 2026-07-31: worldgen's galaxiesInCell
       reads GAL_SPRITES.length for the sprite-pool size — a free identifier
       NO fixture path executed (all three probed cells are empty), so an
       uncached ordinary generated-galaxy branch threw while parity stayed
       green. Empty, special-only and cached branches may not read it. Only the
       length is read; derive it from the verbatim seed pool. */
    GAL_SPRITES: new Array(GAL_SPRITE_SEEDS.length).fill(null),
  };
  for (const [k, v] of Object.entries(hooks)) if (g[k] === undefined) g[k] = v;
}
