import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),sharp=createRequire(require.resolve('free-tex-packer-core'))('sharp'),root=path.resolve(import.meta.dirname,'../../../..'),packet=path.resolve(process.argv[2]??'');if(process.argv.length!==3)throw Error('Usage: roster-sheets.mjs ROSTER_PACKET');
const report=JSON.parse(await fs.readFile(path.join(packet,'native-01/report.json')));if(report.counts.total!==58||new Set(report.rows.map(r=>r.id)).size!==58)throw Error('Incomplete roster sheet inventory');
const out=path.join(packet,'sheets');await fs.mkdir(out);const receipt={sourceCommit:report.sourceCommit,maximumSubjectsPerSheet:12,subjects:0,sheets:[],sources:[]},sha=b=>createHash('sha256').update(b).digest('hex'),esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;');
for(const family of report.families){const rows=report.rows.filter(r=>r.profile===family.profile);for(let first=0;first<rows.length;first+=12){
 const page=rows.slice(first,first+12),W=1800,H=1740,layers=[];const label=(s,x,y,size=22,color='#dfe8ea')=>layers.push({left:x,top:y,input:Buffer.from(`<svg width="${W-x}" height="40"><text x="0" y="29" font-family="sans-serif" font-size="${size}" fill="${color}">${esc(s)}</text></svg>`)});
 label(family.profile+' — '+(first/12+1),24,12,32);label('Source paint review · refused fits stay static · five existing crab films linked in ledger',24,55,22);
 for(const [i,row]of page.entries()){
  const x=20+(i%3)*600,y=112+Math.floor(i/3)*400;label(row.name,x,y,28);label(row.status==='REUSE_COMPLETED'?'FIT / BIND / FILM retained':'FIT REFUSED · binding skipped',x,y+36,20,row.status==='REUSE_COMPLETED'?'#b9e4b5':'#ffbf9e');
  let file;if(row.status==='REUSE_COMPLETED'){const record=JSON.parse(await fs.readFile(path.join(root,'audits/ANATOMY_COMPLETION_20260917/crab-fits-03',row.id,'record.json')));file=path.resolve(root,record.source);}else if(row.sourceMaster)file=path.join(packet,'native-01',row.sourceMaster);
  if(file){const bytes=await fs.readFile(file);receipt.sources.push({id:row.id,file:path.relative(root,file),sha256:sha(bytes)});const sprite=await sharp(bytes).trim().resize(550,225,{fit:'inside'}).png().toBuffer(),m=await sharp(sprite).metadata();layers.push({input:sprite,left:x+Math.floor((560-m.width)/2),top:y+85+Math.floor((225-m.height)/2)});}
  const text=row.status==='REUSE_COMPLETED'?'Exact rest/contact pass; visual acceptance open.':row.reason.replace(/^Error: /,''),words=text.split(' '),lines=[];let line='';for(const word of words){if((line+' '+word).length>49){lines.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)lines.push(line);for(let n=0;n<Math.min(lines.length,3);n++)label(lines[n]+(n===2&&lines.length>3?'…':''),x,y+317+n*24,19);
 }
 const name=family.profile+'-'+String(first/12+1).padStart(2,'0')+'.png',bytes=await sharp({create:{width:W,height:H,channels:4,background:'#17272d'}}).composite(layers).png().toBuffer();await fs.writeFile(path.join(out,name),bytes,{flag:'wx'});receipt.subjects+=page.length;receipt.sheets.push({file:'sheets/'+name,sha256:sha(bytes),profile:family.profile,subjects:page.map(r=>r.id),count:page.length});
}}
if(receipt.subjects!==58||new Set(receipt.sheets.flatMap(r=>r.subjects)).size!==58)throw Error('Sheet omitted or duplicated subject');await fs.writeFile(path.join(packet,'sheet-receipt.json'),JSON.stringify(receipt,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({sheets:receipt.sheets.length,subjects:receipt.subjects}));
