import fs from'node:fs';import assert from'node:assert/strict';import{createRequire}from'node:module';import{createHash}from'node:crypto';import{acquireWorkspaceLock}from'../../port/v2/tools/workspacelock.mjs';
import{createSourceJoinProbe}from'../../port/v2/tools/quadruped-proof/source-join-continuity.mjs';import{familyContractForRecord,familyContactChains}from'../../port/v2/tools/creature-animation/family-contracts.mjs';import{splitObservedSurfaces}from'../../port/v2/tools/creature-animation/split-observed-surfaces.mjs';
const B='audits/C203_PRIMATE_REFERENCES_20261004',J=p=>JSON.parse(fs.readFileSync(p)),sha=b=>createHash('sha256').update(b).digest('hex'),{PNG}=createRequire(process.cwd()+'/port/v2/package.json')('pngjs'),[srcId,outId]=process.argv.slice(2),src=B+'/'+srcId,out=B+'/'+outId;
const pairs=srcId.includes('gorilla')?[['near-upper-arm','neck'],['far-upper-arm','neck'],['jaw','neck'],['far-upper-arm','jaw'],['body','near-hand']]:[['near-thigh','tail-root'],['near-upper-arm','neck'],['far-upper-arm','neck'],['jaw','neck']];
assert(!fs.existsSync(out));const release=acquireWorkspaceLock('C203 preserve exact observed source joins');
try{fs.mkdirSync(out);for(const f of ['authoring.json','presence.json','subject-source.json','master.png'])fs.copyFileSync(src+'/'+f,out+'/'+f);fs.cpSync(src+'/fit01',out+'/fit01',{recursive:true,dereference:false,errorOnExist:true});
const fit=out+'/fit01',record=J(fit+'/record.json'),input=J(fit+'/pre-split-binding.json'),manifest=J(fit+'/parts/manifest.json'),atlas=PNG.sync.read(fs.readFileSync(fit+'/parts/atlas/'+manifest.creatureId+'.png')),probe=createSourceJoinProbe({record,binding:input,atlas:{rgba:atlas.data,width:atlas.width,height:atlas.height}}),before=J(fit+'/binding.json');
const declared=[],authored=pairs.map(pair=>{const key=pair.slice().sort().join('|'),row=probe.excluded.find(r=>r.name===key),existing=probe.joins.find(r=>r.name===key);assert(row||existing,key);if(row)declared.push(pair);const r=row||existing;return{parts:pair,alreadyAutomatic:!!existing,sourceEdges:r.sourceEdges,sourceBounds:[Math.min(...r.samples.map(s=>s.source[0])),Math.min(...r.samples.map(s=>s.source[1])),Math.max(...r.samples.map(s=>s.source[0])),Math.max(...r.samples.map(s=>s.source[1]))]};});
const split=await splitObservedSurfaces(input,record,probe,{fixedJoints:['root'],contactEndpoints:familyContactChains(familyContractForRecord(record)).map(c=>c.end),shapeJoints:[...new Set(input.parts.filter(p=>p.joint!=='root').map(p=>p.joint))],paintBoundaryPairs:declared});
fs.renameSync(fit+'/binding.json',fit+'/binding.before-observed-joins.json');fs.writeFileSync(fit+'/binding.json',JSON.stringify(split.binding,null,2)+'\n',{flag:'wx'});const receipt=J(fit+'/receipt.json');fs.renameSync(fit+'/receipt.json',fit+'/receipt.before-observed-joins.json');fs.writeFileSync(fit+'/receipt.json',JSON.stringify({...receipt,bindingHash:split.binding.bindingHash,surfaces:split.receipt,observedBoundaryAuthoring:'../observed-boundaries.json'},null,2)+'\n',{flag:'wx'});
const controls={recordBytesUnchanged:sha(fs.readFileSync(fit+'/record.json'))===sha(fs.readFileSync(src+'/fit01/record.json')),atlasBytesUnchanged:split.binding.atlasSha256===before.atlasSha256,sourceRGBAUnchanged:sha(fs.readFileSync(out+'/master.png'))===sha(fs.readFileSync(src+'/master.png')),sourceCoordinateChanges:split.receipt.sourceCoordinateChanges};assert(controls.recordBytesUnchanged&&controls.atlasBytesUnchanged&&controls.sourceRGBAUnchanged&&controls.sourceCoordinateChanges===0);
fs.writeFileSync(out+'/observed-boundaries.json',JSON.stringify({schema:'cf.c203-observed-source-joins/v1',sourcePacket:src,basis:'The exact visibly continuous C202 source boundaries are retained after anatomical arm segment remapping. Former forearm pixels now merge with the same-side hand owner. Independent limb overlaps remain independent.',authored,sourceBindingHash:before.bindingHash,resultBindingHash:split.binding.bindingHash,controls,admission:false},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({out,authored,controls}));
}finally{release();}
