/** Exhaustive existing-library diagnostic. Synthetic geometry is explicitly not visual qualification. */
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {pathToFileURL}from'node:url';import{createHash}from'node:crypto';import{rolldown}from'rolldown';
const root=path.resolve(import.meta.dirname,'../../../..'),out=process.argv[2];if(!out||fs.existsSync(out))throw Error('new output required');
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'cf-all-motion-')),sources=new Map(),sha=b=>createHash('sha256').update(b).digest('hex');
try{
 const bundle=await rolldown({input:path.join(root,'port/v2/apps/game/src/motion/index.ts'),platform:'node',plugins:[{name:'hashes',transform(_,id){if(path.isAbsolute(id)&&fs.existsSync(id)&&fs.statSync(id).isFile())sources.set(id,sha(fs.readFileSync(id)));}}]});try{await bundle.write({dir:scratch,format:'es',entryFileNames:'motion.mjs'});}finally{await bundle.close();}
 const m=await import(pathToFileURL(path.join(scratch,'motion.mjs'))),fixture=path.join(root,'port/v2/tools/creature-animation/test-fixtures/family-records.json');sources.set(fixture,sha(fs.readFileSync(fixture)));const {records}=JSON.parse(fs.readFileSync(fixture)),rows=[];
 for(const id of m.KNOWN_TEMPLATE_IDS){const raw=records[id];if(!raw)throw Error('Missing explicit synthetic fixture '+id);const record={...raw,identity:{...raw.identity,earthName:null},recipeHash:sha(JSON.stringify(raw))},card=m.compileBodyCard(record);for(const action of Object.keys(m.actionsFor(id))){const tl=m.buildTimeline(card,action,record.identity.seed),row={template:id,action,samples:0,limitViolations:0,maxOvershootRad:0,maxParityError:0,nonFinite:0,replay:true,settled:true},observed={};const player=m.createGsapPlayer(tl,{setJoint(j,rotation,dx,dy){observed[j]={rotation,dx,dy};}},{now:()=>0});
  try{for(let i=0;i<=240;i++){const ms=tl.durationMs*i/240,p=m.sampleTimeline(tl,ms);player.seek(ms);for(const[j,v]of Object.entries(p.joints)){const l=card.bounds.limitsDeg[j],s=card.projectionSigns?.[j]??1,lo=(s<0?-l.max:l.min)*Math.PI/180,hi=(s<0?-l.min:l.max)*Math.PI/180,d=Math.max(0,v-hi,lo-v);row.nonFinite+=!Number.isFinite(v);if(d>1e-7)row.limitViolations++;row.maxOvershootRad=Math.max(row.maxOvershootRad,d);row.maxParityError=Math.max(row.maxParityError,Math.abs(v-observed[j].rotation));if(j!=='root'&&(observed[j].dx!==0||observed[j].dy!==0))throw Error('non-root displacement');}row.samples++;}
  const ms=tl.durationMs*.437;player.seek(ms);const a=JSON.stringify(observed);player.seek(0);player.seek(tl.durationMs);player.seek(ms);row.replay=a===JSON.stringify(observed);
  if(!tl.loop&&['melee','hit','dodge','cast'].includes(tl.family)){const p=m.sampleTimeline(tl,tl.durationMs);row.settled=Object.values(p.joints).every(v=>Math.abs(v)<1e-8)&&Math.abs(p.root.dx)<1e-8&&Math.abs(p.root.dy)<1e-8;}
  }finally{player.stop();}rows.push(row);
 }}
 const status=rows.every(r=>!r.nonFinite&&!r.limitViolations&&r.maxParityError<2e-5&&r.replay&&r.settled)?'PASS':'FAIL';
 for(const[p,h]of sources)if(sha(fs.readFileSync(p))!==h)throw Error('Source changed');
 const report={schema:'cf.all-animation-diagnostic/v1',status,scope:'All published family action curves at 241 samples each on synthetic contract landmarks. Not skin, seam, contact, arena or art qualification.',rows,sources:[...sources].map(([p,sha256])=>({path:path.relative(root,p),sha256}))};fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status,actions:rows.length,samples:rows.reduce((n,r)=>n+r.samples,0),limits:rows.filter(r=>r.limitViolations).map(r=>({family:r.template,action:r.action,overshoot:r.maxOvershootRad})),parity:Math.max(...rows.map(r=>r.maxParityError)),settle:rows.filter(r=>!r.settled)}));if(status!=='PASS')process.exitCode=1;
}finally{fs.rmSync(scratch,{recursive:true,force:true});}
