import fs from'node:fs';import path from'node:path';import os from'node:os';import http from'node:http';import{execFileSync}from'node:child_process';import{createHash}from'node:crypto';import{rolldown}from'rolldown';import{openChromiumCdp}from'../browsercdp.mjs';import{acquireWorkspaceLock}from'../workspacelock.mjs';
import{nativeCpuPolicy,assessNativeReview}from'./native-cpu-policy.mjs';
import{requireFullRowMedia}from'./review-schedule.mjs';import{inspectEncodedFrames}from'../quadruped-proof/motion-proof-contract.mjs';
const [dirArg,producerArg,outArg,actionsArg='melee:bite,melee:body,melee:tail',mode='full',proof='no-proof',cpuTier='painter']=process.argv.slice(2),dir=path.resolve(dirArg),producer=path.resolve(producerArg),out=path.resolve(outArg);nativeCpuPolicy(cpuTier);if(!['full','rest-only'].includes(mode)||!['no-proof','refusal-proof','root-proof'].includes(proof))throw Error('Invalid native review mode');if(fs.existsSync(out))throw Error('New output required');fs.mkdirSync(out,{recursive:true});const sha=b=>createHash('sha256').update(b).digest('hex');if(sha(fs.readFileSync(path.join(producer,'motion/gsap-adapter.ts')))!=='600e413b90587a5d3b2f40ace148a95e6e692fb82f3b4d2eba2f17b12f0a8660')throw Error('Producer changed');
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'cf-family-native-')),sources=new Map(),report={status:'RUNNING',diagnostic:true,source:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),scope:'Actual painted rig and bounded local motion producer. All listed physical clips; dirty diagnostic, not visual acceptance.'},remember=p=>sources.set(p,{path:p,sha256:sha(fs.readFileSync(p))}),save=()=>fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');let release,server,browser;
try{release=acquireWorkspaceLock('real painted family native review');const bundle=await rolldown({input:path.join(import.meta.dirname,'native-entry.mjs'),platform:'browser',plugins:[{name:'read-only-producer',resolveId(id){if(id.startsWith('cf-proof/'))return path.resolve(producer,id.slice(9));},transform(_,id){if(path.isAbsolute(id)&&fs.existsSync(id)&&fs.statSync(id).isFile())remember(id);}}]});try{await bundle.write({dir:scratch,format:'es',entryFileNames:'bundle.js'});}finally{await bundle.close();}
 const actionIds=actionsArg.split(',');if(actionIds.some(a=>!(/^(melee:[a-z-]+|sway|disturb|harvest|grow)$/.test(a))))throw Error('Invalid physical clip list');fs.writeFileSync(path.join(scratch,'actions.json'),JSON.stringify(actionIds));
 const record=JSON.parse(fs.readFileSync(path.join(dir,'record.json')));report.sharedSubject=['quadruped','brachyuran'].includes(record.template.id);const assets={'record.json':path.join(dir,'record.json'),'binding.json':path.join(dir,'binding.json'),'keyed.png':path.join(dir,'parts/keyed.png'),'atlas.png':path.join(dir,'parts/atlas/'+JSON.parse(fs.readFileSync(path.join(dir,'parts/manifest.json'))).creatureId+'.png'),'master.png':path.resolve(record.source)};for(const[n,p]of Object.entries(assets)){remember(p);fs.copyFileSync(p,path.join(scratch,n));}fs.writeFileSync(path.join(scratch,'index.html'),'<body style="margin:0;background:#14242c"><script type="module" src="bundle.js"></script></body>');
 server=http.createServer((req,res)=>{const n=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';if(n.includes('/')||!fs.existsSync(path.join(scratch,n))){res.writeHead(404).end();return;}res.setHeader('Content-Type',n.endsWith('.js')?'text/javascript':n.endsWith('.json')?'application/json':n.endsWith('.html')?'text/html':'image/png');res.end(fs.readFileSync(path.join(scratch,n)));});await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await openChromiumCdp({label:'Painted family native review',userDataPrefix:'cf-family-review',commandTimeoutMs:60000});report.browser=browser.browser;
 const{targetId}=await browser.send('Target.createTarget',{url:'about:blank'}),{sessionId}=await browser.send('Target.attachToTarget',{targetId,flatten:true}),send=(m,p={})=>browser.send(m,p,sessionId),evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};await send('Page.enable');await send('Runtime.enable');await send('Emulation.setDeviceMetricsOverride',{width:1400,height:800,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:'http://127.0.0.1:'+server.address().port});
 const deadline=performance.now()+60000;for(;;){const s=await evaluate('window.cfFamilyReview?.state');if(s?.status==='FAIL')throw Error(s.error);if(s?.status==='READY')break;if(performance.now()>deadline)throw Error('Readiness timeout');await new Promise(r=>setTimeout(r,100));}
 report.gates=await evaluate('window.cfFamilyReview.gates('+JSON.stringify({restOnly:mode==='rest-only'})+')');for(const[n,b]of Object.entries(report.gates.artifacts))fs.writeFileSync(path.join(out,n),Buffer.from(b,'base64'));delete report.gates.artifacts;save();const shared=['quadruped','brachyuran'].includes(record.template.id);report.sharedPathRed=shared&&(report.gates.restChanged!==0||report.gates.finalRestChanged!==0||report.gates.rows?.some(r=>r.failure)||Boolean(report.gates.presentation?.failure));if(report.sharedPathRed||mode==='rest-only'&&report.gates.status!=='PASS')throw Error('Actual shared family gates failed');
 if(proof==='root-proof'){report.rootProof=await evaluate('window.cfFamilyReview.rootProof()');for(const[n,b]of Object.entries(report.rootProof.artifacts))fs.writeFileSync(path.join(out,n),Buffer.from(b,'base64'));delete report.rootProof.artifacts;if(report.rootProof.status!=='PASS')throw Error('Root instrument control failed');}
 if(mode==='rest-only'){report.status='REST_ONLY_PASS';}else{
 if(proof==='refusal-proof'){report.refusalProof=await evaluate('window.cfFamilyReview.refusalProof()');for(const[n,b]of Object.entries(report.refusalProof.artifacts))fs.writeFileSync(path.join(out,n),Buffer.from(b,'base64'));delete report.refusalProof.artifacts;if(report.refusalProof.status!=='PASS')throw Error('Refusal proof failed');}
 for(const [name,ms]of[['idle',900],['approach',3350],['melee',4780],['hit',6220]])fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(await evaluate('window.cfFamilyReview.still('+ms+')'),'base64'));
 report.actionStills=[];for(const row of report.gates.rows){if(row.id==='approach')continue;for(const fraction of [.25,.5,.75]){const name=row.id.replaceAll(':','-')+'-'+Math.round(fraction*100)+'.png';fs.writeFileSync(path.join(out,name),Buffer.from(await evaluate('window.cfFamilyReview.actionStill('+JSON.stringify(row.id)+','+fraction+')'),'base64'));report.actionStills.push({action:row.id,fraction,path:name});}}
 report.capture=await evaluate('window.cfFamilyReview.capture()');fs.writeFileSync(path.join(out,'family-full-rows.webm'),Buffer.from(report.capture.video,'base64'));delete report.capture.video;const media=JSON.parse(execFileSync('/opt/homebrew/bin/ffprobe',['-v','error','-count_frames','-show_entries','format=duration:stream=codec_type,nb_read_frames,width,height','-of','json',path.join(out,'family-full-rows.webm')],{encoding:'utf8'}));report.capture.encodedMedia=media;save();requireFullRowMedia(Number(media.format.duration),report.capture.durationMs);report.capture.encodedFrames=inspectEncodedFrames(media.streams);report.admission=assessNativeReview(report,cpuTier);report.status=report.admission.status==='PASS'?'DIAGNOSTIC_PASS':'LEAF_RED_WITH_REVIEW_FILM';}
}catch(e){report.status='FAIL';report.error=String(e.stack??e);if(report.sharedSubject&&/Contact:|ARAP skin:|Paint skin folded triangle|Actual shared family gates failed/.test(report.error))report.sharedPathRed=true;process.exitCode=1;}finally{report.sources=[...sources.values()];for(const r of report.sources)if(sha(fs.readFileSync(r.path))!==r.sha256){report.status='FAIL';report.error='source changed: '+r.path;process.exitCode=1;}save();await browser?.close();if(server)await new Promise(r=>server.close(r));release?.();fs.rmSync(scratch,{recursive:true,force:true});}console.log(JSON.stringify({status:report.status,error:report.error,rest:report.gates?.restChanged,capture:report.capture}));
