import{measureStanceReach}from'../../apps/game/src/creature-stance-reach.ts';
import{createFullRowSchedule}from'./review-schedule.mjs';
import{RecoverablePoseError}from'../creature-animation/pose-refusal.mjs';
import{assertPaintPartShape}from'../creature-animation/paint-skin.mjs';
import{createStrideCadence,createStageTravel,assessTemplateRootContinuity}from'../../apps/game/src/creature-stage-travel.ts';
import {sampleSupportResidual} from './contact-support-probe.mjs';
import {assertLegacyContactObserver} from './legacy-contact-observer.mjs';
import {createSkeletonPoseProgram} from '../creature-animation/skeleton-pose.mjs';
import {familyContractForRecord} from '../creature-animation/family-contracts.mjs';
import {Application,Container,Sprite,Texture,Text,RenderTexture}from'pixi.js';
import{loadCreatureRigV1,readCreatureRigRuntimeDiagnostics}from'../../apps/game/src/creature-rig.ts';
import{createCreatureRigPerformance}from'../../apps/game/src/creature-rig-performance.ts';
import{createFamilyContactSolver,contactPaintDriftPx,observedContactSupports,predictContactSupport}from'../../apps/game/src/creature-rig-contact.ts';
import{blendCreaturePoses,closedLoopPose}from'../../apps/game/src/motion-pose-blend.ts';
import{compileBodyCard,buildTimeline,createGsapPlayer,actionsFor}from'cf-proof/motion/index.ts';
import{createSourceJoinProbe,assessSourceJoinContinuity}from'../quadruped-proof/source-join-continuity.mjs';
import{primeRecorder}from'../quadruped-proof/capture-contract.mjs';
import{motionBounds,fitMotionBounds,containsMotion}from'../family-review/motion-framing.mjs';
import {hashJSON} from '../creature-animation/quadruped-template.mjs';
const get=n=>fetch(n).then(r=>{if(!r.ok)throw Error(n);return r;}),json=n=>get(n).then(r=>r.json()),bytes=n=>get(n).then(r=>r.arrayBuffer()),b64=b=>{let s='';const a=new Uint8Array(b);for(let i=0;i<a.length;i+=8192)s+=String.fromCharCode(...a.subarray(i,i+8192));return btoa(s);};
const image=async n=>{const b=await bytes(n),bmp=await createImageBitmap(new Blob([b])),c=new OffscreenCanvas(bmp.width,bmp.height);c.getContext('2d').drawImage(bmp,0,0);return{bytes:new Uint8Array(b),canvas:c,rgba:c.getContext('2d').getImageData(0,0,c.width,c.height).data};};
const state={status:'LOADING'};window.cfFamilyReview={state};
try{
const app=new Application();await app.init({width:1400,height:800,resolution:1,background:0x14242c,antialias:false,autoStart:false,preference:'webgl'});document.body.append(app.canvas);
const record=assertLegacyContactObserver(await json('record.json')),binding=await json('binding.json'),paint=await image('keyed.png'),master=new Uint8Array(await bytes('master.png')),atlas=await image('atlas.png'),rig=await loadCreatureRigV1(record,binding,master,Uint8Array.from({length:paint.canvas.width*paint.canvas.height},(_,i)=>paint.rgba[i*4+3]),atlas.bytes),card=compileBodyCard(record,record.genome),players={},timelines={};
const attackIds=await json('actions.json'),isPlant=card.template.id.startsWith('plant-'),idleId=isPlant?'sway':'idle',library=actionsFor(card.template.id,card.anatomy);
const selected=isPlant?Object.keys(library):['idle','approach',...attackIds,'hit',...Object.keys(library??{})];
for(const id of new Set(selected)){const tl=buildTimeline(card,id,record.identity.seed);timelines[id]=tl;let current={};const player=createGsapPlayer(tl,{setJoint(j,rotation,dx,dy){current[j]={rotation,dx,dy};}},{now:()=>0});players[id]={sample(ms){current={};player.seek(ms);return current;}};}
const contact=createFamilyContactSolver(record,observedContactSupports(record,binding)),owners={};const supportProgram=createSkeletonPoseProgram(familyContractForRecord(record),record.landmarks),supportSamples=[];let lastResolvedPose={},lastPhase={},lastContact={contacts:[],maxError:0},maxContactError=0,maxPaintContactDriftPx=0;
const resolveContact=(p,context)=>{lastContact=contact.resolve(p,{...context,realm:card.realm,...context.actionId.startsWith('melee:')?{travel:'stage'}:{}});lastResolvedPose=lastContact.pose;lastPhase={...context};maxContactError=Math.max(maxContactError,lastContact.maxError);return lastContact.pose;};
for(const [id,p]of Object.entries(players)){const tl=timelines[id],owner=createCreatureRigPerformance(record,rig,[{id,durationMs:tl.durationMs,loop:tl.loop,dispose(){},seek(ms,target){for(const[j,k]of Object.entries(p.sample(ms)))target.setJoint(j,k.rotation,k.dx,k.dy);}}],{refusal:'hold'});owner.play(id,0,0);owners[id]=owner;}
let reviewCapture=false;const updateOwner=(owner,ms,resolve)=>{const before=owner.diagnostics.refusedFrames,pose=owner.update(ms,resolve);if(!reviewCapture&&owner.diagnostics.refusedFrames!==before){const r=owner.diagnostics.lastRefusal;throw new RecoverablePoseError(r.code,r.reason);}return pose;};
const applyAction=(id,ms)=>updateOwner(owners[id],ms,(p,context)=>resolveContact(p,{...context,actionId:timelines[id].actionId}));
const title=new Text({text:'Painted '+record.template.id+' • anatomy action library trial',style:{fontFamily:'Arial',fontSize:27,fill:0xf1e4c7}});title.position.set(40,24);app.stage.addChild(title);
const label=new Text({text:'',style:{fontFamily:'Arial',fontSize:19,fill:0xd3dce0}});label.position.set(740,690);app.stage.addChild(label);
const subtitle=new Text({text:'Source-bound animation study · not final family, contact or arena acceptance',style:{fontFamily:'Arial',fontSize:17,fill:0xb7c7cc}});subtitle.position.set(40,755);app.stage.addChild(subtitle);
const smooth=x=>{x=Math.max(0,Math.min(1,x));return x*x*(3-2*x);};
const schedule=createFullRowSchedule(timelines),sequence=schedule.rows.map(r=>r.id),durationMs=schedule.durationMs,isGait=id=>/^approach(?::(?:walk|trot|gallop|crawl|scuttle))?$/.test(id);
const presentedPose=ms=>{let p=closedLoopPose(players[idleId].sample,ms,timelines[idleId].durationMs),name=idleId,phase={actionId:timelines[idleId].actionId,elapsedMs:ms,durationMs:timelines[idleId].durationMs,weight:1};for(let i=0;i<sequence.length;i++){const {id,startMs:start,endMs:end}=schedule.rows[i];if(ms>=start&&ms<end){const age=ms-start,weight=Math.min(smooth(age/120),smooth((end-ms)/160));const q=isGait(id)?closedLoopPose(players[id].sample,age,timelines[id].bodyMs):players[id].sample(Math.min(Math.max(0,age-120),timelines[id].durationMs));p=blendCreaturePoses(p,q,weight);name=id;phase={actionId:timelines[id].actionId,elapsedMs:isGait(id)?age:Math.max(0,age-120),durationMs:timelines[id].durationMs,weight};}}return{p,name,phase};};
const presentationOwner=createCreatureRigPerformance(record,rig,[{id:'presentation',durationMs,loop:false,dispose(){},seek(ms,target){for(const[j,k]of Object.entries(presentedPose(ms).p))target.setJoint(j,k.rotation,k.dx,k.dy);}}],{refusal:'hold'});presentationOwner.play('presentation',0,0);
const applyPresentation=ms=>updateOwner(presentationOwner,ms,p=>resolveContact(p,presentedPose(ms).phase));
const travelDirection=record.template.id==='brachyuran'?Math.sign(record.landmarks.leg0NearRoot[0]-record.landmarks.leg0FarRoot[0]):1;
const stageTravel=createStageTravel(schedule.rows.flatMap(({id,startMs,endMs})=>isGait(id)&&contact.stride?[{startMs,endMs,distance:travelDirection*contact.stride*(endMs-startMs)/timelines[id].durationMs}]:[]));
const presentationOffset=ms=>stageTravel(ms)-(/^approach:(walk|trot|gallop|crawl|scuttle)$/.test(lastPhase.actionId)?(lastResolvedPose.root?.dx??0)*supportProgram.bodyLength:0);
const worldRootAt=ms=>({ms,action:presentedPose(ms).name,x:presentationOffset(ms)+(lastResolvedPose.root?.dx??0)*supportProgram.bodyLength,y:(lastResolvedPose.root?.dy??0)*supportProgram.bodyLength});
let minX=paint.canvas.width,minY=paint.canvas.height,maxX=0,maxY=0;for(let y=0;y<paint.canvas.height;y++)for(let x=0;x<paint.canvas.width;x++)if(paint.rgba[(y*paint.canvas.width+x)*4+3]>12){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x+1);maxY=Math.max(maxY,y+1);}const readPositions=()=>Object.fromEntries(binding.paintSkin.parts.map(p=>[p.id,rig.parts.find(r=>r.id===p.id).display.children[0].geometry.getBuffer('aPosition').data]));
function* motionFrames(){rig.applyPose({});yield readPositions();for(let i=0;i<=Math.ceil(durationMs*60/1000);i++){const ms=Math.min(durationMs,i*1000/60);try{applyPresentation(ms);}catch(e){throw Error('Framing '+presentedPose(ms).name+'@'+ms+' ms: '+String(e));}const offset=presentationOffset(ms);yield Object.fromEntries(Object.entries(readPositions()).map(([id,p])=>[id,Float32Array.from(p,(v,i)=>v+(i%2?0:offset))]));}}
rig.applyPose({});const view={x:745,y:90,width:610,height:540};let fullMotionBox=motionBounds([readPositions()]),fit=fitMotionBounds(fullMotionBox,view),displayScale=fit.scale,displayX=fit.x,displayY=fit.y;
const previousScale=Math.min(560/((maxX-minX)/record.geometry.width),510/((maxY-minY)/record.geometry.height)),framing={samples:1,fullMotionBox,view,fit,inside:containsMotion(fullMotionBox,fit,view),oldRestOnlyInside:containsMotion(fullMotionBox,{scale:previousScale,x:760-minX/record.geometry.width*previousScale,y:115-minY/record.geometry.height*previousScale},view)};rig.applyPose({});
const left=new Sprite(Texture.from(paint.canvas));left.scale.set(displayScale/record.geometry.width);left.position.set(55-minX/record.geometry.width*displayScale,displayY);app.stage.addChild(left);rig.root.scale.set(displayScale);rig.root.position.set(displayX,displayY);app.stage.addChild(rig.root);
const before=new Text({text:'Source painting · unchanged pixels',style:{fontFamily:'Arial',fontSize:19,fill:0xd3dce0}});before.position.set(40,690);app.stage.addChild(before);
const probe=createSourceJoinProbe({record,binding,atlas:{rgba:atlas.rgba,width:atlas.canvas.width,height:atlas.canvas.height}}),positions=()=>Object.fromEntries(binding.paintSkin.parts.map(p=>[p.id,rig.parts.find(r=>r.id===p.id).display.children[0].geometry.getBuffer('aPosition').data]));
const rootPart=binding.paintSkin.parts.find(p=>p.id==='root');
rig.applyPose({});const rootRest=rootPart?Float32Array.from(positions()[rootPart.id]):null;
const rootDrift=()=>rootRest?Math.max(...positions()[rootPart.id].map((v,i)=>Math.abs(v-rootRest[i]))):0;
const paintContacts=contact.chains.map(chain=>{
 const part=binding.parts.find(p=>p.joint===chain.end),skin=binding.paintSkin.parts.find(p=>p.id===part?.id);
 if(!skin)throw Error('Contact paint: missing endpoint surface '+chain.end);
 let best=null;skin.vertices.forEach((v,i)=>{const xy=[0,0];for(let k=0;k<3;k++){const p=binding.paintSkin.vertices[v.triangle[k]];xy[0]+=p.x*v.barycentric[k]/record.geometry.width;xy[1]+=p.y*v.barycentric[k]/record.geometry.height;}const end=record.landmarks[chain.end],distance=Math.hypot(xy[0]-end[0],xy[1]-end[1]);if(!best||distance<best.distance)best={part:skin.id,index:i,xy,distance,joint:chain.end,vertex:v};});
 if(!best)throw Error('Contact paint: empty endpoint surface');return best;
});
function checkContactPaint(){const current=positions(),matrices=supportProgram.evaluate(lastResolvedPose);supportSamples.push({...lastPhase,contacts:paintContacts.map(mark=>{const c=lastContact.contacts.find(c=>c.joint===mark.joint),p=current[mark.part];return{...sampleSupportResidual({mark,skin:binding.paintSkin,matrices,prediction:(()=>{const p=predictContactSupport(contact.chains.find(c=>c.end===mark.joint).model,matrices);return[p.x,p.y];})(),current:[p[mark.index*2],p[mark.index*2+1]],target:c?[c.paintedTarget.x,c.paintedTarget.y]:null,width:record.geometry.width,height:record.geometry.height}),stance:c?.stance??false};})});for(const c of lastContact.contacts){if(!c.stance)continue;const mark=paintContacts.find(p=>p.joint===c.joint),p=current[mark.part],rest=record.landmarks[c.joint];const drift=contactPaintDriftPx([p[mark.index*2],p[mark.index*2+1]],mark.xy,[c.target.x,c.target.y],rest,[record.geometry.width,record.geometry.height]);maxPaintContactDriftPx=Math.max(maxPaintContactDriftPx,drift);if(drift>.25)throw Error('Contact paint drift '+c.joint+': '+drift);}}
let maximumRootDrift=0,readability={peakSwingFootLowerLeg:0,peakCarapaceDy:0};
function measureReadability(){const current=positions();for(const c of lastContact.contacts){if(c.stance)continue;const mark=paintContacts.find(p=>p.joint===c.joint),chain=contact.chains.find(p=>p.end===c.joint),p=current[mark.part];readability.peakSwingFootLowerLeg=Math.max(readability.peakSwingFootLowerLeg,Math.hypot(p[mark.index*2]-mark.xy[0],p[mark.index*2+1]-mark.xy[1])/chain.chain.lengths.lower);}if(rootRest){const p=current[rootPart.id];for(let i=1;i<p.length;i+=2)readability.peakCarapaceDy=Math.max(readability.peakCarapaceDy,Math.abs(p[i]-rootRest[i]));}}

let rigUpdates=[];function pose(id,ms){const at=performance.now();applyAction(id,ms);rigUpdates.push(performance.now()-at);measureReadability();maximumRootDrift=Math.max(maximumRootDrift,rootDrift());checkContactPaint();label.text=id+' · '+Math.round(ms)+' ms';}
const png=async rgba=>{const c=new OffscreenCanvas(record.geometry.width,record.geometry.height);c.getContext('2d').putImageData(new ImageData(Uint8ClampedArray.from(rgba),c.width,c.height),0,0);return b64(await(await c.convertToBlob({type:'image/png'})).arrayBuffer());};
async function gates({restOnly=false}={}){
 const w=record.geometry.width,h=record.geometry.height,rt=RenderTexture.create({width:w,height:h,resolution:1}),pixels=node=>{app.renderer.render({container:node,target:rt,clear:true});return Uint8Array.from(app.renderer.extract.pixels({target:rt}).pixels);};
 rig.root.scale.set(w,h);rig.root.position.set(0,0);rig.applyPose({});const original=new Sprite(Texture.from(paint.canvas)),expected=pixels(original),rest=pixels(rig.root),changed=(a,b)=>a.reduce((n,v,i)=>n+(v!==b[i]),0),restChanged=changed(rest,expected),rows=[];
 if(restOnly){rig.root.position.x=1;const shiftedChanged=changed(pixels(rig.root),expected);rig.root.position.set(0,0);const finalRestChanged=changed(pixels(rig.root),expected),artifacts={'family-rest.png':await png(rest)};rt.destroy(true);original.destroy();return{status:restChanged===0&&finalRestChanged===0&&shiftedChanged>0?'PASS':'FAIL',scope:'Exact native RGBA rest only; no action/CPU admission',restChanged,finalRestChanged,shiftedChanged,artifacts};}
 for(const id of Object.keys(players)){readability={peakSwingFootLowerLeg:0,peakCarapaceDy:0};const normalPasses=[],updateStart=rigUpdates.length,row={id,samples:0,maxGapPx:0,status:'PASS'};for(let i=0;i<=120;i++){const ms=timelines[id].durationMs*i/120;try{const beforePasses=readCreatureRigRuntimeDiagnostics(rig).normalPasses;pose(id,ms);normalPasses.push(readCreatureRigRuntimeDiagnostics(rig).normalPasses-beforePasses);const seams=assessSourceJoinContinuity(probe,positions());if(seams.status!=='PASS')throw Error('source gap');row.maxGapPx=Math.max(row.maxGapPx,seams.maxGapPx);row.samples++;}catch(e){row.status='FAIL';row.failure={ms,error:String(e)};break;}}const times=rigUpdates.slice(updateStart).sort((a,b)=>a-b);row.updateP95Ms=times[Math.floor(times.length*.95)]??null;row.updateMaxMs=times.at(-1)??null;if(row.updateP95Ms===null||row.updateP95Ms>=2){row.status='FAIL';row.performanceFailure='Per-clip update must be below 2 ms';}Object.assign(row,{readability:{...readability,carapaceUnits:'normalized source height; root painted surface',footUnits:'observed swing support displacement from rest / lower-leg length'},normalPasses});rows.push(row);}
 const rootSamples=[],presentation={samples:0,maxGapPx:0,status:'PASS'};for(let i=0;i<=Math.ceil(durationMs*60/1000);i++){const atMs=Math.min(durationMs,i*1000/60);try{applyPresentation(atMs);rootSamples.push(worldRootAt(atMs));checkContactPaint();maximumRootDrift=Math.max(maximumRootDrift,rootDrift());const seams=assessSourceJoinContinuity(probe,positions());if(seams.status!=='PASS')throw Error('source gap');presentation.samples++;presentation.maxGapPx=Math.max(presentation.maxGapPx,seams.maxGapPx);}catch(e){presentation.status='FAIL';presentation.failure={action:presentedPose(atMs).name,ms:atMs,error:String(e)};break;}}
 const rootContinuity=contact.stride&&rootSamples.length>1?assessTemplateRootContinuity(rootSamples,contact.stride,record.template.id,card.scaleLength):{status:isPlant?'NOT_APPLICABLE':'INCOMPLETE'};if(rootContinuity.status==='FAIL'){presentation.status='FAIL';presentation.continuityFailure=rootContinuity;}
 // Action failures are collected before presentation framing; no readiness scan can erase them.
 if(rows.every(r=>!r.failure)||isPlant){
  try{reviewCapture=isPlant;fullMotionBox=motionBounds(motionFrames());reviewCapture=false;fit=fitMotionBounds(fullMotionBox,view);displayScale=fit.scale;displayX=fit.x;displayY=fit.y;Object.assign(framing,{samples:Math.ceil(durationMs*60/1000)+2,fullMotionBox,fit,inside:containsMotion(fullMotionBox,fit,view)});left.scale.set(displayScale/record.geometry.width);left.position.set(55-minX/record.geometry.width*displayScale,displayY);}
  catch(e){reviewCapture=false;framing.inside=false;framing.failure=String(e);}
 }else{framing.inside=false;framing.skipped='Prior action/presentation failed';}
 rig.applyPose({});const finalRestChanged=changed(pixels(rig.root),expected),p=positions(),mutated=Object.fromEntries(Object.entries(p).map(([k,a])=>[k,new Float32Array(a)])),victim=probe.joins[0].descendantPart;for(let i=0;i<mutated[victim].length;i+=2)mutated[victim][i]+=.01;const negative=assessSourceJoinContinuity(probe,mutated);
 const artifacts={'family-rest.png':await png(rest)};rig.root.scale.set(displayScale);rig.root.position.set(displayX,displayY);rig.applyPose({});app.renderer.render(app.stage);rt.destroy(true);original.destroy();
 return {durationMs,schedule,refusals:Object.fromEntries([...Object.entries(owners),['presentation',presentationOwner]].map(([id,o])=>[id,o.diagnostics])),rootContinuity,supportSamples,contacts:{maxContactError,maxPaintContactDriftPx,paintTolerancePx:.25,chains:contact.chains.map(c=>c.id)},maximumRootDrift,rootSurfaceChecked:Boolean(rootRest),attackIds,actionCount:Object.keys(players).length,allClipPerformance:{scope:'121 accelerated samples per clip before presentation/framing; separate from real-time capture',maxP95Ms:Math.max(...rows.map(r=>r.updateP95Ms??Infinity)),targetMs:2},status:(!isPlant||(rootRest&&maximumRootDrift===0))&&restChanged===0&&finalRestChanged===0&&negative.status==='FAIL'&&rows.every(r=>r.status==='PASS')&&presentation.status==='PASS'&&framing.inside?'PASS':'FAIL',framing,presentation,restChanged,finalRestChanged,rows,negative:{status:negative.status,maxGapPx:negative.maxGapPx},card,runtime:readCreatureRigRuntimeDiagnostics(rig),artifacts};
}
const stageAt=ms=>{const at=performance.now(),{name}=presentedPose(ms);applyPresentation(ms);rig.root.position.set(displayX+presentationOffset(ms)*displayScale,displayY);checkContactPaint();rigUpdates.push(performance.now()-at);label.text=name+' · full row'+(presentationOwner.diagnostics.refusedFrames?' · HELD REFUSALS '+presentationOwner.diagnostics.refusedFrames:'');app.renderer.render(app.stage);};
async function capture(){reviewCapture=true;const supportStart=supportSamples.length,stream=app.canvas.captureStream(0),track=stream.getVideoTracks()[0],chunks=[],recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp9',videoBitsPerSecond:5000000}),stopped=new Promise(r=>recorder.onstop=r);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};stageAt(0);let started=false,recordError=null;recorder.onstart=()=>{started=true;};recorder.onerror=e=>{recordError=e.error??Error('Recorder failed');};recorder.start();await primeRecorder({started:()=>started,paint:()=>stageAt(0),requestFrame:()=>track.requestFrame(),schedule:requestAnimationFrame,now:()=>performance.now()});rigUpdates=[];const frames=[],updates=[];let start;
 try{await new Promise((resolve,reject)=>{const tick=now=>{try{start??=now;const ms=now-start,at=performance.now();if(recordError)throw recordError;stageAt(Math.min(ms,durationMs));track.requestFrame();updates.push(performance.now()-at);frames.push(now);if(ms>=durationMs)resolve();else requestAnimationFrame(tick);}catch(e){reject(e);}};requestAnimationFrame(tick);});}finally{await new Promise(r=>setTimeout(r,120));track.requestFrame();recorder.stop();await stopped;for(const t of stream.getTracks())t.stop();}
 const sorted=[...updates].sort((a,b)=>a-b);rigUpdates.sort((a,b)=>a-b);return{durationMs,schedule,refusals:presentationOwner.diagnostics,supportSamples:supportSamples.slice(supportStart),rigUpdateP95Ms:rigUpdates[Math.floor(rigUpdates.length*.95)],frames:frames.length,fps:(frames.length-1)*1000/(frames.at(-1)-frames[0]),wholeFrameCpuP95Ms:sorted[Math.floor(sorted.length*.95)],video:b64(await new Blob(chunks).arrayBuffer())};}
async function refusalProof(){const snapshots=[],artifacts={},victim=binding.paintSkin.parts[0];let inject=false;const proxy={...rig,applyPose(p){if(inject){const reversed=Float32Array.from(positions()[victim.id],(v,i)=>i%2?v:1-v);assertPaintPartShape(victim,binding.paintSkin,reversed,record.geometry.width,record.geometry.height);throw Error('Refusal control failed to reject reflected geometry');}rig.applyPose(p);}},owner=createCreatureRigPerformance(record,proxy,[{id:'refusal-proof',durationMs:1000,loop:false,dispose(){},seek(ms,t){for(const[j,k]of Object.entries(players[idleId].sample(ms)))t.setJoint(j,k.rotation,k.dx,k.dy);}}],{refusal:'hold'});owner.play('refusal-proof',0,0);rig.root.scale.set(displayScale);rig.root.position.set(displayX,displayY);for(const [name,ms,bad]of[['N-1',100,false],['N',200,true],['N+1',300,false]]){inject=bad;const pose=owner.update(ms);app.renderer.render(app.stage);artifacts['refusal-'+name+'.png']=app.canvas.toDataURL('image/png').split(',')[1];snapshots.push({name,ms,pose,positions:Object.fromEntries(Object.entries(positions()).map(([id,p])=>[id,Array.from(p)]))});}const held=JSON.stringify(snapshots[0].positions)===JSON.stringify(snapshots[1].positions),recovered=JSON.stringify(snapshots[1].positions)!==JSON.stringify(snapshots[2].positions);rig.applyPose({});return{status:held&&recovered&&owner.diagnostics.refusedFrames===1?'PASS':'FAIL',held,recovered,clockAdvanced:owner.sample(300),diagnostics:owner.diagnostics,artifacts};}
async function rootProof(){
 if(!isPlant||!rootPart)throw Error('Root proof requires actual plant root pixels');
 const {bindingHash,paintSkin,sourceJoinTopology,...body}=binding,testBinding={...body,bindingHash:await hashJSON(body)};
 const subject=await loadCreatureRigV1(record,testBinding,master,Uint8Array.from({length:paint.canvas.width*paint.canvas.height},(_,i)=>paint.rgba[i*4+3]),atlas.bytes);
 const priorVisible=rig.root.visible;rig.root.visible=false;subject.root.scale.set(displayScale);subject.root.position.set(displayX,displayY);app.stage.addChild(subject.root);for(const p of subject.parts)p.display.visible=p.id===rootPart.id;
 const snapshots=[],artifacts={};try{for(const[name,pose]of[['root-rest',{}],['root-positive-trunk',{trunk:{rotation:.01}}],['root-negative-translate',{root:{rotation:0,dx:.02,dy:0}}]]){subject.applyPose(pose);app.renderer.render(app.stage);snapshots.push(new Uint8Array(app.renderer.extract.pixels({target:app.stage}).pixels));artifacts[name+'.png']=app.canvas.toDataURL('image/png').split(',')[1];}const changed=(a,b)=>a.reduce((n,v,i)=>n+(v!==b[i]),0),positiveChanged=changed(snapshots[0],snapshots[1]),negativeChanged=changed(snapshots[0],snapshots[2]);return {status:positiveChanged===0&&negativeChanged>0?'PASS':'FAIL',positive:{status:positiveChanged===0?'PASS':'FAIL',changedChannels:positiveChanged},negative:{status:negativeChanged>0?'FAIL':'PASS',changedChannels:negativeChanged},scope:'Actual root-supported textured part through the native rig owner, without field pins; deliberate root translation vs trunk-only bend. Source pixels/record unchanged; test-only binding.',testBindingHash:testBinding.bindingHash,artifacts};}finally{subject.dispose();rig.root.visible=priorVisible;}
}
async function cadence(){
 const actionId=isPlant?'sway':'approach',tl=timelines[actionId],arenaScale=record.geometry.width*.25,targetDistancePx=isPlant?0:1024*.18;
 const reach=measureStanceReach(record,observedContactSupports(record,binding)),plan=createStrideCadence({targetDistancePx,bodyLengthPx:contact.scaleLength*arenaScale,gaitDurationMs:tl.durationMs,stanceReachBodyLengths:isPlant?1:reach.forward});
 const rest=()=>Object.fromEntries(Object.entries(positions()).map(([id,p])=>[id,Array.from(p)]));rig.applyPose({});const original=JSON.stringify(rest()),windows=new Map(),times=[],failures=[];
 const frames=isPlant?121:Math.max(121,plan.cycles*60),total=isPlant?tl.durationMs:plan.durationMs;let maxSpread=0;
 const oldX=rig.root.x,oldY=rig.root.y,oldScale=rig.root.scale.x;rig.root.scale.set(arenaScale);rig.root.position.set(160,100);
 try{for(let i=0;i<frames;i++){
  const ms=total*i/frames,c=plan.sample(ms),age=isPlant?ms:c.gaitMs,phase={actionId:tl.actionId,elapsedMs:age,durationMs:tl.durationMs,travel:'stage',stageDisplacement:c.stageDisplacement,realm:card.realm};
  try{const start=performance.now(),solved=contact.resolve(players[actionId].sample(age),phase);rig.applyPose(solved.pose);times.push(performance.now()-start);lastResolvedPose=solved.pose;
   const current=positions();for(const foot of solved.contacts){if(!foot.stance)continue;const mark=paintContacts.find(p=>p.joint===foot.joint),p=current[mark.part],x=(foot.space==='body'?0:c.worldDisplacementPx)+p[mark.index*2]*arenaScale,y=p[mark.index*2+1]*arenaScale,key=c.stanceWindow+':'+foot.joint;
    let w=windows.get(key);if(!w){w={joint:foot.joint,space:foot.space??'arena',window:c.stanceWindow,samples:0,x,y,maxDriftPx:0};windows.set(key,w);}w.samples++;w.maxDriftPx=Math.max(w.maxDriftPx,Math.hypot(x-w.x,y-w.y));maxSpread=Math.max(maxSpread,w.maxDriftPx);
   }
  }catch(e){failures.push({ms,phase,error:String(e.stack??e)});break;}
  rig.root.x=160+c.worldDisplacementPx;label.text='Cadence '+(isPlant?'rooted flora':c.stanceWindow)+' / '+plan.cycles+' cycles';app.renderer.render(app.stage);
  if(i%60===0)await new Promise(requestAnimationFrame);
 }
 const still=app.canvas.toDataURL('image/png').split(',')[1];rig.applyPose({});const exactRest=JSON.stringify(rest())===original;times.sort((a,b)=>a-b);
 return{status:failures.length||!exactRest||maxSpread>.5?'FAIL':'PASS',template:record.template.id,reach,scope:isPlant?'Rooted flora: no gait or contact chains; planting not applicable':'Actual native Pixi painted rig, gait sampler, family solver and stance-local cadence',plan:{cycles:plan.cycles,durationMs:plan.durationMs,targetDistancePx,bodyLengthPx:plan.bodyLengthPx,maxStanceTravelBodyLengths:plan.maxStanceTravelBodyLengths},frames:times.length,expectedFrames:frames,refusals:failures.length,failures,exactRest,maxStanceDriftPx:isPlant?null:maxSpread,windows:[...windows.values()],rigP95Ms:times[Math.floor(times.length*.95)]??null,still};
 }finally{rig.root.scale.set(oldScale);rig.root.position.set(oldX,oldY);}
}
window.cfFamilyReview={state,gates,capture,cadence,refusalProof,rootProof,actionStill(id,fraction){if(!players[id]||!Number.isFinite(fraction)||fraction<0||fraction>1)throw Error('Invalid action still');rig.root.position.set(displayX,displayY);reviewCapture=isPlant;try{pose(id,timelines[id].durationMs*fraction);app.renderer.render(app.stage);return app.canvas.toDataURL('image/png').split(',')[1];}finally{reviewCapture=false;}},still(ms){reviewCapture=isPlant;try{stageAt(ms);return app.canvas.toDataURL('image/png').split(',')[1];}finally{reviewCapture=false;}}};state.status='READY';rig.applyPose({});app.renderer.render(app.stage);
}catch(e){state.status='FAIL';state.error=String(e.stack??e);}
