/** Rebuildable local review page; original captures/masters stay untouched. */
import fs from'node:fs';import path from'node:path';import{execFileSync}from'node:child_process';
const out=path.resolve(process.argv[2]);if(fs.existsSync(out))throw Error('New review directory required');fs.mkdirSync(out,{recursive:true});
const base='audits/ANIMATION_COMPLETION_20260916',inputs=[['fish','Painted fish','fish-native-04'],['bird','Painted bird (earlier solver snapshot)','bird-native-02'],['frog','Earth frog','frog-native-04'],['procedural','Painted procedural quadruped','broad-native-01']],rows=[];
for(const[id,title,folder]of inputs){const source=path.join(base,folder),r=JSON.parse(fs.readFileSync(path.join(source,'report.json')));if(r.status!=='DIAGNOSTIC_PASS')throw Error('Unpassed source '+folder);const dir=path.join(out,id);fs.mkdirSync(dir);fs.copyFileSync(path.join(source,'report.json'),path.join(dir,'report.json'));for(const a of r.actionStills)fs.copyFileSync(path.join(source,a.path),path.join(dir,a.path));fs.copyFileSync(path.join(source,'idle.png'),path.join(dir,'poster.png'));
 execFileSync('/opt/homebrew/bin/ffmpeg',['-v','error','-i',path.join(source,'family-10s.webm'),'-an','-c:v','libx264','-crf','19','-pix_fmt','yuv420p','-movflags','+faststart',path.join(dir,'film.mp4')]);
 const media=JSON.parse(execFileSync('/opt/homebrew/bin/ffprobe',['-v','error','-count_frames','-show_entries','format=duration:stream=codec_type,nb_read_frames,width,height','-of','json',path.join(dir,'film.mp4')],{encoding:'utf8'}));if(Number(media.format.duration)<10||!media.streams.some(s=>s.codec_type==='video'&&Number(s.nb_read_frames)>=590))throw Error('Incomplete review movie '+id);
 rows.push({id,title,source,stills:r.actionStills,fps:r.capture.fps,updateP95:r.capture.rigUpdateP95Ms,allClipP95:r.gates.allClipPerformance?.maxP95Ms??null,clips:r.gates.rows.filter(x=>x.id!=='approach').length,media});
}
fs.writeFileSync(path.join(out,'review.json'),JSON.stringify({scope:'Painted animation studies, not final universal/phone acceptance',rows},null,2)+'\n');
fs.writeFileSync(path.join(out,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Creature animation review</title><style>body{background:#14242c;color:#eadfc9;font:18px/1.5 system-ui;margin:0}main{max-width:1200px;margin:auto;padding:24px}button,select{font:inherit;padding:10px;background:#29414a;color:inherit;border:1px solid #a1b4b7;border-radius:6px;margin:4px}button[aria-pressed=true]{background:#575d36}a{color:#a3d6e1}video,img{width:100%;display:block;background:#14242c}label{display:block}.note{color:#b8c9cd}details{margin-top:24px}button:focus-visible,select:focus-visible,a:focus-visible{outline:3px solid #ffda83}</style><main><h1>Painted creatures · shared animation</h1><p>The left creature is the source painting; the right uses the shared rig. Choose a film or inspect individual action poses.</p><nav id="families" aria-label="Creature"></nav><h2 id="name"></h2><p id="measure" class="note"></p><button id="play">Play ten-second film</button><video id="film" controls playsinline muted preload="metadata"></video><p id="status" role="status"></p><a id="report">Source-bound report</a><details open><summary>Individual action poses</summary><label>Action <select id="action"></select></label><label>Clip position <select id="fraction"><option value="0.25">25%</option><option value="0.5" selected>50%</option><option value="0.75">75%</option></select></label><img id="pose" alt="Source painting beside the selected animated pose"></details><p class="note">These are family-library trials. A displayed action is not permission for every species to use it; actual battle selection requires its observed anatomy, weapons and habitat. Timings are Mac measurements. The goal is under2ms per creature; results above that remain open. No physical iPhone qualification is claimed.</p><p><a href="../species-coverage/">631-species coverage board</a> · <a href="../anatomy-battle/">Earlier three-creature biome battle</a></p></main><script>
const rows=${JSON.stringify(rows)},q=s=>document.querySelector(s),film=q('#film');let selected=rows[0];
function pose(){const a=selected.stills.find(s=>s.action===q('#action').value&&s.fraction===Number(q('#fraction').value));q('#pose').src=selected.id+'/'+a.path;}
function choose(r){selected=r;film.pause();film.src=r.id+'/film.mp4';film.poster=r.id+'/poster.png';film.load();q('#name').textContent=r.title;q('#measure').textContent=r.clips+' action clips checked · captured '+r.fps.toFixed(1)+' fps · capture update p95 '+r.updateP95.toFixed(1)+' ms'+(r.allClipP95===null?'':' · worst individually sampled clip p95 '+r.allClipP95.toFixed(1)+' ms');q('#report').href=r.id+'/report.json';q('#status').textContent='Press Play to review motion.';q('#action').replaceChildren(...[...new Set(r.stills.map(s=>s.action))].map(id=>{const o=document.createElement('option');o.value=id;o.textContent=id;return o;}));document.querySelectorAll('[data-id]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===r.id)));pose();}
for(const r of rows){const b=document.createElement('button');b.textContent=r.title;b.dataset.id=r.id;b.onclick=()=>choose(r);q('#families').append(b);}q('#action').onchange=pose;q('#fraction').onchange=pose;q('#play').onclick=()=>film.play().catch(()=>q('#status').textContent='Video could not start. The per-action images and report remain available.');film.onplaying=()=>q('#status').textContent='Playing the captured native animation study.';film.onerror=()=>q('#status').textContent='Film unavailable; inspect the action poses below.';choose(rows[0]);</script></html>`);
console.log(JSON.stringify({out,subjects:rows.length,frames:rows.reduce((n,r)=>n+r.stills.length,0)}));
