/** Painted geometry diagnostic; no GPU, art acceptance or performance claim. */
import fs from'node:fs';import os from'node:os';import path from'node:path';import{pathToFileURL}from'node:url';import{rolldown}from'rolldown';import{createHash}from'node:crypto';
import{createSkeletonPoseProgram}from'../creature-animation/skeleton-pose.mjs';
import{familyContractForRecord}from'../creature-animation/family-contracts.mjs';
import{createCompiledSkinField,applyCompiledSkinField}from'../creature-animation/compiled-skin-field.mjs';
import{createArapScratch,solveArapSkin}from'../creature-animation/arap-skin.mjs';
import{applyPaintPart,paintPartAreas,assertPaintPartShape}from'../creature-animation/paint-skin.mjs';
const[dirArg,outArg]=process.argv.slice(2),dir=path.resolve(dirArg),out=path.resolve(outArg);if(fs.existsSync(out))throw Error('New output required');
const root=path.resolve(import.meta.dirname,'../../../..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'cf-skin-audit-')),sources=new Map(),sha=b=>createHash('sha256').update(b).digest('hex'),remember=p=>sources.set(p,sha(fs.readFileSync(p)));
try{const bundle=await rolldown({input:path.join(root,'port/v2/apps/game/src/motion/index.ts'),platform:'node',plugins:[{name:'hash',transform(_,id){if(path.isAbsolute(id)&&fs.existsSync(id)&&fs.statSync(id).isFile())remember(id);}}]});try{await bundle.write({dir:temp,format:'es',entryFileNames:'motion.mjs'});}finally{await bundle.close();}
 const m=await import(pathToFileURL(path.join(temp,'motion.mjs'))),recordPath=path.join(dir,'record.json'),bindingPath=path.join(dir,'binding.json');remember(recordPath);remember(bindingPath);for(const name of['arap-skin.mjs','orientation-projector.mjs','compiled-skin-field.mjs','skeleton-pose.mjs','paint-skin.mjs','family-contracts.mjs','anatomy-inventory.mjs'])remember(path.join(root,'port/v2/tools/creature-animation',name));
 const r=JSON.parse(fs.readFileSync(recordPath)),b=JSON.parse(fs.readFileSync(bindingPath)),s=b.paintSkin,w=r.geometry.width,h=r.geometry.height,card=m.compileBodyCard(r,r.genome),program=createSkeletonPoseProgram(familyContractForRecord(r),r.landmarks),field=createCompiledSkinField(s,w,h),scratch=createArapScratch(s.vertices,s.triangles,w,h,s.solver),target=new Float32Array(s.vertices.length*2),output=target.slice(),parts=s.parts.map(p=>({p,positions:new Float32Array(p.vertices.length*2),areas:paintPartAreas(p,s)})),rows=[];
 if(process.argv[4]){const match=/^([a-z:-]+)@([0-9.]+)$/.exec(process.argv[4]);if(!match)throw Error('Snapshot must be action@milliseconds');const tl=m.buildTimeline(card,match[1],r.identity.seed),ms=Number(match[2]);if(!Number.isFinite(ms)||ms<0||ms>tl.durationMs)throw Error('Snapshot time outside clip');const p=m.sampleTimeline(tl,ms),pose=Object.fromEntries(Object.entries(p.joints).map(([j,rotation])=>[j,{rotation,dx:j==='root'?p.root.dx:0,dy:j==='root'?p.root.dy:0}]));applyCompiledSkinField(field,program.evaluate(pose),target);const fixture={schema:'cf.orientation-regression/v1',source:{record:sha(fs.readFileSync(recordPath)),binding:sha(fs.readFileSync(bindingPath)),action:match[1],ms},width:w,height:h,vertices:s.vertices.map(({x,y})=>({x,y})),triangles:s.triangles,solver:s.solver,target:Array.from(target)};if(fs.existsSync(out+'.target.json'))throw Error('New target output required');fs.writeFileSync(out+'.target.json',JSON.stringify(fixture)+'\n');}
 for(const id of Object.keys(m.actionsFor(r.template.id))){const tl=m.buildTimeline(card,id,r.identity.seed),row={id,samples:0,status:'PASS'};for(let i=0;i<=120;i++){const ms=tl.durationMs*i/120,p=m.sampleTimeline(tl,ms),pose=Object.fromEntries(Object.entries(p.joints).map(([j,rotation])=>[j,{rotation,dx:j==='root'?p.root.dx:0,dy:j==='root'?p.root.dy:0}]));try{applyCompiledSkinField(field,program.evaluate(pose),target);solveArapSkin(scratch,target,output);for(const part of parts){applyPaintPart(part.p,output,part.positions);assertPaintPartShape(part.p,s,part.positions,w,h,part.areas);}row.samples++;}catch(e){row.status='FAIL';row.failure={ms,error:String(e),stats:{...scratch.stats},folds:[]};const q=scratch.position;for(let k=0;k<scratch.triangles.length;k+=3){const ids=Array.from(scratch.triangles.slice(k,k+3)),[a,b,c]=ids.map(x=>x*2),ratio=((q[b]-q[a])*(q[c+1]-q[a+1])-(q[b+1]-q[a+1])*(q[c]-q[a]))/scratch.areas[k/3];if(ratio<=0)row.failure.folds.push({triangle:k/3,ratio,vertices:ids.map(index=>({index,source:s.vertices[index],pin:Boolean(scratch.pins[index]),target:[target[index*2]*w,target[index*2+1]*h],solved:[q[index*2],q[index*2+1]]}))});}break;}}rows.push(row);}
 const report={schema:'cf.painted-skin-action-audit/v1',scope:'Every family action on actual fitted skin, 121 samples/clip. No rendered pixels or art acceptance.',status:rows.every(r=>r.status==='PASS')?'PASS':'FAIL',rows,sources:[...sources].map(([p,sha256])=>({path:path.relative(root,p),sha256}))};for(const[p,h]of sources)if(sha(fs.readFileSync(p))!==h)throw Error('Source changed');fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,rows:rows.map(({failure,...r})=>({...r,...(failure?{error:failure.error,ms:failure.ms,folds:failure.folds}: {})}))}));if(report.status!=='PASS')process.exitCode=1;
}finally{fs.rmSync(temp,{recursive:true,force:true});}
