import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{createHash}from'node:crypto';
import{sealFamilyRecord}from'../../port/v2/tools/creature-animation/family-record.mjs';import{hashJSON}from'../../port/v2/tools/creature-animation/quadruped-template.mjs';
const packet='audits/BEAR_CONTACT_DIAGNOSTICS_20260922',folded=['leg0Far','leg1Far','leg2Far','leg3Far'],changes=[];
const sha=b=>createHash('sha256').update(b).digest('hex');
for(const subject of ['mud-crab','vent-crab']){const dir='audits/ANATOMY_COMPLETION_20260917/crab-fits-03/'+subject,old=JSON.parse(fs.readFileSync(dir+'/record.json')),presence={schema:'cf.anatomy-presence/v2',absent:[],hidden:[],folded},record=await sealFamilyRecord({...old,anatomy:presence}),{recipeHash:oh,...ob}=old,{recipeHash:nh,anatomy,...nb}=record;assert.deepEqual(ob,nb,'presence only');const archive=packet+'/declaration-before/'+subject;fs.mkdirSync(archive,{recursive:true});const files=[];
 for(const name of ['record.json','binding.json','parts/binding.json']){const p=dir+'/'+name,bytes=fs.readFileSync(p);fs.mkdirSync(path.dirname(archive+'/'+name),{recursive:true});fs.writeFileSync(archive+'/'+name,bytes,{flag:'wx'});let value=record;
  if(name!=='record.json'){const b=JSON.parse(bytes),{bindingHash,...body}=b;assert.equal(body.recordRecipeHash,oh);body.recordRecipeHash=nh;value={...body,bindingHash:await hashJSON(body)};const{bindingHash:_new,recordRecipeHash:_newRecord,...unchanged}=value,{bindingHash:_old,recordRecipeHash:_oldRecord,...prior}=b;assert.deepEqual(unchanged,prior,'binding only re-associated, no skin/weight/pin/atlas/part changes');}
  const output=JSON.stringify(value,null,2)+'\n';fs.writeFileSync(p+'.tmp',output);fs.renameSync(p+'.tmp',p);files.push({file:p,beforeSha256:sha(bytes),afterSha256:sha(output)});
 }
 const presPath=dir+'/presence.json';fs.writeFileSync(presPath,JSON.stringify(presence,null,2)+'\n',{flag:'wx'});changes.push({subject,presence,presenceFile:presPath,presenceSha256:sha(fs.readFileSync(presPath)),beforeRecipeHash:oh,afterRecipeHash:nh,files,authority:'Nick overnight item4: far legs declared folded; all four named Far chains, not inferred from geometry or copied from later painted fits',sourcePixelsChanged:0,landmarksChanged:0,skinChanges:0});
}fs.writeFileSync(packet+'/folded-declarations.json',JSON.stringify(changes,null,2)+'\n',{flag:'wx'});
