import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{execFileSync}from'node:child_process';
import{fixture}from'../ANATOMY_SINGLE_RUN_20260919/R3-S/offline.ts';
import{observedContactSupports}from'../../port/v2/apps/game/src/creature-rig-contact.ts';
import{createDiagnosticFamilyContactSolver}from'./solver-instrument.ts';
const out='audits/BEAR_CONTACT_DIAGNOSTICS_20260922',bear='audits/VISION_D2_GUARDIAN_20260921/fit-01',old=JSON.parse(fs.readFileSync(bear+'/static.json','utf8'));
function sample(folder,id,ms){const f=fixture(path.resolve(folder));let input:any,phase:any,error:any;const original=f.contact.resolve;f.contact.resolve=(p,q)=>{input=structuredClone(p);phase=structuredClone(q);return original(p,q);};try{id==='presentation'?f.presentation(ms):f.action(id,ms);}catch(e){error=String(e);}finally{f.close();}assert(input&&phase);return{f,input,phase,error};}
function run(f,input,phase,passes){const trace:any[]=[];let error=null,result=null;try{result=createDiagnosticFamilyContactSolver(f.record,observedContactSupports(f.record,f.binding),{passes,trace:v=>trace.push(v)}).resolve(input,phase);}catch(e){error=String(e);}return{passes,error,result:result?{maxError:result.maxError,maxPaintTargetErrorPx:result.maxPaintTargetErrorPx}:null,trace};}
const result:any={producer:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),runtime:process.version,scope:'Diagnostic clone only; production solver iteration budget and all gates unchanged',bear:[],controls:[]};
for(const row of old.rows.filter(r=>r.error)){const ms=row.error.ms,{f,input,phase,error}=sample(bear,row.id,ms),baseline=run(f,input,phase,3);assert.equal(error,row.error.message.split('\n')[0]);assert.equal(baseline.error,error);const extended=run(f,input,phase,32);result.bear.push({id:row.id,ms,input,phase,baseline,extended});const it=extended.trace.filter(v=>v.event==='iteration');console.log(JSON.stringify({id:row.id,baseline:baseline.error,curve:it.filter(v=>[0,1,2,3,4,8,16,32].includes(v.pass)).map(v=>({pass:v.pass,max:Math.max(...v.supports.map(s=>s.residualPx)),worst:v.supports.reduce((a,b)=>a.residualPx>b.residualPx?a:b).joint})),extended:extended.error}));}
for(const[subject,folder]of[['crab','audits/ANATOMY_COMPLETION_20260917/crab-fits-03/crab'],['civet','audits/ANATOMY_SINGLE_RUN_20260919/R3-S/civet-input-01']]){const f=fixture(path.resolve(folder));f.player('idle');const times=[0,f.timelines.idle.durationMs/120];f.close();for(const ms of times){const q=sample(folder,'idle',ms),r=run(q.f,q.input,q.phase,3);assert.equal(r.error,q.error??null);result.controls.push({subject,ms,width:q.f.w,height:q.f.h,scaleLength:q.f.contact.scaleLength,run:r});}}
fs.writeFileSync(out+'/bear-diagnostic.json',JSON.stringify(result,null,2)+'\n',{flag:'wx'});
