from pathlib import Path
import json,math,hashlib
p=Path('audits/BEAR_CONTACT_DIAGNOSTICS_20260922');fit=Path('audits/VISION_D2_GUARDIAN_20260921/fit-01')
read=lambda f:json.loads(f.read_text())
d=read(p/'bear-diagnostic.json');rest=read(p/'bear-rest-static.json');observed=read(fit/'static.json');hist=read(p/'reach-history.json');after=read(p/'reach-after.json');decl=read(p/'folded-declarations.json')
curves=[]
for r in d['bear']:
 if r['id']=='approach:gallop':continue
 curve={t['pass']:t for t in r['extended']['trace'] if t['event']=='iteration'}
 curves.append({'id':r['id'],'ms':r['ms'],'worstJoint':max(curve[3]['supports'],key=lambda s:s['residualPx'])['joint'],'passes':{str(n):max(s['residualPx'] for s in curve[n]['supports']) for n in [0,1,2,3,4,8,16,32]},'perSupport3':curve[3]['supports'],'perSupport32':curve[32]['supports']})
g=next(r for r in d['bear'] if r['id']=='approach:gallop')['baseline']['trace'][0];worst=max(g['legs'],key=lambda l:l['shiftNeeded']);w=g['width']
summary={'diagnosticProducer':d['producer'],'curves':curves,'absoluteGatePx':.25,'gallop':{'joint':worst['joint'],'hip':worst['hip'],'knee':worst['knee'],'requiredRootCompressionPx':g['shift']*w,'boundPx':g['bound']*w,'excessPx':(g['shift']-g['bound'])*w,'legLengthPx':worst['reach']*w,'rootTargetDistancePx':worst['distance']*w},'controls':[]}
for c in d['controls']:
 it=[t for t in c['run']['trace'] if t['event']=='iteration'][-1];summary['controls'].append({'subject':c['subject'],'ms':c['ms'],'width':c['width'],'residualPx':max(s['residualPx'] for s in it['supports'])})
(p/'diagnostic-summary.json').write_text(json.dumps(summary,indent=2)+'\n')
lines=['# Bear support iteration diagnosis','',f"Diagnostic producer `{d['producer']}`; original runtime/fit producer `1ff30009`. All sixteen first-refusal replays exactly reproduce the retained errors with the original three corrections. Only the audit clone was measured through 32 corrections; production remains unchanged.",'','## Convergence and paw','', 'The fourteen support-refusing action rows and presentation all fail on **hindFarAnkle**. More iterations approach a two-cycle around **0.305154 px**, not a passing solution. At pass 32 the other active supports are within 0.000000538 px. All four bear support models reduce to 100% ankle ownership: no conflicting mixed weights were found. These are LBS/kinematic residuals before ARAP publication, so extra ARAP iterations cannot explain this refusal.','', 'The hind-far support is offset (−3, −12) source pixels from its ankle, distance 12.369317 px; its almost straight two-bone chain makes the endpoint-offset fixed point oscillate as shared root accommodation changes. At idle, pass31 and32 predict opposite sides of the target with almost equal residual, rather than converging. This is a non-convergent endpoint-offset iteration on this geometry, not evidence that four differently weighted supports demand incompatible poses.','', '| First refusing row | ms | Pass 3 px | Pass 8 px | Pass 16 px | Pass 32 px |','|---|---:|---:|---:|---:|---:|']
for c in curves:lines.append(f"| {c['id']} | {c['ms']:.3f} | {c['passes']['3']:.9f} | {c['passes']['8']:.9f} | {c['passes']['16']:.9f} | {c['passes']['32']:.9f} |")
lines+=['','Per-support vectors, targets, offsets and stance membership at every pass are retained in [bear-diagnostic.json](bear-diagnostic.json); compact pass3/pass32 breakdown is in [diagnostic-summary.json](diagnostic-summary.json).','', '## Gate scale and controls','', 'The gate is **absolute native source pixels**, not a fraction of body length or screen size: the solver multiplies normalized x/y residual by record.geometry.width/height, then compares the Euclidean length with0.25. Resizing a record would change the pixel residual; no resize was performed. Root compression is a separate scale-relative gate at0.08×measured motion length.','', '| Control | Idle sample ms | Native width | Pass 3 maximum residual px |','|---|---:|---:|---:|']
for c in summary['controls']:lines.append(f"| {c['subject']} | {c['ms']:.9f} | {c['width']} | {c['residualPx']:.12g} |")
x=summary['gallop'];lines+=['','## Gallop','',f"At180.266667ms, the limiting chain is **{x['hip']} → {x['knee']} → {x['joint']}**, on the initial endpoint solve before any support correction. It needs{x['requiredRootCompressionPx']:.9f}px of shared downward root accommodation against{x['boundPx']:.9f}px: **{x['excessPx']:.9f}px over**. Root-to-target distance{x['rootTargetDistancePx']:.9f}px exceeds its two-bone length{x['legLengthPx']:.9f}px. This is a chain reach/compression failure, not an angular-limit failure. Rest supports reproduce it at the same sample.",'','## One proposed fix — Nick decision, not applied','', 'Authorize an **analytic rigid-support IK branch for endpoint-only supports**, solving the observed rigid support point directly and deriving the anatomical ankle transform from its unchanged offset. Keep the mixed-weight path, exact rest, terminal rule, existing limits, compression and0.25px gates unchanged. This targets the oscillating endpoint-offset fixed point without raising iteration count or changing paint/weights/landmarks. It needs its own positive/negative controls and S2 producer before adoption. It does not claim to solve gallop’s independently demonstrated compression limit; that refusal remains. No proposed fix was implemented in this run.']
(p/'BEAR_DIAGNOSIS.md').write_text('\n'.join(lines)+'\n')
lines=['# Brown Bear — observed and REST-support static comparison','', '**Common runtime solver and fit producer: `1ff30009d9b8cda3a92d72a2ef07a36c8506d91b`.** Record, binding, clips, gates and solver bytes are unchanged between the two tables. The retained observed evidence was produced at1ff30009; the new REST tool run was signed at`'+rest['producer']+'`. Distinct tool-producer hashes are retained rather than relabeling historical evidence.','', 'Observed:5/20 action rows complete plus presentation refuses. REST:18/20 action rows and presentation complete at the solver; gallop and tail refuse compression. Both have exact rest PASS. REST mode still measures actual painted drift against the unchanged0.25px gate, retaining RED while continuing to distinguish surface failure from solver admission. The stage’s default REST mode does not establish painted-surface planting.','', 'Claude’s read-only G6 review reports zero stage refusals on its selected full turn and3.10ms guardian rig p95. That is a different schedule from this full action library, which includes gallop and tail. This packet neither reruns nor supersedes that native film.','', '## Retained observed supports','', '| Row | Successful samples | Drift px before first refusal | First refusal |','|---|---:|---:|---|']
for r in observed['rows']:
 reason=r['error']['message'].split('\n')[0].removeprefix('Error: ') if r['error'] else 'PASS'
 lines.append(f"| {r['id']} | {r['samples']} | {r['maxPaintDriftPx']:.6f} | {reason} |")
lines+=['','## REST supports','', '| Row | Successful samples | Solver row | Painted drift px | Painted 0.25px gate |','|---|---:|---|---:|---|']
for r in rest['rows']:
 reason=r['error']['message'].split('\n')[0].removeprefix('Error: ') if r['error'] else 'PASS'
 lines.append(f"| {r['id']} | {r['samples']} | {reason} | {r['maxPaintDriftPx']:.6f} | {r['paintGate']} |")
lines+=['','Observed evidence remains [static.json](static.json); REST data and source hashes: [bear-rest-static.json](../../BEAR_CONTACT_DIAGNOSTICS_20260922/bear-rest-static.json), [bear-rest-static.sources.json](../../BEAR_CONTACT_DIAGNOSTICS_20260922/bear-rest-static.sources.json). The producer contains no bear repair.','', 'Detailed root cause and the single proposed fix for Nick: [BEAR_DIAGNOSIS.md](../../BEAR_CONTACT_DIAGNOSTICS_20260922/BEAR_DIAGNOSIS.md). Original1254² size finding and independent60px compiler comparison remain separate. The hand fit is comparison truth, not a claim of observed-support animation admission.']
(fit/'STATIC_VERDICT.md').write_text('\n'.join(lines)+'\n')
lines=['# Freshwater reach history','',f"Measurement producer `{hist['producer']}`. Before solver: `6279e180` (a817ad64 parent). After: `a817ad64`; `1ff30009` has identical solver bytes to a817ad64. Same records/bindings and local motion sampler throughout; no checkout/sync or source mutation during comparison.",'', '**No reach regression inside a817ad64 or1ff30009.** For all six subjects, before/after probe traces (full successful resolver results and refusal strings) hash identically on both rest and observed support models. Without a folded declaration, a817ad64’s new stage branch is inert. Source hashes: history-source-receipts.json; exact traces are summarized and hash-bound in reach-history.json.','', 'The measured change is in Claude’s `port/v2/apps/game/src/battle2/parts-rig.ts`, commit **1dab84c2938a41fa234eb97fa559691412f0d793**: fractions[0.55,0.75,0.95] became[0.05,0.25,0.45,0.55,0.75,0.95], and the result gained a0.9 margin. The new first half exposes the opposing stance group. Freshwater’s old second-half reading0.126953125 becomes first-half minimum0.0703125, then0.06328125 after margin. This is corrected measurement coverage, not a solver defect or basis for restoring the larger allowance. S2 is unchanged because solver-mode outputs never changed.','', '| Subject | Support model | Old second-half, no margin | First-half, no margin | Both halves ×0.9 |','|---|---|---:|---:|---:|']
for r in hist['subjects']:
 for m in r['models']:
  g=m['after']['groups'];lines.append(f"| {r['subject']} | {m['mode']} | {g[0]['unmargined']:.9f} | {g[1]['unmargined']:.9f} | {g[2]['margin90']:.9f} |")
lines+=['','The coarse8-bisection search carries each sample’s admitted bound into the next, so the last digits can differ from an independent per-sample search. The shared121-phase helper is a separate measurement (no0.9 margin); it is compared before/after in FOLDED_REACH.md. No solver fix or new Nick decision is needed for this finding.']
(p/'FRESHWATER_HISTORY.md').write_text('\n'.join(lines)+'\n')
lines=['# Declared folded far sides — original painter fits','', 'Nick’s overnight item4 declares the far legs on the original crab-fits-03 Mud and Vent fits. Applied explicitly as **leg0Far, leg1Far, leg2Far, leg3Far** on each. This is Nick’s declaration, not an automatic image classifier, a short-bone inference, or a transfer of slots from the later P1 paintings. Freshwater is unchanged.','', 'Each fit now has presence.json and matching record.anatomy. Recipe hashes and both binding association/hash headers were resealed so the stage loader that reads record.json consumes the declaration. The complete old JSON inputs are retained under declaration-before/. No landmarks, masks, part inventory, skin vertices/weights/pins, source channels, atlas or clips changed; apply-folded.mjs asserts this. Historical intake receipts retain their original identity.','', '| Subject | Model | Forward before | Forward after | Backward before | Backward after |','|---|---|---:|---:|---:|---:|']
for r in after['rows']:
 b=next(x for x in hist['helperBefore'] if x['subject']==r['subject'])
 for mode in ['rest','observed']:lines.append(f"| {r['subject']} | {mode} | {b[mode]['forward']:.6f} | {r[mode]['forward']:.6f} | {b[mode]['backward']:.6f} | {r[mode]['backward']:.6f} |")
lines+=['','Units: body lengths. Exact same121-phase,24-bisection shared helper before/after. **Only forward reach lifts; backward reach stays limited by the undeclared near side.** Claude must use the direction matching its local facing/travel, not apply the new forward allowance to reverse travel. These are sampled solver envelopes, not a new native stance/CPU certification.','', 'After producer: `'+after['producer']+'`. Positive/negative declaration controls prove solver-mode equality, folded targets body-relative, and undeclared stance targets receding. The full six-subject S2 sweep is separately retained; all receipts and decompressed per-support sample bytes match the prior signed ledger.','', '## Identity receipts','']
for r in decl:
 lines+=['- '+r['subject']+': `'+r['presenceFile']+'`, SHA256 `'+r['presenceSha256']+'`; record recipe `'+r['afterRecipeHash']+'`.']
lines+=['','Full before/after file SHA256s and unchanged-source assertions: [folded-declarations.json](folded-declarations.json). After measurement: [reach-after.json](reach-after.json).']
(p/'FOLDED_REACH.md').write_text('\n'.join(lines)+'\n')
(p/'S2_LEDGER.md').write_text('''# S2 ledger

Producer `99fc32eed25828cf1612516a342f7d0710584437`, signed and verified before the one sweep. Five crabs plus Civet PASS. All six complete subject receipts and all decompressed per-support sample bytes exactly equal the previous signed STAGE_CADENCE_REACH_20260922/s2 packet. Five crabs remain R2c′ row-identical; Civet maximum0.16525637288346104px; exact rest and presentation PASS. No S2 halt.

Evidence: s2/static.json, per-subject static and support-sample files; exact identity assertions and hashes in s2/identity.json. Source-hashed runner: s2-controls.sources.json and s2-controls.log.

The S2 instrument pins the same original signed source-join probe froma817ad64 because byte identity includes its affine breakpoint selection. All current runtime solver/skin/pose modules are loaded and source-hashed. The later source-join bin-search correction is already independently controlled on the bear; it is not a runtime solver change. No S2 threshold was changed or probe failure skipped. Diagnostic-only producers used the prior ledger reference; only the declaration producer changed sentinel inputs, and it received this single sweep. No other subject battery was repeated.
''')
