/** Bounded numerical comparison; native pixels/frame timing remain native gates. */
import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{createHash}from'node:crypto';import{performance}from'node:perf_hooks';import{createRequire}from'node:module';
import * as before from'./arap-before.mjs';import * as after from'../../../port/v2/tools/creature-animation/arap-skin.mjs';
import{createCompiledSkinField,applyCompiledSkinField}from'../../../port/v2/tools/creature-animation/compiled-skin-field.mjs';import{GRAPH}from'../../../port/v2/tools/creature-animation/quadruped-template.mjs';import{composeAffine,rotationAround,IDENTITY_AFFINE}from'../../../port/v2/tools/creature-animation/kinematics.ts';
import{applyPaintPart,paintPartAreas,assertPaintPartShape}from'../../../port/v2/tools/creature-animation/paint-skin.mjs';import{createSourceJoinProbe,assessSourceJoinContinuity}from'../../../port/v2/tools/quadruped-proof/source-join-continuity.mjs';import{createRenderedContactProbe,assessRenderedContacts}from'../../../port/v2/tools/quadruped-proof/rendered-contact.mjs';
const root=path.resolve(import.meta.dirname,'../../..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p))),hash=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex'),require=createRequire(path.join(root,'port/v2/package.json')),{PNG}=createRequire(require.resolve('free-tex-packer-core'))('pngjs'),candidate='audits/C2_CONTINUOUS_SKIN_20260916/candidate-10',poses='audits/C2_CONTINUOUS_SKIN_20260916/current-producer-poses-v2',out=process.argv[2]??path.join(import.meta.dirname,'report.json');assert.ok(!fs.existsSync(out),'new output only');
function matrices(record,pose){const out={},length=Math.hypot(record.landmarks.chest[0]-record.landmarks.pelvis[0],record.landmarks.chest[1]-record.landmarks.pelvis[1]);for(const[j,parent]of[['root',null],...GRAPH]){const pivot=record.landmarks[parent??'root'],key=pose[j],local=key?rotationAround({x:pivot[0],y:pivot[1]},key.rotation,{x:(key.dx??0)*length,y:(key.dy??0)*length}):IDENTITY_AFFINE;out[j]=parent?composeAffine(out[parent],local):local;}return out;}
const bytes=a=>Buffer.from(a.buffer,a.byteOffset,a.byteLength),same=(a,b)=>bytes(a).equals(bytes(b)),maxDifference=(a,b,w,h)=>{let d=0;for(let i=0;i<a.length;i+=2)d=Math.max(d,Math.hypot((a[i]-b[i])*w,(a[i+1]-b[i+1])*h));return d;},checkDifference=(a,b,w,h)=>{const d=maxDifference(a,b,w,h);assert.ok(Number.isFinite(d)&&d<=.001,'kernel difference beyond .001 native px: '+d);return d;};
assert.throws(()=>checkDifference(new Float32Array([0,0]),new Float32Array([.01/1254,0]),1254,1254));
const report={schema:'cf.arap-wasm-leaf-comparison/v1',status:'PASS',scope:'Wasm sweep against the current JS reference: exact output and statistics in both precisions, independent shape checks, and CPU microbenchmark. Native pixels/live frame time remain native gates.',maximumAllowedNativeDifferencePx:.001,node:process.version,source:{before:hash(new URL('./arap-before.mjs',import.meta.url)),after:hash(path.join(root,'port/v2/tools/creature-animation/arap-skin.mjs')),poses:hash(path.join(root,poses,'report.json')),manifest:hash(path.join(root,candidate,'manifest.json'))},controls:{pointZeroOnePixelMutationRejected:true},rows:[]};report.source.leaf=Object.fromEntries(['arap-sweep.c','arap-sweep.wasm','arap-sweep-bytes.mjs','arap-sweep-build.json','wasm-arap-sweep.mjs','build-arap-sweep.mjs'].map(p=>[p,hash(path.join(root,'port/v2/tools/creature-animation',p))]));
for(const spec of read(candidate+'/manifest.json').results){const record=read(spec.record),binding=read(candidate+'/'+spec.id+'.binding.json'),skin=binding.paintSkin,{width,height}=record.geometry,trace=read(poses+'/'+spec.id+'-poses.json'),frames=[...Object.entries(trace.namedPoses).map(([name,p])=>({...p,name})),...trace.dense],compiled=createCompiledSkinField(skin,width,height),row={id:spec.id,fieldVertices:skin.vertices.length,pins:skin.solver.pins.length,samples:frames.length,numerical:{},micro:{}};let nativeTargets;
 const png=PNG.sync.read(fs.readFileSync(path.join(root,spec.base,'atlas',spec.id+'.png'))),atlas={rgba:png.data,width:png.width,height:png.height},joins=createSourceJoinProbe({record,binding,atlas}),contacts=createRenderedContactProbe({record,binding,atlas});
 for(const Type of[Float32Array,Float64Array]){const old=before.createArapScratch(skin.vertices,skin.triangles,width,height,skin.solver),fresh=after.createArapScratch(skin.vertices,skin.triangles,width,height,skin.solver),a=new Type(skin.vertices.length*2),b=a.slice(),targets=[],published={},oldPublished={},parts=skin.parts.map(p=>{published[p.id]=new Float32Array(p.vertices.length*2);oldPublished[p.id]=new Float32Array(p.vertices.length*2);return{p,areas:paintPartAreas(p,skin)};}),stats={samples:frames.length,exactFieldSamples:0,maxFieldDifferencePx:0,maxActualPartDifferencePx:0,restExact:true,hardPinsExact:true,targetsUnchanged:true,folds:0,minAreaRatio:1,maxSourceGapPx:0,maxPlantedRestDisplacementPx:0,maxPawTransformErrorPx:0,maxStatsDifference:{},worst:null};
  for(const [i,frame]of frames.entries()){assert.equal(fresh.sweepBackend,'wasm','must measure admitted Wasm leaf');row.sweepBackend=fresh.sweepBackend;const m=matrices(record,frame.pose),target=a.slice();applyCompiledSkinField(compiled,m,target);const saved=target.slice(),sa=before.solveArapSkin(old,target,a),sb=after.solveArapSkin(fresh,target,b);assert.ok(same(a,b),'exact sweep output parity');assert.deepEqual(sb,sa,'exact sweep stats parity');if(same(a,b))stats.exactFieldSamples++;const delta=checkDifference(a,b,width,height);if(delta>stats.maxFieldDifferencePx){stats.maxFieldDifferencePx=delta;stats.worst={index:i,atMs:frame.atMs,name:frame.name??null};}for(const pin of skin.solver.pins){assert.equal(b[pin*2],target[pin*2]);assert.equal(b[pin*2+1],target[pin*2+1]);}assert.ok(same(target,saved),'target mutation');assert.equal(sb.flippedTriangles,0);stats.minAreaRatio=Math.min(stats.minAreaRatio,sb.minimumAreaRatio);for(const[key,value]of Object.entries(sa))if(typeof value==='number'){const difference=Math.abs(sb[key]-value);assert.ok(Number.isFinite(difference));stats.maxStatsDifference[key]=Math.max(stats.maxStatsDifference[key]??0,difference);}
   for(const{p,areas}of parts){applyPaintPart(p,a,oldPublished[p.id]);applyPaintPart(p,b,published[p.id]);assertPaintPartShape(p,skin,published[p.id],width,height,areas);stats.maxActualPartDifferencePx=Math.max(stats.maxActualPartDifferencePx,checkDifference(oldPublished[p.id],published[p.id],width,height));if(frame.name==='rest')assert.ok(same(oldPublished[p.id],published[p.id]),'rest part bytes changed');}
   const join=assessSourceJoinContinuity(joins,published),contact=assessRenderedContacts(contacts,{positionsByPart:published,matrices:m,planted:frame.planted});assert.equal(join.status,'PASS');assert.ok(!frame.planted||contact.maxRenderedRestDisplacementPx<=1);assert.ok(contact.maxRenderedPawTransformErrorPx<=1);stats.maxSourceGapPx=Math.max(stats.maxSourceGapPx,join.maxGapPx);if(frame.planted)stats.maxPlantedRestDisplacementPx=Math.max(stats.maxPlantedRestDisplacementPx,contact.maxRenderedRestDisplacementPx);stats.maxPawTransformErrorPx=Math.max(stats.maxPawTransformErrorPx,contact.maxRenderedPawTransformErrorPx);if(frame.name==='rest')assert.ok(same(a,b),'rest field bytes changed');targets.push(target);
  }
  row.numerical[Type.name]=stats;if(Type===Float32Array)nativeTargets=targets;
 }
 const old=before.createArapScratch(skin.vertices,skin.triangles,width,height,skin.solver),fresh=after.createArapScratch(skin.vertices,skin.triangles,width,height,skin.solver),output=new Float32Array(skin.vertices.length*2);for(let i=0;i<120;i++){before.solveArapSkin(old,nativeTargets[i],output);after.solveArapSkin(fresh,nativeTargets[i],output);}const timed={before:[],after:[]};for(let round=0;round<2;round++)for(const name of round?['after','before']:['before','after']){const fn=name==='before'?before.solveArapSkin:after.solveArapSkin,scratch=name==='before'?old:fresh;for(const target of nativeTargets){const start=performance.now();fn(scratch,target,output);timed[name].push(performance.now()-start);}}
 for(const[name,values]of Object.entries(timed)){values.sort((a,b)=>a-b);row.micro[name]={samples:values.length,medianMs:values[Math.floor(values.length*.5)],p95Ms:values[Math.floor(values.length*.95)],meanMs:values.reduce((a,b)=>a+b,0)/values.length};}row.micro.medianSpeedup=row.micro.before.medianMs/row.micro.after.medianMs;report.rows.push(row);console.log(JSON.stringify(row));
}
fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(out);
