import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import * as audit from './compiler.audit.mjs';
import * as original from '../../port/v2/tools/painted-creature/compile-library-master.mjs';
const base=import.meta.dirname,sha=b=>createHash('sha256').update(b).digest('hex'),receipt=JSON.parse(fs.readFileSync(base+'/transform-receipt.json')),source=fs.readFileSync(receipt.source,'utf8');assert.equal(sha(source),receipt.sourceSha256);let replay=source;for(const t of receipt.transforms){assert.equal(replay.split(t.before).length,2);replay=replay.replace(t.before,t.after);}replay+=receipt.appended;assert.equal(sha(replay),receipt.outputSha256);assert.equal(replay,fs.readFileSync(base+'/compiler.audit.mjs','utf8'));
const controls=[];const ok=(name,fn)=>{fn();controls.push({name,status:'PASS'})};
ok('Production bytes unchanged and exact transform replay',()=>assert.equal(sha(fs.readFileSync(receipt.source)),receipt.sourceSha256));
for(const row of JSON.parse(fs.readFileSync(base+'/pilot.json')).filter(r=>['Leech'].includes(r.name))){ok(row.name+' exact canonical route, truthful requested leg count and bound source',()=>{const subject=JSON.parse(fs.readFileSync(row.packet+'/subject-source.json')),request=JSON.parse(fs.readFileSync(row.packet+'/request.json'));assert.equal(audit.libraryFamily(subject.profile,subject.species),row.family);assert.equal(request.requestedVisibleLegs,{Leech:0}[row.name]);assert.equal(request.promptSha256,sha(fs.readFileSync(row.packet+'/prompt.txt')));assert.equal(request.kitSha256,sha(fs.readFileSync('ART_KIT.md')));assert.equal(request.referenceSha256,'c53add2993caba39b6dc12dc75d5d767be86896a7c41cfaa6c94f356e8d92a62');});ok(row.name+' mixed route refused',()=>assert.throws(()=>audit.libraryFamily({candidateTemplates:[row.family,'quadruped']},{name:row.name})));ok(row.name+' wrong named template refused',()=>assert.throws(()=>audit.controlledLibraryLayout(row.family,'Wolf')));}
for(const[family,name]of [['quadruped','Civet'],['biped-bird','Heron'],['serpent','Python'],['insect','Ant'],['fish','Trout'],['primate','Capuchin'],['myriapod','Centipede'],['cephalopod','Octopus'],['flyer-membrane','Bat']])ok('Existing layout unchanged '+family,()=>assert.deepEqual(audit.controlledLibraryLayout(family,name),original.controlledLibraryLayout(family,name)));
ok('Production compiler continues refusing specialized source route',()=>assert.throws(()=>original.libraryFamily({candidateTemplates:['annelid']},{name:'Earthworm'})));
fs.writeFileSync(base+'/controls.json',JSON.stringify({scope:'Audit extension only; no native execution or biological admission',sourceSha256:receipt.sourceSha256,auditCompilerSha256:receipt.outputSha256,controls},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({controls:controls.length,passed:controls.every(c=>c.status==='PASS')}));
