import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {createRequire,registerHooks} from 'node:module';
import {resolve} from '../../port/v2/tools/effects-proof/resolve-ts-hook.mjs';registerHooks({resolve});
const {compileBodyCard,buildTimeline,createGsapPlayer}=await import('../../port/v2/apps/game/src/motion/index.ts');
const {withPaintedContactSupports}=await import('../../port/v2/apps/game/src/motion/painted-supports.ts');
const {loadCreatureRigV1}=await import('../../port/v2/apps/game/src/creature-rig.ts');
const {createPaintPublication}=await import('../C132_FAINT_GROUND_20261002/paint-publication.mjs');
const {rasterPaint}=await import('../C132_FAINT_GROUND_20261002/render-mesh.mjs');
const {createOpaqueSeamSamplingGuard,applyOpaqueSeamSamplingGuard}=await import('../../port/v2/tools/creature-animation/seam-sampling-guard.mjs');
const req=createRequire(new URL('../../port/v2/package.json',import.meta.url)),{PNG}=req('pngjs'),{BufferImageSource,Texture}=req('pixi.js'),base='audits/C192_SPECIALIZED_REFERENCES_20261002',id=process.argv[2];assert(/^\d\d-[a-z0-9-]+$/.test(id));
const dir=base+'/'+id,fit=dir+'/d28/fit',read=p=>fs.readFileSync(p),json=p=>JSON.parse(read(p)),sha=b=>createHash('sha256').update(b).digest('hex'),pins=new Map(),pin=p=>pins.set(p,sha(read(p))),reportPath=dir+'/publication-d28.json';assert(!fs.existsSync(reportPath));
function scan(d,re){for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=d+'/'+e.name;if(e.isDirectory())scan(p,re);else if(re.test(p))pin(p);}}
scan('port/v2/apps/game/src/motion',/\.ts$/);scan('port/v2/tools/creature-animation',/\.(mjs|ts|wasm)$/);for(const p of ['port/v2/apps/game/src/creature-rig.ts','port/v2/apps/game/src/creature-rig-contact.ts',base+'/review-d28.mjs','audits/C132_FAINT_GROUND_20261002/paint-publication.mjs','audits/C132_FAINT_GROUND_20261002/render-mesh.mjs',fit+'/record.json',fit+'/binding.json',fit+'/parts/keyed.png',dir+'/master.png',dir+'/authoring.json'])pin(p);
const record=json(fit+'/record.json'),binding=json(fit+'/binding.json'),card=withPaintedContactSupports(compileBodyCard(record,record.genome),record,binding),publication=createPaintPublication(record,binding,card.realm),atlasPath=fit+'/parts/atlas/'+fs.readdirSync(fit+'/parts/atlas').find(p=>p.endsWith('.png')),atlasBytes=read(atlasPath),atlas=PNG.sync.read(atlasBytes),keyed=PNG.sync.read(read(fit+'/parts/keyed.png'));pin(atlasPath);
const guard=createOpaqueSeamSamplingGuard({record,binding,atlas:{width:atlas.width,height:atlas.height,rgba:atlas.data}}),before=sha(atlas.data),guarded={...atlas,data:applyOpaqueSeamSamplingGuard(Uint8Array.from(atlas.data),atlas.width,atlas.height,guard)};assert.equal(sha(atlas.data),before);
const alpha=Uint8Array.from({length:keyed.width*keyed.height},(_,i)=>keyed.data[i*4+3]),texture=new Texture({source:new BufferImageSource({resource:new Uint8Array(atlas.data),width:atlas.width,height:atlas.height})}),rig=await loadCreatureRigV1(record,binding,read(dir+'/master.png'),alpha,atlasBytes,async()=>texture),staticReport=json(dir+'/static-d28.json'),gait=staticReport.actionInventory.find(a=>a.startsWith('approach')),attack=staticReport.actionInventory.find(a=>a==='cast'||a.startsWith('attack:')),actions=['idle',gait,...(attack?[attack]:[]),'hit','faint'],rows=[];
try{for(const action of actions){const tl=buildTimeline(card,action,record.identity.seed);let pose={};const player=createGsapPlayer(tl,{setJoint(j,rotation,dx,dy){pose[j]={rotation,dx,dy};}},{now:()=>0});try{for(const fraction of action==='idle'?[0.5]:action==='faint'?[.5,1]:[.5]){
 const elapsedMs=tl.durationMs*fraction,row={action,fraction,elapsedMs,status:'PASS',qualityAccepted:false};try{pose={};player.seek(elapsedMs);const frame=publication.publish(pose,{actionId:tl.actionId,elapsedMs,durationMs:tl.durationMs,weight:1});rig.applyPose(frame.resolved);let coordinates=0;for(const part of rig.parts){const actual=part.display.children[0].geometry.getBuffer('aPosition').data,expected=frame.positions[part.id];assert.equal(actual.length,expected.length);assert(Buffer.from(actual.buffer,actual.byteOffset,actual.byteLength).equals(Buffer.from(expected.buffer,expected.byteOffset,expected.byteLength)),'actual publication differs '+part.id);coordinates+=actual.length;}row.byteParityCoordinates=coordinates;row.maximumPublishedContactDriftPx=Math.max(0,...frame.publishedContacts.map(c=>c.driftPx));row.files=[];
 for(const side of ['left','right']){const p=dir+'/motion-d28-'+action.replaceAll(':','-')+'-'+Math.round(fraction*100)+'-'+side+'.png';fs.writeFileSync(p,PNG.sync.write(rasterPaint(record,binding,guarded,frame.positions,side==='left'?1:-1)),{flag:'wx'});row.files.push({path:p,sha256:sha(read(p))});}
 }catch(e){row.status='REFUSED';row.reason=String(e.stack??e).replaceAll(/\/Users\/[^/\s"\\]+/g,'~');}rows.push(row);
 }}finally{player.stop();}}}finally{rig.dispose();}
for(const [p,h]of pins)assert.equal(sha(read(p)),h,'source drift '+p);
const out={schema:'cf.c186-specialized-publication/v1',scope:'Source-coordinate software raster, current contact/skin/ARAP/rigid-parent publication byte-compared to actual loaded CreatureRigV1. Canonical library samples, no stage choreography or native film. No visual/performance admission.',id,recordRecipeHash:record.recipeHash,bindingHash:binding.bindingHash,rows,sourcePins:[...pins].map(([path,sha256])=>({path,sha256})),sourceUnchanged:true,nativeRuns:0,qualityAccepted:false};fs.writeFileSync(reportPath,JSON.stringify(out,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({id,rows:rows.map(({action,fraction,status,reason})=>({action,fraction,status,reason}))}));if(rows.some(r=>r.status!=='PASS'))process.exitCode=1;
