import fs from'node:fs';import{createHash}from'node:crypto';import{compileLibraryMaster}from'../../port/v2/tools/painted-creature/compile-library-master.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),base='audits/BOBCAT_LAYOUT_C96_20260927',names=JSON.parse(fs.readFileSync(base+'/queued-names.json')).names,rows=[];
const framing='ZOOMED-OUT COMPOSITION: paint a SMALL specimen centred in a large empty magenta square. The complete creature spans ONLY HALF the canvas width and at most HALF its height. Keep at least 200 pixels of empty magenta on every side of this 1254-square canvas. Do not enlarge the specimen to fill the image. Preserve all natural anatomy, toes, antennae, bill and true tail. Empty margin is intentional; never crop or shorten anatomy.';
const layouts={
 serpent:'REFERENCE LAYOUT: side-on, head RIGHT and true tapering tail LEFT. One low shallow horizontal S-curve whose centreline advances monotonically from tail to head in x. No coils, knots, crossing, U-turn, raised head or hooked terminal tail. Preserve natural trunk thickness, scale patterns, head shape and true tail; expose a rattlesnake rattle only when this species has one. The continuous body stays within the same low ground band.',
 quadruped:'REFERENCE LAYOUT: quiet planted walking STRIDE, all FOUR legs clearly APART from their body attachments down to each foot, with visible background gaps. Offset near and far forelegs and near and far hindlegs naturally. Keep the real species tail visibly attached and continuous; preserve a naturally short tail. No rearing, seated pose, crossed legs or duplicate limb. Choose a natural side-view head pose exposing BOTH ears as separate complete silhouettes, including BOTH ear tips; offset the far ear visibly above or beside the near ear. The true tail must sit clear of the body and legs from its visible root to its tip. Do not invent an ear, lengthen a short tail, or add a tail to a naturally tailless animal.',
 'biped-bird':'REFERENCE LAYOUT: standing bird with naturally FOLDED wings held ABOVE the visible tail. Keep its entire tail root and true feather tail continuous and distinct. Where natural for this species, fold the wing tips visibly SHORT OF the tail tip and ABOVE the tail feathers so their boundaries can be read separately. Preserve natural feather lengths: never shorten wings or lengthen the tail to fake this. Near and far legs visibly separated all the way from the feathered body to both planted feet, not just separated toes. Preserve species-correct short tails and long bills; no invented extra wing or gap through the body.',
 insect:'REFERENCE LAYOUT: strict side profile, head RIGHT. All SIX thoracic legs visible in three near/far pairs, each pair offset so the shafts and tarsi are readable from their real attachments. Preserve the full natural abdomen at LEFT. Natural adult wing resting position overrides a generic folded-wing request: dragonfly wings held out flat, damselfly wings closed over back, mayfly wings upright. No invented vertebrate tail, extra legs or hidden-paint declaration.',
 fish:'REFERENCE LAYOUT: horizontal fish, head RIGHT and complete caudal tail LEFT; species-correct fin count, finlets, barbels and tail shape. Natural fin rays and fin roots must stay distinct; no detached pieces. Keep the tail stalk continuous.'};
for(const[i,name]of names.entries()){
 const id=String(i+1).padStart(2,'0')+'-'+name.toLowerCase().replaceAll(' ','-'),packet=base+'/'+id;
 if(process.argv.includes('--resume')&&fs.existsSync(packet+'/request.json')){const request=JSON.parse(fs.readFileSync(packet+'/request.json'));if(request.name!==name||sha(fs.readFileSync(packet+'/prompt.txt'))!==request.promptSha256||!layouts[request.family])throw Error('Exact prior packet required');rows.push({id,name,family:request.family,packet,master:packet+'/master.png'});console.log(id,'retained unchanged');continue;}
 const r=await compileLibraryMaster(name,packet),file=packet+'/prompt.txt',old=fs.readFileSync(file,'utf8'),request=JSON.parse(fs.readFileSync(packet+'/request.json')),species=JSON.parse(fs.readFileSync(packet+'/subject-source.json')).species;
 if(sha(old)!==request.promptSha256||!layouts[r.family])throw Error('Exact supported compiler output required');
 const prefix='Species identity features FIRST: '+species.mustRead.join('; ')+'. One Earth '+name+'. These identifying patterns and structures override conflicting generic colour or procedural-genome suggestions.\n'+framing+'\n'+layouts[r.family]+'\n\n',prompt=prefix+old;
 fs.writeFileSync(file+'.tmp',prompt,{flag:'wx'});fs.renameSync(file+'.tmp',file);fs.writeFileSync(packet+'/request.json.tmp',JSON.stringify({...request,basePromptSha256:request.promptSha256,promptSha256:sha(prompt),layoutCompilerSha256:sha(fs.readFileSync(import.meta.filename)),layoutClarification:prefix},null,2)+'\n',{flag:'wx'});fs.renameSync(packet+'/request.json.tmp',packet+'/request.json');rows.push({id,name,family:r.family,packet,master:packet+'/master.png'});console.log(id,r.family);
}
fs.writeFileSync(base+'/pilot.json',JSON.stringify(rows,null,2)+'\n',{flag:'wx'});
