// GENERATED by tools/morph/build-card-masters.mjs from its CARD_ARCHETYPES list — do not edit by hand; re-run the tool.
import type { PaintedCardArchetype } from './painted-card-source.js';
export const CARD_ARCHETYPES: readonly PaintedCardArchetype[] = Object.freeze([
  { earthName: 'Crab', dir: 'port/v2/apps/game/assets/painted-cards/crab/' },
  { earthName: 'Coconut Crab', dir: 'port/v2/apps/game/assets/painted-cards/coconut-crab/' },
  { earthName: 'Freshwater Crab', dir: 'port/v2/apps/game/assets/painted-cards/freshwater-crab/' },
  { earthName: 'Mud Crab', dir: 'port/v2/apps/game/assets/painted-cards/mud-crab/' },
  { earthName: 'Vent Crab', dir: 'port/v2/apps/game/assets/painted-cards/vent-crab/' },
  { earthName: 'Civet', dir: 'port/v2/apps/game/assets/painted-cards/civet-sentinel-input-01/' },
  { earthName: 'Salmon', dir: 'port/v2/apps/game/assets/painted-cards/salmon/' },
  { earthName: 'Eagle', dir: 'port/v2/apps/game/assets/painted-cards/eagle/' },
  { earthName: 'Beetle', dir: 'port/v2/apps/game/assets/painted-cards/beetle/' },
  { earthName: 'Python', dir: 'port/v2/apps/game/assets/painted-cards/python/' },
  { earthName: 'Tree Frog', dir: 'port/v2/apps/game/assets/painted-cards/tree-frog/' },
  { earthName: 'Chimpanzee', dir: 'port/v2/apps/game/assets/painted-cards/chimpanzee/' },
  { earthName: 'Starfish', dir: 'port/v2/apps/game/assets/painted-cards/starfish/' },
  { earthName: 'Tarantula', dir: 'port/v2/apps/game/assets/painted-cards/tarantula/' },
  { earthName: 'Octopus', dir: 'port/v2/apps/game/assets/painted-cards/octopus/' },
  { earthName: 'Fruit Bat', dir: 'port/v2/apps/game/assets/painted-cards/fruit-bat/' },
  { earthName: 'Centipede', dir: 'port/v2/apps/game/assets/painted-cards/centipede/' },
]);
