/** Bounded CPU comparison, never a native frame-time claim. Run from repo root. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createHash}from'node:crypto';import{performance}from'node:perf_hooks';
import * as before from './arap-before.mjs';import * as after from '../../../port/v2/tools/creature-animation/arap-skin.mjs';
import{createCompiledSkinField,applyCompiledSkinField}from'../../../port/v2/tools/creature-animation/compiled-skin-field.mjs';
import{GRAPH}from'../../../port/v2/tools/creature-animation/quadruped-template.mjs';import{composeAffine,rotationAround,IDENTITY_AFFINE}from'../../../port/v2/tools/creature-animation/kinematics.ts';
const root=path.resolve(import.meta.dirname,'../../..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p))),hash=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex'),candidate='audits/C2_CONTINUOUS_SKIN_20260916/candidate-10',poses='audits/C2_CONTINUOUS_SKIN_20260916/current-producer-poses-v2',out=process.argv[2]??path.join(import.meta.dirname,'report.json');assert.ok(!fs.existsSync(out),'new output only');
function matrices(record,pose){const out={},length=Math.hypot(record.landmarks.chest[0]-record.landmarks.pelvis[0],record.landmarks.chest[1]-record.landmarks.pelvis[1]);for(const[j,parent]of[['root',null],...GRAPH]){const pivot=record.landmarks[parent??'root'],key=pose[j],local=key?rotationAround({x:pivot[0],y:pivot[1]},key.rotation,{x:(key.dx??0)*length,y:(key.dy??0)*length}):IDENTITY_AFFINE;out[j]=parent?composeAffine(out[parent],local):local;}return out;}
const bytes=a=>Buffer.from(a.buffer,a.byteOffset,a.byteLength),same=(a,b)=>bytes(a).equals(bytes(b));
// Exercise the actual comparator with a one-bit mutation, not a tolerance.
const control=new Float64Array([.375]),mutant=control.slice();new Uint8Array(mutant.buffer)[0]^=1;assert.equal(same(control,mutant),false);
const report={schema:'cf.arap-kernel-parity/v1',status:'PASS',scope:'CPU microbenchmark and exact buffer/stat parity. Does not qualify native frame time, browser arithmetic or capture acceptance.',node:process.version,source:{before:hash(new URL('./arap-before.mjs',import.meta.url)),after:hash(path.join(root,'port/v2/tools/creature-animation/arap-skin.mjs')),poses:hash(path.join(root,poses,'report.json')),manifest:hash(path.join(root,candidate,'manifest.json'))},controls:{singleBitMutationRejected:true},rows:[]};
for(const spec of read(candidate+'/manifest.json').results){const record=read(spec.record),binding=read(candidate+'/'+spec.id+'.binding.json'),skin=binding.paintSkin,{width,height}=record.geometry,trace=read(poses+'/'+spec.id+'-poses.json'),frames=[...Object.values(trace.namedPoses),...trace.dense],compiled=createCompiledSkinField(skin,width,height),row={id:spec.id,fieldVertices:skin.vertices.length,pins:skin.solver.pins.length,samples:frames.length,parity:{},micro:{}};let nativeTargets;
 for(const Type of[Float32Array,Float64Array]){const old=before.createArapScratch(skin.vertices,skin.triangles,width,height,skin.solver),fresh=after.createArapScratch(skin.vertices,skin.triangles,width,height,skin.solver),a=new Type(skin.vertices.length*2),b=a.slice(),targets=[];
  for(const [i,frame]of frames.entries()){const target=a.slice();applyCompiledSkinField(compiled,matrices(record,frame.pose),target);const saved=bytes(target).toString('base64'),sa=before.solveArapSkin(old,target,a),sb=after.solveArapSkin(fresh,target,b);assert.ok(same(a,b),spec.id+' '+Type.name+' output '+i);assert.deepEqual(sb,sa,spec.id+' '+Type.name+' stats '+i);assert.equal(bytes(target).toString('base64'),saved,'input mutation');targets.push(target);}
  row.parity[Type.name]={samples:frames.length,outputBytesIdentical:true,statsIdentical:true,targetsUnchanged:true};if(Type===Float32Array)nativeTargets=targets;
 }
 // Warm both functions equally, then reverse their order for the second sweep.
 const old=before.createArapScratch(skin.vertices,skin.triangles,width,height,skin.solver),fresh=after.createArapScratch(skin.vertices,skin.triangles,width,height,skin.solver),output=new Float32Array(skin.vertices.length*2);for(let i=0;i<120;i++){before.solveArapSkin(old,nativeTargets[i],output);after.solveArapSkin(fresh,nativeTargets[i],output);}const timed={before:[],after:[]};for(let round=0;round<2;round++)for(const name of round?['after','before']:['before','after']){const fn=name==='before'?before.solveArapSkin:after.solveArapSkin,scratch=name==='before'?old:fresh;for(const target of nativeTargets){const start=performance.now();fn(scratch,target,output);timed[name].push(performance.now()-start);}}
 for(const[name,values]of Object.entries(timed)){values.sort((a,b)=>a-b);row.micro[name]={samples:values.length,medianMs:values[Math.floor(values.length*.5)],p95Ms:values[Math.floor(values.length*.95)],meanMs:values.reduce((a,b)=>a+b,0)/values.length};}row.micro.medianSpeedup=row.micro.before.medianMs/row.micro.after.medianMs;report.rows.push(row);console.log(JSON.stringify(row));
}
fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(out);
