import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import{registerHooks}from'node:module';
import{resolve}from'../../port/v2/tools/effects-proof/resolve-ts-hook.mjs';registerHooks({resolve});
const{compileBodyCard}=await import('../../port/v2/apps/game/src/motion/body-card.ts'),{buildTimeline}=await import('../../port/v2/apps/game/src/motion/timeline.ts'),{actionsFor}=await import('../../port/v2/apps/game/src/motion/family-actions.ts'),{compileAnatomyAttack}=await import('../../port/v2/apps/game/src/anatomy-attacks.ts');
const base='audits/C198_PRAWN_ATTACK_20261003',fit='audits/C196_SPECIALIZED_REFERENCES_20261003/01-prawn-contours/fit01',read=p=>JSON.parse(fs.readFileSync(p)),sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex'),r=read(fit+'/record.json'),c=compileBodyCard(r,r.genome),failures=[];
for(const[name,call]of[['generic melee',()=>buildTimeline(c,'melee',c.identity.seed)],['anatomical attack',()=>compileAnatomyAttack(c,'water',0)]]){try{call();throw Error('expected original refusal');}catch(e){failures.push({name,reason:e.message});}}
assert.match(failures[0].reason,/no admitted crustacean-small melee for weapons \[\]/);assert.match(failures[1].reason,/no admitted move/);
const fixtures=read('port/v2/tools/creature-animation/test-fixtures/family-records.json').records,unchanged=[];
for(const [family,record]of Object.entries(fixtures)){const card=compileBodyCard(record,record.genome),timelines={};for(const id of Object.keys(actionsFor(family,card.anatomy)))timelines[id]=buildTimeline(card,id,card.identity.seed);unchanged.push({family,record,timelines});}
const other=['audits/C186_SPECIALIZED_REFERENCES_20261002/01-earthworm-direct/fit01','audits/C192_SPECIALIZED_REFERENCES_20261002/10-snail-contours/d28/fit','audits/C196_SPECIALIZED_REFERENCES_20261003/03-mussel-islands/d28/fit'];
for(const f of other){const record=read(f+'/record.json'),card=compileBodyCard(record,record.genome),timelines={};for(const id of Object.keys(actionsFor(card.template.id,card.anatomy)))timelines[id]=buildTimeline(card,id,card.identity.seed);unchanged.push({family:card.template.id,record,timelines});}
const prior={};for(const id of Object.keys(actionsFor(c.template.id,c.anatomy)))prior[id]=buildTimeline(c,id,c.identity.seed);
fs.writeFileSync(base+'/baseline.json',JSON.stringify({schema:'cf.c198-prawn-baseline/v1',fit,recipeHash:r.recipeHash,recordSha256:sha(fit+'/record.json'),bindingSha256:sha(fit+'/binding.json'),weapons:c.weapons,failures,prior,unchanged},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({failures,unchangedRows:unchanged.length,priorActions:Object.keys(prior).length}));
