from pathlib import Path

def replace(file,old,new):
 p=Path(file); s=p.read_text(); assert s.count(old)==1,(file,s.count(old)); q=p.with_name(p.name+'.c198-tmp'); q.write_text(s.replace(old,new)); q.replace(p)
base='port/v2/apps/game/src/'
replace(base+'anatomy-attacks.ts',"export const ANATOMY_ATTACKS:readonly AnatomyAttack[]=Object.freeze([", "export const ANATOMY_ATTACKS:readonly AnatomyAttack[]=Object.freeze([\n row('crustacean-small','claw','claw','Foreleg tip strike',['thorax','head','leg0NearRoot','leg0NearKnee','leg0NearFoot','leg0FarRoot','leg0FarKnee','leg0FarFoot'],'leg0NearFoot',['water'],'strike'),")
old=' group("small-crustacean",["Brine Shrimp", "Water Flea", "Krill", "Copepod", "Amphipod", "Cave Shrimp", "Freshwater Shrimp", "Shrimp", "Prawn", "Giant Isopod", "Isopod", "Vent Shrimp", "Fairy Shrimp", "Tadpole Shrimp"],["crustacean-small"],["water"],[],"Observed segmented swimming/crawling appendages; no generic stinger.",true),'
new=' group("shrimp-prawn",["Cave Shrimp", "Freshwater Shrimp", "Shrimp", "Prawn", "Vent Shrimp"],["crustacean-small"],["water"],["claw"],"Observed bilateral foreleg root/knee/tip strike; no articulated pincer closure without fixed/dactyl landmarks.",true),\n group("small-crustacean",["Brine Shrimp", "Water Flea", "Krill", "Copepod", "Amphipod", "Giant Isopod", "Isopod", "Fairy Shrimp", "Tadpole Shrimp"],["crustacean-small"],["water"],[],"Observed segmented swimming/crawling appendages; no generic stinger.",true),'
replace(base+'earth-fauna-profiles.ts',old,new)
replace(base+'motion/specialized-actions.ts'," // Physical contacts require source-observed parts/capabilities in the selector."," // Physical contacts require source-observed parts/capabilities in the selector.\n // Geometry-directed foreleg motion is authored by smallCrustaceanAttackAction.\n if(id==='crustacean-small')actions.push({id:'melee:claw',family:'melee',loop:false,poses:[P(1,{})]});")
replace(base+'motion/timeline.ts',"import {castAttackAction,CAST_ATTACK_NOTE} from './cast-attack.js';","import {castAttackAction,CAST_ATTACK_NOTE} from './cast-attack.js';\nimport {smallCrustaceanAttackAction} from './small-crustacean-attack.js';")
replace(base+'motion/timeline.ts',"const sprawler=sprawlerAction(card,authored),axial=axialFaintAction(card,sprawler),action=castAttackAction(card,axial);","const sprawler=sprawlerAction(card,authored),axial=axialFaintAction(card,sprawler),action=smallCrustaceanAttackAction(card,castAttackAction(card,axial));")
# The broad contract test now includes this new family via an actual retained record.
replace(base+'anatomy-attacks.test.ts',"(family==='brachyuran'?read('ANATOMY_COMPLETION_20260917/crab-fits-03/crab/record.json'):undefined)","(family==='brachyuran'?read('ANATOMY_COMPLETION_20260917/crab-fits-03/crab/record.json'):family==='crustacean-small'?read('C196_SPECIALIZED_REFERENCES_20261003/01-prawn-contours/fit01/record.json'):undefined)")
replace(base+'earth-fauna-profiles.test.ts',"it('wires exactly the 53 previously empty identities without claiming fits or changing habitats/weapons',()=>{","it('retains the 53 observed-fit requirements; only the five reviewed shrimp/prawn intents gain a foreleg strike',()=>{")
replace(base+'earth-fauna-profiles.test.ts',"expect(p.intendedMoves).toEqual(row.intendedMoves);expect(p.candidateTemplates)","expect(p.intendedMoves).toEqual(['Cave Shrimp','Freshwater Shrimp','Shrimp','Prawn','Vent Shrimp'].includes(row.name)?['claw']:row.intendedMoves);expect(p.candidateTemplates)")
