import assert from'node:assert/strict';import fs from'node:fs';import{createHash}from'node:crypto';
import{placeFirstAxisRemainder}from'./first-axis-remainder.mjs';
const parts=['root',...Array.from({length:6},(_,i)=>'spine'+i),'dorsal'].map(joint=>({id:joint,joint})),width=100,height=10,labels=new Uint8Array(width*height),rgba=new Uint8Array(labels.length*4),record={template:{id:'fish'},landmarks:Object.fromEntries(['root',...Array.from({length:6},(_,i)=>'spine'+i)].map((j,i)=>[j,[.9-i*.1,.5]]))};
function put(x,y,owner){labels[y*width+x]=owner;rgba[(y*width+x)*4+3]=255;}
put(90,5,1);put(84,5,2);put(45,5,2);put(44,5,8);const input={parts,width,height,labels,rgba,record,remainder:2};
const before=Buffer.from(rgba),r=placeFirstAxisRemainder(input);assert.equal(r.labels[545],6);assert.equal(r.labels[584],2);assert.equal(r.labels[590],1);assert.equal(r.labels[544],8);assert.deepEqual(Buffer.from(rgba),before);assert.equal(labels[545],2);
const mutations=[{name:'wrong-owner',input:{...input,remainder:8},match:/first-spine remainder/},{name:'root-remainder',input:{...input,remainder:1},match:/first-spine remainder/},{name:'duplicate-spine-owner',input:{...input,parts:[...parts,{id:'extra',joint:'spine3'}]},match:/unique owner/},{name:'missing-painted-root',input:{...input,labels:Uint8Array.from(labels,x=>x===1?2:x)},match:/painted root/},{name:'nonmonotone-axis',input:{...input,record:{...record,landmarks:{...record.landmarks,spine3:[.95,.5]}}},match:/monotone/},{name:'invalid-raster',input:{...input,width:99},match:/raster shape/}];
for(const m of mutations)assert.throws(()=>placeFirstAxisRemainder(m.input),m.match,m.name);
const source=fs.readFileSync(new URL('first-axis-remainder.mjs',import.meta.url),'utf8'),old="need(owner('spine0')===remainder,'first-spine remainder identity');";assert.equal(source.split(old).length,2);const mutant=(await import('data:text/javascript;base64,'+Buffer.from(source.replace(old,'')).toString('base64'))).placeFirstAxisRemainder;
assert.doesNotThrow(()=>mutant(mutations[0].input));assert.notEqual(mutant(mutations[0].input).labels[544],8,'disabled identity guard edits protected dorsal owner');
const sha=b=>createHash('sha256').update(b).digest('hex');fs.writeFileSync(new URL('controls.json',import.meta.url),JSON.stringify({positive:'exact expected placement, separate root/front-spine/foreign owners and original RGBA preserved',refusals:mutations.map(m=>m.name),disabledIdentityGuard:'changes protected dorsal label: control detects weakened identity',helperSha256:sha(source)},null,2)+'\n');console.log('7 controls PASS; disabled identity guard demonstrably edits foreign paint');
