// Packet-only P1 guardian compilation; no intake, landmark, mask or binding writers.
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
const out=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(out,'../../..');
const template='audits/VISION_P1_QUADRUPED_20260921/generation-01/prompt.txt',guide='port/v2/apps/game/smoke/gp71-platinum-repair-current-2026-08-11-03ea297/portraits/earth-fauna/Brown_Bear.png',atlas='audits/MIDGAME_ART_DIRECTION_20260908/01-discovery-atlas.png',catalogue='port/v2/reference/fauna.json';
const read=p=>fs.readFileSync(path.join(root,p)),sha=b=>createHash('sha256').update(b).digest('hex'),write=(p,b)=>fs.writeFileSync(path.join(out,p),b,{flag:'wx'}),json=(p,v)=>write(p,JSON.stringify(v,null,2)+'\n');
const matches=JSON.parse(read(catalogue)).filter(x=>x.name==='Brown Bear');if(matches.length!==1||matches[0].posture!=='quadruped')throw Error('Brown Bear catalogue');const bear=matches[0];
if(sha(read(atlas))!=='c53add2993caba39b6dc12dc75d5d767be86896a7c41cfaa6c94f356e8d92a62')throw Error('Style lock changed');
let prompt=read(template).toString('utf8');const section=(a,b,value)=>{if(prompt.split(a).length!==2||prompt.split(b).length!==2)throw Error('Nonunique section');prompt=prompt.slice(0,prompt.indexOf(a)+a.length)+value+prompt.slice(prompt.indexOf(b));};
const count='one head, exactly one head; four legs, two forelegs and two hindlegs, with four separately readable broad plantigrade paws; two small rounded ears; two anatomical small dark eyes, far eye naturally occluded in side view; one short bear tail';
const adaptation=prompt.split('\n').filter(x=>x.startsWith('  Fauna adaptation:'));if(adaptation.length!==1)throw Error('Fauna slot');prompt=prompt.replace(adaptation[0],`  Fauna adaptation: Earth named anatomy and natural materials take priority. Brown Bear, quadruped mammal, Earth-temperate apex guardian; ${bear.mustRead.join('; ')}. Natural brown fur. This isolated guardian master is the authorized D2 subject, not a change to the generated roster.`);
section('SUBJECT\n','\n\nACCURACY\n',`One Earth Brown Bear (Ursus arctos), the authorized Earth-temperate apex guardian, intended for titanic battle-screen fill; ${count}; ${bear.mustRead.join('; ')}; ${bear.note}. Heavy connected shoulder and forequarter mass, dense deep brown fur with tawny guard-hair tips, dark muzzle and long pale digging claws. Use the attached side-on painter guide for body proportions and facing: broad shoulder hump is the highest point, lowered hips, head facing right. Render all four paws separately readable by a modest natural offset of the far-side legs. Stand on four legs, never upright. The guide is anatomical reference only: do not copy its flat graphic shading, dark background or merged leg silhouettes.\nFace and temper: broad heavy forehead, low brow above small deep-set dark eyes, short rounded ears angled back, a dished concave nasal bridge, broad black nose, wrinkled muzzle, tight upper lip lifted in a restrained threatening snarl, glimpsed natural canine teeth and heavy lower jaw; watchful, territorial and dangerous, never friendly or cute. More ornate focal paint detail than ordinary fauna comes from layered shoulder guard hairs, individual muzzle folds, worn natural claw ridges and dense brow texture, without added armour or appendages. Sol's retained One signature is explicitly no biome hazard in source: carry no invented black glass, shards, ring shadow or other hazard motif. Preserve the source-owned Sol ivory natural light and Earth materials.`);
section('ACCURACY\n','\n\nLAYOUT\n',`  Anatomy/count constraints: ${count}.\n  Must include: complete body, shoulder hump, all four paws, whole muzzle, two ears and short tail.\n  Must exclude: armour, gear, horns, extra growths, scenery, floor, cast shadow, text, a second animal, extra or missing legs.\n  Scale relationship: titanic apex guardian, intended to fill the battle screen through stage scale; no person or scale bar in the master.`);
section('LAYOUT\n','\n\nTECHNICAL OUTPUT\n','  One isolated full-body Brown Bear guardian, centred and weighty.\n  Side-on facing right, matching the painter guide; four separately readable paws.\n  Entire anatomy in frame; no floor or base.\n  Framing target: 80 percent; safe margin at least 8 percent on every side.');
const old='Create a square 1024 x 1024 PNG.';if(prompt.split(old).length!==2)throw Error('Size slot');prompt=prompt.replace(old,'Create a square 1536 x 1536 PNG (exact output dimensions: 1536 pixels wide and 1536 pixels high).');
const kit=read('ART_KIT.md').toString('utf8'),a='THE GUARDIAN RULE:',b='THE MORPH RULE (breeding and variants):';if(kit.split(a).length!==2||kit.split(b).length!==2)throw Error('Guardian block');const guardian=kit.slice(kit.indexOf(a),kit.indexOf(b)).trim();prompt=prompt.replace('\n\nSUBJECT\n','\n\n'+guardian+'\n\nSOURCE APPLICATION\n  The Sol system card above owns the One signature. Its no-hazard declaration overrides the guardian block’s illustrative alien-material examples; do not invent a source hazard.\n\nSUBJECT\n');
write('prompt.txt',prompt);write('anatomy-guide.png',read(guide));json('subject-source.json',{species:bear,catalogue,guide,guideNativeSize:[440,440],handLandmarks:false,sourceNote:'Actual fauna.json headFrac is 0.27; the design note says 0.22. Catalogue is authoritative. Retained painter guide is native 440 square, not resampled.'});
json('request.json',{schema:'cf.painted-master-request/v1',species:'Brown Bear',generation:1,sourceHead:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),compiler:'compile-prompt.mjs',compilerSha256:sha(fs.readFileSync(fileURLToPath(import.meta.url))),template:{path:template,sha256:sha(read(template))},catalogue:{path:catalogue,sha256:sha(read(catalogue))},kit:{path:'ART_KIT.md',sha256:sha(read('ART_KIT.md'))},sentPromptSha256:sha(prompt),tool:'image_gen.imagegen',model:'not exposed',seed:null,seedReason:'No seed parameter exposed',references:[{role:'Discovery Atlas style lock',path:path.join(root,atlas),sha256:sha(read(atlas))},{role:'Side-on painter anatomy guide only',path:path.join(out,'anatomy-guide.png'),source:guide,sha256:sha(read(guide))}],requestedSize:[1536,1536],format:'PNG',background:'#FF00FF (P1 technical block); delivered alpha also accepted by D2',generationCount:1,guardianCpuGateMs:5,guardianTier:'desktop-only',landmarkBoundPx:60,handLandmarks:false,fitPerformed:false,rigPerformed:false,intakePerformed:false});
console.log('Brown Bear guardian prompt compiled; P1 style/system source retained, 1536 square requested.');
