import fs from'node:fs';import os from'node:os';import assert from'node:assert/strict';import{createHash}from'node:crypto';
const base='audits/C183_PAINTED_BIRD_FAINT_20261002',json=p=>JSON.parse(fs.readFileSync(p)),sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex'),write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const before=json(base+'/baseline-01.json'),after=json(base+'/corrected-01.json'),typecheck=json(base+'/typecheck-01.json');assert.equal(before.exitCode,1);assert.equal(after.exitCode,0);assert.equal(typecheck.exitCode,0);
const test='port/v2/apps/game/src/motion/painted-bird-author.test.ts',reference='CREATURE_ANIMATION.md',runtime=before.sources.filter(s=>s.path!==test).map(s=>{assert.equal(sha(s.path),s.sha256);assert.equal(after.sources.find(r=>r.path===s.path).sha256,s.sha256);return{...s,unchangedAcrossCorrection:true};});
assert.equal(sha(test),after.sources.find(s=>s.path===test).sha256);assert.equal(sha(test),typecheck.testSource.sha256);
assert.equal(sha(base+'/painted-bird-author.before.ts.txt'),before.sources.find(s=>s.path===test).sha256);
const inputs=json('audits/BIRD_SUPPORT_C75_20260927/inputs.json').cases.flatMap(([name,dir])=>['record.json','binding.json'].map(file=>({name,path:dir+'/'+file,sha256:sha(dir+'/'+file)})));
const files=[];for(const name of fs.readdirSync(base).sort()){const p=base+'/'+name;assert(fs.statSync(p).isFile());const bytes=fs.readFileSync(p);assert(!bytes.includes(Buffer.from(os.homedir())),'private home path');files.push({path:p,bytes:bytes.length,sha256:sha(p)});}
const disk=fs.statfsSync('.'),freeGiB=Number((disk.bavail*disk.bsize/2**30).toFixed(2));
write(base+'/delivery.json',{schema:'cf.c183-painted-bird-faint-delivery/v1',status:'TARGETED_PASS_RUNTIME_UNCHANGED',sourceHead:before.sourceHead,baseline:{fail:5,pass:7,receipt:base+'/baseline-01.json'},corrected:{pass:23,fail:0,receipt:base+'/corrected-01.json'},typecheck:{status:'PASS',receipt:base+'/typecheck-01.json'},changedFiles:[{path:test,sha256:sha(test)},{path:reference,sha256:sha(reference)}],runtimeSourceProof:runtime,fixtureInputs:inputs,initialRedPreserved:true,initialTestPreserved:true,negativeControls:['restored final neck curl','erased initial head nod','changed wing track','widened joint limit','changed duration'],existingPaintOutcomeMutationTestsPreserved:true,numericLimitsChanged:false,runtimeBehaviorChanged:false,nativeRuns:0,fullDevelopRuns:0,visualAcceptanceClaimed:false,freeGiB,fileCount:files.length,bytes:files.reduce((s,r)=>s+r.bytes,0),files});
console.log(JSON.stringify({delivery:base+'/delivery.json',sha256:sha(base+'/delivery.json'),files:files.length,freeGiB,changedFiles:[test,reference],runtimeUnchanged:true}));
