import fs from'node:fs';import path from'node:path';import{createHash}from'node:crypto';import{createRequire}from'node:module';
const req=createRequire(process.cwd()+'/port/v2/package.json'),sharp=createRequire(req.resolve('free-tex-packer-core'))('sharp'),base=path.dirname(new URL(import.meta.url).pathname),results=JSON.parse(fs.readFileSync(base+'/results.json')),sha=b=>createHash('sha256').update(b).digest('hex'),escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;'),text=(x,y,s,size=25,color='#eef2f7')=>`<text x="${x}" y="${y}" font-family="Helvetica,Arial,sans-serif" font-size="${size}" fill="${color}">${escape(s)}</text>`,receipts=[],overview=[];
const canvas=(width,height,items,labels)=>sharp({create:{width,height,channels:4,background:'#15212d'}}).composite([...items,{input:Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">${labels.join('')}</svg>`)}]).png().toBuffer();
for(const [index,r]of results.filter(r=>!r.retained).entries()){
 const record=JSON.parse(fs.readFileSync(r.input+'/record.json')),hidden=record.anatomy?.hidden??[],items=[],sources=[],title=r.id.replaceAll('-',' '),refs=[{name:'Civet · accepted reference',path:'audits/ANATOMY_SINGLE_RUN_20260919/R3-S/civet-input-01/parts/keyed.png'},{name:title+' · accepted painting',path:record.source},{name:'Painter · family control',path:'audits/ANATOMY_COMPLETION_20260917/crab-masks-05/'+r.id+'-master.png'}];
 for(const[i,ref]of refs.entries()){const bytes=fs.readFileSync(ref.path),input=await sharp(bytes).resize(590,500,{fit:'contain',background:'#1c2b37'}).flatten({background:'#1c2b37'}).png().toBuffer();items.push({input,left:20+640*i,top:140});sources.push({...ref,sha256:sha(bytes)});}
 for(const[i,name]of['melee-pinch-50','faint-50'].entries()){const file=r.native+'/'+name+'.png',bytes=fs.readFileSync(file);items.push({input:await sharp(bytes).extract({left:740,top:90,width:620,height:540}).resize(900,570,{fit:'contain',background:'#1c2b37'}).png().toBuffer(),left:30+960*i,top:800});sources.push({path:file,sha256:sha(bytes)});}
 const labels=[text(30,48,'P1 canonical desktop · '+title,34),text(30,90,`${8-hidden.length} visible walking chains · hidden: ${hidden.join(', ')||'none'} · boundary 24 / interior 56`,24,'#b9cada'),...refs.map((ref,i)=>text(20+640*i,126,ref.name,24)),text(30,683,`Full-film rig p95 ${r.admission.valueMs.toFixed(2)} ms / 3.50 ms · ${r.admission.status} · exact rest ${r.restChanged}/${r.finalRestChanged}`,28,r.admission.status==='PASS'?'#a9e5b1':'#ffb787'),text(30,725,`Planted drift ${r.maxPlantedDriftPx.toFixed(6)} px · seam gap ${r.maxGapPx.toFixed(6)} px · root continuity ${r.rootContinuity.status}`,24),text(30,780,'Pinch · actual native pose at 50%',24),text(990,780,'Faint · actual native pose at 50%',24),text(30,1410,`Full-row film ${Number(r.filmDuration).toFixed(2)} s · ${r.frames} encoded frames · ${r.refusals.refusedFrames} refused frames`,24),text(30,1450,r.id==='mud-crab'?'T2: facial orbs retained as body paint; no additional eye joints.':'Art accepted by Nick. Sources remain immutable; display scaling is sheet-only.',23,'#b9cada')];
 const filename=r.id+'-sheet.png',png=await canvas(1920,1480,items,labels);if(fs.existsSync(base+'/'+filename)){if(sha(fs.readFileSync(base+'/'+filename))!==sha(png))throw Error('Existing sheet differs; retain before repair');}else fs.writeFileSync(base+'/'+filename,png,{flag:'wx'});receipts.push({id:r.id,sheet:filename,sheetSha256:sha(png),sources,filmSha256:sha(fs.readFileSync(r.native+'/family-full-rows.webm')),admission:r.admission,scope:'Native evidence; no new painting/intake; comparison images display-scaled only'});
 overview.push({input:await sharp(png).resize(960,740).png().toBuffer(),left:(index%2)*960,top:100+Math.floor(index/2)*740});
}
const all=await canvas(1920,1580,overview,[text(30,52,'Four accepted paintings · canonical desktop native delivery',35),text(30,87,'IC-3 frozen after delivery. No new intake, painting, P2 or roster until IC-4 passes.',24,'#b9cada')]);fs.writeFileSync(base+'/four-crabs-overview.png',all,{flag:'wx'});fs.writeFileSync(base+'/sheet-receipts.json',JSON.stringify({sheets:receipts,overviewSha256:sha(all)},null,2)+'\n');
