import fs from'node:fs';import assert from'node:assert/strict';import{createHash}from'node:crypto';import{createRequire,registerHooks}from'node:module';
import{resolve}from'../../port/v2/tools/effects-proof/resolve-ts-hook.mjs';registerHooks({resolve});
import{traceSourcePixels}from'../C169_NAPE_RECUT_20261002/source-trace.mjs';
const{compileBodyCard,buildTimeline,createGsapPlayer}=await import('../../port/v2/apps/game/src/motion/index.ts'),{withPaintedContactSupports}=await import('../../port/v2/apps/game/src/motion/painted-supports.ts'),{createPaintPublication}=await import('../C132_FAINT_GROUND_20261002/paint-publication.mjs');
const req=createRequire(new URL('../../port/v2/package.json',import.meta.url)),{PNG}=req('pngjs'),base='audits/C196_SPECIALIZED_REFERENCES_20261003',old='audits/C192_SPECIALIZED_REFERENCES_20261002',read=p=>fs.readFileSync(p),json=p=>JSON.parse(read(p)),sha=b=>createHash('sha256').update(b).digest('hex'),pin=p=>({path:p,sha256:sha(read(p))});
function components(w,h,on){const labels=new Int32Array(w*h).fill(-1),rows=[];for(let i=0;i<labels.length;i++){if(labels[i]>=0||!on(i))continue;const id=rows.length,stack=[i];labels[i]=id;let n=0,sx=0,sy=0,x0=w,y0=h,x1=0,y1=0,first=i;while(stack.length){const j=stack.pop(),x=j%w,y=Math.floor(j/w);n++;sx+=x;sy+=y;x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const X=x+dx,Y=y+dy,k=Y*w+X;if((dx||dy)&&X>=0&&Y>=0&&X<w&&Y<h&&labels[k]<0&&on(k)){labels[k]=id;stack.push(k);}}}rows.push({id,pixels:n,bounds:[x0,y0,x1,y1],centroid:[sx/n,sy/n],first:[first%w,Math.floor(first/w)]});}return{labels,rows};}
const outputs=[];
for(const q of [{id:'prawn',packet:'08-prawn-opaque',fit:'d28/fit',action:'cast',image:'motion-d28-cast-50-left.png'},{id:'shrimp',packet:'09-shrimp-opaque',fit:'d28/fit',action:'approach:swim',image:'motion-d28-approach-swim-50-left.png'},{id:'mussel',packet:'11-mussel-dorsal',fit:'fit01',action:'cast',image:'motion-cast-50-left.png'}]){
 const dir=old+'/'+q.packet,fit=dir+'/'+q.fit,record=json(fit+'/record.json'),binding=json(fit+'/binding.json'),card=withPaintedContactSupports(compileBodyCard(record,record.genome),record,binding),publication=createPaintPublication(record,binding,card.realm),atlasPath=fit+'/parts/atlas/'+fs.readdirSync(fit+'/parts/atlas').find(n=>n.endsWith('.png')),atlas=PNG.sync.read(read(atlasPath)),keyed=PNG.sync.read(read(fit+'/parts/keyed.png')),image=PNG.sync.read(read(dir+'/'+q.image)),{width:w,height:h}=keyed,tl=buildTimeline(card,q.action,record.identity.seed);let pose={};const player=createGsapPlayer(tl,{setJoint(j,rotation,dx,dy){pose[j]={rotation,dx,dy};}},{now:()=>0});
 const inputs=[fit+'/record.json',fit+'/binding.json',atlasPath,fit+'/parts/keyed.png',dir+'/'+q.image,dir+'/master.png',dir+'/authoring.json'].map(pin);
 player.seek(tl.durationMs*.5);const frame=publication.publish(pose,{actionId:tl.actionId,elapsedMs:tl.durationMs*.5,durationMs:tl.durationMs,weight:1}),trace=traceSourcePixels(record,binding,atlas,frame.positions);player.stop();
 const source=components(w,h,i=>keyed.data[i*4+3]>0),ground=Math.round(record.geometry.groundLineY*h),paint=components(w,h,i=>Math.floor(i/w)!==ground&&(image.data[i*4]!==235||image.data[i*4+1]!==235||image.data[i*4+2]!==232));
 const fragments=paint.rows.filter(c=>c.pixels<=120).map(c=>{const target=c.first.map(v=>v+.5);let nearest=null,distance=Infinity;for(const p of trace){const d=Math.hypot(p.published[0]*w-target[0],p.published[1]*h-target[1]);if(d<distance){distance=d;nearest=p;}}assert(nearest);const component=source.rows[source.labels[nearest.source[1]*w+nearest.source[0]]];return{...c,closest:{part:nearest.part,joint:nearest.joint,source:nearest.source,publishedSourcePixels:nearest.published.map((v,i)=>v*(i?h:w)),distance},sourceComponent:component,classification:distance<=2?(component.pixels<=120?'already disconnected in established keyed source':'continuous source paint separates during posed publication'):'nearest positive-alpha attribution exceeds 2px; unresolved'};});
 const row={id:q.id,sourcePacket:dir,fit,action:q.action,fraction:.5,coordinateSpace:'1254-square source-coordinate software raster, not native screen',inputs,keyedComponents:source.rows.length,posedComponents:paint.rows.length,fragments,largePaintComponents:paint.rows.filter(c=>c.pixels>120),qualityAccepted:false,nativeRuns:0};outputs.push(row);for(const p of inputs)assert.equal(sha(read(p.path)),p.sha256);console.log(JSON.stringify({id:q.id,fragments:fragments.map(f=>({bounds:f.bounds,pixels:f.pixels,part:f.closest.part,source:f.closest.source,keyedComponent:f.sourceComponent.pixels,classification:f.classification})),large:row.largePaintComponents.map(c=>({pixels:c.pixels,bounds:c.bounds}))}));
}
fs.writeFileSync(base+'/attribution.json',JSON.stringify({schema:'cf.c196-positive-alpha-fragment-attribution/v1',writer:pin(base+'/attribute.mjs'),traceHelper:pin('audits/C169_NAPE_RECUT_20261002/source-trace.mjs'),rows:outputs},null,2)+'\n',{flag:'wx'});
