import fs from'node:fs';import assert from'node:assert/strict';import{createHash}from'node:crypto';
const base='audits/C196_SPECIALIZED_REFERENCES_20261003',src='audits/C196_CREATURE_SUPPLY_20261003/24-leech',dir=base+'/05-leech-reference',read=p=>fs.readFileSync(p),sha=b=>createHash('sha256').update(b).digest('hex'),write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n',{flag:'wx'});
assert.equal(sha(read(src+'/master.png')),'5890c3418b39794dab2437345f73ca059f7271060a0afe91f0145870c0507061');
// Independently observed centreline, anterior small sucker right to posterior broad sucker left.
// These twelve controls follow the visible continuous body; they are not copied from Earthworm.
const points=[[1036,726],[966,689],[891,665],[824,636],[750,593],[677,556],[602,540],[529,552],[455,581],[389,622],[326,674],[257,725]],landmarksPx={root:[621,554],...Object.fromEntries(points.map((p,i)=>['segment'+i,p]))};
function clip(poly,mid,n,positive){const side=p=>(p[0]-mid[0])*n[0]+(p[1]-mid[1])*n[1],out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],sa=side(a)*(positive?1:-1),sb=side(b)*(positive?1:-1);if(sa>=0)out.push(a);if((sa>=0)!==(sb>=0)){const t=sa/(sa-sb);out.push([a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])]);}}return out;}
const parts=points.map((p,i)=>{let poly=[[0,0],[1254,0],[1254,1254],[0,1254]];for(const j of [i-1,i+1])if(points[j]){const q=points[j],mid=[(p[0]+q[0])/2,(p[1]+q[1])/2],n=[p[0]-q[0],p[1]-q[1]];poly=clip(poly,mid,n,true);}assert(poly.length>=3);return{id:'segment'+i,joint:'segment'+i,layer:'near',polygonPx:poly};});
const limitations=['Independent second-species annelid source (Leech), not Earthworm reused against itself. C195 accepted Earthworm direct fit remains immutable.','Twelve observed centreline controls cover the continuous annulated body, small anterior right sucker and broad posterior left sucker. These are coarse motion controls, not twelve claimed biological segments. No eyes, feet, suckers or source pixels are invented.','The larger posterior disc remains broad and the body glossy; identity/paint style and moving-ground contact require full-size/native review. GroundLineY is the lowest painted posterior rim, not proof of a native stance.','No tiny artificial root paint patch is cut out of the body. The root landmark remains in the structural record; existing segment paint covers the body continuously.','New source anatomy and labels were independently observed; no global reference-pool promotion or auto-author result is implied.'];
fs.mkdirSync(dir);for(const n of ['master.png','subject-source.json'])fs.copyFileSync(src+'/'+n,dir+'/'+n,fs.constants.COPYFILE_EXCL);write(dir+'/presence.json',{schema:'cf.anatomy-presence/v2',absent:[],hidden:[],folded:[]});write(dir+'/authoring.json',{id:'c196-observed-leech',family:'annelid',landmarksPx,groundLineY:786/1254,materials:{surface:'slick'},remainderPart:'segment6',parts,coverage:{scope:'Independently observed Leech annelid reference',limitations,sourceLandmarksReused:false,sourceLabelsReused:false,qualityAccepted:false,nativeAcceptance:false}});write(dir+'/source-correction.json',{schema:'cf.c196-observed-leech/v1',source:src,sourceMasterSha256:sha(read(src+'/master.png')),sourceSubjectSha256:sha(read(src+'/subject-source.json')),sourcePromptSha256:sha(read(src+'/prompt.txt')),sourceGenerationSha256:sha(read(src+'/generation.json')),authoringSha256:sha(read(dir+'/authoring.json')),observedLandmarks:landmarksPx,qualityAccepted:false,nativeRuns:0});
