import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{createRequire}from'node:module';import{createHash}from'node:crypto';
import{placeRemainderIslands,MAX_SHARE}from'../G1_AUTO_AUTHOR_20260926/remainder-islands-fit.mjs';
const base='audits/C196_SPECIALIZED_REFERENCES_20261003',old='audits/C192_SPECIALIZED_REFERENCES_20261002',read=p=>fs.readFileSync(p),json=p=>JSON.parse(read(p)),sha=b=>createHash('sha256').update(b).digest('hex'),pin=p=>({path:p,sha256:sha(read(p))}),req=createRequire(path.resolve('port/v2/package.json')),sharp=createRequire(req.resolve('free-tex-packer-core'))('sharp');
async function decode(fit){const d=json(fit+'/declaration.json'),{data,info}=await sharp(fit+'/parts/ownership.png').ensureAlpha().raw().toBuffer({resolveWithObject:true}),map=new Map(d.parts.map((p,i)=>{const k=i+1;return[[(k*83)%200+35,(k*137)%200+35,(k*47)%200+35].join(','),k];})),labels=new Uint8Array(info.width*info.height);for(let i=0;i<labels.length;i++)if(data[i*4+3]){const k=map.get([...data.subarray(i*4,i*4+3)].join(','));assert(k);labels[i]=k;}return{d,labels,w:info.width,h:info.height,joint:i=>labels[i]?d.parts[labels[i]-1].joint:null};}
const rows=[];
for(const q of [{id:'01-prawn-contours',prior:'08-prawn-opaque',points:[{p:[516,456],joint:'leg4FarFoot'},{p:[1082,499],joint:'antennaFarTip'}]},{id:'02-shrimp-contours',prior:'09-shrimp-opaque',points:[]},{id:'04-shrimp-distal-only',prior:'09-shrimp-opaque',points:[{p:[427,473],joint:'leg4FarFoot'},{p:[510,444],joint:'leg3FarFoot'},{p:[594,827],joint:'leg2NearFoot'}]}]){
 const dir=base+'/'+q.id,prior=old+'/'+q.prior,a=await decode(prior+'/d28/fit'),b=await decode(dir+'/fit01'),oldRecord=json(prior+'/d28/fit/record.json'),record=json(dir+'/fit01/record.json'),before=await sharp(prior+'/d28/fit/parts/keyed.png').ensureAlpha().raw().toBuffer(),after=await sharp(dir+'/fit01/parts/keyed.png').ensureAlpha().raw().toBuffer();
 assert.deepEqual(read(prior+'/master.png'),read(dir+'/master.png'));assert.deepEqual(before,after);assert.deepEqual(oldRecord.landmarks,record.landmarks);assert.deepEqual(oldRecord.materials,record.materials);assert.deepEqual(oldRecord.genome,record.genome);assert.deepEqual(oldRecord.anatomy,record.anatomy);assert.equal(oldRecord.geometry.groundLineY,record.geometry.groundLineY);
 const transfers={};let changed=0;for(let i=0;i<a.labels.length;i++){const from=a.joint(i),to=b.joint(i);assert.equal(Boolean(from),Boolean(to));if(from!==to){changed++;const k=from+' -> '+to;transfers[k]=(transfers[k]??0)+1;}}
 const attributed=q.points.map(({p,joint})=>{const i=p[1]*a.w+p[0],from=a.joint(i),to=b.joint(i);assert.equal(to,joint);assert.notEqual(from,to);return{source:p,oldJoint:from,newJoint:to};});
 const painted=b.labels.findIndex(Boolean),bad=Buffer.from(after);bad[painted*4]^=1;assert.throws(()=>assert.deepEqual(bad,before));const removed=Buffer.from(after);removed[painted*4+3]=0;assert.throws(()=>assert.deepEqual(removed,before));const stolen=Uint8Array.from(b.labels);stolen[painted]=stolen[painted]===1?2:1;assert.throws(()=>assert.deepEqual(stolen,b.labels));
 rows.push({id:q.id,source:pin(dir+'/master.png'),priorAuthor:pin(prior+'/authoring.json'),author:pin(dir+'/authoring.json'),landmarksMaterialsGenomePresenceGroundUnchanged:true,keyedRgbaChanges:0,changedOwnedPixels:changed,transfers,attributed,controls:{changedRgbaRejected:true,deletedPaintRejected:true,stolenOwnerRejected:true},qualityAccepted:false});
}
assert.equal(MAX_SHARE,.5);const src=old+'/11-mussel-dorsal/fit01',dst=base+'/03-mussel-islands/d28/fit',a=await decode(src),b=await decode(dst),remainder=a.d.parts.findIndex(p=>p.id===a.d.remainderPart)+1,original=Uint8Array.from(a.labels),placed=placeRemainderIslands(a.labels,a.w,a.h,remainder);assert.deepEqual(a.labels,original);assert.deepEqual(placed.labels,b.labels);let otherChanges=0;for(let i=0;i<a.labels.length;i++)if(a.labels[i]!==b.labels[i]&&a.labels[i]!==remainder)otherChanges++;assert.equal(otherChanges,0);assert.equal(placed.moved,153);assert.deepEqual(read(src+'/record.json'),read(dst+'/record.json'));assert.deepEqual(await sharp(src+'/parts/keyed.png').ensureAlpha().raw().toBuffer(),await sharp(dst+'/parts/keyed.png').ensureAlpha().raw().toBuffer());
const control=Uint8Array.from([1,1,1,1,0,2,2,1,1,0]);assert.equal(placeRemainderIslands(control,10,1,1).moved,2);assert.throws(()=>placeRemainderIslands(control,10,1,1,.05),/structural/);
const hand='audits/C186_SPECIALIZED_REFERENCES_20261002/01-earthworm-direct',handRecord=json(hand+'/fit01/record.json'),priorFinal=json(old+'/final-controls.json').earthworm;for(const p of priorFinal.files)assert.equal(sha(read(p.path)),p.sha256,'Earthworm accepted source/diagnostic input unchanged');assert.equal(handRecord.kind,'annelid');assert.equal(handRecord.recipeHash,priorFinal.directRecipe);
const output={schema:'cf.c196-source-and-ownership-controls/v1',writer:pin(base+'/controls.mjs'),rows,mussel:{defaultCap:MAX_SHARE,movedPixels:placed.moved,remainderPixels:placed.remainderPixels,replayMismatch:0,sourceRgbaChanges:0,otherPriorOwnerChanges:otherChanges,largestAndInputProtected:true,explicitStricterCapRefuses:true},earthworm:{directRecipe:handRecord.recipeHash,source:pin(hand+'/master.png'),acceptedDirectSourceUnchanged:true,priorEvidenceUnchanged:true},qualityAccepted:false,nativeRuns:0};fs.writeFileSync(base+'/controls.json',JSON.stringify(output,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({ownershipRows:rows.map(r=>({id:r.id,changed:r.changedOwnedPixels,attributed:r.attributed})),mussel:output.mussel,earthworm:'unchanged',status:'PASS'}));
