import fs from'node:fs';import os from'node:os';import assert from'node:assert/strict';import{createHash}from'node:crypto';
const base='audits/C196_SPECIALIZED_REFERENCES_20261003',prior='audits/C192_SPECIALIZED_REFERENCES_20261002',read=p=>fs.readFileSync(p),json=p=>JSON.parse(read(p)),sha=b=>createHash('sha256').update(b).digest('hex'),pin=p=>({path:p,sha256:sha(read(p)),bytes:read(p).length}),write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const choices=[
 {id:'01-prawn-contours',fit:'fit01',status:'IMPROVED_DIAGNOSTIC_CANDIDATE',notes:'Traced free limb/antenna flecks removed; pink swimmeret fringe and fine source ends remain visual concerns. Parent full-size comparison concurs.',images:['master.png','motion-cast-50-left.png','motion-cast-50-right.png','motion-faint-50-right.png']},
 {id:'04-shrimp-distal-only',fit:'fit01',status:'HELD_VISUAL',notes:'Distal fragments removed; restored exact original proximal/body polygons. Existing underside rear leg-root separation remains clear. Parent concurs.',images:['master.png','motion-approach-swim-50-left.png','motion-approach-swim-50-right.png','motion-cast-50-right.png']},
 {id:'03-mussel-islands',fit:'d28/fit',status:'HELD_VISUAL',notes:'153px D28 placement removes small siphon fleck, broad shell/mantle/foot openings unchanged. Parent concurs. Not a qualified real-bivalve film.',images:['master.png','motion-d28-cast-50-left.png','motion-d28-cast-50-right.png']},
 {id:'05-leech-reference',fit:'fit01',status:'MANUAL_REFERENCE_CANDIDATE',notes:'Continuous visible body and two suckers in reviewed cast/faint. Glossy finish, broad posterior sucker and lifted raw cast retain style/native grounding qualifications. Parent concurs.',images:['master.png','joint-preview-01.png','motion-cast-50-left.png','motion-cast-50-right.png','motion-faint-100-right.png']}
];let actions=0,samples=0,poses=0,stills=0;
const selected=choices.map(q=>{const dir=base+'/'+q.id,d28=q.fit==='d28/fit',stat=json(dir+'/'+(d28?'static-d28.json':'static-01.json')),pub=json(dir+'/'+(d28?'publication-d28.json':'publication-review.json')),record=json(dir+'/'+q.fit+'/record.json');assert.equal(stat.status,'PASS_STATIC');assert(stat.rows.every(r=>r.status==='PASS'));assert(pub.rows.every(r=>r.status==='PASS'));actions+=stat.rows.length;samples+=stat.rows.reduce((n,r)=>n+r.samples,0);poses+=pub.rows.length;stills+=pub.rows.reduce((n,r)=>n+r.files.length,0);for(const r of pub.rows)for(const f of r.files)assert.equal(sha(read(f.path)),f.sha256);return{...q,fit:dir+'/'+q.fit,recipeHash:record.recipeHash,bindingHash:json(dir+'/'+q.fit+'/binding.json').bindingHash,masterSha256:record.geometry.cutoutAssetHash,fullSizeInspected:q.images.map(n=>pin(dir+'/'+n)),qualityAccepted:false,nativeRuns:0};});
assert.deepEqual([actions,samples,poses,stills],[43,5203,24,48]);
write(base+'/visual-review.json',{schema:'cf.c196-specialized-visual-review/v1',scope:'Only listed full-size software source-coordinate images inspected. No gallery/native/performance admission.',selected,rejected:[{id:'02-shrimp-contours',status:'REJECTED_VISUAL_REGRESSION',reason:'Widened proximal regions increased existing body notch despite static green.',inspected:pin(base+'/02-shrimp-contours/motion-approach-swim-50-left.png')}],unchangedSnail:{fit:prior+'/10-snail-contours/d28/fit',status:'C243_DIAGNOSTIC_CANDIDATE_AWAITING_CLAUDE_SCORING',newGeneration:0,newAuthoring:0},earthworm:{directFit:'audits/C186_SPECIALIZED_REFERENCES_20261002/01-earthworm-direct/fit01',status:'C195_ACCEPTED_DIRECT_FIT_UNCHANGED',transfer:pin(base+'/earthworm-transfer-result.json')},nativeRuns:0,qualityAccepted:false});
const previous=json(prior+'/delivery.json');for(const f of previous.files){assert.equal(read(f.path).length,f.bytes);assert.equal(sha(read(f.path)),f.sha256);}
write(base+'/prior-packet-recheck.json',{schema:'cf.c196-prior-packet-recheck/v1',priorDelivery:pin(prior+'/delivery.json'),verifiedFiles:previous.fileCount,verifiedBytes:previous.totalBytes,allUnchanged:true});
const walk=p=>fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>{const f=p+'/'+e.name;assert(!e.isSymbolicLink(),'no symlink '+f);assert(e.isFile()||e.isDirectory());return e.isDirectory()?walk(f):[f];});
const paths=walk(base).sort();let checkedText=0;for(const p of paths)if(/\.(?:mjs|json|txt|md|log)$/.test(p)){const s=read(p).toString();assert(!s.includes(os.homedir()),'expanded home path in '+p);assert(!/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i.test(s),'email in '+p);checkedText++;}
const files=paths.map(pin),totalBytes=files.reduce((n,f)=>n+f.bytes,0);write(base+'/delivery.json',{schema:'cf.c196-specialized-delivery/v1',workspace:'~/Projects/celestial-frontier-openai-mac',state:'FROZEN_DIAGNOSTIC_DELIVERY_WITH_VISUAL_HOLDS',selected:selected.map(({id,fit,status,recipeHash,bindingHash,masterSha256})=>({id,fit,status,recipeHash,bindingHash,masterSha256})),selectedChecks:{actions,samples,softwarePoses:poses,softwareImages:stills},includingRejected:{actions:54,samples:6534,softwarePoses:30,softwareImages:60},sourceGenerationByThisTask:0,newSourceProvidedBySupply:1,privacy:{checkedText,expandedHomePaths:0,emailRecords:0,symlinks:0},diskFreeGiB:{start:132,end:132},files,fileCount:files.length,totalBytes,inventoryExcludes:['delivery.json'],productChanges:0,poolChanges:0,nativeRuns:0,qualityAccepted:false});console.log(JSON.stringify({deliverySha256:sha(read(base+'/delivery.json')),files:files.length,bytes:totalBytes,selected:{actions,samples,poses,stills},cpu:'TERMINAL'}));
