import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {createHash} from 'node:crypto';
const base=import.meta.dirname,root=path.resolve(base,'../..'),sha=b=>createHash('sha256').update(b).digest('hex');
const pilot=JSON.parse(fs.readFileSync(base+'/pilot.json')),observations=JSON.parse(fs.readFileSync(base+'/observations.json'));
if(pilot.length!==4||new Set(pilot.map(r=>r.name)).size!==4)throw Error('Exact unique4');
for(const r of pilot){const d=root+'/'+r.packet,g=JSON.parse(fs.readFileSync(d+'/generation.json')),q=JSON.parse(fs.readFileSync(d+'/request.json')),bytes=fs.readFileSync(d+'/master.png'),source=g.sourcePath.startsWith('~/')?path.join(os.homedir(),g.sourcePath.slice(2)):path.resolve(root,g.sourcePath);if(sha(bytes)!==g.masterSha256||!bytes.equals(fs.readFileSync(source))||sha(fs.readFileSync(d+'/prompt.txt'))!==q.promptSha256||g.promptSha256!==q.promptSha256||q.referenceSha256!==sha(fs.readFileSync(root+'/'+q.reference)))throw Error('Immutable provenance '+r.name);const o=observations.find(o=>o.id===r.id);if(o?.masterSha256!==g.masterSha256||o.width!==1254||o.height!==1254)throw Error('Native dimensions '+r.name);}
const files=[];function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory())walk(f);else if(e.isFile()&&e.name!=='delivery.json'){const b=fs.readFileSync(f);if(/\.(json|mjs|md|txt)$/.test(e.name)&&(b.includes(Buffer.from(os.homedir()))||b.includes(Buffer.from('/'+'Users/'))))throw Error('Unsanitized record '+path.relative(root,f));files.push({path:path.relative(root,f),sha256:sha(b),bytes:b.length});}}}walk(base);files.sort((a,b)=>a.path.localeCompare(b.path));const d={schema:'cf.g2-source-delivery/v1',scope:'Four specialized originals; audit-only compiler extension, explicit source holds, no rig/native/gallery admission',originals:4,nativeDimensions:[1254,1254],framingPass:observations.filter(o=>o.framing.status==='PASS_FRAMING_ONLY').length,framingRefused:observations.filter(o=>o.framing.status==='REFUSE').map(o=>o.name),masterBytes:pilot.reduce((n,r)=>n+fs.statSync(root+'/'+r.master).size,0),files,bytes:files.reduce((n,f)=>n+f.bytes,0)};fs.writeFileSync(base+'/delivery.json',JSON.stringify(d,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({files:files.length,bytes:d.bytes,masterBytes:d.masterBytes,deliverySha256:sha(fs.readFileSync(base+'/delivery.json'))}));
