import fs from 'node:fs';
import {createHash} from 'node:crypto';
const base=import.meta.dirname,source='port/v2/tools/painted-creature/compile-library-master.mjs',original=fs.readFileSync(source,'utf8'),sha=s=>createHash('sha256').update(s).digest('hex');
const transforms=[];let s=original;const once=(before,after)=>{if(s.split(before).length!==2)throw Error('Unique transform required');transforms.push({before,after});s=s.replace(before,after);};
once("from 'rolldown'","from '../../port/v2/node_modules/rolldown/dist/index.mjs'");
once("from '../creature-animation/family-contracts.mjs'","from '../../port/v2/tools/creature-animation/family-contracts.mjs'");
once("from './pattern-observation.mjs'","from '../../port/v2/tools/painted-creature/pattern-observation.mjs'");
once("path.resolve(import.meta.dirname,'../../../..')","path.resolve(import.meta.dirname,'../..')");
once(" const candidates=profile?.candidateTemplates??[];"," const candidates=profile?.candidateTemplates??[];\n if(SIMPLE[species.name]){const family=SIMPLE[species.name].family;if(candidates.length!==1||candidates[0]!==family)throw Error('Simple source canonical family mismatch');return family;}");
once("export function controlledLibraryLayout(family,name){","export function controlledLibraryLayout(family,name){\n if(Object.values(SIMPLE).some(r=>r.family===family)){const row=SIMPLE[name];if(!row||row.family!==family)throw Error('Exact simple source species required');return {legs:0,accuracy:row.accuracy,layout:row.layout};}");
const common='One whole anatomically accurate adult in the approved painted hand on flat pure magenta. The entire natural specimen, every appendage and complete body edge fit in the middle HALF of a native 1254 by 1254 canvas with about 300 pixels of empty magenta on all sides. No scenery, floor, shadow, labels, artificial ground, arrows, detached body parts or props. Biological identity takes priority over generic procedural body vocabulary. ';
const simple={
 Earthworm:{family:'annelid',accuracy:'one continuous segmented annelid tube, actual clitellum, no legs, eyes, antennae or invented head parts',layout:common+'One earthworm in a low extended gentle curve from left posterior to right anterior, no coil, crossing or overlap. Entire body visible from actual rounded anterior end through natural tapered posterior. Preserve real moist ringed segments and swollen clitellum near the front. No mouth drawn as a vertebrate face, no eyes or limbs.'},
 Sponge:{family:'sessile-filter',accuracy:'one irregular porous sponge with attached basal tissue and a real osculum; no animal head, jaws, limbs or eyes',layout:common+'One natural irregular tubular vase-shaped sea sponge upright with its own basal attachment tissue visible and a clear real osculum at the top. Preserve uneven porous living walls and asymmetric outline. The osculum is a water outlet, not a mouth. No eyes, tentacles, limbs, extra tubes, rock, seabed or invented support prop.'},
 Snail:{family:'gastropod',accuracy:'one coiled shell, one continuous muscular foot and head, two eye-bearing long tentacles and two short feelers, real mouth',layout:common+'One ordinary terrestrial snail in right-facing shallow side view, shell on back and full flat muscular foot extended left to right. Show both actual upper eye-bearing tentacles independently with their eye tips, two real short lower feelers, and the small real mouth below the front of the head. Preserve complete foot edge and shell connection. No invented legs, human eyes, head stalk duplicates or snake body.'},
 Mussel:{family:'bivalve',accuracy:'two actual hinged valves, mantle edge, small muscular foot and byssal threads where visible; no invented eyes or paired siphon tubes',layout:common+'One dark blue-black mussel in a shallow side view, two wedge-shaped valves slightly naturally open so their genuine hinge and mantle rim are visible. The real small muscular foot protrudes modestly from the mantle margin and fine byssal beard threads remain visible near its base. Show both continuous valves with natural concentric growth lines. Do not turn the foot into a tongue or animal leg; no human mouth, eyes, tentacles, added paired siphons, rock or scenery.'}
};
s+='\n/** Audit-only four-source vocabulary. Not production compiler support or measured anatomy. */\nconst SIMPLE=Object.freeze('+JSON.stringify(simple)+');\n';
fs.writeFileSync(base+'/compiler.audit.mjs',s,{flag:'wx'});
fs.writeFileSync(base+'/transform-receipt.json',JSON.stringify({schema:'cf.audit-compiler-transform/v1',source,sourceSha256:sha(original),output:'audits/C196_SIMPLE_ORIGINALS_20261002/compiler.audit.mjs',outputSha256:sha(s),transforms,appended:s.slice(original.length+transforms.reduce((n,t)=>n+t.after.length-t.before.length,0)),scope:'Only local import resolution plus four exact named canonical family routes and painting layouts. All canonical identity, kit export, material/style paragraph, dimensions and provenance owners retained. Production file untouched.'},null,2)+'\n',{flag:'wx'});
