import {compileCreatureFinishV1} from '../../port/v2/apps/game/src/landfall-conditioning.js';
import {createAiCreatureOriginalStoreV1,creatureOriginalKey,type AiCreatureOriginalV1} from '../../port/v2/apps/game/src/creature-originals.js';
import {createCreatureFinishEngineV1,type CreatureFinishSourceV1} from '../../port/v2/apps/game/src/creature-finish-engine.js';
import {LocalModelSha256V1} from '../../port/v2/apps/game/src/local-model-sha256.js';
const sha=(b:Uint8Array)=>new LocalModelSha256V1().update(b).digestHex();
const state:any={status:'idle',rows:[],events:[],artifacts:{}};
let worker:Worker|undefined,store:ReturnType<typeof createAiCreatureOriginalStoreV1>|undefined;
async function bytes(url:string){const r=await fetch(url);if(!r.ok)throw Error('input fetch '+url);return new Uint8Array(await r.arrayBuffer());}
async function paint(recipe:any){return new Promise<any>((resolve,reject)=>{worker!.onmessage=({data})=>{if(data.type==='progress'){state.events.push({phase:data.phase,stage:data.stage,elapsedMs:data.elapsedMs});if(state.events.length>500)state.events.shift();}else if(data.type==='complete')resolve(data);else reject(Error(data.message));};worker!.onerror=e=>reject(Error(e.message));const transfer=[recipe.master.buffer,recipe.labels.buffer];worker!.postMessage({stage:'creature-finish-v1',requestId:state.rows.length,recipe},transfer);if(transfer.some(buffer=>buffer.byteLength!==0))reject(Error('ArrayBuffers not transferred'));state.detachedTransfers=(state.detachedTransfers??0)+transfer.length;});}
async function start(){state.status='running';store=createAiCreatureOriginalStoreV1();let engine:ReturnType<typeof createCreatureFinishEngineV1>|undefined,phone:ReturnType<typeof createCreatureFinishEngineV1>|undefined;const WorkerConstructor=globalThis.Worker;
 try{const inputs=await(await fetch('/inputs.json')).json(),recipes=new Map<string,any>(),sources:CreatureFinishSourceV1[]=[],originals=new Map<string,AiCreatureOriginalV1>();let inferences=0,creates=0;
  engine=createCreatureFinishEngineV1({tier:'desktop',store,createInfer:async()=>{creates++;worker=new Worker('/kit-stage-worker.mjs',{type:'module'});return async s=>{const recipe=recipes.get(s.individualId);if(!recipe||s.modelHash!==inputs.modelHash||s.settingsHash!==sha(new TextEncoder().encode(JSON.stringify({settings:recipe.settings,prompt:recipe.prompt,seed:recipe.seed}))))throw Error('adapter model/settings pin');inferences++;const ref=(bytes:Uint8Array)=>({width:s.width,height:s.height,sha256:sha(bytes),buffer:bytes.slice().buffer});
     const outbound={...recipe,seed:s.seed,master:ref(s.rgba),labels:ref(s.labels)};
     if(!state.corruptTransferRefused){const bad={...outbound,master:ref(s.rgba),labels:ref(s.labels)};new Uint8Array(bad.labels.buffer)[0]^=1;const before=state.events.length;try{await paint(bad);throw Error('Corrupt transferred labels accepted');}catch(e){if(!String(e).includes('hash mismatch'))throw e;state.corruptTransferRefused=true;state.corruptTransferModelEvents=state.events.length-before;if(state.corruptTransferModelEvents!==0)throw Error('Corrupt input started model');}}
     const result=await paint(outbound);if(result.width!==1254||result.height!==1254||result.workCanvas.width!==1264||result.workCanvas.height!==1264)throw Error('Work canvas dimensions');state.lastInference={elapsedMs:result.elapsedMs,editablePixels:result.editablePixels,sessionCreates:result.sessionCreates,width:result.width,height:result.height,workCanvas:result.workCanvas};return {rgba:new Uint8Array(result.rgba),labels:s.labels.slice(),binding:s.binding.slice()};};}});
  for(const input of inputs.subjects){state.subject=input.id;const row:any={id:input.id,status:'FAIL'};state.rows.push(row);
   const recipe=compileCreatureFinishV1(input);recipes.set(input.id,recipe);
   const masterPng=await bytes(input.masterPng.url),labels=await bytes(input.labels.url),binding=await bytes(input.binding.url);
   const source:CreatureFinishSourceV1={individualId:input.id,visualKey:input.visualKey,recordRecipeHash:input.recordRecipeHash,modelHash:inputs.modelHash,settingsHash:sha(new TextEncoder().encode(JSON.stringify({settings:recipe.settings,prompt:recipe.prompt,seed:recipe.seed}))),seed:recipe.seed,width:input.width,height:input.height,masterPng,labels,binding,cutoutAssetHash:input.cutoutAssetHash,labelsHash:input.labels.sha256,bindingHash:input.binding.sha256};sources.push(source);
   const count=inferences,pending=engine.request(source),duplicate=engine.request(source);if(pending!==duplicate)throw Error('native dedupe');const result=await pending;if(result.status!=='original')throw Error(result.reason);
   originals.set(result.original.key,result.original);state.artifacts[input.id]=result.original.blob;row.sha256=result.original.sha256;row.receipt=JSON.parse(result.original.receipt);row.details=state.lastInference;
   const cached=await engine.request(source);row.retention={firstOrigin:result.origin,secondOrigin:cached.status==='original'?cached.origin:'fallback',inferences:inferences-count,duplicatePromise:true};if(result.origin!=='inference'||cached.status!=='original'||cached.origin!=='cache'||inferences-count!==1)throw Error('native retention');row.status='PASS';
  }
  engine.close();worker?.terminate();worker=undefined;store.close();store=undefined;
  await new Promise<void>((resolve,reject)=>{const r=indexedDB.deleteDatabase('cf-ai-creature-originals-v1');r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('phone fresh-store blocked'));});
  store=createAiCreatureOriginalStoreV1();let phoneCreates=0;
  globalThis.Worker=function(){throw Error('phone Worker construction');} as unknown as typeof Worker;
  phone=createCreatureFinishEngineV1({tier:'phone',store,createInfer:async()=>{phoneCreates++;throw Error('phone inference');},delivered:async identity=>originals.get(creatureOriginalKey(identity))??null});
  for(const source of sources){const result=await phone.request(source),row=state.rows.find((r:any)=>r.id===source.individualId);row.phone={status:result.status,origin:result.status==='original'?result.origin:result.reason,exactBytes:result.status==='original'&&result.original.sha256===row.sha256};if(result.status!=='original'||result.origin!=='delivery'||!row.phone.exactBytes)throw Error('phone delivery');}
  state.phoneMissing=await phone.request({...sources[0]!,individualId:'not-delivered'});if(state.phoneMissing.status!=='fallback'||phoneCreates!==0)throw Error('phone zero-model gate');
  state.modelCreates=creates;state.modelInferences=inferences;state.phoneCreates=phoneCreates;state.status='complete';
 }catch(e){state.status='failed';state.error=String(e);}finally{globalThis.Worker=WorkerConstructor;engine?.close();phone?.close();worker?.terminate();store?.close();}}
(window as any).creatureProof={start,snapshot:()=>({status:state.status,subject:state.subject,rows:state.rows.map((r:any)=>({id:r.id,status:r.status})),last:state.events.at(-1)}),report:()=>({status:state.status,rows:state.rows,events:state.events,error:state.error,modelCreates:state.modelCreates,modelInferences:state.modelInferences,phoneCreates:state.phoneCreates,phoneMissing:state.phoneMissing,corruptTransferRefused:state.corruptTransferRefused,corruptTransferModelEvents:state.corruptTransferModelEvents,detachedTransfers:state.detachedTransfers}),artifact:async(id:string)=>{const bytes=new Uint8Array(await state.artifacts[id].arrayBuffer());let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);}};
