import fs from'node:fs';import{spawnSync,execFileSync}from'node:child_process';
const base='audits/STAGE_CADENCE_REACH_20260922',old='audits/ANATOMY_COMPLETION_20260917',subjects=[...['crab','coconut-crab','freshwater-crab','mud-crab','vent-crab'].map(id=>({id,input:old+'/crab-fits-03/'+id,action:'melee:pinch'})),{id:'persimmon',input:old+'/persimmon-04',action:'sway'},{id:'cranberry',input:old+'/cranberry-07',action:'sway'},{id:'devils-club',input:old+'/devils-club-06',action:'sway'},{id:'civet',input:'audits/ANATOMY_SINGLE_RUN_20260919/R3-S/civet-input-01',action:'melee:bite'}];
const summary={producer:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),status:'RUNNING',subjects:[],unrun:[]};if(fs.existsSync(base+'/native-summary.json'))throw Error('One run only');
for(const s of subjects){const out=base+'/native/'+s.id,fd=fs.openSync(base+'/'+s.id+'-native.log','wx');let run;try{run=spawnSync(process.execPath,['port/v2/tools/animation-completion/cadence-runner.mjs',s.input,'port/v2/apps/game/src',out,s.action],{stdio:['ignore',fd,fd],timeout:240000});}finally{fs.closeSync(fd);}
 const report=fs.existsSync(out+'/report.json')?JSON.parse(fs.readFileSync(out+'/report.json')):null;summary.subjects.push({id:s.id,input:s.input,report:out+'/report.json',status:report?.status??'INSTRUMENT_RED',sharedPathRed:report?.sharedPathRed??false,error:report?.error??run.error?.message,cadence:report?.cadence?{...report.cadence,windows:undefined}:null,cpu:report?.cpu});console.log(JSON.stringify(summary.subjects.at(-1)));
 if(report?.sharedPathRed){summary.status='S2_STOP';summary.unrun=subjects.slice(subjects.indexOf(s)+1).map(x=>x.id);fs.writeFileSync(base+'/native-summary.json',JSON.stringify(summary,null,2)+'\n');process.exitCode=1;break;}
 fs.writeFileSync(base+'/native-summary.json',JSON.stringify(summary,null,2)+'\n');
}
if(summary.status==='RUNNING'){summary.status='NATIVE_COMPLETE';fs.writeFileSync(base+'/native-summary.json',JSON.stringify(summary,null,2)+'\n');}
