/** Only the retained hit/dodge first-contact failures; no paint solve or film. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createHash}from'node:crypto';
import{compileBodyCard,buildTimeline,createGsapPlayer}from'/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/apps/game/src/motion/index.ts';
import{createCreatureRigPerformance}from'/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/apps/game/src/creature-rig-performance.ts';
import{createFamilyContactSolver,observedContactSupports}from'/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/apps/game/src/creature-rig-contact.ts';
import{familyContractForRecord}from'/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/creature-animation/family-contracts.mjs';
import{createContactTravel}from'/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/apps/game/src/creature-contact-travel.ts';
import{sampleKeys}from'/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/apps/game/src/motion/timeline.ts';
import{createSkeletonPoseProgram}from'/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/creature-animation/skeleton-pose.mjs';
import{transformPoint}from'/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/creature-animation/kinematics.ts';
const base='/Users/nick/Projects/celestial-frontier-openai-mac/audits/ARCHETYPE_FINISH_20260923/12-myriapod',sha=b=>createHash('sha256').update(b).digest('hex'),inputs=new Map(),read=name=>{const p=path.join(base,name),b=fs.readFileSync(p);inputs.set(p,sha(b));return JSON.parse(b.toString());};
const previous=read('static-04.json'),record=read('fit-07/record.json'),binding=read('fit-07/binding.json');assert.equal(record.recipeHash,previous.recordRecipeHash);assert.equal(binding.bindingHash,previous.bindingHash);
for(const[p,hash]of inputs){const retained=previous.inputs.find(x=>x.path===p);if(retained)assert.equal(hash,retained.sha256);}
const scan=read('static-paint-diagnosis04/report.json');assert.equal(scan.recordRecipeHash,record.recipeHash);assert.equal(scan.bindingHash,binding.bindingHash);
const card=compileBodyCard(record,record.genome),template=familyContractForRecord(record),supports=observedContactSupports(record,binding),contact=createFamilyContactSolver(record,supports),results=[];
const id='dodge',row=scan.targetScan.rows.find(r=>r.action===id),tl=buildTimeline(card,id,record.identity.seed),travel=createContactTravel(tl.root.dx,card.bodyLength),program=createSkeletonPoseProgram(template,record.landmarks),limiting=contact.chains.find(c=>c.id==='leg0Far')!;
// Select the largest support-distance excess among the ten ALREADY retained
// error poses by geometric arithmetic only. No additional contact resolve.
const extentSelection=row.errors.map(prior=>{const at=travel.sample(prior.ms),cycle=at.progress,swing=limiting.group===1?cycle<.5:cycle>=.5,local=swing?(limiting.group===1?cycle*2:(cycle-.5)*2):0,smooth=v=>v*v*(3-2*v),step=limiting.group===1?(cycle<.5?smooth(cycle*2):1):(cycle<.5?0:smooth((cycle-.5)*2)),lift=Math.sin(Math.PI*local)**2,pose=structuredClone(prior.rawPose);pose.root.dx=(at.base+at.stride*at.progress)/card.bodyLength+pose.root.dx-sampleKeys(tl.root.dx,prior.ms);const root=transformPoint(program.evaluate(pose)[limiting.hip]!,limiting.root),target={x:limiting.endPoint.x+at.base+at.stride*step-(swing?Math.sign(limiting.endPoint.x-limiting.root.x)*limiting.chain.lengths.lower*.10*lift:0)+limiting.offset.x,y:limiting.endPoint.y+Math.sign(limiting.root.y-limiting.endPoint.y)*(swing?lift*limiting.chain.lengths.lower*.15:0)+limiting.offset.y},maximum=limiting.chain.lengths.upper+Math.hypot(limiting.support.x-limiting.joint.x,limiting.support.y-limiting.joint.y),distance=Math.hypot(target.x-root.x,target.y-root.y);return{ms:prior.ms,sampleIndex:prior.sampleIndex,root,target,distancePx:distance*record.geometry.width,maxPx:maximum*record.geometry.width,outerExcessPx:(distance-maximum)*record.geometry.width};});
const largest=extentSelection.reduce((a,b)=>b.outerExcessPx>a.outerExcessPx?b:a),selected=[row.errors[0],row.errors.find(p=>p.ms===largest.ms)];assert.notEqual(selected[0].ms,selected[1].ms);
for(const prior of selected){
 const ms=prior.ms;assert.equal(ms,tl.durationMs*prior.sampleIndex/120);
 let raw:any={},attemptedPose:any,phase:any,trace:any[]=[],publicationCalls=0,error='',causes:string[]=[],stacks:any[]=[];
 const player=createGsapPlayer(tl,{setJoint(j,rotation,dx,dy){raw[j]={rotation,dx,dy};}},{now:()=>0});
 const rig:any={recipeHash:record.recipeHash,templateId:record.template.id,applyPose(){publicationCalls++;throw Error('Unexpected successful contact; no publication permitted');}},owner=createCreatureRigPerformance(record,rig,[{id,durationMs:tl.durationMs,loop:tl.loop,dispose(){},seek(at,target){raw={};player.seek(at);for(const[j,k]of Object.entries(raw)as any)target.setJoint(j,k.rotation,k.dx,k.dy);}}]);
 (globalThis as any).__compactContactTrace=(event,data)=>trace.push({event,...structuredClone(data)});
 try{owner.play(id,0,0);owner.update(ms,(pose,p)=>{attemptedPose=structuredClone(pose);phase={...p,actionId:tl.actionId,realm:card.realm};return contact.resolve(pose,phase).pose;});}
 catch(e){error=String(e);for(let c:any=e;c;c=c.cause){stacks.push({message:String(c),stack:c.stack??null});if(c!==e)causes.push(String(c));}}
 finally{delete(globalThis as any).__compactContactTrace;player.stop();}
 assert.equal(error,prior.error.split('\n')[0],'Exact retained refusal '+id);assert.equal(publicationCalls,0);assert.deepEqual(attemptedPose,prior.rawPose,'Exact attempted pose from retained scan');
 const targetTrace=trace.find(t=>t.event==='targets'),failedChain='leg0Far',chainTrace=trace.filter(t=>(t.event==='endpoint-reach'||t.event==='rigid-reach')&&t.id===failedChain);
 const summarized=chainTrace.map(t=>({event:t.event,pass:t.pass??null,rootPx:{x:t.root.x*record.geometry.width,y:t.root.y*record.geometry.height},targetPx:{x:t.target.x*record.geometry.width,y:t.target.y*record.geometry.height},deltaPx:{x:t.dx*record.geometry.width,y:(t.target.y-t.root.y)*record.geometry.height},distancePx:t.distance*record.geometry.width,minPx:t.min*record.geometry.width,maxPx:t.max*record.geometry.width,outerExcessPx:(t.distance-t.max)*record.geometry.width,aboveHip:t.target.y<t.root.y,horizontalRefusal:Math.abs(t.dx)>=t.max}));
 results.push({id,ms,phase,retainedErrorExact:true,error,causes,stacks,attemptedPose,rawPoseExactRetained:true,rootKeys:tl.root,bodyMs:tl.bodyMs,durationMs:tl.durationMs,sourceTravel:targetTrace.sourceTravel,rootBeforeContact:attemptedPose.root,rootAfterSourceTravel:targetTrace.pose.root,failedChain,chainReach:summarized,trace,publicationCalls});
 console.log(JSON.stringify({id,ms,error,causes,sourceTravel:targetTrace.sourceTravel,rootBeforeContact:attemptedPose.root,rootAfterSourceTravel:targetTrace.pose.root,failedChain,chainReach:summarized}));
}
const report={schema:'cf.compact-myriapod-first-contact-refusal/v1',status:'EXACT_TWO_REFUSALS_REPRODUCED',scope:'First and largest already-retained fit07 dodge contact refusals; extent selection is ten-source-pose arithmetic only, real GSAP/performance/contact, exact invertible observational inserts. No ARAP, published paint, full static, browser, film, CPU certificate, altered policy or optimized coordinates.',staticPoseCaveat:'Actual attemptedPose captured before contact.resolve is byte-structure equal to the retained targetScan rawPose; first failure is not the earlier static ARAP stop.',recordRecipeHash:record.recipeHash,bindingHash:binding.bindingHash,bodyLength:card.bodyLength,scaleLength:contact.scaleLength,compressionBoundPx:contact.scaleLength*.08*record.geometry.height,template,extentSelection,largestExtentMs:largest.ms,chains:contact.chains.map(c=>({id:c.id,group:c.group,hip:c.hip,knee:c.knee,end:c.end,root:c.root,joint:c.joint,endPoint:c.endPoint,support:c.support,model:c.model,offset:c.offset,endpointOnly:c.endpointOnly,lengths:c.chain.lengths,restDistance:Math.hypot(c.endPoint.x-c.root.x,c.endPoint.y-c.root.y),minimum:Math.abs(c.chain.lengths.upper-c.chain.lengths.lower),maximum:c.chain.lengths.upper+c.chain.lengths.lower})),results,inputs:[...inputs].map(([file,sha256])=>({file,sha256,unchanged:sha(fs.readFileSync(file))===sha256}))};assert(report.inputs.every(i=>i.unchanged));
fs.writeFileSync(path.join(base,'static-contact-diagnosis03.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});
