/** Only the retained hit/dodge first-contact failures; no paint solve or film. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createHash}from'node:crypto';
import{compileBodyCard,buildTimeline,createGsapPlayer}from'/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/apps/game/src/motion/index.ts';
import{createCreatureRigPerformance}from'/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/apps/game/src/creature-rig-performance.ts';
import{createFamilyContactSolver,observedContactSupports}from'/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/apps/game/src/creature-rig-contact.ts';
import{familyContractForRecord}from'/Users/nick/Projects/celestial-frontier-openai-mac/port/v2/tools/creature-animation/family-contracts.mjs';
const base='/Users/nick/Projects/celestial-frontier-openai-mac/audits/ARCHETYPE_FINISH_20260923/12-myriapod',sha=b=>createHash('sha256').update(b).digest('hex'),inputs=new Map(),read=name=>{const p=path.join(base,name),b=fs.readFileSync(p);inputs.set(p,sha(b));return JSON.parse(b.toString());};
const previous=read('static-03.json'),record=read('fit-06/record.json'),binding=read('fit-06/binding.json');assert.equal(record.recipeHash,previous.recordRecipeHash);assert.equal(binding.bindingHash,previous.bindingHash);
for(const[p,hash]of inputs){const retained=previous.inputs.find(x=>x.path===p);if(retained)assert.equal(hash,retained.sha256);}
const scan=read('static-paint-diagnosis03/report.json');assert.equal(scan.recordRecipeHash,record.recipeHash);assert.equal(scan.bindingHash,binding.bindingHash);
const card=compileBodyCard(record,record.genome),template=familyContractForRecord(record),supports=observedContactSupports(record,binding),contact=createFamilyContactSolver(record,supports),results=[];
for(const id of ['hit','dodge']){
 const row=scan.targetScan.rows.find(r=>r.action===id),prior=row.errors[0],ms=prior.ms,tl=buildTimeline(card,id,record.identity.seed);assert.equal(ms,tl.durationMs*prior.sampleIndex/120);
 let raw:any={},attemptedPose:any,phase:any,trace:any[]=[],publicationCalls=0,error='',causes:string[]=[];
 const player=createGsapPlayer(tl,{setJoint(j,rotation,dx,dy){raw[j]={rotation,dx,dy};}},{now:()=>0});
 const rig:any={recipeHash:record.recipeHash,templateId:record.template.id,applyPose(){publicationCalls++;throw Error('Unexpected successful contact; no publication permitted');}},owner=createCreatureRigPerformance(record,rig,[{id,durationMs:tl.durationMs,loop:tl.loop,dispose(){},seek(at,target){raw={};player.seek(at);for(const[j,k]of Object.entries(raw)as any)target.setJoint(j,k.rotation,k.dx,k.dy);}}]);
 (globalThis as any).__compactContactTrace=(event,data)=>trace.push({event,...structuredClone(data)});
 try{owner.play(id,0,0);owner.update(ms,(pose,p)=>{attemptedPose=structuredClone(pose);phase={...p,actionId:tl.actionId,realm:card.realm};return contact.resolve(pose,phase).pose;});}
 catch(e){error=String(e);for(let c=(e as any).cause;c;c=c.cause)causes.push(String(c));}
 finally{delete(globalThis as any).__compactContactTrace;player.stop();}
 assert.equal(error,prior.error.split('\n')[0],'Exact retained refusal '+id);assert.equal(publicationCalls,0);assert.deepEqual(attemptedPose,prior.rawPose,'Exact attempted pose from retained scan');
 const targetTrace=trace.find(t=>t.event==='targets'),failedChain=id==='hit'?'leg13Far':'leg0Far',chainTrace=trace.filter(t=>(t.event==='endpoint-reach'||t.event==='rigid-reach')&&t.id===failedChain);
 const summarized=chainTrace.map(t=>({event:t.event,pass:t.pass??null,rootPx:{x:t.root.x*record.geometry.width,y:t.root.y*record.geometry.height},targetPx:{x:t.target.x*record.geometry.width,y:t.target.y*record.geometry.height},deltaPx:{x:t.dx*record.geometry.width,y:(t.target.y-t.root.y)*record.geometry.height},distancePx:t.distance*record.geometry.width,minPx:t.min*record.geometry.width,maxPx:t.max*record.geometry.width,outerExcessPx:(t.distance-t.max)*record.geometry.width,aboveHip:t.target.y<t.root.y,horizontalRefusal:Math.abs(t.dx)>=t.max}));
 results.push({id,ms,phase,retainedErrorExact:true,error,causes,attemptedPose,rawPoseExactRetained:true,rootKeys:tl.root,bodyMs:tl.bodyMs,durationMs:tl.durationMs,sourceTravel:targetTrace.sourceTravel,rootBeforeContact:attemptedPose.root,rootAfterSourceTravel:targetTrace.pose.root,failedChain,chainReach:summarized,trace,publicationCalls});
 console.log(JSON.stringify({id,ms,error,causes,sourceTravel:targetTrace.sourceTravel,rootBeforeContact:attemptedPose.root,rootAfterSourceTravel:targetTrace.pose.root,failedChain,chainReach:summarized}));
}
const report={schema:'cf.compact-myriapod-first-contact-refusal/v1',status:'EXACT_TWO_REFUSALS_REPRODUCED',scope:'Only first newly exposed hit/dodge contact refusals from retained fit06 target scan, real GSAP/performance/contact, exact invertible observational inserts. No ARAP, published paint, full static, browser, film, CPU certificate, altered policy or optimized coordinates.',staticPoseCaveat:'Actual attemptedPose captured before contact.resolve is byte-structure equal to the retained targetScan rawPose; first failure is not the earlier static ARAP stop.',recordRecipeHash:record.recipeHash,bindingHash:binding.bindingHash,bodyLength:card.bodyLength,scaleLength:contact.scaleLength,compressionBoundPx:contact.scaleLength*.08*record.geometry.height,template,chains:contact.chains.map(c=>({id:c.id,group:c.group,hip:c.hip,knee:c.knee,end:c.end,root:c.root,joint:c.joint,endPoint:c.endPoint,support:c.support,model:c.model,offset:c.offset,endpointOnly:c.endpointOnly,lengths:c.chain.lengths,restDistance:Math.hypot(c.endPoint.x-c.root.x,c.endPoint.y-c.root.y),minimum:Math.abs(c.chain.lengths.upper-c.chain.lengths.lower),maximum:c.chain.lengths.upper+c.chain.lengths.lower})),results,inputs:[...inputs].map(([file,sha256])=>({file,sha256,unchanged:sha(fs.readFileSync(file))===sha256}))};assert(report.inputs.every(i=>i.unchanged));
fs.writeFileSync(path.join(base,'static-contact-diagnosis02.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});
