import fs from 'node:fs';
import {createHash} from 'node:crypto';
const base='audits/C196_FRAMING_SUCCESSORS_20261002',prior='audits/C196_QUADRUPED_ORIGINALS_20261002',sha=b=>createHash('sha256').update(b).digest('hex'),rows=JSON.parse(fs.readFileSync(prior+'/pilot.json')),obs=JSON.parse(fs.readFileSync(prior+'/observations.json'));
const referencePrompt=fs.readFileSync('audits/C173_HOLD_SOURCE_REPAINTS_20261002/mako-shark-framing-v2/prompt.txt','utf8'),paragraph=referencePrompt.split('APPROVED ART_KIT PARAGRAPH (unchanged):\n')[1].trimEnd();if(!paragraph||!fs.readFileSync('ART_KIT.md','utf8').includes(paragraph))throw Error('Exact ART_KIT paragraph');
const pilot=[];for(const row of rows.filter(r=>obs.find(o=>o.id===r.id)?.framing.status==='REFUSE')){
 const id=row.id+'-framing-v2',packet=base+'/'+id;fs.mkdirSync(packet,{recursive:false});const originalRequest=JSON.parse(fs.readFileSync(row.packet+'/request.json')),inputSha256=sha(fs.readFileSync(row.master));
 const prompt='EDIT TARGET: the attached '+row.name+' painting. Make a fresh 1254 x 1254 PNG version with a much SMALLER whole specimen centered on pure #FF00FF magenta. Preserve the species, exact natural anatomy, painted detail, complete unshortened tail and every leg, toe and other appendage. Change only composition scale and surrounding empty space. The animal must now occupy only HALF of the canvas width. Make the empty margin on each left and right side about 300 pixels. Do not simply regenerate the same close framing. Do not crop, shorten, remove or invent anatomy. No text, guides, border, scenery or cast shadow. Every pixel outside the animal is flat pure magenta. Preserve the native 1254-square output size. This is only a framing correction; do not silently change the pose or claim to fix existing anatomy/contact holds.\n\nAPPROVED ART_KIT PARAGRAPH (unchanged):\n'+paragraph+'\n';
 fs.writeFileSync(packet+'/prompt.txt',prompt,{flag:'wx'});fs.copyFileSync(row.packet+'/subject-source.json',packet+'/subject-source.json',fs.constants.COPYFILE_EXCL);
 fs.writeFileSync(packet+'/request.json',JSON.stringify({schema:'cf.g2-framing-edit/v1',id,name:row.name,family:row.family,tool:'image_gen.imagegen',intent:'edit',promptSha256:sha(prompt),requestedSize:[1254,1254],reference:row.master,referenceSha256:inputSha256,actualInputRole:'sole edit target; original master',originalRequest:row.packet+'/request.json',originalRequestSha256:sha(fs.readFileSync(row.packet+'/request.json')),originalStyleReferenceSha256:originalRequest.referenceSha256,kitSha256:sha(fs.readFileSync('ART_KIT.md')),priorFraming:obs.find(o=>o.id===row.id).framing,scope:'One authorized framing-only edit; unchanged prior originals. All existing anatomy and contact holds remain pending independent review.'},null,2)+'\n',{flag:'wx'});pilot.push({id,name:row.name,family:row.family,packet,master:packet+'/master.png',purpose:'FRAMING_ONLY_SUCCESSOR',originalMaster:row.master});
}if(pilot.length!==6)throw Error('Exact six measured framing refusals');fs.writeFileSync(base+'/pilot.json',JSON.stringify(pilot,null,2)+'\n',{flag:'wx'});
