import test from'node:test';import assert from'node:assert/strict';import{buildPaintSkin}from'./build-paint-skin.mjs';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createRequire} from 'node:module';import {createHash} from 'node:crypto';import {hashJSON,hashBytes} from './quadruped-template.mjs';
const require=createRequire(import.meta.url),sharp=createRequire(require.resolve('free-tex-packer-core'))('sharp');
test('mesh profile refuses nonpositive, fractional and excessive steps before reading sources',async()=>{for(const key of['boundaryStep','interiorStep'])for(const value of[0,-1,.5,2049,Infinity,NaN])await assert.rejects(()=>buildPaintSkin('/not-read',null,null,{[key]:value}),new RegExp('Paint skin: invalid '+key));});
async function paintedFixture(){
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'cf-mesh-refinement-'));fs.mkdirSync(path.join(directory,'parts'));fs.mkdirSync(path.join(directory,'atlas'));
 const width=64,height=64,raw=Buffer.alloc(width*height*4);
 for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=(y*width+x)*4;raw[i]=31+x;raw[i+1]=52+y;raw[i+2]=78;raw[i+3]=(x>=32&&y>=32)||(x===8&&y===8)?0:255;}
 const atlas=await sharp(raw,{raw:{width,height,channels:4}}).png().toBuffer();fs.writeFileSync(path.join(directory,'atlas/fixture.png'),atlas);
 const parts=[],manifest=[];for(const [id,joint,x] of [['body','root',0],['leg','foreNearRoot',32]]){const cutout={x,y:0,width:32,height:64},png=await sharp(raw,{raw:{width,height,channels:4}}).extract({left:x,top:0,width:32,height:64}).png().toBuffer();fs.writeFileSync(path.join(directory,'parts',id+'.png'),png);manifest.push({name:id+'.png',path:'parts/'+id+'.png',sha256:await hashBytes(png)});parts.push({id,joint,kind:'part',layer:'near',frame:{...cutout},cutout});}
 const record={template:{id:'quadruped'},geometry:{width,height},recipeHash:'a'.repeat(64)},body={schema:'cf.creature-parts/v1',recordRecipeHash:record.recipeHash,atlasSha256:await hashBytes(atlas),atlasSize:{width,height},parts};
 fs.writeFileSync(path.join(directory,'binding.json'),JSON.stringify({...body,bindingHash:await hashJSON(body)}));fs.writeFileSync(path.join(directory,'manifest.json'),JSON.stringify({creatureId:'fixture',parts:manifest}));
 return{directory,record,seams:{seamBridges:{groups:[]}},dispose(){fs.rmSync(directory,{recursive:true,force:true});}};
}
let oldWriter;
async function retainedWriter(){
 if(oldWriter)return oldWriter;
 const file=new URL('../../../../audits/ARCHETYPE_REPAIRS_20260922/03-biped-bird/mesh-writer-before/build-paint-skin.mjs',import.meta.url),bytes=fs.readFileSync(file);
 assert.equal(createHash('sha256').update(bytes).digest('hex'),'190133cbe97d99ea1bf61a644d19f6e64a3dad7fe07485a86ce4b53ad04c56b6');
 // Preserve the old algorithm verbatim; only resolve its relative imports from
 // its original package location while loading the immutable retained bytes.
 let source=bytes.toString();for(const name of ['verify-parts.mjs','quadruped-template.mjs','family-contracts.mjs','paint-skin.mjs']){const from="from './"+name+"'";assert.equal(source.split(from).length,2);source=source.replace(from,"from '"+new URL('./'+name,import.meta.url).href+"'");}
 const from='createRequire(import.meta.url)';assert.equal(source.split(from).length,2);source=source.replace(from,'createRequire('+JSON.stringify(new URL('./build-paint-skin.mjs',import.meta.url).href)+')');
 oldWriter=(await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'))).buildPaintSkin;return oldWriter;
}
test('absent and empty refinements are byte-identical to the retained writer including receipt and hashes',async()=>{const f=await paintedFixture();try{const old=await retainedWriter();for(const options of [{},{boundaryStep:16,interiorStep:32,includeTopology:true}]){const before=await old(f.directory,f.seams,f.record,options);for(const current of [options,{...options,refinements:[]}]){const result=await buildPaintSkin(f.directory,f.seams,f.record,current);assert.equal(JSON.stringify(result),JSON.stringify(before));assert.equal(Object.hasOwn(result.receipt,'refinements'),false);}}}finally{f.dispose();}});
const geometricTriangles=(skin,predicate)=>{const out=[];for(let i=0;i<skin.triangles.length;i+=3){const points=skin.triangles.slice(i,i+3).map(k=>skin.vertices[k]);if(points.every(predicate))out.push(JSON.stringify(points));}return out.sort();};
test('local rectangles refine intersecting ink while preserving distant geometry, source ownership and packed bytes',async()=>{const f=await paintedFixture();try{const options={boundaryStep:16,interiorStep:32,includeTopology:true},rect={x:0,y:0,width:16,height:16,boundaryStep:4,interiorStep:8},before=await buildPaintSkin(f.directory,f.seams,f.record,options),after=await buildPaintSkin(f.directory,f.seams,f.record,{...options,refinements:[rect]});assert.ok(after.receipt.vertices>before.receipt.vertices);assert.ok(after.receipt.leaves>before.receipt.leaves);const distant=v=>v.y>=32&&v.x<=32;const unchanged=geometricTriangles(before.binding.paintSkin,distant);assert.ok(unchanged.length>0);assert.deepEqual(geometricTriangles(after.binding.paintSkin,distant),unchanged);assert.deepEqual(after.ownershipEdges,before.ownershipEdges);assert.deepEqual(after.receipt.packedPixels,before.receipt.packedPixels);assert.deepEqual(after.binding.parts,before.binding.parts);assert.deepEqual(after.receipt.refinements,[rect]);const saved=structuredClone(rect);rect.boundaryStep=1;assert.deepEqual(after.receipt.refinements,[saved],'Receipt must snapshot the authored rectangle');const coarse={...saved,boundaryStep:8,interiorStep:16};const overlap=await buildPaintSkin(f.directory,f.seams,f.record,{...options,refinements:[coarse,saved]}),reversed=await buildPaintSkin(f.directory,f.seams,f.record,{...options,refinements:[saved,coarse]});assert.equal(JSON.stringify(overlap.binding),JSON.stringify(after.binding));assert.equal(JSON.stringify(reversed.binding),JSON.stringify(after.binding));}finally{f.dispose();}});
test('refinement confined to an empty quadtree region retains binding bytes and records only the authored receipt',async()=>{const f=await paintedFixture();try{const options={boundaryStep:16,interiorStep:32,includeTopology:true},rect={x:48,y:48,width:8,height:8,boundaryStep:1,interiorStep:1},before=await buildPaintSkin(f.directory,f.seams,f.record,options),after=await buildPaintSkin(f.directory,f.seams,f.record,{...options,refinements:[rect]});assert.equal(JSON.stringify(after.binding),JSON.stringify(before.binding));assert.deepEqual(after.receipt.refinements,[rect]);const {refinements,...receipt}=after.receipt;assert.equal(JSON.stringify(receipt),JSON.stringify(before.receipt));}finally{f.dispose();}});
test('malformed, out-of-image and coarsening refinement rectangles refuse before source reads',async()=>{const record={geometry:{width:64,height:64}},rect={x:0,y:0,width:16,height:16,boundaryStep:4,interiorStep:8};for(const refinements of [null,{},'rectangle'])await assert.rejects(()=>buildPaintSkin('/not-read',null,record,{refinements}),/Paint skin: invalid refinements/);for(const value of [null,[],{...rect,extra:true},{...rect,x:-1},{...rect,y:.5},{...rect,width:0},{...rect,height:-1},{...rect,x:64},{...rect,y:64},{...rect,width:65},{...rect,height:65},{...rect,boundaryStep:0},{...rect,boundaryStep:9},{...rect,interiorStep:33},{...rect,interiorStep:2049},{...rect,interiorStep:Infinity},{...rect,boundaryStep:NaN}])await assert.rejects(()=>buildPaintSkin('/not-read',null,record,{refinements:[value]}),/Paint skin: invalid refinement/);});
