/** Rebuildable evidence index. Contract tests never promote a species to fitted. */
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import {pathToFileURL} from 'node:url';import {rolldown} from 'rolldown';
const root=path.resolve(import.meta.dirname,'../../../..'),out=path.resolve(process.argv[2]);if(fs.existsSync(out))throw Error('New evidence file required');
const sha=b=>createHash('sha256').update(b).digest('hex'),sources=new Map(),temp=fs.mkdtempSync(path.join(os.tmpdir(),'cf-coverage-ledger-'));
try{
 const bundle=await rolldown({input:path.join(root,'port/v2/apps/game/src/missing-body-structures.ts'),platform:'node',plugins:[{name:'sources',transform(_,id){if(path.isAbsolute(id)&&fs.existsSync(id)&&fs.statSync(id).isFile())sources.set(path.relative(root,id),sha(fs.readFileSync(id)));}}]});try{await bundle.write({file:path.join(temp,'entry.mjs'),format:'es'});}finally{await bundle.close();}
 const {missingBodyStructures}=await import(pathToFileURL(path.join(temp,'entry.mjs')));
 const records=execFileSync('rg',['--files','audits','-g','*record.json','-g','*landmarks.json'],{cwd:root,encoding:'utf8'}).trim().split('\n').flatMap(file=>{try{const r=JSON.parse(fs.readFileSync(path.join(root,file)));if(!r.geometry?.cutoutAssetHash||!r.template?.id||!r.identity)return [];return [{file,sha256:sha(fs.readFileSync(path.join(root,file))),r}];}catch{return [];}});
 const bindings=execFileSync('rg',['--files','audits','-g','*binding.json'],{cwd:root,encoding:'utf8'}).trim().split('\n').flatMap(file=>{try{const bytes=fs.readFileSync(path.join(root,file)),v=JSON.parse(bytes);return v.recordRecipeHash?[{file,sha256:sha(bytes),recordRecipeHash:v.recordRecipeHash,hasPaintSkin:Boolean(v.paintSkin)}]:[];}catch{return [];}});
 const masters=fs.readdirSync(path.join(root,'audits/ART_KIT_ENGINE_FIRST_20260912/masters')).filter(n=>n.endsWith('.png')&&n!=='earth-temperate.png').sort().map(name=>{
  const file='audits/ART_KIT_ENGINE_FIRST_20260912/masters/'+name,hash=sha(fs.readFileSync(path.join(root,file))),fits=records.filter(v=>v.r.geometry.cutoutAssetHash===hash).map(v=>({record:v.file,sha256:v.sha256,template:v.r.template.id,coverage:v.r.coverage??null,bindings:bindings.filter(b=>b.recordRecipeHash===v.r.recipeHash),bindingExists:bindings.some(b=>b.recordRecipeHash===v.r.recipeHash&&b.hasPaintSkin)}));
  return {master:file,sha256:hash,fits,status:fits.some(f=>f.bindingExists)?'fit-artifact-exists-review-required':'no-matching-complete-binding-found',scope:'Input hash match only; archived or unqualified fits remain listed, never silently selected.'};
 });
 const censusPath=process.argv[3]?path.resolve(process.argv[3]):null;
 const census=censusPath?JSON.parse(fs.readFileSync(censusPath)):null;
 if(census){
  if(census.schema!=='cf.native-painter-census/v1'||census.status!=='DIAGNOSTIC_PASS'||!Array.isArray(census.sources)||!census.sources.length)throw Error('Native census must be complete and source bound');
  for(const source of census.sources){const file=path.resolve(root,source.path);if(!file.startsWith(root+path.sep)||sha(fs.readFileSync(file))!==source.sha256)throw Error('Stale census source: '+source.path);}
 }
 const observations=new Map((census?.rows??[]).filter(r=>r.kind==='earth'&&r.observation&&r.status==='RASTER_PASS').map(r=>[r.id,r]));
 const rows=missingBodyStructures().map(r=>({...r,structureStatus:'candidate-contract',observationStatus:observations.has('fauna:'+r.name)?'partial-source-features':'needs-source-observation',observationEvidence:observations.has('fauna:'+r.name)?{path:path.relative(root,censusPath),owner:observations.get('fauna:'+r.name).observation.owner,geometryAdmission:observations.get('fauna:'+r.name).geometryAdmission?.status??'not-compiled'}:null,fitArtifacts:records.filter(v=>v.r.identity.earthName===r.name).map(v=>({record:v.file,sha256:v.sha256,template:v.r.template.id,bindings:bindings.filter(b=>b.recordRecipeHash===v.r.recipeHash)})).filter(v=>v.bindings.some(b=>b.hasPaintSkin)),paintedFitStatus:'not-qualified',acceptance:null,openRequirements:[r.anatomyRequirements,'Qualify observed topology/counts against candidate; do not invent or truncate parts','Bind actual painted master, part masks, exact-rest and complete-action evidence','Native capture, habitat/contact and visual acceptance']}));
 const report={schema:'cf.painted-coverage-ledger/v1',sourceHead:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),scope:'Working candidate evidence; no species promotion from contract fixtures.',counts:{missingSpecies:rows.length,newlyQualifiedMissingSpecies:0,missingSpeciesWithBindingArtifacts:rows.filter(r=>r.fitArtifacts.length).length,observedMissingSpecies:rows.filter(r=>r.observationStatus==='partial-source-features').length,acceptedCutoutMasters:masters.length,mastersWithMatchingBinding:masters.filter(m=>m.fits.some(f=>f.bindingExists)).length},missingSpecies:rows,masters,evidenceInputs:censusPath?[{path:path.relative(root,censusPath),sha256:sha(fs.readFileSync(censusPath))}]:[],sources:[...sources].map(([file,sha256])=>({file,sha256}))};
 for(const[file,hash]of sources)if(sha(fs.readFileSync(path.join(root,file)))!==hash)throw Error('Source changed');
 fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.counts));
}finally{fs.rmSync(temp,{recursive:true,force:true});}
