import test from 'node:test';
import assert from 'node:assert/strict';
import {createArapScratch,solveArapSkin} from './arap-skin.mjs';
import * as before from '../../../../audits/ARCHETYPE_REPAIRS_20260922/03-biped-bird/solver-before/arap-skin.mjs';
const native=globalThis.WebAssembly,bytes=a=>Buffer.from(a.buffer,a.byteOffset,a.byteLength);
function fan(){const vertices=[{x:80,y:80}],triangles=[];for(let i=0;i<11;i++){const angle=i*2*Math.PI/11;vertices.push({x:80+60*Math.cos(angle),y:80+60*Math.sin(angle)});triangles.push(0,i+1,(i+1)%11+1);}return{vertices,triangles,width:160,height:160,options:{pins:[1,4]}};}
function create(owner,f,runtime=native){try{globalThis.WebAssembly=runtime;return owner.createArapScratch(f.vertices,f.triangles,f.width,f.height,f.options);}finally{globalThis.WebAssembly=native;}}
function outcome(owner,s,target,output){try{return{stats:{...owner.solveArapSkin(s,target,output)}};}catch(error){return{error:{name:error.name,message:error.message,code:error.code??null}};}}
function comparePose(old,fresh,target,Type=Float32Array){const saved=target.slice(),a=new Type(target.length).fill(-77),b=a.slice(),oldResult=outcome(before,old,target,a),newResult=outcome({solveArapSkin},fresh,target,b);assert.deepEqual(newResult,oldResult);assert.ok(bytes(a).equals(bytes(b)),'Published output bytes differ');assert.ok(bytes(target).equals(bytes(saved)),'Target bytes changed');assert.ok(bytes(fresh.position).equals(bytes(old.position)),'Solver position bytes differ');for(const key of ['size','projections','visits','stalled'])assert.equal(fresh.orientationQueue[key],old.orientationQueue[key],key);if(newResult.error)assert.ok(b.every(v=>v===-77),'Refused publication changed caller output');else for(let i=0;i<fresh.pins.length;i++)if(fresh.pins[i]){assert.equal(b[i*2],new Type([target[i*2]])[0]);assert.equal(b[i*2+1],new Type([target[i*2+1]])[0]);}return newResult;}
function target(f,phase){return Float64Array.from(f.vertices.flatMap((p,i)=>[(p.x+5*Math.sin(phase+i))/f.width,(p.y+7*Math.cos(phase-i))/f.height]));}
test('integrated admitted forward kernel preserves targets, pins, all output bytes and diagnostics',()=>{const f=fan(),old=create(before,f),fresh=create({createArapScratch},f);assert.ok(fresh.orientationKernel);for(const phase of[.4,-.2,.1])for(const Type of[Float32Array,Float64Array])assert.ok(comparePose(old,fresh,target(f,phase),Type).stats);});
test('unavailable Wasm retains the original JS path without changing admitted outcomes',()=>{const f=fan(),old=create(before,f),fresh=create({createArapScratch},f,null);assert.equal(fresh.orientationKernel,null);assert.equal(fresh.sweepBackend,'js');for(const phase of[.4,-.2,.1])assert.ok(comparePose(old,fresh,target(f,phase)).stats);});
test('a real leaf trap after private-memory work falls back from untouched input and disables the leaf',()=>{let calls=0,traps=0;const runtime={Module:native.Module,Memory:native.Memory,Instance:class{constructor(module,imports){const instance=new native.Instance(module,imports);this.exports={...instance.exports};if(instance.exports.forward)this.exports.forward=(...args)=>{calls++;const result=instance.exports.forward(...args);if(calls>2){traps++;throw new native.RuntimeError('deliberate post-leaf trap');}return result;};}}};const f=fan(),old=create(before,f),fresh=create({createArapScratch},f,runtime);assert.ok(fresh.orientationKernel,'Two admission probes must succeed');assert.equal(calls,2);assert.ok(comparePose(old,fresh,target(f,.4)).stats);assert.equal(traps,1);assert.equal(fresh.orientationKernel,null);assert.ok(comparePose(old,fresh,target(f,-.2)).stats);assert.equal(traps,1,'Disabled leaf must not be retried');});
test('floor underflow retains original source admission and the JS solver',()=>{const f={vertices:[{x:0,y:0},{x:.0001,y:0},{x:0,y:.0001}],triangles:[0,1,2],width:1,height:1,options:{minimumAreaRatio:Number.MIN_VALUE,pins:[0]}},old=create(before,f),fresh=create({createArapScratch},f);assert.equal(old.triangleFloors[0],0);assert.equal(fresh.triangleFloors[0],0);assert.equal(fresh.orientationKernel,null);comparePose(old,fresh,Float64Array.of(0,0,.0001,0,.00002,-.00009));});
test('floor overflow retains original source admission and identical refusal without publication',()=>{const f={vertices:[{x:0,y:0},{x:1e200,y:0},{x:0,y:1e200}],triangles:[0,1,2],width:1e200,height:1e200,options:{}},old=create(before,f),fresh=create({createArapScratch},f);assert.equal(old.triangleFloors[0],Infinity);assert.equal(fresh.triangleFloors[0],Infinity);assert.equal(fresh.orientationKernel,null);const result=comparePose(old,fresh,Float64Array.of(0,0,1,0,0,1));assert.ok(result.error);});
test('contradictory hard pins retain exact recoverable refusal and atomic output on admitted and fallback paths',()=>{const f={vertices:[{x:0,y:0},{x:10,y:0},{x:0,y:10}],triangles:[0,1,2],width:10,height:10,options:{pins:[0,1,2]}},t=Float64Array.of(0,0,0,1,1,0);for(const runtime of[native,null]){const old=create(before,f),fresh=create({createArapScratch},f,runtime),result=comparePose(old,fresh,t);assert.equal(result.error.code,'ARAP_FOLD');assert.equal(fresh.orientationQueue.stalled,true);assert.deepEqual(fresh.position,Float64Array.of(0,0,0,10,10,0));}});
