import test from'node:test';import assert from'node:assert/strict';import {splitSkinBranches}from'./split-skin-branches.mjs';import{createArapScratch,solveArapSkin}from'./arap-skin.mjs';import{hashJSON}from'./quadruped-template.mjs';
async function seal(binding,record){const {recipeHash,...body}=record;record.recipeHash=await hashJSON(body);binding.recordRecipeHash=record.recipeHash;const {bindingHash,...source}=binding;binding.bindingHash=await hashJSON(source);return{binding,record};}
async function fixture(){const vs=[{x:3,y:7,weights:[['foreFarPaw',1]]},{x:6,y:7,weights:[['foreNearPaw',1]]},{x:6,y:8,weights:[['foreNearPaw',1]]}],vertices=vs.map((_,i)=>({triangle:[0,1,2],barycentric:[+(i===0),+(i===1),+(i===2)]})),parts=[{id:'far',joint:'foreFarPaw',kind:'part'},{id:'near',joint:'foreNearPaw',kind:'part'}],binding={schema:'cf.creature-parts/v1',recordRecipeHash:'recipe',bindingHash:'old',atlasSha256:'atlas',parts,paintSkin:{schema:'cf.paint-skin/v1',vertices:vs,triangles:[0,1,2],parts:parts.map(p=>({id:p.id,vertices:structuredClone(vertices),indices:[0,1,2]}))}},record={recipeHash:'recipe',template:{id:'quadruped',version:1},geometry:{width:10,height:10},landmarks:{foreFarRoot:[.3,.2],foreFarKnee:[.3,.4],foreNearRoot:[.6,.2],foreNearKnee:[.6,.4]}};return seal(binding,record);}
test('branch reindex preserves every source interpolation but opposing paws have separate vertices/solver topology',async()=>{const {binding,record}=await fixture(),saved=structuredClone(binding),result=await splitSkinBranches(binding,record,{diffusionIterations:0}),skin=result.binding.paintSkin;assert.equal(result.receipt.sourceInterpolationDifferentCoordinates,0);assert.equal(skin.vertices.length,6);assert.equal(skin.parts.length,2);assert.deepEqual(binding,saved);const far=skin.parts[0].vertices[0].triangle,near=skin.parts[1].vertices[0].triangle;assert.ok(far.every(i=>!near.includes(i)));assert.ok(far.every(i=>skin.vertices[i].weights[0][0]==='foreFarPaw'));assert.ok(near.every(i=>skin.vertices[i].weights[0][0]==='foreNearPaw'));const target=Float64Array.from(skin.vertices.flatMap((v,i)=>[v.x/10+(far.includes(i)?.4:-.4),v.y/10])),scratch=createArapScratch(skin.vertices,skin.triangles,10,10,skin.solver),output=target.slice();assert.equal(solveArapSkin(scratch,target,output).flippedTriangles,0);assert.deepEqual(output,target);const oldTarget=new Float64Array([.7,.7,.2,.7,.2,.8]),old=createArapScratch(binding.paintSkin.vertices,[0,1,2],10,10,{pins:[0,1,2]});assert.throws(()=>solveArapSkin(old,oldTarget,oldTarget.slice()),/unresolved folded triangles/);});
test('proximal root socket stays shared and malformed source references fail closed',async()=>{const {binding,record}=await fixture();binding.paintSkin.vertices[0].y=1;binding.paintSkin.vertices[0].weights=[['chest',1]];binding.parts.forEach(p=>p.joint=p.joint.replace('Paw','Knee'));await seal(binding,record);const result=await splitSkinBranches(binding,record,{diffusionIterations:2}),parts=result.binding.paintSkin.parts;assert.equal(parts[0].vertices[0].triangle[0],parts[1].vertices[0].triangle[0]);const broken=structuredClone(binding);broken.paintSkin.parts[0].vertices[0].triangle[0]=999;await seal(broken,record);await assert.rejects(()=>splitSkinBranches(broken,record),/field reference/);await assert.rejects(()=>splitSkinBranches(binding,{...record,recipeHash:'other'}),/corrupted source record/);});
test('a bent distal paw behind the root plane retains its painted limb ownership',async()=>{const {binding,record}=await fixture();for(const v of binding.paintSkin.vertices)v.y-=6.5;await seal(binding,record);const result=await splitSkinBranches(binding,record,{diffusionIterations:0}),[far,near]=result.binding.paintSkin.parts;assert.ok(far.vertices[0].triangle.every(i=>!near.vertices[0].triangle.includes(i)));assert.equal(result.receipt.surfaces.axial,0);const oldPlaneWouldMerge=binding.paintSkin.vertices.every(v=>v.y/10<record.landmarks.foreFarRoot[1]);assert.equal(oldPlaneWouldMerge,true);});
test('source/record corruption and unsupported anatomy refuse before producing a binding',async()=>{const {binding,record}=await fixture(),badSource=structuredClone(binding);badSource.paintSkin.vertices[0].x+=1;await assert.rejects(()=>splitSkinBranches(badSource,record),/corrupted source binding/);const badRecord=structuredClone(record);badRecord.landmarks.foreFarRoot[0]+=.1;await assert.rejects(()=>splitSkinBranches(binding,badRecord),/corrupted source record/);const other=structuredClone(record),copy=structuredClone(binding);other.template.id='serpent';await seal(copy,other);await assert.rejects(()=>splitSkinBranches(copy,other),/unsupported anatomy/);const invalid=structuredClone(binding);invalid.parts[0].joint='imaginary-limb';await seal(invalid,record);await assert.rejects(()=>splitSkinBranches(invalid,record),/part ownership/);});
test('uniform authoring scale preserves normalized interpolation, weights and surfaces and repeated builds are identical',async()=>{const {binding,record}=await fixture(),first=await splitSkinBranches(binding,record),again=await splitSkinBranches(binding,record);assert.equal(first.binding.bindingHash,again.binding.bindingHash);const larger=structuredClone(binding),largerRecord=structuredClone(record);largerRecord.geometry.width*=2;largerRecord.geometry.height*=2;for(const v of larger.paintSkin.vertices){v.x*=2;v.y*=2;}await seal(larger,largerRecord);const second=await splitSkinBranches(larger,largerRecord);assert.deepEqual(second.vertexSources,first.vertexSources);assert.deepEqual(second.vertexSurfaces,first.vertexSurfaces);assert.deepEqual(second.binding.paintSkin.triangles,first.binding.paintSkin.triangles);for(let i=0;i<first.binding.paintSkin.vertices.length;i++){const a=first.binding.paintSkin.vertices[i],b=second.binding.paintSkin.vertices[i];assert.equal(a.x,b.x/2);assert.equal(a.y,b.y/2);assert.deepEqual(a.weights,b.weights);}assert.equal(first.binding.atlasSha256,binding.atlasSha256);assert.deepEqual(first.binding.parts,binding.parts);});
test('actual part faces enter solver topology even when cached vertex interpolation references other faces',async()=>{
 const {binding,record}=await fixture();binding.parts=[{id:'chest',joint:'chest',kind:'part'}];
 const points=[[1,1],[4,1],[2,4],[2,0],[5,3],[0,3]];binding.paintSkin.vertices=points.map(([x,y])=>({x,y,weights:[['chest',1]]}));
 const refs=[[0,1,3],[1,2,4],[2,0,5]],part={id:'chest',vertices:refs.map(triangle=>({triangle,barycentric:[1,0,0]})),indices:[0,1,2]};
 binding.paintSkin.parts=[part];binding.paintSkin.triangles=[...refs.flat(),0,1,2];await seal(binding,record);
 const before=await splitSkinBranches(binding,record,{diffusionIterations:0});const key=(result,ids)=>ids.map(i=>result.vertexSources[i]).sort((a,b)=>a-b).join(',');
 const faces=result=>Array.from({length:result.binding.paintSkin.triangles.length/3},(_,i)=>key(result,result.binding.paintSkin.triangles.slice(i*3,i*3+3)));
 assert.ok(!faces(before).includes('0,1,2'),'old cached-reference collector omits the actual face');
 part.fieldTriangles=[0,1,2];await seal(binding,record);const after=await splitSkinBranches(binding,record,{diffusionIterations:0});assert.ok(faces(after).includes('0,1,2'));assert.equal(after.receipt.explicitPartFaces,1);
 part.fieldTriangles=[0,1];await seal(binding,record);await assert.rejects(()=>splitSkinBranches(binding,record),/part face provenance/);
});
test('actual ancestral attachment welds below root plane while an opposing sibling remains separate',async()=>{
 const {binding,record}=await fixture();binding.parts.forEach(p=>p.joint=p.joint.replace('Paw','Knee'));
 binding.parts.unshift({id:'chest',joint:'chest',kind:'part'});binding.paintSkin.parts.unshift({...structuredClone(binding.paintSkin.parts[0]),id:'chest'});await seal(binding,record);
 const options={diffusionIterations:0,attachmentEdges:[{ancestorPart:'chest',sourcePart:'near',edge:[[5,7],[5,7.1]]}]},result=await splitSkinBranches(binding,record,options),[chest,far,near]=result.binding.paintSkin.parts;
 assert.deepEqual(chest.vertices[0].triangle,near.vertices[0].triangle);assert.ok(far.vertices[0].triangle.every(i=>!near.vertices[0].triangle.includes(i)));assert.equal(result.receipt.attachmentSockets.foreNear.edges,1);
 const old=await splitSkinBranches(binding,record,{diffusionIterations:0});assert.notDeepEqual(old.binding.paintSkin.parts[0].vertices[0].triangle,old.binding.paintSkin.parts[2].vertices[0].triangle,'root-plane-only negative control disconnects this real attachment');
});
test('physical proximal skin joins axial/upper sibling owners while limb pairs and distal crossings remain split',async()=>{
 const {binding,record}=await fixture();binding.parts[1].joint='foreNearKnee';binding.parts.unshift({id:'neck',joint:'neck',kind:'part'});binding.paintSkin.parts.unshift({...structuredClone(binding.paintSkin.parts[0]),id:'neck'});await seal(binding,record);
 const edge=[[5,7],[5,7.1]],edges=[{ownerParts:['near','neck'],edge},{ownerParts:['far','neck'],edge},{ownerParts:['far','near'],edge}];
 const result=await splitSkinBranches(binding,record,{diffusionIterations:0,attachmentEdges:edges}),[neck,far,near]=result.binding.paintSkin.parts;
 assert.deepEqual(neck.vertices[0].triangle,near.vertices[0].triangle,'upper ownership shares physical neck skin despite sibling bones');assert.ok(far.vertices[0].triangle.every(i=>!neck.vertices[0].triangle.includes(i)),'distal paw cannot be welded to axial paint or opposite limb');
 assert.deepEqual(result.receipt.physicalSkinAdjacency.classes,{'axial-continuous':0,'same-limb-continuous':0,'axial-upper-socket':1,'independent-limbs':1,'axial-distal-crossing':1});
 const ancestorOnly=await splitSkinBranches(binding,record,{diffusionIterations:0,attachmentEdges:[]});assert.notDeepEqual(ancestorOnly.binding.paintSkin.parts[0].vertices[0].triangle,ancestorOnly.binding.paintSkin.parts[2].vertices[0].triangle,'bone-ancestor-only inventory leaves the neck cut open');
});
test('shared shoulder skin retains proximal limb influence without importing distal foot transforms',async()=>{
 const {binding,record}=await fixture();binding.parts[1].joint='foreNearKnee';binding.parts.unshift({id:'chest',joint:'chest',kind:'part'});binding.paintSkin.parts.unshift({...structuredClone(binding.paintSkin.parts[0]),id:'chest'});await seal(binding,record);
 const result=await splitSkinBranches(binding,record,{diffusionIterations:0,attachmentEdges:[{ownerParts:['chest','near'],edge:[[5,7],[5,7.1]]}]});
 const axial=result.binding.paintSkin.vertices.filter((v,i)=>result.vertexSurfaces[i]==='axial');assert.ok(axial.some(v=>v.weights.some(([j,w])=>j==='foreNearKnee'&&w>0)));assert.ok(axial.every(v=>v.weights.every(([j])=>!j.endsWith('Paw')&&!j.endsWith('Ankle'))));
});
test('shared muscle influences cross a socket continuously while an opposing distal foot remains independent',async()=>{
 const {binding,record}=await fixture();binding.parts[0].joint='foreFarKnee';binding.parts[1].joint='foreNearKnee';binding.paintSkin.vertices.forEach(v=>v.weights=[['tail1',.25],['foreFarKnee',.25],['foreNearAnkle',.5]]);await seal(binding,record);
 const r=await splitSkinBranches(binding,record,{diffusionIterations:0,attachmentEdges:[]}),skin=r.binding.paintSkin;
 for(let i=0;i<skin.vertices.length;i++){const v=skin.vertices[i],surface=r.vertexSurfaces[i];assert.ok(v.weights.some(([j,w])=>j==='tail1'&&w===.25));assert.ok(v.weights.some(([j,w])=>j==='foreFarKnee'&&w===.25));assert.ok(v.weights.some(([j,w])=>j===surface+'Ankle'&&w===.5));assert.ok(v.weights.every(([j])=>!j.endsWith('Ankle')||j===surface+'Ankle'));}
 const far=skin.parts[0].vertices[0].triangle,near=skin.parts[1].vertices[0].triangle;assert.ok(far.every(i=>!near.includes(i)));
 // An opposing ankle translation contributes exactly zero to the far surface.
 assert.ok(far.every(i=>!skin.vertices[i].weights.some(([j])=>j==='foreNearAnkle'||j==='foreNearPaw')));
});
