import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
import{createWasmArapPass}from'./wasm-arap-sweep.mjs';import{ARAP_SWEEP_BYTES}from'./arap-sweep-bytes.mjs';import{admitArapSweepObject}from'./build-arap-sweep.mjs';import{createArapScratch,solveArapSkin}from'./arap-skin.mjs';import * as reference from '../../../../audits/C2_CONTINUOUS_SKIN_20260916/cpu-kernel-05/arap-before.mjs';
const bytes=a=>Buffer.from(a.buffer,a.byteOffset,a.byteLength),native=globalThis.WebAssembly;
function fan(spokes=11){const vertices=[{x:80,y:80}],triangles=[];for(let i=0;i<spokes;i++){const t=i*2*Math.PI/spokes;vertices.push({x:80+60*Math.cos(t),y:80+60*Math.sin(t)});triangles.push(0,i+1,(i+1)%spokes+1);}return{vertices,triangles};}
function pair(runtime){if(arguments.length===0)runtime=native;const{vertices,triangles}=fan(),options={pins:[1,4]},old=reference.createArapScratch(vertices,triangles,160,160,options);let fresh;try{globalThis.WebAssembly=runtime;fresh=createArapScratch(vertices,triangles,160,160,options);}finally{globalThis.WebAssembly=native;}for(const Type of[Float32Array,Float64Array])for(const phase of[.4,-.2,.1]){const target=Type.from(vertices.flatMap((p,i)=>[(p.x+5*Math.sin(phase+i))/160,(p.y+7*Math.cos(phase-i))/160])),a=target.slice(),b=target.slice(),saved=target.slice();assert.deepEqual(solveArapSkin(fresh,target,b),reference.solveArapSkin(old,target,a));assert.ok(bytes(a).equals(bytes(b)));assert.deepEqual(target,saved);for(const p of options.pins){assert.equal(b[p*2],target[p*2]);assert.equal(b[p*2+1],target[p*2+1]);}}return fresh;}
function runtimeWithBytes(binary){function Module(){return new native.Module(binary);}Module.imports=native.Module.imports;Module.exports=native.Module.exports;return{Module,Instance:native.Instance,Memory:native.Memory};}
test('real admitted Wasm leaf matches the current JS solver exactly and shares fixed scratch memory',()=>{const s=pair();assert.equal(s.sweepBackend,'wasm');assert.equal(s.normalPasses,s.sweepKernel.normalPasses);assert.ok(s.normalPasses>0);assert.equal(s.robustFallbacks,0);assert.equal(s.position.buffer,s.rhs.buffer);assert.equal(s.sweepKernel.position,s.position);assert.equal(s.sweepKernel.rhs,s.rhs);const memory=s.position.buffer;s.position.set(s.rest);s.target.set(s.rest);assert.equal(s.sweepKernel.runPass(4),true);assert.equal(s.position.buffer,memory);assert.throws(()=>s.sweepKernel.runPass(0),/sweep budget/);assert.throws(()=>s.sweepKernel.runPass(33),/sweep budget/);});
test('absent Wasm and denied memory use the actual JS fallback with exact outputs',()=>{assert.equal(pair(undefined).sweepBackend,'js');assert.equal(pair(null).sweepBackend,'js');const denied={Module:native.Module,Instance:native.Instance,Memory:class{constructor(){throw Error('memory denied');}}};assert.equal(pair(denied).sweepBackend,'js');});
test('a real add-to-subtract binary mutant is rejected by admission and the runtime falls back',()=>{const mutant=ARAP_SWEEP_BYTES.slice(),at=mutant.indexOf(0xa0);assert.ok(at>0);mutant[at]=0xa1;assert.ok(native.validate(mutant),'mutant must remain a valid module');assert.equal(pair(runtimeWithBytes(mutant)).sweepBackend,'js');});
function input(s){return{rest:s.rest.slice(),rows:s.solveRows.slice(),neighbours:s.neighbourDofs.slice(),reciprocals:s.solveReciprocals.slice(),starts:s.starts.slice(),deltas:s.deltas.slice(),lambda:s.lambda.slice()};}
test('leaf snapshots all invariants and refuses malformed rows instead of silently accepting them',()=>{const{vertices,triangles}=fan(8),s=reference.createArapScratch(vertices,triangles,160,160),c=input(s),kernel=createWasmArapPass(c);assert.ok(kernel);kernel.position.set(s.rest);for(let i=0;i<kernel.target.length;i++)kernel.target[i]=s.rest[i]+(i%7-3)/32;const expected=createWasmArapPass(c);expected.position.set(kernel.position);expected.target.set(kernel.target);for(const a of Object.values(c))a.fill(0);assert.equal(kernel.runPass(3),true);assert.equal(expected.runPass(3),true);assert.deepEqual(kernel.position,expected.position);assert.deepEqual(kernel.rotation,expected.rotation);assert.deepEqual(kernel.rhs,expected.rhs);const invalid=input(s);invalid.rows[3]=2**30;assert.throws(()=>createWasmArapPass(invalid),/compiled neighbor/);});
test('normal-range refusal precedes every position and RHS write, then robust JS preserves exact results',()=>{const{vertices,triangles}=fan(),s=createArapScratch(vertices,triangles,160,160),kernel=s.sweepKernel;assert.equal(s.sweepBackend,'wasm');kernel.position.set(s.rest);kernel.position[kernel.position.length-2]=1e200;kernel.rhs.fill(7);const unchanged=kernel.position.slice();assert.equal(kernel.runPass(4),false);assert.deepEqual(kernel.position,unchanged);assert.ok(kernel.rhs.every(v=>v===7));assert.equal(kernel.robustFallbacks,1);assert.equal(s.robustFallbacks,1);const old=reference.createArapScratch(vertices,triangles,160,160),target=Float64Array.from(vertices.flatMap(p=>[p.x/160*1e-120,p.y/160*1e-120])),a=target.slice(),b=target.slice();assert.deepEqual(solveArapSkin(s,target,b),reference.solveArapSkin(old,target,a));assert.ok(bytes(a).equals(bytes(b)));assert.ok(kernel.robustFallbacks>1);});

const leb=n=>{const a=[];do{a.push((n&127)|(n>127?128:0));n>>>=7;}while(n);return a;},section=(id,body)=>[id,...leb(body.length),...body],header=[0,97,115,109,1,0,0,0];
function split(binary){let at=8;const list=[],uint=()=>{let n=0,shift=0,b;do{b=binary[at++];n|=(b&127)<<shift;shift+=7;}while(b&128);return n;};while(at<binary.length){const id=binary[at++],length=uint();list.push({id,body:binary.slice(at,at+length)});at+=length;}return list;}
test('strict artifact admission rejects relocation/global/data/table/function-import controls',()=>{const sections=split(ARAP_SWEEP_BYTES).filter(s=>s.id!==7),object=Uint8Array.from([...header,...sections.flatMap(s=>section(s.id,s.body))]);assert.deepEqual(admitArapSweepObject(object),ARAP_SWEEP_BYTES);assert.deepEqual(fs.readFileSync(new URL('./arap-sweep.wasm',import.meta.url)),Buffer.from(ARAP_SWEEP_BYTES));for(const id of[4,6,9,11,12]){const mutant=Uint8Array.from([...object,...section(id,[0])]);assert.throws(()=>admitArapSweepObject(mutant),/forbidden section/);}const name=Buffer.from('reloc.CODE');assert.throws(()=>admitArapSweepObject(Uint8Array.from([...object,...section(0,[...leb(name.length),...name,0,0])])),/custom section reloc.CODE/);const imported=sections.map(s=>s.id===2?{id:2,body:Uint8Array.from([1,3,101,110,118,1,102,0,0])}:s);assert.throws(()=>admitArapSweepObject(Uint8Array.from([...header,...imported.flatMap(s=>section(s.id,s.body))])),/memory-only import/);assert.throws(()=>admitArapSweepObject(ARAP_SWEEP_BYTES),/forbidden section 7/);});
test('a late disconnected-component norm refusal cannot publish an earlier component update',()=>{const vertices=[{x:0,y:0},{x:10,y:0},{x:0,y:10},{x:20,y:20},{x:30,y:20},{x:20,y:30}],s=createArapScratch(vertices,[0,1,2,3,4,5],40,40),k=s.sweepKernel;assert.equal(s.sweepBackend,'wasm');k.position.set(s.rest);k.target.set(s.rest);k.rotation.fill(-99);k.rhs.fill(7);k.position[10]=1e200;const original=k.position.slice();assert.equal(k.runPass(4),false);assert.notEqual(k.rotation[0],-99,'first component must reach the rotation stage');assert.equal(k.rotation[6],-99,'second component must refuse before its rotation write');assert.deepEqual(k.position,original);assert.ok(k.rhs.every(v=>v===7));assert.equal(s.robustFallbacks,1);});
