import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createWasmOrientationForward} from './wasm-orientation-forward.mjs';
import {ORIENTATION_FORWARD_BYTES} from './orientation-forward-bytes.mjs';
import {admitOrientationForwardObject} from './build-orientation-forward.mjs';
const native=globalThis.WebAssembly;
// Verbatim pre-optimization owner, SHA-256 7832c6a9d41ef37c229b9f346f629b8afc397e1055fa375f847cd9b87a59bcf4.
// This oracle retains ordered scalar operations and Object.is progress.
function forwardProjection(s){const{position:p,triangleDofs,triangleSigns,triangleFloors,triangleMovable}=s;let orientationPasses=0;
 for(let pass=0;pass<s.orientationIterations;pass++){
  let changed=0,progressed=false;for(let k=0;k<triangleDofs.length;k+=3){
   const a=triangleDofs[k],b=triangleDofs[k+1],c=triangleDofs[k+2],triangle=k/3,sign=triangleSigns[triangle],movable=triangleMovable[triangle];
   const area=(p[b]-p[a])*(p[c+1]-p[a+1])-(p[b+1]-p[a+1])*(p[c]-p[a]),constraint=area*sign-triangleFloors[triangle];
   if(constraint>=0)continue;changed++;
   const ax=p[b+1]-p[c+1],ay=p[c]-p[b],bx=p[c+1]-p[a+1],by=p[a]-p[c],cx=p[a+1]-p[b+1],cy=p[b]-p[a];
   const norm=(movable&1?ax*ax+ay*ay:0)+(movable&2?bx*bx+by*by:0)+(movable&4?cx*cx+cy*cy:0);if(norm<1e-20)continue;
   const scale=-constraint*sign/norm;
   if(movable&1){const x=p[a],y=p[a+1];p[a]+=scale*ax;p[a+1]+=scale*ay;if(!Object.is(x,p[a])||!Object.is(y,p[a+1]))progressed=true;}
   if(movable&2){const x=p[b],y=p[b+1];p[b]+=scale*bx;p[b+1]+=scale*by;if(!Object.is(x,p[b])||!Object.is(y,p[b+1]))progressed=true;}
   if(movable&4){const x=p[c],y=p[c+1];p[c]+=scale*cx;p[c+1]+=scale*cy;if(!Object.is(x,p[c])||!Object.is(y,p[c+1]))progressed=true;}
  }
  // Repeating a sweep that changed no Float64 coordinate is an exact no-op,
  // including signed zero. Keep the final orientation refusal: a stalled
  // contradictory contact pose still fails and never publishes its pixels.
  orientationPasses=pass+1;if(!changed||!progressed){s.orientationQueue.stalled=!progressed;break;}
 }
 return orientationPasses;
}

function fixture({position=[0,0,2,0,0,-1],dofs=[0,2,4],signs=[1],floors=[.25],movable=[7]}={}){return{position:Float64Array.from(position),triangleDofs:Uint32Array.from(dofs),triangleSigns:Int8Array.from(signs),triangleFloors:Float64Array.from(floors),triangleMovable:Uint8Array.from(movable)};}
function clone(c){return Object.fromEntries(Object.entries(c).map(([key,value])=>[key,value.slice()]));}
function compare(c,iterations=64){const before=c.position.slice(),expected={...clone(c),orientationIterations:iterations,orientationQueue:{stalled:false}},kernel=createWasmOrientationForward(c);assert.ok(kernel,'Actual Wasm must be admitted');assert.deepEqual(c.position,before,'Admission may not change caller positions');const wanted=forwardProjection(expected),actual=c.position.slice(),passes=kernel.run(actual,iterations);assert.equal(passes,wanted);assert.equal(kernel.stalled,expected.orientationQueue.stalled);for(let i=0;i<actual.length;i++)assert.ok(Object.is(actual[i],expected.position[i]),'Float64 coordinate '+i);assert.deepEqual(c.position,before);return{kernel,actual,expected,passes};}
test('every pin mask and orientation sign preserves exact coordinates, counts and stalled state',()=>{let deformed=0;for(let mask=0;mask<=7;mask++)for(const sign of[-1,1])for(const iterations of[1,2,17,64]){const c=fixture({movable:[mask],signs:[sign]}),{actual}=compare(c,iterations);for(let vertex=0;vertex<3;vertex++){if(!(mask&(1<<vertex))){assert.ok(Object.is(actual[vertex*2],c.position[vertex*2]));assert.ok(Object.is(actual[vertex*2+1],c.position[vertex*2+1]));}else if(actual[vertex*2]!==c.position[vertex*2]||actual[vertex*2+1]!==c.position[vertex*2+1])deformed++;}}assert.ok(deformed>0,'Fixtures must exercise projection');});
test('deterministic shared-vertex fixtures preserve scalar ordering over repeated seeks',()=>{for(let seed=1;seed<=24;seed++){const position=[];for(let i=0;i<12;i++)position.push(((i*73+seed*29)%127-63)/8);const c=fixture({position,dofs:[0,2,4,0,4,6,0,6,8,0,8,10,0,10,2],signs:[1,-1,1,-1,1],floors:[.2,.3,.4,.5,.6],movable:[7,6,5,3,7]});for(const iterations of[1,7,64])compare(c,iterations);const k=createWasmOrientationForward(c),first=c.position.slice(),again=c.position.slice();assert.equal(k.run(first,64),k.run(again,64));assert.deepEqual(first,again);}});
test('signed-zero-only progress consumes the second pass before stalling',()=>{const c=fixture({position:[-0,1,1,1,2,1],floors:[Number.MIN_VALUE],movable:[1]}),r=compare(c);assert.equal(r.passes,2);assert.equal(r.kernel.stalled,true);assert.ok(Object.is(r.actual[0],0));assert.ok(Object.is(c.position[0],-0));assert.equal(r.actual[1],1);});
test('stationary pinned and degenerate constraints stall; contradictory constraints retain the full 64 sweeps',()=>{const pinned=compare(fixture({movable:[0]}));assert.equal(pinned.passes,1);assert.equal(pinned.kernel.stalled,true);assert.deepEqual(pinned.actual,fixture().position);const degenerate=compare(fixture({position:[1,1,1,1,1,1]}));assert.equal(degenerate.passes,1);assert.equal(degenerate.kernel.stalled,true);const contradictory=compare(fixture({dofs:[0,2,4,0,4,2],signs:[1,1],floors:[.25,.25],movable:[7,7]}));assert.equal(contradictory.passes,64);assert.equal(contradictory.kernel.stalled,false);});
test('extreme finite inputs preserve Object.is behavior when arithmetic overflows or underflows',()=>{for(const c of[fixture({position:[-1e308,-1e308,1e308,1e308,1e308,-1e308]}),fixture({position:[-0,0,Number.MIN_VALUE,0,0,-Number.MIN_VALUE],floors:[Number.MIN_VALUE]}),fixture({position:[0,-0,1e-12,0,0,-1e-12],floors:[1e-30]})])compare(c);});
test('fixed private topology survives caller mutation and runtime absence uses an explicit null fallback',()=>{const c=fixture(),before=clone(c),k=createWasmOrientationForward(c),other=createWasmOrientationForward(before);for(const value of Object.values(c))value.fill(0);const a=before.position.slice(),b=before.position.slice();assert.equal(k.run(a,64),other.run(b,64));assert.deepEqual(a,b);assert.equal(k.stalled,other.stalled);assert.equal(createWasmOrientationForward(before,null),null);const denied={Module:native.Module,Instance:native.Instance,Memory:class{constructor(){throw Error('denied');}}};assert.equal(createWasmOrientationForward(before,denied),null);});
function runtimeWithBytes(binary){function Module(){return new native.Module(binary);}Module.imports=native.Module.imports;Module.exports=native.Module.exports;return{Module,Instance:native.Instance,Memory:native.Memory};}
test('valid arithmetic mutant and a no-op forward export are rejected before caller mutation',()=>{const mutant=ORIENTATION_FORWARD_BYTES.slice(),at=mutant.indexOf(0xa2);assert.ok(at>0);mutant[at]=0xa0;assert.ok(native.validate(mutant));const c=fixture(),saved=c.position.slice();assert.equal(createWasmOrientationForward(c,runtimeWithBytes(mutant)),null);assert.deepEqual(c.position,saved);const noop={Module:native.Module,Memory:native.Memory,Instance:class{constructor(){this.exports={forward:()=>1};}}};assert.equal(createWasmOrientationForward(c,noop),null);assert.deepEqual(c.position,saved);});
test('malformed constraints and over-budget calls fail closed',()=>{for(const mutate of[c=>c.triangleDofs[0]=1,c=>c.triangleDofs[2]=6,c=>c.triangleSigns[0]=0,c=>c.triangleFloors[0]=NaN,c=>c.triangleMovable[0]=8]){const c=fixture();mutate(c);assert.throws(()=>createWasmOrientationForward(c),/Orientation forward Wasm/);}const c=fixture(),k=createWasmOrientationForward(c),saved=c.position.slice();for(const n of[0,65,1.5,NaN])assert.throws(()=>k.run(c.position,n),/sweep budget/);assert.throws(()=>k.run(new Float32Array(6),1),/position buffer/);assert.deepEqual(c.position,saved);});
const leb=n=>{const a=[];do{a.push((n&127)|(n>127?128:0));n>>>=7;}while(n);return a;},section=(id,body)=>[id,...leb(body.length),...body],header=[0,97,115,109,1,0,0,0];
function split(binary){let at=8;const list=[],uint=()=>{let n=0,shift=0,b;do{b=binary[at++];n|=(b&127)<<shift;shift+=7;}while(b&128);return n;};while(at<binary.length){const id=binary[at++],length=uint();list.push({id,body:binary.slice(at,at+length)});at+=length;}return list;}
test('memory-only artifact admission rejects relocation, globals, tables, data and function imports',()=>{const sections=split(ORIENTATION_FORWARD_BYTES).filter(s=>s.id!==7),object=Uint8Array.from([...header,...sections.flatMap(s=>section(s.id,s.body))]);assert.deepEqual(admitOrientationForwardObject(object),ORIENTATION_FORWARD_BYTES);assert.deepEqual(fs.readFileSync(new URL('./orientation-forward.wasm',import.meta.url)),Buffer.from(ORIENTATION_FORWARD_BYTES));for(const id of[4,6,9,11,12])assert.throws(()=>admitOrientationForwardObject(Uint8Array.from([...object,...section(id,[0])])),/forbidden section/);const name=Buffer.from('reloc.CODE');assert.throws(()=>admitOrientationForwardObject(Uint8Array.from([...object,...section(0,[...leb(name.length),...name,0,0])])),/custom section reloc.CODE/);const imported=sections.map(s=>s.id===2?{id:2,body:Uint8Array.from([1,3,101,110,118,1,102,0,0])}:s);assert.throws(()=>admitOrientationForwardObject(Uint8Array.from([...header,...imported.flatMap(s=>section(s.id,s.body))])),/memory-only import/);assert.throws(()=>admitOrientationForwardObject(ORIENTATION_FORWARD_BYTES),/forbidden section 7/);});
