/* CODE + HARDENING FIXTURES — capture and verify the share/champion/where codecs
   and the two genome hardeners.
   Port Phase 0 / Gate A: "capture representative saves, share codes, champion
   codes, and migration fixtures". Feeds Gate C.

   USAGE
     node tools/codefixtures.js --capture
     node tools/codefixtures.js --check     # a GATE

   ⚠ SCOPE, STATED HONESTLY: this pins the CODEC and LOAD-PATH HARDENING surface —
   encodeCreature/decodeCreature (share AND champion), encodeWhere/decodeWhere,
   normGenome (untrusted import) and _sanitizeSavedGenome (load path). It does NOT
   capture a full save round-trip, because buildSave/loadSave are app-layer and not
   exposed to the probe realm. Gate C's "a REAL veteran save imports successfully"
   therefore remains OPEN and cannot be closed by this fixture — a synthetic save
   generated by the same code that reads it proves very little. See ROADMAP.

   ⚠ NEVER re-capture to make a failing --check pass. Same rule as baseline.json. */
'use strict';
const fs = require('fs');
const path = require('path');
const { bootProbe, root } = require('./_probeboot.js');

const OUT = path.join(root, 'port', 'baseline-v1.8.9', 'code-fixtures.json');
const CAPTURE = process.argv.includes('--capture');
const CHECK = process.argv.includes('--check');
if (!CAPTURE && !CHECK) { console.error('usage: node tools/codefixtures.js --capture | --check'); process.exit(2); }

bootProbe({ probe: 'codefixtures-probe.js', global: '__CODEFX__' }).then(({ value, errors, window }) => {
  if (!value || value.error) {
    console.error('CODE FIXTURES: probe failed —', (value && value.error) || 'no result');
    if (errors.length) console.error(errors.slice(0, 5).join('\n'));
    process.exit(1);
  }

  const buckets = ['creatureCodes', 'championCodes', 'whereCodes', 'normGenome', 'sanitizeSavedGenome', 'cleanName'];
  const countOf = (v) => buckets.reduce((a, b) => a + Object.keys(v[b] || {}).length, 0);

  /* ---- the invariants worth asserting OUTRIGHT, not just recording ---- */
  const invariants = [];
  const sg = value.sanitizeSavedGenome || {};
  for (const k of Object.keys(sg).sort()) {
    if (!/^size_/.test(k)) continue;
    /* v1.8.7: the load path must NOT rewrite `size`. An honestly-bred size>5
       genome survives unchanged; v1.8.6 clamped it and permanently rewrote ~12%
       of bred creatures. This is the executable form of that rule. */
    invariants.push({ name: 'sizePreserved:' + k, ok: sg[k].sizePreserved === true, detail: sg[k].sizeIn + ' -> ' + sg[k].sizeOut });
  }

  if (CAPTURE) {
    const fixture = {
      _comment: [
        'CODEC + HARDENING FIXTURES — port Phase 0 / Gate A, feeding Gate C.',
        '',
        'Curated adversarial cases, deliberately NOT a volume corpus —',
        'golden-seeds.json already covers volume. A random corpus will never',
        'contain size:1e6 or a __proto__ key; a codec needs named edges with',
        'stated expectations.',
        '',
        '⚠ THE size_* CASES ARE THE POINT. crossGenome mutates `size` without',
        'wrapping, so honestly-bred genomes carry size>5 (12.4% of lineages by',
        'generation 5). v1.8.6 added a load-path clamp that permanently rewrote',
        'them into titanic, maximum-vitality creatures; v1.8.7 reverted it. The',
        'port MUST reproduce the v1.8.7 behaviour: _sanitizeSavedGenome leaves',
        '`size` UNCHANGED. `invariants` below asserts this outright.',
        '',
        'CANONICAL FORM matches goldenseeds-probe.js: numbers rounded to 1e-9,',
        'object keys sorted, undefined -> null.',
        '',
        'SCOPE: codec + hardening only. buildSave/loadSave are app-layer and not',
        'reachable from the probe realm, so a FULL save round-trip is not captured',
        'here and Gate C stays open pending a real veteran save.',
        '',
        '⚠ DO NOT REGENERATE THIS TO MAKE A FAILING --check PASS.',
      ],
      capturedAt: '2026-07-31',
      capturedAgainst: 'v1.8.9 (tag v1.8.9, commit 92098e9)',
      cases: countOf(value),
      invariants,
      ...value,
    };
    fs.mkdirSync(path.dirname(OUT), { recursive: true });
    fs.writeFileSync(OUT, JSON.stringify(fixture, null, 1));
    const failed = invariants.filter((i) => !i.ok);
    console.log('CODE FIXTURES captured');
    for (const b of buckets) console.log('  ' + b.padEnd(22) + Object.keys(value[b] || {}).length + ' cases');
    console.log('  invariants            ' + invariants.length + ' (' + (invariants.length - failed.length) + ' hold)');
    for (const f of failed) console.log('    ⚠ VIOLATED: ' + f.name + ' — ' + f.detail);
    console.log('  written               ' + path.relative(root, OUT) + ' (' + (fs.statSync(OUT).size / 1024).toFixed(0) + ' KB)');
    window.close();
    process.exit(failed.length || errors.length ? 1 : 0);
  }

  /* ---------- --check ---------- */
  if (!fs.existsSync(OUT)) { console.error('CODE FIXTURES: no fixture at ' + OUT + ' — run --capture first'); process.exit(1); }
  const base = JSON.parse(fs.readFileSync(OUT, 'utf8'));
  let bad = 0;
  for (const b of buckets) {
    const B = base[b] || {}, G = value[b] || {};
    for (const k of Object.keys(B).sort()) {
      if (!(k in G)) { console.error('  MISSING case ' + b + '.' + k); bad++; continue; }
      const x = JSON.stringify(B[k]), y = JSON.stringify(G[k]);
      if (x !== y) { console.error('  MISMATCH ' + b + '.' + k); console.error('      was: ' + x.slice(0, 200)); console.error('      now: ' + y.slice(0, 200)); bad++; }
    }
    for (const k of Object.keys(G)) if (!(k in B)) { console.error('  NEW case not in fixture: ' + b + '.' + k); bad++; }
  }
  const iv = invariants.filter((i) => !i.ok);
  for (const f of iv) { console.error('  ⚠ INVARIANT VIOLATED: ' + f.name + ' — ' + f.detail); bad++; }

  console.log('');
  if (bad) console.log('CODE FIXTURES: FAIL — ' + bad + ' difference(s). Observable codec or hardening behavior changed.');
  else console.log('CODE FIXTURES: PASS — ' + base.cases + ' cases, ' + invariants.length + ' invariants hold');
  window.close();
  process.exit(bad ? 1 : 0);
}).catch((e) => { console.error('CODE FIXTURES: ' + (e && e.stack || e)); process.exit(1); });
