import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {compileLibraryMaster,controlledLibraryLayout} from '../../port/v2/tools/painted-creature/compile-library-master.mjs';
const base='audits/C196_QUADRUPED_ORIGINALS_20261002',sha=b=>createHash('sha256').update(b).digest('hex');
const reptiles=['Caiman','Crocodile','Monitor Lizard','Anole','Skink','Mountain Lizard','Lizard','Whiptail','Agama','Gila Monster','Frilled Lizard','Chameleon','Marine Iguana'];
const ungulates=['Giraffe','Buffalo','Banteng','Water Buffalo'];
const primates=['Tamarin','Langur','Monkey','Mandrill','Marmoset','Aye-Aye','Proboscis Monkey'];
const names=[...reptiles,...ungulates,...primates];
const reasons={Caiman:'C167 unexplained-paint refusal; expose connected four-limb contours and tail root.',Crocodile:'C167 unexplained-paint refusal; expose connected four-limb contours and tail root.','Monitor Lizard':'C167 jaw refusal; separate true jaw contour, naturally level head and all four limbs.',Anole:'C167 far-limb refusal; expose both real far limb chains.',Skink:'C167 hind-paw refusal; expose full hind ankle and foot without changing its short natural limbs.','Mountain Lizard':'C167 hind-paw refusal; expose hind ankle and complete foot.',Lizard:'C167 hind-ankle refusal; preserve readable natural joint bends.',Whiptail:'C167 far-limb refusal; expose both real far limb chains.',Agama:'C167 single-contact refusal; four grounded, separately readable feet.','Gila Monster':'C167 unexplained-paint refusal; keep scales inside continuous anatomical contours.','Frilled Lizard':'C167 unexplained-paint refusal; natural relaxed folded frill and leg roots.',Chameleon:'C167 unexplained-paint refusal; preserve actual grasping feet and tail contours.','Marine Iguana':'C167 far-limb refusal; expose both real far limb chains.',Giraffe:'Prior C110/C136 far-ear/crown source limitation; show both actual ears and all four hoof chains.',Buffalo:'Prior C110/C136 far-ear and proximal foreleg overlap; show natural ear/horn boundaries and separate upper limb contours.',Banteng:'Prior C110/C136 far-ear and upper foreleg overlap; show natural ear/horn boundaries and separate upper limb contours.','Water Buffalo':'Prior C110/C136 far-ear and upper foreleg overlap; show natural ear/horn boundaries and separate upper limb contours.'};
const prior=new Map();for(const f of execFileSync('rg',['--files','-g','pilot.json','audits'],{encoding:'utf8'}).trim().split('\n')){const d=JSON.parse(fs.readFileSync(f));for(const r of(Array.isArray(d)?d:d.subjects||d.rows||d.pilot||d.creatures||[]))if(r.name)prior.set(r.name,[...(prior.get(r.name)||[]),f]);}
const coverage=JSON.parse(fs.readFileSync('audits/GENERATED_GALLERY_20260927/coverage.json'));
const accepted=new Set(Object.values(coverage.families).flatMap(f=>f.names??[]));
for(const name of names){if(accepted.has(name))throw Error('Accepted species duplicate: '+name);if(primates.includes(name)&&prior.has(name))throw Error('First-painting claim changed: '+name);}
const sprawler='Strict side profile facing RIGHT, head right and full natural tail left. One adult reptile with exactly FOUR true legs, two forelegs and two hindlegs. Keep its trunk naturally LOW and its real elbows and knees sprawled outward, never mammal-like straight pillars. Use a quiet grounded walking stance in which all four actual limb chains are visible from shoulder or hip through elbow or knee, ankle and complete foot. Offset near and far limbs naturally, preserving separate contours and clear magenta between shafts; do not merely split toes below merged upper legs. Every foot rests on the same level. Head and jaw remain naturally level and visibly above the foot contact level, not dipped into it. Preserve real toe/claw anatomy and full tail continuously from its biological root to tip, with no crossing of limbs. Reptiles have no mammalian external ear pinnae: do not invent ears, fur, hooves or horns. Retain actual species scales, crests, dewlaps, frills and markings. No scenery, floor, shadow, branch, props or labels. Keep every structure inside the canvas with generous clear margin.';
const hoof='Strict side profile facing RIGHT with a very slight natural head turn only as needed to show both real ears. One adult hoofed quadruped in a quiet grounded walking stance, exactly FOUR naturally connected limbs with four separately readable hooves at the same ground level. Separate both foreleg contours from their actual shoulder roots through wrists and hooves, and both hindlegs from their actual hip roots through hocks and hooves. Preserve species-correct limb length and natural joint bends. Show both ears with their actual crown attachments and distinguish them from horns or ossicones; never relocate or invent an ear to expose it. Keep the head naturally raised, muzzle above ground, actual neck length and natural tail completely visible away from limbs. Preserve canonical horns, coat, patches and hoof anatomy; no generic horse anatomy. No floor, shadow, scenery, props or text. Keep the complete silhouette with generous margins.';
const primateExtra='SOURCE READABILITY: a natural grounded quadrupedal walking stance, two hands and two feet all visible at one level, with four separately traceable natural limb chains and all actual contact surfaces. Keep the true tail clear of the arms and legs, never add a prehensile tip where the species lacks one. No supporting branch, bark, rope, scenery or prop. Preserve actual hand, foot, ear, face and digit anatomy rather than converting the animal to a four-pawed mammal.';
const composition='FINAL COMPOSITION CHECK: the 1254 by 1254 canvas is mostly empty pure magenta. Zoom the complete specimen OUT. Every arm, leg, wing, antenna, tail, tentacle and other part must fit within the central rectangle x=314 through x=940, y=314 through y=940. The rectangle is only an invisible placement guide: DO NOT paint a frame, line, ruler, label or grid. Make the entire animal smaller, never shorten its natural appendages to fit. Preserve detailed painted surfaces.';
const once=(s,a,b)=>{if(s.split(a).length!==2)throw Error('Unique exact edit required');return s.replace(a,b);};
const rows=[];for(const[i,name]of names.entries()){
 const id=String(i+1).padStart(2,'0')+'-'+name.toLowerCase().replaceAll(' ','-'),packet=base+'/'+id,c=await compileLibraryMaster(name,packet),r=JSON.parse(fs.readFileSync(packet+'/request.json')),sub=JSON.parse(fs.readFileSync(packet+'/subject-source.json'));let prompt=fs.readFileSync(packet+'/prompt.txt','utf8');if(sha(prompt)!==r.promptSha256)throw Error('Canonical prompt hash');
 const old=controlledLibraryLayout(c.family,name).layout,override=reptiles.includes(name)?sprawler:ungulates.includes(name)?hoof:null;
 if(override){const start=prompt.indexOf('\nSUBJECT\n'),end=prompt.indexOf('\n\nACCURACY\n'),section=prompt.slice(start,end);prompt=once(prompt,section,once(section,old,override));prompt=once(prompt,'\n\nLAYOUT\n'+old+'\n\nTECHNICAL OUTPUT\n','\n\nLAYOUT\n'+override+'\n\nTECHNICAL OUTPUT\n');}
 const identity='SPECIES AND ANATOMY PRIORITY: '+sub.species.mustRead.join('; ')+'.',extra=primates.includes(name)?primateExtra:'';prompt=composition+'\n\n'+identity+'\n'+extra+'\n\n'+prompt+'\n\n'+identity+'\n'+extra+'\n'+composition+'\n';
 const purpose=primates.includes(name)?'NEW_ORIGINAL':'TARGETED_SOURCE_REPAINT',repairReason=reasons[name]??null;
 fs.writeFileSync(packet+'/prompt.txt.tmp',prompt,{flag:'wx'});fs.renameSync(packet+'/prompt.txt.tmp',packet+'/prompt.txt');fs.writeFileSync(packet+'/request.json.tmp',JSON.stringify({...r,basePromptSha256:r.promptSha256,promptSha256:sha(prompt),batchCompilerSha256:sha(fs.readFileSync(import.meta.filename)),purpose,repairReason,priorPilotPaths:prior.get(name)??[],layoutOverride:override,additionalSourceReadability:extra||null,compositionCheck:composition,admission:'GENERATED_CANDIDATE_ONLY; no semantic presence, rig admission or motion claim'},null,2)+'\n',{flag:'wx'});fs.renameSync(packet+'/request.json.tmp',packet+'/request.json');rows.push({id,name,family:c.family,packet,master:packet+'/master.png',purpose,repairReason});console.log(id,c.family);
}
fs.writeFileSync(base+'/pilot.json',JSON.stringify(rows,null,2)+'\n',{flag:'wx'});
fs.writeFileSync(base+'/selection.json',JSON.stringify({schema:'cf.g2-selection/v1',newOriginals:7,targetedSourceRepaints:17,total:24,coverageSource:'audits/GENERATED_GALLERY_20260927/coverage.json',coverageSha256:sha(fs.readFileSync('audits/GENERATED_GALLERY_20260927/coverage.json')),coveredAtSelection:196,priorPilotNames:prior.size,excluded:'All selected species unaccepted. Ordinary supported quadrupeds already have originals. Untouched turtles, sloth and pinnipeds require appropriate shell/flipper/material support; no forced substitute anatomy. Seven unpainted primates use their canonical controlled family.',rows},null,2)+'\n',{flag:'wx'});
