import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {compileLibraryMaster} from '../../port/v2/tools/painted-creature/compile-library-master.mjs';
const packet='audits/C203_NATIVE_HOLDS_20261004/snow-petrel-folded-source-01',sha=b=>createHash('sha256').update(b).digest('hex');
await compileLibraryMaster('Snow Petrel',packet);
const q=JSON.parse(fs.readFileSync(packet+'/request.json')),canonical=fs.readFileSync(packet+'/prompt.txt','utf8');
const correction='TARGETED SOURCE CORRECTION: Natural adult Snow Petrel calmly standing with both wings naturally FOLDED tight against its body. No raised wing, spread flight fan or lifted shoulder; continuous feather coverts blend through the shoulder and back with no seams or cut lines. The far folded wing appears only as its own visible narrow upper edge and natural root emergence behind the near wing; no invented extra wing. Both distinct dark feet and complete lower leg shafts must be clearly separated, each with naturally flexed ankle on the same ground plane. Preserve white plumage, small black hooked bill with natural tubular nostril, dark eye and complete short feather tail. Entire head crown, beak, both natural wings and feet are in frame.';
const composition='COMPOSITION PRIORITY: small complete animal centered on native1254 by1254 magenta canvas; whole silhouette in central two-thirds with generous empty margin, no crop, floor or shadow.';
const prompt=composition+'\n'+correction+'\n\n'+canonical+'\n\n'+correction+'\n'+composition+'\n';
fs.writeFileSync(packet+'/prompt.canonical.txt',canonical,{flag:'wx'});fs.writeFileSync(packet+'/prompt.txt.tmp',prompt,{flag:'wx'});fs.renameSync(packet+'/prompt.txt.tmp',packet+'/prompt.txt');
fs.writeFileSync(packet+'/request.json.tmp',JSON.stringify({...q,basePromptSha256:q.promptSha256,promptSha256:sha(prompt),sourceCorrection:correction,compositionCheck:composition,purpose:'TARGETED_SOURCE_REPAINT',priorSource:'audits/C198_SOURCE_HOLDS_20261003/03-snow-petrel-open/master.png',admission:'SOURCE_CANDIDATE_ONLY'},null,2)+'\n',{flag:'wx'});fs.renameSync(packet+'/request.json.tmp',packet+'/request.json');
