import fs from 'node:fs';
import {compileBodyCard,buildTimeline} from '../../port/v2/apps/game/src/motion/index.ts';
import {withPaintedContactSupports} from '../../port/v2/apps/game/src/motion/painted-supports.ts';
import {createFamilyContactSolver,observedContactSupports} from '../../port/v2/apps/game/src/creature-rig-contact.ts';
import {sampleClip,addPose} from '../../port/v2/apps/game/src/battle2/choreography.ts';
const B='audits/C203_NATIVE_HOLDS_20261004',fit='audits/C202_NATIVE_HOLDS_20261004/red-fox-source-01/fit01',record=JSON.parse(fs.readFileSync(fit+'/record.json','utf8')),binding=JSON.parse(fs.readFileSync(fit+'/binding.json','utf8')),card=withPaintedContactSupports(compileBodyCard(record,record.genome),record,binding),solver=createFamilyContactSolver(record,observedContactSupports(record,binding)),gait=buildTimeline(card,'approach',5),idle=buildTimeline(card,'idle',5),torso=new Set(['root','pelvis','spine','chest']);
function gain(p:ReturnType<typeof sampleClip>,g:number){return Object.fromEntries(Object.entries(p).map(([j,v])=>[j,torso.has(j)?{rotation:v.rotation*g,dx:(v.dx??0)*g,dy:(v.dy??0)*g}:v]));}
const rows=[];for(const g of [1,.75,.5,.25,0])for(const ig of [1,.5,0]){let first:any=null,n=0;for(let i=0;i<=120&&!first;i++)for(let k=0;k<32&&!first;k++){const ms=gait.durationMs*i/120,pose=addPose(gain(sampleClip({source:'timeline',timeline:idle},idle.durationMs*k/32),ig),gain(sampleClip({source:'timeline',timeline:gait},ms),g));try{solver.resolve(pose,{actionId:gait.actionId,elapsedMs:ms,durationMs:gait.durationMs,realm:card.realm,weight:1,travel:'stage',stageDisplacement:0});n++;}catch(e){first={ms,idleFraction:k/32,error:String(e)};}}rows.push({gaitTorsoGain:g,idleTorsoGain:ig,status:first?'RED':'PASS_ZERO_DISPLACEMENT',samples:n,first});}
fs.writeFileSync(B+'/fox-layered-probe.json',JSON.stringify({fit,scope:'Audit-only full120by32composite probe; same contact predicates and observed supports. No product modification or native acceptance.',rows},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(rows));
