/** One immutable intake/static/native attempt for an authored sprint packet. */
import fs from 'node:fs';import path from 'node:path';import cp from 'node:child_process';import crypto from 'node:crypto';
const root='/Users/nick/Projects/celestial-frontier-openai-mac',dir=path.resolve(process.argv[2]),number=Number(process.argv[3]),sprint=path.join(root,'audits/ARCHETYPE_SPRINT_20260922'),fit=dir+'/fit-01';
if(!dir.startsWith(sprint+'/')||!Number.isInteger(number)||number<2||number>12)throw Error('owned packet/item required');
const stages=[];const run=(name,args)=>{const startedAt=new Date().toISOString(),start=performance.now();const r=cp.spawnSync(process.execPath,args,{cwd:root,env:{...process.env,CF_BROWSER:'/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge'},encoding:'utf8',maxBuffer:64*1024*1024,timeout:600000});fs.writeFileSync(dir+'/'+name+'.log',(r.stdout??'')+(r.stderr??'')+(r.error?'\n'+String(r.error):''));stages.push({name,command:[process.execPath,...args],startedAt,endedAt:new Date().toISOString(),durationMs:performance.now()-start,exitCode:r.status,signal:r.signal,error:r.error?.message});fs.writeFileSync(dir+'/execution.json',JSON.stringify({id:'archetype-sprint-'+path.basename(dir)+'-01',stages,noRetry:true},null,2)+'\n');console.log(name+': '+r.status);return r.status;};
if(run('intake',[sprint+'/intake.mjs',dir,fit])===0){run('static',[sprint+'/static-runner.mjs',fit,dir+'/static.json']);run('native',['/Users/nick/Projects/celestial-frontier-anthropic-mac/port/v2/tools/battle2-proof/native-runner.mjs',fit,fit,dir+'/native-01']);}
run('sheet',[sprint+'/review-sheet.mjs',dir]);run('finish',[sprint+'/finish-item.mjs',dir,String(number)]);

const files=[];const visit=p=>{for(const n of fs.readdirSync(p).sort()){const q=path.join(p,n);if(fs.statSync(q).isDirectory())visit(q);else if(q!==dir+'/manifest.json'){const b=fs.readFileSync(q);files.push({path:path.relative(dir,q),bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex')});}}};visit(dir);fs.writeFileSync(dir+'/manifest.json',JSON.stringify({files},null,2)+'\n');
