import test from 'node:test';import assert from 'node:assert/strict';
import{waveMetrics,contactMetrics,pathFollowing,strikeMetrics}from'./metrics.mjs';
const n=240,chain=['a','b','c','d','e'],wave=lag=>Object.fromEntries(chain.map((j,k)=>[j,Array.from({length:n},(_,i)=>.1*Math.sin(2*Math.PI*(i/n-k*lag)))]));
test('travelling wave passes; standing, anti-phase and reversed waves fail',()=>{assert.equal(waveMetrics(wave(.125),chain).status,'PASS');for(const lag of [0,.5,-.125])assert.equal(waveMetrics(wave(lag),chain).status,'FAIL');});
test('chain identity and sample integrity refuse rather than silently pass',()=>{assert.throws(()=>waveMetrics(wave(.125),['a','missing','c']),/missing/);assert.throws(()=>waveMetrics(wave(.125),[]),/unidentified/);assert.throws(()=>waveMetrics({a:[NaN]},chain),/insufficient/);});
const ids=['FrontFar','MidNear','HindFar','FrontNear','MidFar','HindNear'],phases=Object.fromEntries(ids.map((j,k)=>[j,k<3?0:.5]));
function feet(duty=.65,swapped=false){return Array.from({length:n},(_,i)=>Object.fromEntries(ids.map(j=>{const phase=swapped&&j==='HindFar'?.5:phases[j],u=((i/n-phase)%1+1)%1;return[j,{stance:u<duty,lift:u<duty?0:.1*Math.sin(Math.PI*(u-duty)/(1-duty))**2}];})));}
test('tripod passes; one swapped foot and forced half-duty fail',()=>{assert.equal(contactMetrics(feet(),ids,phases).status,'PASS');assert.equal(contactMetrics(feet(.65,true),ids,phases).status,'FAIL');assert.equal(contactMetrics(feet(.5),ids,phases).status,'FAIL');assert.throws(()=>contactMetrics([{}],ids,phases),/unidentified/);});
test('path needs real history; matching path passes and displaced path fails',()=>{const s=Array.from({length:1000},(_,i)=>Object.fromEntries(chain.map((j,k)=>[j,{x:(i-k*10)/100,y:Math.sin((i-k*10)/100)}])));assert.equal(pathFollowing(s,chain,{bodyLength:1,lagSamples:10,worldHistory:true}).status,'PASS');s.forEach(row=>row.c.y+=.5);assert.equal(pathFollowing(s,chain,{bodyLength:1,lagSamples:10,worldHistory:true}).status,'FAIL');assert.throws(()=>pathFollowing(s,chain,{bodyLength:1,lagSamples:10}),/history absent/);});
test('strike distinguishes fast extension from a slow generic excursion',()=>{const points=span=>Array.from({length:241},(_,i)=>({x:i/240<.2?0:Math.min(.4,Math.max(0,(i/240-.2)/span*.4)),y:0}));assert.equal(strikeMetrics(points(.15),1,1000).status,'PASS');assert.equal(strikeMetrics(points(.65),1,1000).status,'FAIL');});
