import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {compileLibraryMaster} from '../../port/v2/tools/painted-creature/compile-library-master.mjs';
const base='audits/C206_BIRD_SOURCE_REPAINTS_20261002',sha=b=>createHash('sha256').update(b).digest('hex');
const selections=[
 ['Snipe',81,'Expose two actual leg chains from their visible feather margins through both ankles and natural long toes. Keep the extremely long straight bill, high rear-set eye and bold cream back stripes. Do not invent bare proximal anatomy behind feathers.'],
 ['Godwit',81,'Separate the real far leg contour from the near leg from its visible body emergence to its complete foot. Preserve the very long faintly upswept pale-based bill, long dark legs and cinnamon breast with dark chevrons.'],
 ['Avocet',81,'Show both real long blue-grey leg shafts from visible body emergence, complete feet and the natural short tail beneath the folded wing. Keep connected tissue; no cutout gap at the tail root. The needle bill curves strongly UP.'],
 ['Moorhen',81,'Show both real greenish legs independently emerging from the feathered body and complete long toes. Preserve the natural cocked short tail and white undertail flashes; do not lower or lengthen it to fit a generic bird silhouette.'],
 ['Egret',121,'Expose two natural leg contours from the visible feather margin, with separately readable dark ankles and feet. Show the true short tail distinctly from breeding plumes; do not turn those plumes into an invented long tail. Preserve white plumage, S-neck and spear bill.'],
 ['Stork',121,'Separate both actual very long red leg chains from the visible body margin to complete feet. Keep the neck naturally extended rather than heron-kinked; show the connected short tail and black folded wing as distinguishable surfaces.'],
 ['Bittern',92,'Keep the naturally thick hunched retractable neck and brown-and-buff streaked camouflage. For this quiet source view the dagger bill is level, not the upward reed-freeze display. Separate both real legs from their visible feather margin through the long toes; do not elongate the concealed thighs.'],
 ['Condor',101,'Separate the two real feet and complete visible lower leg chains without changing their natural short proportions. Preserve the bare wrinkled head, white neck ruff, massive folded wings and true complete tail. Keep both contact silhouettes readable and naturally connected.'],
 ['Turkey',121,'Use a quiet natural non-display pose with the broad barred tail folded, not a raised fan. Preserve the true breast beard as hanging bristles, the bare warty blue/red head, wattle and snood. Two true legs and full toes remain distinct; beard is not an extra limb.'],
 ['Grouse',121,'Use a quiet non-display pose with the real broad barred tail naturally folded, not a spread fan. Preserve feathered legs and feet, plump body and short rounded bill. Separate the two foot silhouettes without removing real feather fringes.'],
 ['Peacock',121,'Keep the male long eyespotted train fully folded and naturally trailing; it consists of upper tail coverts, not the true tail. Show the actual small supporting tail under the train only where naturally visible, never fabricate one or shorten the train. Two real legs and feet are separate. Zoom out to retain every train tip.'],
 ['Guineafowl',76,'Retain the tiny bare blue/red head and real helmet casque, thin naked neck and rounded body densely speckled with white dots. Show each complete natural foot and its toes independently; the natural short tail droops downward, not a long plume.'],
 ['Pheasant',76,'Keep the ring-necked male identity, red facial wattle, green-black head, white neck ring and extremely long barred pointed tail, longer than the body. Make the connected tail root distinguishable from folded wing surfaces and separate the two real ankle/foot contours. Zoom out rather than shortening the tail.'],
 ['Guillemot',87,'Use the natural upright brown-and-white guillemot stance with slender dagger bill, narrow head and genuinely short feather tail. Show two true webbed feet, clear webbing joining the natural front toes, and rear-set short legs; no long raptor tail.'],
 ['Auk',92,'A natural upright razorbill-type auk, taller than long, with short stubby folded wings, genuinely short tail and short rear-set legs. Show both real webbed feet distinctly without elongating the legs. Keep the dark grooved bill and black back/white front.'],
 ['Grebe',92,'BIOLOGICAL POSE PRIORITY: the real legs emerge very far back. Use a natural low resting stance with the body inclined and feet placed as a real grebe supports itself, not a generic marching duck. Paint separate flattened lobes on each toe, NOT a web joining the toes. Keep the puffy rounded rear with no invented visible feather-tail fan. Expose only anatomy truly visible in this natural stance.'],
 ['Penguin',118,'Use a fully upright natural penguin stance, two short rear-set webbed feet with real toe webbing, and the natural small stiff short tail. The two real stiff flippers are its wings, held at the sides, not feathered flying wings. Never add long flowing tail fronds or artificially long legs.'],
 ['Pelican',101,'Use a heavy-bodied pelican resting naturally on very short legs, with a long neck kinked onto the shoulders. Keep the enormous real bill and its throat pouch anatomically proportioned, no invented dramatic crest. Show both actual webbed feet and a natural short tail whose root remains connected beside the folded wing. No forced long-legged marching pose.'],
 ['Screamer',98,'A real horned screamer: bulky goose-like body, small chicken-like head and short hooked bill, a thin flexible curved forehead spine, and real small bony wing-bend spurs. No goat horn, no huge golden wing horn, no raptor body. Keep partly webbed natural feet. The far spur appears only if truly visible; do not invent an extra wing to expose it.'],
 ['Hornbill',83,'The huge downcurved bill has a naturally closed outer casque covering its hollow interior. Do NOT paint an open tube, hole or cutaway in the casque. Preserve the coloured bare throat/eye skin, lashes and long broad tail. Separate both actual feet and distinguish the true connected tail root from folded wing feathers.'],
 ['Parrot',83,'A compact Amazon-type parrot, not a macaw: stocky green body, short square tail, short deeply hooked bill with fleshy cere, and normally feathered face. No large bare striped macaw facial patch. Both real feet show the natural zygodactyl arrangement, two toes forward and two back, with independently readable grounded contacts.'],
 ['Macaw',83,'Preserve the enormous pale hooked bill, bare white facial patch with fine feather lines and tail streamers naturally far longer than the body. Show the actual zygodactyl feet, two toes forward and two back, independently. Tail feathers remain naturally straight or gently trailing, not an invented curled loop; keep the real tail root connected below the folded wings.'],
 ['Tern',98,'Preserve the natural deeply forked complete feather tail with two distinct unbroken streamers, not crossed hair-thin strings. Show the slim dagger bill, black cap and natural long narrow wings folded against the body. Two short legs and true webbed feet remain distinct; tail roots stay biologically connected.'],
 ['Weaverbird',83,'A naturally standing male masked weaver for the isolated source, no nest or hanging prop: bright yellow plumage, black facial mask and thick conical bill. Both actual legs visibly emerge separately from their feather margins to the natural ankles and toes. Do not invent exposed proximal segments or elongate its short legs.']
];
const coveragePath='audits/GENERATED_GALLERY_20260927/coverage.json',coverage=JSON.parse(fs.readFileSync(coveragePath));
const accepted=new Set(coverage.families.flatMap(f=>f.names??[]));
const reserved=['Hawk','Crow','Snowy Owl','Basking Shark','Great White Shark','Mako Shark','Whale Shark','Snailfish','Tiger Shark','Flounder','Snow Petrel','Rhea','Giraffe','Banteng'];
const rows=[],evidence=[];
const composition='COMPOSITION: square native 1254 by 1254 painting. Keep the entire specimen small, inside the central half of the canvas, with generous pure magenta around every bill, toe, plume and tail tip. Preserve real proportions by zooming out, never shortening appendages. No ground, cast shadow, scenery, perch, branch, prop, text, diagram or framing marks.';
for(const[i,[name,previousBatch,correction]]of selections.entries()){
 if(accepted.has(name)||reserved.includes(name))throw Error('Accepted or reserved duplicate '+name);
 const previousBase=`audits/G2_C${previousBatch}_20260927`,previousPilot=previousBase+'/pilot.json',prior=JSON.parse(fs.readFileSync(previousPilot)).find(r=>r.name===name);
 if(!prior)throw Error('Missing previous subject '+name);
 const previousSummary=`audits/G1_AUTO_AUTHOR_20260926/auto-g2c${previousBatch}/summary.json`,old=JSON.parse(fs.readFileSync(previousSummary)).find(r=>r.id===prior.id),visualPath=previousBase+'/visual-notes.json',oldVisual=JSON.parse(fs.readFileSync(visualPath))[name];
 if(!old||!oldVisual||!(old.verdict==='REFUSE'||old.static==='INTAKE_REFUSED'))throw Error('Missing actual source refusal '+name);
 const id=String(i+1).padStart(2,'0')+'-'+name.toLowerCase().replaceAll(' ','-'),packet=base+'/'+id,c=await compileLibraryMaster(name,packet);
 if(c.family!=='biped-bird')throw Error('Canonical family changed '+name);
 const request=JSON.parse(fs.readFileSync(packet+'/request.json')),canonical=fs.readFileSync(packet+'/prompt.txt','utf8');if(sha(canonical)!==request.promptSha256)throw Error('Canonical prompt hash');
 const sourceCorrection='TARGETED SOURCE REPAINT — BIOLOGICAL PRIORITY: '+correction+' Preserve the real species anatomy if a generic pose instruction conflicts. No invented far wing, false leg, disconnected tail, artificial gap through tissue or removal of actual appendages. This request does not establish measured anatomical presence.';
 const prompt=composition+'\n'+sourceCorrection+'\n\n'+canonical+'\n\n'+sourceCorrection+'\n'+composition+'\n';
 fs.writeFileSync(packet+'/prompt.canonical.txt',canonical,{flag:'wx'});
 fs.writeFileSync(packet+'/prompt.txt.tmp',prompt,{flag:'wx'});fs.renameSync(packet+'/prompt.txt.tmp',packet+'/prompt.txt');
 const repairReason={previousId:prior.id,previousMaster:prior.master,previousSummary,verdict:old.verdict,reasons:old.reasons,static:old.static??null,previousVisual:oldVisual,correction};
 fs.writeFileSync(packet+'/request.json.tmp',JSON.stringify({...request,basePromptSha256:request.promptSha256,promptSha256:sha(prompt),batchCompilerSha256:sha(fs.readFileSync(import.meta.filename)),purpose:'TARGETED_SOURCE_REPAINT',repairReason,layoutOverride:null,sourceCorrection,compositionCheck:composition,admission:'GENERATED_CANDIDATE_ONLY; no semantic presence, rig admission or motion claim'},null,2)+'\n',{flag:'wx'});fs.renameSync(packet+'/request.json.tmp',packet+'/request.json');
 rows.push({id,name,family:c.family,packet,master:packet+'/master.png',purpose:'TARGETED_SOURCE_REPAINT',repairReason});
 for(const source of [previousPilot,previousSummary,visualPath])if(!evidence.some(r=>r.path===source)){const b=fs.readFileSync(source);evidence.push({path:source,sha256:sha(b),bytes:b.length});}
 console.log(id);
}
fs.writeFileSync(base+'/pilot.json',JSON.stringify(rows,null,2)+'\n',{flag:'wx'});
fs.writeFileSync(base+'/selection.json',JSON.stringify({schema:'cf.g2-selection/v1',newOriginals:0,targetedSourceRepaints:24,total:24,coverageSource:coveragePath,coverageSha256:sha(fs.readFileSync(coveragePath)),coveredAtSelection:204,coverageAuthority:'Claude mailbox C179; local coverage may precede the signed merge',reserved,exclusions:'All accepted species, C197 review queue, fixed Hawk/Crow/Snowy Owl fits and other assigned source queues excluded. Loon excluded because its biology forbids the generic walking pose.',pipeline:'Unchanged production canonical compiler and locked ART_KIT/DiscoveryAtlas. Canonical prompt retained byte-identically; explicit species-specific source corrections and composition appended without replacing canonical sections.',evidence,rows},null,2)+'\n',{flag:'wx'});
