import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {createHash} from 'node:crypto';
const base=import.meta.dirname,root=path.resolve(base,'../..'),sha=b=>createHash('sha256').update(b).digest('hex');
const pilot=JSON.parse(fs.readFileSync(base+'/pilot.json')),observations=JSON.parse(fs.readFileSync(base+'/observations.json'));
if(pilot.length!==24||new Set(pilot.map(r=>r.name)).size!==24)throw Error('Exact unique24');
for(const r of pilot){const d=root+'/'+r.packet,g=JSON.parse(fs.readFileSync(d+'/generation.json')),q=JSON.parse(fs.readFileSync(d+'/request.json')),bytes=fs.readFileSync(d+'/master.png'),source=g.sourcePath.startsWith('~/')?path.join(os.homedir(),g.sourcePath.slice(2)):path.resolve(root,g.sourcePath);if(sha(bytes)!==g.masterSha256||!bytes.equals(fs.readFileSync(source))||sha(fs.readFileSync(d+'/prompt.txt'))!==q.promptSha256||g.promptSha256!==q.promptSha256||q.referenceSha256!==sha(fs.readFileSync(root+'/'+q.reference)))throw Error('Immutable provenance '+r.name);const o=observations.find(o=>o.id===r.id);if(o?.masterSha256!==g.masterSha256||o.width!==1254||o.height!==1254)throw Error('Native dimensions '+r.name);}
const pipelineInputs=['port/v2/tools/painted-creature/compile-library-master.mjs','ART_KIT.md','audits/MIDGAME_ART_DIRECTION_20260908/01-discovery-atlas.png'].map(p=>{const b=fs.readFileSync(root+'/'+p);return{path:p,sha256:sha(b),bytes:b.length};});
for(const r of pilot){const d=root+'/'+r.packet,q=JSON.parse(fs.readFileSync(d+'/request.json')),canonical=fs.readFileSync(d+'/prompt.canonical.txt','utf8'),actual=fs.readFileSync(d+'/prompt.txt','utf8');if(q.compilerSha256!==pipelineInputs[0].sha256||q.kitSha256!==pipelineInputs[1].sha256||q.referenceSha256!==pipelineInputs[2].sha256||q.basePromptSha256!==sha(canonical)||q.layoutOverride!==null||q.purpose!=='TARGETED_SOURCE_REPAINT'||actual!==q.compositionCheck+'\n'+q.sourceCorrection+'\n\n'+canonical+'\n\n'+q.sourceCorrection+'\n'+q.compositionCheck+'\n')throw Error('Unchanged pipeline proof '+r.name);}
fs.writeFileSync(base+'/pipeline-proof.json',JSON.stringify({schema:'cf.g2-unchanged-pipeline-proof/v1',status:'PASS',subjects:24,canonicalPromptsRetained:true,canonicalSectionsUnchanged:true,sourceCorrectionAppendicesExplicit:true,productionInputs:pipelineInputs,scope:'Exact canonical compiler/ART_KIT/style bytes and request assembly; no generated anatomy admission'},null,2)+'\n',{flag:'wx'});
const files=[];function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory())walk(f);else if(e.isFile()&&e.name!=='delivery.json'){const b=fs.readFileSync(f);if(/\.(json|mjs|md|txt)$/.test(e.name)&&(b.includes(Buffer.from(os.homedir()))||b.includes(Buffer.from('/'+'Users/'))))throw Error('Unsanitized record '+path.relative(root,f));files.push({path:path.relative(root,f),sha256:sha(b),bytes:b.length});}}}walk(base);files.sort((a,b)=>a.path.localeCompare(b.path));const d={schema:'cf.g2-source-delivery/v1',scope:'24 targeted bird source repaints; canonical compiler unchanged, explicit source holds, no rig/native/gallery admission',originals:24,nativeDimensions:[1254,1254],framingPass:observations.filter(o=>o.framing.status==='PASS_FRAMING_ONLY').length,framingRefused:observations.filter(o=>o.framing.status==='REFUSE').map(o=>o.name),masterBytes:pilot.reduce((n,r)=>n+fs.statSync(root+'/'+r.master).size,0),files,bytes:files.reduce((n,f)=>n+f.bytes,0)};fs.writeFileSync(base+'/delivery.json',JSON.stringify(d,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({files:files.length,bytes:d.bytes,masterBytes:d.masterBytes,deliverySha256:sha(fs.readFileSync(base+'/delivery.json'))}));
