import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { setTimeout as delay } from 'node:timers/promises';
import { openChromiumCdp } from '../../port/v2/tools/browsercdp.mjs';

// One local header diagnostic; run under the shared tool lock outside macOS Seatbelt.
// node audits/AV_CHARTER_HEADER_PREVIEW_20260908/native-header.mjs /absolute/evidence-dist /absolute/fresh-output
assert.equal(process.argv.length,4,'Expected evidence-dist and fresh-output');
const repo=fs.realpathSync(fileURLToPath(new URL('../..',import.meta.url))),dist=fs.realpathSync(process.argv[2]),out=path.resolve(process.argv[3]);
assert(!fs.existsSync(out)&&!out.startsWith(dist+path.sep),'Output must be fresh and outside dist');assert.equal(fs.realpathSync(path.dirname(out)),path.dirname(out));fs.mkdirSync(out);
fs.copyFileSync(fileURLToPath(import.meta.url),path.join(out,'runner.mjs'),fs.constants.COPYFILE_EXCL);
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const report={schema:'cf-native-charter-header-preview/v1',status:'RUNNING',certification:false,startedAt:new Date().toISOString(),dist,sources:{},served:{},cases:[],inputs:[],screenshots:[],errors:[],limitations:[
  'Fresh isolated expedition and native Charters opener/scroll/Close; pixel controls temporarily hide existing objective text and remove header paint only.',
  'Six scoped phone/desktop style cases; not a layout certificate, physical-device check or human visual acceptance.',
  'Coverage means no objective ink leaks into the independently cropped sticky title/Close band at the measured overlap; no broad UI/art audit.']};
for(const file of ['port/v2/apps/game/src/main.ts','port/v2/apps/game/src/panels.ts','port/v2/apps/game/src/ui-sheet-style.ts','port/v2/apps/game/src/ui-presentation-tokens.ts','port/v2/apps/game/src/pilot-runtime-style.ts','port/v2/apps/game/src/audiovisual-pilot.ts','port/v2/apps/game/index.html',path.relative(repo,fileURLToPath(import.meta.url))])report.sources[file]=hash(fs.readFileSync(path.join(repo,file)));
const persist=()=>fs.writeFileSync(path.join(out,'review.json'),JSON.stringify(report,null,2)+'\n');
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.wav':'audio/wav','.woff2':'font/woff2'};
const server=http.createServer((req,res)=>{try{assert(req.method==='GET'||req.method==='HEAD');const name=decodeURIComponent(new URL(req.url,'http://127.0.0.1').pathname),file=fs.realpathSync(path.resolve(dist,'.'+(name==='/'?'/index.html':name)));assert(file.startsWith(dist+path.sep)&&fs.statSync(file).isFile());const b=fs.readFileSync(file),key=path.relative(dist,file),digest=hash(b);assert(!report.served[key]||report.served[key]===digest,'Served bytes changed');report.served[key]=digest;res.writeHead(200,{'Content-Type':types[path.extname(file)]??'application/octet-stream','Cache-Control':'no-store'});res.end(req.method==='HEAD'?undefined:b)}catch{res.writeHead(404);res.end('Not found')}});
const S='window.__CF_SLICE__';
const ready=`(()=>{const s=${S}?.api.state(),p=s?.persistence,r=p?.runtime;return p?.ready===true&&p.hold===null&&p.seedBootstrapPending===false&&p.bootRouteRepairPending===false&&p.mutationBlocked===false&&p.documentToken===${S}.documentToken&&r?.visible===true&&r.answerable===true&&r.leaseOwned===true&&r.accruing===true&&r.staleBlocked===false&&s.sceneResources.pendingPersistenceWrites===0})()`;
const state=`(()=>{const s=${S}?.api.state();return{documentToken:${S}?.documentToken,bodyClass:document.body.className,pilot:document.body.hasAttribute('data-cf-pilot-look'),viewport:[innerWidth,innerHeight,devicePixelRatio],mode:s?.mode,persistence:s?.persistence,panel:s?.panelOpen,scrollTop:document.querySelector('#chpanel')?.scrollTop,forcedColors:matchMedia('(forced-colors:active)').matches,inputs:window.__cfHeaderInputs}})()`;
function headerGeometry(){
  const panel=document.querySelector('#chpanel'),header=panel.querySelector(':scope > .sheet-header'),close=panel.querySelector(':scope > [data-pnx]'),label=panel.querySelector('[data-sel="charter-goal"] label');
  if(!header||!close||!label)throw Error('Real Charters header/Close/objective missing');
  const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,left:r.left,top:r.top,right:r.right,bottom:r.bottom}},pr=rect(panel),hr=rect(header),cr=rect(close),ps=getComputedStyle(panel),hs=getComputedStyle(header),pseudo=getComputedStyle(header,'::after'),range=document.createRange();range.selectNodeContents(label);const line=range.getClientRects()[0];
  if(!line)throw Error('Objective has no rendered text rectangle');
  const band={left:pr.left+parseFloat(ps.borderLeftWidth),right:pr.right-parseFloat(ps.borderRightWidth),top:pr.top+parseFloat(ps.borderTopWidth),bottom:Math.max(hr.bottom,cr.bottom)};
  const scrollbarWidth=parseFloat(getComputedStyle(panel,'::-webkit-scrollbar').width);
  if(!Number.isFinite(scrollbarWidth)||scrollbarWidth<0||scrollbarWidth>12)throw Error('Unknown native scrollbar lane');
  const clip={x:Math.ceil(band.left)+1,y:Math.ceil(band.top)+1,width:Math.floor(band.right-scrollbarWidth)-Math.ceil(band.left)-2,height:Math.floor(band.bottom)-Math.ceil(band.top)-2,scale:1};
  if(cr.right>clip.x+clip.width||line.right>clip.x+clip.width)throw Error('Scrollbar exclusion would crop Close or objective ink');
  const overlap=Math.max(0,Math.min(line.bottom,clip.y+clip.height)-Math.max(line.top,clip.y));
  return{panel:pr,header:hr,close:cr,scrollbarWidth,label:rect(label),line:{top:line.top,bottom:line.bottom,left:line.left,right:line.right,height:line.height},band,clip,overlap,scrollTop:panel.scrollTop,scrollHeight:panel.scrollHeight,clientHeight:panel.clientHeight,title:header.textContent,objective:label.textContent,headerStyle:{position:hs.position,top:hs.top,background:hs.backgroundColor,opacity:hs.opacity,zIndex:hs.zIndex},pseudo:{content:pseudo.content,top:pseudo.top,bottom:pseudo.bottom,left:pseudo.left,right:pseudo.right,background:pseudo.backgroundColor},closeHit:document.elementFromPoint(cr.x+cr.width/2,cr.y+cr.height/2)===close};
}
let browser,send,evaluate;
try{
  await new Promise((r,j)=>{server.once('error',j);server.listen(0,'127.0.0.1',r)});report.origin=`http://127.0.0.1:${server.address().port}`;persist();
  browser=await openChromiumCdp({label:'native scrolled Charters header',userDataPrefix:'cf-charter-header-20260908',commandTimeoutMs:15000,onEvent:e=>{if(e.method==='Runtime.exceptionThrown')report.errors.push(e.params.exceptionDetails)}});report.browser=browser.browser;
  const {targetId}=await browser.send('Target.createTarget',{url:'about:blank'}),{sessionId}=await browser.send('Target.attachToTarget',{targetId,flatten:true});send=(method,params={})=>browser.send(method,params,sessionId);await send('Runtime.enable');await send('Page.enable');
  evaluate=async expression=>{report.pendingEvaluation={expression,sha256:hash(expression),at:new Date().toISOString()};persist();const a=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});assert(!a.exceptionDetails,JSON.stringify(a.exceptionDetails));report.pendingEvaluation=null;return a.result.value};
  const frames=()=>evaluate('document.fonts.ready.then(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r(true)))))');
  const wait=async(name,condition)=>{report.waiting={name,condition};persist();const end=Date.now()+15000;while(!await evaluate(condition)){assert(Date.now()<end,'Timed out: '+name);await delay(100)}report.waiting=null};
  const geometry=()=>evaluate(`(${headerGeometry.toString()})()`);
  await send('Page.addScriptToEvaluateOnNewDocument',{source:`window.__cfHeaderInputs=[];for(const type of ['click','wheel'])document.addEventListener(type,e=>{if(window.__cfHeaderInputs.length<200)window.__cfHeaderInputs.push({type,trusted:e.isTrusted,close:e.target.closest?.('[data-pnx]')?.dataset.pnx??null,opener:!!e.target.closest?.('#objchip'),panel:!!e.target.closest?.('#chpanel'),at:performance.now()})},true)`});
  const click=async(selector,scroll=true)=>{const point=await evaluate(`(async()=>{const a=document.querySelectorAll(${JSON.stringify(selector)});if(a.length!==1)throw Error('Nonunique '+${JSON.stringify(selector)});const e=a[0];if(${scroll})e.scrollIntoView({block:'center'});await document.fonts.ready;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const b=e.getBoundingClientRect(),x=b.x+b.width/2,y=b.y+b.height/2,h=document.elementFromPoint(x,y);if(e.disabled||b.width<=0||b.height<=0||!(h===e||e.contains(h)))throw Error('Occluded '+${JSON.stringify(selector)});return{x,y}})()`),before=await evaluate('window.__cfHeaderInputs.length');
    await send('Input.dispatchMouseEvent',{type:'mouseMoved',...point,button:'none'});await send('Input.dispatchMouseEvent',{type:'mousePressed',...point,button:'left',buttons:1,clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',...point,button:'left',buttons:0,clickCount:1});await frames();const inputs=await evaluate(`window.__cfHeaderInputs.slice(${before})`);assert(inputs.length===1&&inputs[0].trusted&&inputs[0].type==='click');report.inputs.push({selector,point,...inputs[0]});persist()};
  const shot=async(name,clip)=>{const {data}=await send('Page.captureScreenshot',{format:'png',...(clip?{clip,captureBeyondViewport:false}:{})}),bytes=Buffer.from(data,'base64');fs.writeFileSync(path.join(out,name+'.png'),bytes,{flag:'wx'});report.screenshots.push({path:name+'.png',sha256:hash(bytes),clip:clip??null});persist();return data};
  const pixels=async(a,b)=>evaluate(`(async()=>{const read=async data=>{const image=new Image();image.src='data:image/png;base64,'+data;await image.decode();const c=document.createElement('canvas');try{c.width=image.naturalWidth;c.height=image.naturalHeight;const ctx=c.getContext('2d');ctx.drawImage(image,0,0);return{width:c.width,height:c.height,data:ctx.getImageData(0,0,c.width,c.height).data}}finally{c.width=c.height=0}};const a=await read(${JSON.stringify(a)}),b=await read(${JSON.stringify(b)});if(a.width!==b.width||a.height!==b.height||!a.data.length)throw Error('Pixel crop mismatch');let changedPixels=0,changedChannels=0;for(let i=0;i<a.data.length;i+=4){let changed=false;for(let k=0;k<4;k++)if(a.data[i+k]!==b.data[i+k]){changed=true;changedChannels++}if(changed)changedPixels++}return{width:a.width,height:a.height,changedPixels,changedChannels}})()`);
  const viewport=async(w,h,dpr,touch)=>{await send('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:dpr,mobile:touch});await send('Emulation.setTouchEmulationEnabled',{enabled:touch,maxTouchPoints:1});await frames()};
  await viewport(390,844,2,true);await send('Page.navigate',{url:report.origin+'/?avpilot=1'});await wait('answerable pilot',`${S}?.api&&${ready}&&document.querySelector('[data-cf-audiovisual-pilot]')`);
  if(await evaluate(`${S}.api.state().tutActive`)){await click('[data-sel=tutskip]');await wait('Training closed',`!${S}.api.state().tutActive&&${ready}`)}
  const restoreProbe=()=>evaluate(`(()=>{const p=window.__cfHeaderProbe;if(!p)return null;p.fault?.remove();if(p.hadStyle)p.label.setAttribute('style',p.style);else{p.label.setAttribute('style','');p.label.removeAttribute('style')}const valid=p.label.hasAttribute('style')===p.hadStyle&&p.label.getAttribute('style')===p.style;if(p.started)${S}.app.ticker.start();delete window.__cfHeaderProbe;return{valid}})()`);
  const probe=async(name,pilot,control=false)=>{
    const entry={name,status:'RUNNING',state:await evaluate(state)};report.cases.push(entry);assert.equal(entry.state.pilot,pilot);persist();await click('#objchip');await wait('Charters open',`document.querySelector('#chpanel').getAttribute('aria-hidden')==='false'`);await frames();
    entry.opened=await geometry();assert(entry.opened.scrollHeight>entry.opened.clientHeight,'Fresh Charters must genuinely overflow');await shot(name+'-before-scroll');
    for(let i=0;i<20;i++){const g=await geometry();if(g.scrollTop>0&&g.overlap>=Math.min(8,g.line.height*.5))break;const x=g.panel.x+g.panel.width*.45,y=Math.min(g.panel.bottom-25,g.header.bottom+60),deltaY=Math.max(-120,Math.min(120,(g.line.top+g.line.bottom-g.band.top-g.band.bottom)/2));assert(Math.abs(deltaY)>1,'Native scroll alignment stalled');assert(await evaluate(`!!document.elementFromPoint(${x},${y})?.closest('#chpanel')`));const before=await evaluate('window.__cfHeaderInputs.length');await send('Input.dispatchMouseEvent',{type:'mouseMoved',x,y,button:'none'});await send('Input.dispatchMouseEvent',{type:'mouseWheel',x,y,deltaX:0,deltaY});await delay(120);await frames();const events=await evaluate(`window.__cfHeaderInputs.slice(${before})`);assert(events.some(e=>e.type==='wheel'&&e.trusted&&e.panel));entry.wheels??=[];entry.wheels.push({x,y,deltaY,events})}
    entry.scrolled=await geometry();assert(entry.scrolled.scrollTop>0&&entry.scrolled.overlap>=Math.min(8,entry.scrolled.line.height*.5),'No actual objective text beneath required header band');assert.equal(entry.scrolled.headerStyle.position,'sticky');assert(entry.scrolled.closeHit,'Scrolled Close must retain its native centre');
    const clip=entry.scrolled.clip;assert(clip.width>44&&clip.height>20);await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:1,y:1,button:'none'});await frames();
    await evaluate(`(()=>{const label=document.querySelector('#chpanel [data-sel="charter-goal"] label');window.__cfHeaderProbe={label,hadStyle:label.hasAttribute('style'),style:label.getAttribute('style'),started:${S}.app.ticker.started,fault:null};${S}.app.ticker.stop();return true})()`);
    try{
      const base=await shot(name+'-header-visible',clip);await evaluate(`window.__cfHeaderProbe.label.style.setProperty('visibility','hidden','important');true`);await frames();const hiddenGeometry=await geometry(),hidden=await shot(name+'-header-text-hidden',clip);entry.fixed=await pixels(base,hidden);assert.deepEqual(hiddenGeometry.label,entry.scrolled.label);assert.deepEqual(hiddenGeometry.header,entry.scrolled.header);assert.equal(hiddenGeometry.scrollTop,entry.scrolled.scrollTop);persist();
      await evaluate(`(()=>{const p=window.__cfHeaderProbe;if(p.hadStyle)p.label.setAttribute('style',p.style);else{p.label.setAttribute('style','');p.label.removeAttribute('style')}if(p.label.hasAttribute('style')!==p.hadStyle||p.label.getAttribute('style')!==p.style)throw Error('Objective style restore mismatch');return true})()`);await frames();const restored=await shot(name+'-header-restored',clip);entry.restored=await pixels(base,restored);assert.equal(entry.restored.changedPixels,0,'Restored header pixels changed');assert.equal(entry.fixed.changedPixels,0,'Body objective ink leaks through header paint band');
      if(control){await evaluate(`(()=>{const p=window.__cfHeaderProbe,s=document.createElement('style');s.textContent='#chpanel .sheet-header,#chpanel .sheet-header::before,#chpanel .sheet-header::after{background:transparent!important;box-shadow:none!important;backdrop-filter:none!important}';document.head.append(s);p.fault=s;return true})()`);await frames();entry.faultGeometry=await geometry();assert.deepEqual(entry.faultGeometry.label,entry.scrolled.label);assert.deepEqual(entry.faultGeometry.header,entry.scrolled.header);assert.equal(entry.faultGeometry.scrollTop,entry.scrolled.scrollTop);const faulty=await shot(name+'-fault-transparent',clip);await evaluate(`window.__cfHeaderProbe.label.style.setProperty('visibility','hidden','important');true`);await frames();const faultyHidden=await shot(name+'-fault-transparent-text-hidden',clip);entry.negative=await pixels(faulty,faultyHidden);assert(entry.negative.changedPixels>0,'Transparent paint fault failed to expose the actual underlying objective');persist()}
      await evaluate(`(()=>{const p=window.__cfHeaderProbe;p.fault?.remove();p.fault=null;if(p.hadStyle)p.label.setAttribute('style',p.style);else{p.label.setAttribute('style','');p.label.removeAttribute('style')}return true})()`);await frames();entry.afterControl=await pixels(base,await shot(name+'-header-control-restored',clip));assert.equal(entry.afterControl.changedPixels,0,'Paint control did not restore exact header pixels');
    }finally{const restored=await restoreProbe();assert(restored?.valid,'Exact objective style restoration failed');await frames()}
    entry.finalGeometry=await geometry();assert.deepEqual(entry.finalGeometry.label,entry.scrolled.label);assert.equal(entry.finalGeometry.scrollTop,entry.scrolled.scrollTop);await shot(name+'-after-restoration');
    await click('#chpanel [data-pnx="ch"]',false);await wait('native Close completes',`document.querySelector('#chpanel').getAttribute('aria-hidden')==='true'`);entry.status='PASS';persist();
  };
  const togglePilot=async()=>{await click('[data-cf-pilot-controls] summary');await click('[data-cf-pilot-controls] button:nth-of-type(1)');await click('[data-cf-pilot-controls] summary');await frames()};
  const prefs=async(large)=>{await click('#docksets');await click(`[data-pref="size"][data-value="${large?'fs-xl':''}"]`);await wait('text preference settled',ready);await click(`[data-pref="tone"][data-value="${large?'tone-max':''}"]`);await wait('contrast preference settled',ready);await click('#setpanel [data-pnx="set"]',false)};
  await probe('phone-pilot',true,true);await togglePilot();await probe('phone-current',false);
  await prefs(true);await probe('phone-current-large-max',false);await send('Emulation.setEmulatedMedia',{features:[{name:'forced-colors',value:'active'}]});await frames();assert(await evaluate(`matchMedia('(forced-colors:active)').matches`));await probe('phone-current-large-max-forced',false);
  await send('Emulation.setEmulatedMedia',{features:[{name:'forced-colors',value:'none'}]});await frames();await prefs(false);await viewport(1440,1000,1,false);await probe('desktop-current',false);await togglePilot();await probe('desktop-pilot',true);
  assert.equal(report.errors.length,0,'Browser runtime exception');report.status='PASS';
}catch(error){report.status='FAIL';report.failure=String(error.stack??error);process.exitCode=1;const failedEvaluation=report.pendingEvaluation;
  try{report.failureState=await evaluate?.(state)}catch(e){report.failureStateError=String(e)}report.failedEvaluation=failedEvaluation;
  try{const a=await send?.('Page.captureScreenshot',{format:'png'});if(a)fs.writeFileSync(path.join(out,'failure.png'),Buffer.from(a.data,'base64'),{flag:'wx'})}catch(e){report.failureScreenshotError=String(e)}
}finally{const cleanup=[];
  try{if(evaluate)await evaluate(`(()=>{const p=window.__cfHeaderProbe;if(!p)return true;p.fault?.remove();if(p.hadStyle)p.label.setAttribute('style',p.style);else{p.label.setAttribute('style','');p.label.removeAttribute('style')}if(p.started)${S}.app.ticker.start();delete window.__cfHeaderProbe;return true})()`)}catch(e){cleanup.push('Probe restoration: '+e)}
  try{await browser?.close()}catch(e){cleanup.push(String(e))}if(server.listening){server.closeAllConnections();await new Promise(r=>server.close(r))}
  try{for(const [file,digest]of Object.entries(report.sources))assert.equal(hash(fs.readFileSync(path.join(repo,file))),digest,'Source changed: '+file);for(const [file,digest]of Object.entries(report.served))assert.equal(hash(fs.readFileSync(path.join(dist,file))),digest,'Dist changed: '+file)}catch(e){cleanup.push(String(e))}
  if(cleanup.length){report.cleanupFailures=cleanup;report.status='FAIL';process.exitCode=1}report.endedAt=new Date().toISOString();persist();
}
console.log(JSON.stringify({status:report.status,output:out,failure:report.failure}));
